### ISSUE TITLE
Auto-submit segments once the server is back

### ISSUE THREAD

**Issue by SameenAhnaf** [ajayyy/SponsorBlock#1006]
Currently, segments are saved as draft if the server is down while submitting segments. A setting like `Track Videos with Unsubmitted Segments` could be added. 

<b> 1. Notify: </b> A notification will appear if Sponsorblock server is back. Note that this popup should appear only while browsing YouTube website as submitting segments isn't an emergency task of someone's life. Three options will be shown in the notification.
1. `Recheck`: Check if all the segments were upto the mark.
2. `Submit`: Submit all predefined segments instantly without any other extra click.
3. `Delete draft`: As of now, unsubmitted segments remain as draft. All drafts will be deleted instantly. A confirmation popup could be seperately added. 

<b> 2. Notify, if nobody submitted: </b> Notification will only appear if nobody submitted segments of the videos. If the user tried to submit segments 5 videos and segments of 3 are already submitted, only 2 unsubmitted segments will be newly submitted. Same options will be kept. However, `Recheck` will only show the unsubmitted segments.

<b> 3. Save history: </b> Sponsorblock will keep tracks of videos of which the user tried to submit segments. Deleting any video from the history will delete that video's draft. The video will also remove instantly if the user himself submitted the segments. A `Tick mark` could be shown if someone else already submitted his or her segments.

<details><summary> Related problems:  </summary>
Many users prefer to pause watch history and it's a pain in the neck to keep track of all the videos. Even if watch history is disabled, it's often hard to remember the videos for which the segments are supposed to be submitted. Note that users with the least number of unsubmitted segments should be prioritized in terms of server notification. 
</details>

**Comment by ajayyy** [comment]
I'd be fine with a UI listing unsubmitted segments though in the options
