### ISSUE TITLE
Allow multiple highlights and downloading them

### ISSUE THREAD

**Issue by SameenAhnaf** [ajayyy/SponsorBlock#1007]
<b> Multiple highlights for a video: </b> Suppose, I'm attending a math class and 4 or 5 problems are solved and notes of those problems will have to be taken at seperate timestamps. As expected, a single highlight won't solve the problem unfortunately. Yes, highlight will be a specific timestamp with a single value. But I'd like to add such timestamps in multiple numbers.

<b> Download highlights of all videos in a playlist: </b>It'll be nice to easily download all highlights at once instead of downloading them seperately. All the highlights should be kept in a PDF file. Adding the video title and highlight timestamp will be a nice addition. (As I suggested in my previous para, every single video may have multiple highlights)

**Comment by ajayyy** [comment]
rejected

**Comment by ajayyy** [comment]
I am working on chapters btw #409

**Comment by SameenAhnaf** [comment]
That'll be an awesome addition, undoubtedly. However, my problem is different.

Taking frequent screenshots on desktop is quite tricky. I just want to select timestamps at once and get information about the full topic. This would remove a lot of hassle.
1. Taking screenshots now.
2. Save them with an appropriate name.
3. Compile into a PDF file.
