### ISSUE TITLE
Make a segment called "water" - Label enhancement

### ISSUE THREAD

**Issue by usera123ewqfd1234** [ajayyy/SponsorBlock#1008]
I have an idea, please add a segment with the name "Water", it will designate something that does not apply to video, for example, the topic of the video "How to learn to use the tablet", and there is "water" where the author tells, for example, "i am found this tablet that i was looking for it all my life and so on", this does not apply to the topic of the video, and the"important"segment will not miss, since "water" is in the middle of the video, in general "water" in the video on YouTube a lot, and if add this segment, then people will save much more time.

**Comment by usera123ewqfd1234** [comment]
No, this is not a joke. Let's draw an analogy with drinks, here we have half a mug of a drink, we do not have enough of it, but we need to give the drink to a person, we need to quickly pretend that the drink has filled the mug completely, we dilute the drink with water and now we have a full mug. Do you understand the analogy?

**Comment by mmomentum** [comment]
why not just call it "irrelevant" or "padding"? it is a good idea though, IMO. lots of videos do have a lot of padding to stretch them out for extra ad revenue

**Comment by ajayyy** [comment]
Ah, you mean filler stuff. We are actually discussing this on discord/matrix in #new-category-discussion
