### ISSUE TITLE
Cache prepared statements

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#102]
Right now they are created every time they are needed.

**Comment by OfficialNoob** [comment]
What about a in-memory database such as Redis? http://redis.js.org/

**Comment by ajayyy** [comment]
Sqlite is easier for others to use

**Comment by OfficialNoob** [comment]
client.set("string key", "string val", redis.print);
does not look hard

**Comment by ajayyy** [comment]
No, for other people to use this DB in their own projects.

Downloading one .db file and opening it is easy.

**Comment by OfficialNoob** [comment]
https://redis.io/topics/persistence you can have a file copy of the database

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlockServer/issues/109
