### ISSUE TITLE
Blank userID is causing set userID to be hidden

### ISSUE THREAD

**Issue by newmediacrew** [ajayyy/SponsorBlock#1025]
Hello,

When I try to submit a sponsor / promotion part of a YouTube video I get the message 

Server said this request was invalid Error Code: 400
Check status.sponsor.ajay.app for server status.
No valid userID field(s) provided.

Using macOS Monterey
Safari Version 15.1 (17612.2.9.1.20)
Sponsorblock for YouTube version 3.4.1

https://imgur.com/a/BqFSbol

Video trying to submit https://www.youtube.com/watch?v=yaG9mFlrB8k

**Comment by AronHK** [comment]
It seems like you have to be on the main server and it specifically has to be null, not empty. It doesn't hide on beta for some reason.
I randomly got a null userID while testing, but I'm not sure how..
