### ISSUE TITLE
SponsorBlock constantly either does not load segments or does not skip segments even if they are shown on the timeline.

### ISSUE THREAD

**Issue by McCaffeteria** [ajayyy/SponsorBlock#1030]
This issue is a duplicate of [#989](https://github.com/ajayyy/SponsorBlock/issues/989#issuecomment-954180560) because you pushed an update that did nothing, ignored everyone in the issue telling you it's not fixed, marked the issue as solved, and then continued to ignore the issue thread.

Please do not mark this issue as solved if the issue _isn't solved_ and don't mark this as a duplicate unless you _reopen the old issue._

When loading a youtube video the extensions sometimes randomly doesn't load segments. No green segments are shown on the timeline. When the video gets to a sponsored segment and doesn't skip it I interact with the SponsorBlock extension in any way (pressing the "Segment Starts Now" button is easiest because it is always visible, but "Open SponsorBlock Popup" functions identically), which seems to "wake up" the extension and the segments load in right away. If the video is partway through a segment as it loads in this way it instantly skips to the end of the segment as it should.

If the segments _are_ shown when the youtube video loads this does not mean they will be there by the time the segment is reached. If the video is refreshed for any reason (for example, by manually pressing the browser tab refresh button, or via another extension like Adblock for Youtube) there is yet another opportunity for the segments to fail to load.

Occasionally _even if segments are shown_ the video will just play through them, though this is rare.

**_PLEASE FIX THIS_**

I understand that bug fixing is difficult, and I want you to understand that I'm not saying to fix this _instantly_. I understand that's just not possible sometimes, especially if youtube is actively trying to prevent your extension from functioning. I also understand you have other priorities, there are lots of issues as it is here on the GitHub. I don't want to tell you what order you should be developing your app in.

What I _am_ asking is that you simply work on it until it _is_ fixed, however long that ends up taking. The last time I posted this issue you marked it as closed before actually verifying that it was solved.

It's not solved, it's still just as broken as it was a month ago, and it's still broken on both Firefox and Chrome as of v3.4.1, and it's still broken on Chrome (Haven't validated it on firefox and the person with the issue on firefox hasn't replied to the closed issue since) as of v3.5.1

Please actually fix this.

**Comment by ajayyy** [comment]
Blocked for being hostile
