### ISSUE TITLE
[not sure] beta is same as release (except name)

### ISSUE THREAD

**Issue by eladkarako** [ajayyy/SponsorBlock#1032]
<img src="https://user-images.githubusercontent.com/415238/139944186-da851998-54d3-4c2d-b279-6c38988c4978.png">

<img src="https://user-images.githubusercontent.com/415238/139944201-51bd9453-0de0-4c53-a02c-6361ce9b3128.png">

<img src="https://user-images.githubusercontent.com/415238/139944226-2ae43eff-d455-4364-9a4e-ecb8dd7b5d34.png">

**Comment by ajayyy** [comment]
yes
