### ISSUE TITLE
High CPU usage on Youtube Music

### ISSUE THREAD

**Issue by rohmishra** [ajayyy/SponsorBlock#1034]
Having the extension enabled on Firefox while listening to YTM results in significant CPU usage by extension.

Firefox Profiler:
https://share.firefox.dev/3CVLctC

**Comment by ajayyy** [comment]
duplicate of #501

**Comment by rohmishra** [comment]
Thanks! I dont know how i missed that, Its been a long day maybe i should really go to sleep now :P
