### ISSUE TITLE
"This song is unavailable due to copirasty" parts of the video

### ISSUE THREAD

**Issue by S-trace** [ajayyy/SponsorBlock#1035]
Hello.

Recently I have seen an unusual copirasty problem: 
The music video I watched was broken with the "This song is unavailable due to copirasty (WMG)" embedded directly in the video stream: https://youtu.be/UvMDCwW5tlk?t=6411 till https://youtu.be/UvMDCwW5tlk?t=6716

Should this new problem create a new category of segments ("No music (copirasty)") or not?

**Comment by ajayyy** [comment]
I don't know what "copirasty" is, but it probably is fine under the current non-music category
