### ISSUE TITLE
fixed segments that muted most of a video and now I cannot submit?

### ISSUE THREAD

**Issue by derpyderpaderp** [ajayyy/SponsorBlock#1040]
Their was a video where someone muted spots that weren't even sponsors so I made my own and disliked the muted parts in that video. Mine were quality and only muted the parts I considered to be a sponsor, self promotion, etc. Their is no way it was downvoted to the point that it did this, as I only removed segments not needed for the video. Someone is clearly abusing the like/dislike feature and it needs to be patched.

I should add I have been doing this same exact thing for a long time now and never had any issues, in fact I see most of the time the segments that were blocked were typically mine mixed in with others.

**Comment by ajayyy** [comment]
Please rephrase your thoughts clearly with examples. I do not understand anything you said

**Comment by derpyderpaderp** [comment]
Okay, I will try my best. Their were segments on a video that was muted that didn't need to be. It's a detailing channel and the only thing he was talking about was stuff he was using on particular part of the vehicle (Not sponsored by at all). These segments are used to inform on the type of product you should use on that particular part (More of a tutorial). So naturally I downvoted the segments. I then proceeded to block parts that were actually sponsors for example, products they sell/products they are sponsored by. Which is what this was intended for. I am now unable to submit because it says I am temporarily unable to submit segments because I did them wrong? I read through the link it popped up and I didn't do anything that should deem mine as wrong. 

I have been doing this for quite a while and didn't have any issues until this video. Which makes me believe someone is abusing your extension and getting people temp banned from submitting segments. It also didn't provide me with anywhere to counter these claims (which should be something added to a extension like this) and if it is should be in a more convenient spot.

**Comment by ajayyy** [comment]
Can you send the exact error message?

**Comment by mchangrh** [comment]
Oh, if you're talking about `TheDetailGeek` then I believe I warned you for using a skip "Interaction Reminder" over a visual indicator

**Comment by mchangrh** [comment]
The segments marked as sponsor are because he mentions that you can "check out the products I use in the description, which are amazon affiliate links"

>This includes:
> Advertisement of affiliate links

https://wiki.sponsor.ajay.app/w/Sponsor

I believe this is your userID?https://sb.ltn.fi/userid/b41ea10cc959403bbf185cbbed4c52c1dd8786862ee37618d997874f3eb62b09/

Warning Reason: 
```
https://sb.ltn.fi/video/QYNcniaofZo/
skip over content (mute already exists)

https://sb.ltn.fi/video/8Psl7MvnH3c/
two selfpromo that don't chain in place of one
```

**Comment by mchangrh** [comment]
resolved in discord, can be closed
