### ISSUE TITLE
Allow users to report segments via extension itself

### ISSUE THREAD

**Issue by Topkek-190** [ajayyy/SponsorBlock#1041]
Here goes nothing

The general idea behind this is to implement a report form in the extension. A user sees a wrong segment, clicks on report and gets a form for submitting a report. Once all the required details are filled in and the report is submitted, the report is forwarded to the communication servers(i.e. Discord/Matrix). The client extension keeps listening for notifications and when a report is approved and action is taken, the notification is entered into a queue. Whenever the extension goes online, the notification is forwarded to the user. If the the report isn't approved, a notification with a custom body can be sent to the user and the the user can be asked to join the Matrix or Discord for subsequent queries

**Comment by ajayyy** [comment]
That's what the vote buttons are for

**Comment by Topkek-190** [comment]
Exactly, but VIP segments cannot be downvoted by people other than VIPs themselves

**Comment by ajayyy** [comment]
Failed downvote are forwarded to a channel on discord, but since they are almost all wrong votes, it doesn't get looked at much unfortunately

**Comment by Topkek-190** [comment]
This is why I'm requesting a report form, since a written report has to be more concise than a downvote, the possibility of a report being wrong is lower than the possibility of a vote being wrong
