### ISSUE TITLE
Keep database of ReplayGain for YouTube videos

### ISSUE THREAD

**Issue by Svk1190** [ajayyy/SponsorBlock#1043]
YouTube normalizes the volume of loud songs, but does not normalize the volume of softer songs (as reported in https://www.meterplugs.com/blog/2019/09/18/youtube-changes-loudness-reference-to-14-lufs.html). So the user may find that different videos have different volumes, which might be a jarring experience. So it would be helpful if the user can select a "ReplayGain" button, which would calculate the ReplayGain of the video and upload it in the database. In future, when other users try to play this video, the volume would be automatically adjusted. The web version of YouTube supports volume modification inside the app without modifying the global volume. The Android app (YouTube Vanced or other apps) does not support individual volume control, so the volume adjustment would need to be done at a global level. 

It might be helpful to also include a local database for each user, where the user may finetune the volume as per personal taste and store the volume customizations for personal use (the personal database may also include personal segment skips for videos). The database can be exported from one machine and imported into another machine, where it can be merged with an existing database.

**Comment by ajayyy** [comment]
Out of scope

**Comment by sbrl** [comment]
A shame this is out of scope, it would be quite useful.
