### ISSUE TITLE
Skipping doesn't work 99% of the time

### ISSUE THREAD

**Issue by Bevan0** [ajayyy/SponsorBlock#1044]
I'm on Firefox (Linux 64bit) and sponsor sections don't autoskip. The "Segment starts now" button appears and the in-page popup works fine, even showing the sponsor segments. However, there are no coloured sections on the video player and autoskipping doesn't work. I tested on Firefox on Windows 10 and it works flawlessly.
Debug info:
`{
    "debug": {
        "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:94.0) Gecko/20100101 Firefox/94.0",
        "platform": "Linux x86_64",
        "language": "en-US",
        "extensionVersion": "3.6.1"
    },
    "config": {
        "previewCategoryUpdate": true,
        "segmentTimes": [
            [
                "jvFs9BidIGs",
                [
                    {
                        "segment": [
                            601.824727
                        ],
                        "UUID": null,
                        "category": "chooseACategory",
                        "actionType": "skip",
                        "source": 1
                    }
                ]
            ],
            [
                "oP1Oq3JLNbc",
                [
                    {
                        "segment": [
                            262,
                            325
                        ],
                        "UUID": null,
                        "category": "sponsor",
                        "actionType": "skip",
                        "source": 1
                    }
                ]
            ]
        ],
        "lastIsVipUpdate": 1636603532175,
        "isVip": false,
        "autoSkipOnMusicVideosUpdate": true,
        "categorySelections": [
            {
                "name": "selfpromo",
                "option": 1
            },
            {
                "name": "interaction",
                "option": 1
            },
            {
                "name": "sponsor",
                "option": 2
            }
        ],
        "hideVideoPlayerControls": false,
        "dontShowNotice": false,
        "minutesSaved": 328.1820510166668,
        "supportInvidious": true,
        "skipCount": 623,
        "defaultCategory": "chooseACategory",
        "whitelistedChannels": 0,
        "forceChannelCheck": false,
        "skipKeybind": "Enter",
        "startSponsorKeybind": ";",
        "submitKeybind": "'",
        "sponsorTimesContributed": 0,
        "submissionCountSinceCategories": 0,
        "showTimeWithSkips": true,
        "disableSkipping": false,
        "muteSegments": true,
        "trackViewCount": true,
        "trackViewCountInPrivate": true,
        "noticeVisibilityMode": 3,
        "hideInfoButtonPlayerControls": false,
        "hideDeleteButtonPlayerControls": false,
        "hideUploadButtonPlayerControls": false,
        "hideSkipButtonPlayerControls": false,
        "hideDiscordLaunches": 0,
        "hideDiscordLink": false,
        "invidiousInstances": 1,
        "serverAddress": "Default server address",
        "minDuration": 0,
        "skipNoticeDuration": 4,
        "audioNotificationOnSkip": false,
        "checkForUnlistedVideos": false,
        "testingServer": false,
        "refetchWhenNotFound": true,
        "ytInfoPermissionGranted": false,
        "allowExpirements": true,
        "showDonationLink": true,
        "autoHideInfoButton": true,
        "autoSkipOnMusicVideos": false,
        "scrollToEditTimeUpdate": false,
        "colorPalette": {
            "red": "#780303",
            "white": "#ffffff",
            "locked": "#ffc83d"
        },
        "barTypes": {
            "preview-chooseACategory": {
                "color": "#ffffff",
                "opacity": "0.7"
            },
            "sponsor": {
                "color": "#00d400",
                "opacity": "0.7"
            },
            "preview-sponsor": {
                "color": "#007800",
                "opacity": "0.7"
            },
            "selfpromo": {
                "color": "#ffff00",
                "opacity": "0.7"
            },
            "preview-selfpromo": {
                "color": "#bfbf35",
                "opacity": "0.7"
            },
            "interaction": {
                "color": "#cc00ff",
                "opacity": "0.7"
            },
            "preview-interaction": {
                "color": "#6c0087",
                "opacity": "0.7"
            },
            "intro": {
                "color": "#00ffff",
                "opacity": "0.7"
            },
            "preview-intro": {
                "color": "#008080",
                "opacity": "0.7"
            },
            "outro": {
                "color": "#0202ed",
                "opacity": "0.7"
            },
            "preview-outro": {
                "color": "#000070",
                "opacity": "0.7"
            },
            "preview": {
                "color": "#008fd6",
                "opacity": "0.7"
            },
            "preview-preview": {
                "color": "#005799",
                "opacity": "0.7"
            },
            "music_offtopic": {
                "color": "#ff9900",
                "opacity": "0.7"
            },
            "preview-music_offtopic": {
                "color": "#a6634a",
                "opacity": "0.7"
            },
            "poi_highlight": {
                "color": "#ff1684",
                "opacity": "0.7"
            },
            "preview-poi_highlight": {
                "color": "#9b044c",
                "opacity": "0.7"
            },
            "filler": {
                "color": "#7300FF",
                "opacity": "0.9"
            },
            "preview-filler": {
                "color": "#2E0066",
                "opacity": "0.7"
            }
        }
    }
}`

**Comment by mchangrh** [comment]
do you have any other extensions that interact with youtube?

any adblocks or youtube enhancers?

**Comment by Bevan0** [comment]
Just uBlock Origin and Decentraleyes. Decentraleyes says it isn't doing anything on the website.

**Comment by mchangrh** [comment]
do segment categories appear and can you go to `about:dbugging` and inspect sponsorblock?

**Comment by Bevan0** [comment]
The segment bars don't appear, no notifications. Creating segments also doesn't work, instead creates the segment 0:00.000 - 0:00.000.
It does show in about:debugging and I can inspect it.

**Comment by mchangrh** [comment]
can you post the debugging errors here in a codeblock ? (```/ triple backtick) or a pastebin? it sounds like it's having trouble getting the player element

**Comment by Bevan0** [comment]
```Error: Please use $(ref:runtime.getURL). main.js:59
The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page. 2
Use of nsIFile in content process is deprecated. NetUtil.jsm:253:8```

**Comment by mchangrh** [comment]
I think you either have another debugging tab or firebug open and it's not allowing console errors or logs to be displayed, can you try again or does it always show "web console logging api ... has been disabled"?

**Comment by Bevan0** [comment]
It always shows it.

**Comment by mchangrh** [comment]
Unfortunately, I don't think I'll be able to help you any further if it's not logging any errors.

you can try seeing if the video element is visible by running this in the console
```
const video = document.querySelector('video')
video.duration
video.currentTime
```

I think you might have very aggressive privacy settings or other plugins that are interfering with YouTube or SponsorBlock. I would suggest trying SponsorBlock in a new profile with just ublock origin and SponsorBlock and install your other addons until it breaks
