### ISSUE TITLE
Rejected Submit Sponsorblock

### ISSUE THREAD

**Issue by Zusyaku** [ajayyy/SponsorBlock#1046]
Hello admin why my account sponsor block cannot submit segmen and say in pop up

Can submit the segment
rejected by auto moderator

**Comment by ajayyy** [comment]
You probably got a warning. Could you join https://discord.gg/SponsorBlock or https://matrix.to/#/#sponsor:ajay.app?via=ajay.app&via=matrix.org&via=mozilla.org and send your public userID (see the username section)

**Comment by Zusyaku** [comment]
I didn't break any rules anything

and this my id and username you can check
https://pastebin.com/DRDxufmE

**Comment by ajayyy** [comment]
Please delete that pastebin if you can as that contains your private ID (it is your password for submitting).

Your warning was: Endcards not covering the end of videos (using round seconds or submitting on vanced)

Looks like a problem with your client. In future, please add a second to the end if submitting on Vanced to make sure the endcards truely reach the end of the video.

Your warning is now removed

**Comment by Zusyaku** [comment]
okah i will deleted
