### ISSUE TITLE
403 New submissions are not allowed for the following category

### ISSUE THREAD

**Issue by gzzz** [ajayyy/SponsorBlock#1049]
When I try to send one short segment of interaction, I get an error:

> 403 New submissions are not allowed for the following category: 'interaction'. A moderator has decided that no new segments are needed on this video and that all current segments of this category are timed perfectly.
> If you believe this is incorrect, please contact someone on discord.gg/SponsorBlock or matrix.to/#/#sponsor:ajay.app

What does it mean?
Why is the new segment unwanted, how can the "moderator" find out, and why does he decide it instead of the user?

**Comment by ajayyy** [comment]
That hostility is completely unnecessary. Please send the videoID and segment you think is missing to the discord/matrix listed above or via https://chat.sponsor.ajay.app
