### ISSUE TITLE
Server Issues with Sponsorblock (was: Sponsorblock segments were all removed by Youtube!)

### ISSUE THREAD

**Issue by TheRealHamtaro126** [ajayyy/SponsorBlock#1050]
I've come back to youtube to see that either Youtube removed all SponsorBlock segments (More likely), or Firefox might've outright rejected this extension (Very less likely, so I doubt it), Is there any hope to avoid sponsors after all this?

I am using the latest Firefox.

EDIT: mchangrh says it is a server issue, that explains a lot,

**Comment by mchangrh** [comment]
The server isn't tuned properly so there are some issues getting segments (actually happening)

**Comment by TheRealHamtaro126** [comment]
Thank you for telling me, I will be patient.

**Comment by mchangrh** [comment]
@ajayyy please close this
