### ISSUE TITLE
[feature request] add segment skipping for sections with music

### ISSUE THREAD

**Issue by InnerCato** [ajayyy/SponsorBlock#1051]
What if your listening to news or something like that and you want to skip a segment with music. currently there is no way except manually double tapping the screen to skip. Maybe you could make a new segment for skipping music?

**Comment by FlorianZahn** [comment]
Please provide an example video. How would this differ from the non-music category. Can you use the filler category?

**Comment by InnerCato** [comment]
Sorry for replying so late but the music section would differ from the non-music section because the music section would skip parts with music but the non-music section skips parts with music

**Comment by FlorianZahn** [comment]
Would the filler category apply?

**Comment by InnerCato** [comment]
Yes
