### ISSUE TITLE
[Feature request] Option to skip to second-to-last second of the video

### ISSUE THREAD

**Issue by voidless** [ajayyy/SponsorBlock#1052]
Please add option to only skip segments to second-to-last second of the video.
For example a video of length 4:32 has an ad at the end. I want it to be skipped only to 4:31, so the video plays the last second.

It will fix problems with greasymonkey scripts which disable youtube playlist autoplay.
The scripts check for the last second, and cannot do that if it is skipped.

Thank you!

**Comment by FlorianZahn** [comment]
This is not a sponsor block issue. I suggest you use this greasemonkey script instead:
https://greasyfork.org/en/scripts/415542-youtube-prevent-playlist-autoplay
