### ISSUE TITLE
SponsorBlock malfunctions when used through a third party website

### ISSUE THREAD

**Issue by Shadetail** [ajayyy/SponsorBlock#1055]
It seems that when next video gets loaded on [youtube-playlist-randomizer.bitbucket.io](https://youtube-playlist-randomizer.bitbucket.io/), the sponsor skipping data does not load or unload. It only gets loaded on the first video upon loading or refreshing the website, meaning that any subsequent videos will try to skip at the same locations, skipping over parts of the actual video. And if any segments that should be skipped exist in subsequent videos, they will not be skipped (unless they miraculously coincided with segments locations of the first video that was loaded).

I understand this is probably simply not supported and not really a bug, but I figured it might be worth mentioning as if support for this website or a general bugfix could be made or added, it would mean a lot for me due to ability to skip non-music segments rather than having to keep SponsorBlock disabled.

Reason I'm using this thirdparty website rather than youtube itself is that youtube playlist shuffle feature is so broken with large playlists that someone actually went and made this third party website to amend the issue.

**Comment by mchangrh** [comment]
It works on that site https://discord.com/channels/603643120093233162/603643180663177220/897933307390590976

resolution: 
> oh i just messed around with it a bunch and it was just because a lot of the skip settings were disabled, those settings just happened to have been changed right as i started using this playlist site
my bad, it does work, thank you very much

**Comment by ajayyy** [comment]
#150
