### ISSUE TITLE
Manual skipping current segment by a mouse click

### ISSUE THREAD

**Issue by coldner** [ajayyy/SponsorBlock#1056]
Currently, I can manually skip by keypress only. Is it possible to implement a button on a player which can be used for manual skipping?

**Comment by FlorianZahn** [comment]
https://i.imgur.com/VYDVQKg.png
Do you mean a button down there, which triggers a  manual skip?
In the options you can enable/disable skipNotices that pop up after skipping a segment, or when you can manually skip. They contain a button that can not only be triggered by pressing "enter", but also by clicking it with your mouse.

**Comment by coldner** [comment]
It's working. Thanks.
