### ISSUE TITLE
Make more white list of channel options

### ISSUE THREAD

**Issue by usera123ewqfd1234** [ajayyy/SponsorBlock#1058]
Make it possible to whitelist a specific segment category on specific youtube channel.
For example, I want on some YouTube channel to be able not to skip the "Filler" category, but I don't want to disable skipping of this category for all YouTube channels.

And make possible specific videos can be whitelisted.
For example, I want to be able to add a specific segment to the whitelist on a specific video without disabling the ability to skip it for all YouTube channels.

**Comment by mchangrh** [comment]
#435
