### ISSUE TITLE
Unchaptered video bug

### ISSUE THREAD

**Issue by erkinalp** [ajayyy/SponsorBlock#1060]
Skipped parts are not visible in an unchaptered video's timeline.

**Comment by mchangrh** [comment]
Could you please elaborate?

Segments on a unchaptered video have had both label on hover and the timeline overlay
https://www.youtube.com/watch?v=dNpQiljvmYg (intro + endcards)

**Comment by erkinalp** [comment]
Weird. Cannot reproduce now.
