### ISSUE TITLE
Localization is not displayed in the Safari version

### ISSUE THREAD

**Issue by rakleed** [ajayyy/SponsorBlock#1061]
Localization is not displayed in the Safari version. For example, if I set the Russian language in the Chrome settings, then the SponsorBlock interface is also displayed in Russian. But if I select Russian in the macOS settings, then in Safari, SponsorBlock will still display the entire interface in English.

macOS 12.0.1, SponsorBlock 3.4.1 for Safari.

**Comment by ajayyy** [comment]
Yep, need to do that. Right now it isn't due to https://github.com/ajayyy/SponsorBlock/issues/801 as Safari has a shorter word limit, so all the translation files are rejected.

**Comment by ajayyy** [comment]
Does it work properly on the latest version for you?

**Comment by rakleed** [comment]
Yes, on macOS and iOS.
