### ISSUE TITLE
Add a link to Crowdin to the README

### ISSUE THREAD

**Issue by rakleed** [ajayyy/SponsorBlock#1062]
Please add a link to Crowdin in the README so it can be easily found. And now I found out about this in a long-closed issue, which is very inconvenient.

**Comment by ajayyy** [comment]
There is. Search for "translate"

**Comment by rakleed** [comment]
@ajayyy I was able to find it, but it is very hard to see. Maybe you can add a little explanation to make it easier to find the translation link?

**Comment by mchangrh** [comment]
Maybe replace the `Important Links` link for wiki with the wiki main page?

https://wiki.sponsor.ajay.app/w/Main_Page

**Comment by rakleed** [comment]
@ajayyy it's just that most projects have information about the translation in a separate subheading in the README or CONTRIBUTING, which allows you to quickly find it. For example:
- https://github.com/darkreader/darkreader/blob/master/CONTRIBUTING.md#translation
- https://github.com/alyssaxuu/screenity#translating-screenity-to-other-languages
- https://github.com/syncthing/syncthing/blob/main/CONTRIBUTING.md#contributing-translations
