### ISSUE TITLE
Skip to Highlight disappears if Info button is set to not auto-hide

### ISSUE THREAD

**Issue by lord-blex** [ajayyy/SponsorBlock#1063]
Steps to reproduce:
1. Set _Keep Skip To Highlight Button On Player_ to ON
2. Set _Auto-hide Info Button_ to OFF
3. Load a video with a Highlight segment, wait for the full button with text to hide
4. There is no way to bring it back, though you can still click a small invisible button next to the timer

If I set _Auto-hide Info Button_ to ON, the skip to highlight button pops up each time I hover over the player controls, as normal.

**Comment by ajayyy** [comment]
This is the correct behavior. The option disables auto-hide for all buttons.

**Comment by lord-blex** [comment]
If it's affecting both the info button and the highlight button it should probably say so in the label.

In this case, the problem is that with auto-hide off, the highlight button is _still hidden_ and there is no way to make it appear.
Expected behavior would be that with auto-hide off, the highlight button would always be visible on the player.
(Assuming _Keep Skip To Highlight Button On Player_ is on.)

**Comment by ajayyy** [comment]
yea, forgot there is already a seperate option for it anyway

**Comment by lord-blex** [comment]
Sorry, now I'm not sure if we understood each other or not.
_Should_ both options affect the highlight button?

Either way, the steps outlined in the op result in unwanted behavior.
I recorded a video to illustrate: https://www.youtube.com/watch?v=jBRFkIbTh7w
From 0:00, when auto-hide is on, the highlight button also auto-hides, and hovering over the player brings it forth. This seems to be correct behavior, whether the auto-hide button should affect the highlight button or not.
Then at 0:18 I disable auto-hide, _keep highlight is still on_, but as you can see at 0:29, _it still disappears and cannot be brought back_.

I think switching to just the icon instead of the full button with text is good, even with Keep Skip To Highlight Button On Player. But the icon should remain visible, or it should appear when I hover.

**Comment by ajayyy** [comment]
Yea, I fixed it. That setting now doesn't affect highlight

**Comment by lord-blex** [comment]
Yeah sorry, I just noticed the linked commit. For some reason at first I only saw that the issue was closed.
