### ISSUE TITLE
Playback speed is not correctly taken into account for the remaining seconds of a skip notice

### ISSUE THREAD

**Issue by Sky-NiniKo** [ajayyy/SponsorBlock#1067]
When the playback speed is x2 for example the remaining time is divided by 2 but the timer also goes twice as fast so it's like dividing the time by 4. And conversely for a speed of x0.25. The remaining time will be multiplied by 4 but the timer will go 4 times slower so it's as if it was 16 times longer.
It is possible that it is a problem on my side but I tested with firefox and chrome and I have the same results.

**Comment by ajayyy** [comment]
Are you sure this isn't another extension. The time should not take into account playback speed

**Comment by Sky-NiniKo** [comment]
No, I use the built-in YouTube feature on a chrome with only SponsorBlock enabled.

**Comment by mchangrh** [comment]
This is how it is in the code

the **skipNotice** duration does not take into account playback speed if that's what you're talking about 

old example from the site
[![image](https://sponsor.ajay.app/new_notice.gif)](https://sponsor.ajay.app/new_notice.gif)

**Comment by mchangrh** [comment]
That's the only timer that came to mind, hopefully I'm not also misunderstanding

**Comment by Sky-NiniKo** [comment]
I have a hard time putting words to the problem so here is a video that I hope will be understandable.



https://user-images.githubusercontent.com/61370893/144016618-d75e6255-467a-43cc-a46e-1d5913851627.mp4

**Comment by mchangrh** [comment]
Thanks for the video! It is indeed the problem I described.

**Comment by mchangrh** [comment]
.take

**Comment by mchangrh** [comment]
https://github.com/ajayyy/SponsorBlock/blob/c3107ffcff63938a035ebe211f9de452b211f5ab/src/components/SkipNoticeComponent.tsx#L618 takes the playbackspeed into account but the timer is also running at playback speed
