### ISSUE TITLE
"Filler Tangent" skips overuse

### ISSUE THREAD

**Issue by usermyname12** [ajayyy/SponsorBlock#1068]
https://www.youtube.com/watch?v=Vxwx5VflRN4

https://i.imgur.com/xfaroU5.png

Some videos are meant to be funny. So i have 2 solutions: either disable sponsorblock for this channel or disable filler skips completely. None is ideal. The same happens to techlinked but to a lesser degree, I don't know how effective voting is and i don't want to waste my time downvoting 30 inputs.

**Comment by ajayyy** [comment]
That's the point of the category, disable it if you don't like it
