### ISSUE TITLE
[Feature request] Allow us to skip segments marked as mute

### ISSUE THREAD

**Issue by detogni-elia** [ajayyy/SponsorBlock#1075]
As the title says, it would be nice to be able to directly skip a segment that's marked as mute. Right now if i get a sponsor segment with no clear cut to a sponsor but only in the voice over, i have to stare at a mute video unless i decide to manually scroll to the end of the segment. I personally find the sudden loss of audio more annoying than the sponsor, it would be nice to just allow us to skip it altogether.

**Comment by mchangrh** [comment]
should this be split into 

- treating mute segments as skip
and
- adding skip/ unskip dialog to mute

**Comment by detogni-elia** [comment]
Yes that's basically what i had in mind. We could decide what to do with mute segments directly from the settings, but if someone has the option "treat mute segments as mute" and still wants to skip that part of the video, the skip button on the dialog would allow to do so.
