### ISSUE TITLE
[Feature request] After downvoting a segment, ignore it on the frontend for that user

### ISSUE THREAD

**Issue by tacohitbox** [ajayyy/SponsorBlock#1082]
If someone were to downvote a segment that didn't fit the video, ignore the segment addition for the user who downvoted it on the frontend.

**Comment by ajayyy** [comment]
Should be the current behavior

**Comment by tacohitbox** [comment]
it's not for me :/

**Comment by ajayyy** [comment]
It only works when using the skip notice right now, not the main info popup

**Comment by DShip91** [comment]
> It only works when using the skip notice right now, not the main info popup

Yeah, that's not true. I downvoted a segment using the skip notice but as soon as I refresh the video, the segment is back.
