### ISSUE TITLE
[Suggestion] Add comments for videos that have them disabled

### ISSUE THREAD

**Issue by flarn2006** [ajayyy/SponsorBlock#1084]
The idea is, if you're running SponsorBlock, then instead of just seeing a message saying comments are disabled, SponsorBlock would provide its own comment system as a replacement. It could work just like YouTube's built-in comment system, with the exception that comments would be submitted to and fetched from SponsorBlock's server instead of YouTube's. This would limit the ability of uploaders to prevent open discussion, as they might do if they're trying to hide something or mislead people.

It could also be useful for videos that have had comments forcibly disabled due to COPPA. I'm not sure whether this would result in legal trouble (you might not even be in the US) but there's probably something you could put in terms of use to avoid it, e.g. requiring 13+ age to use this feature even if it isn't actually enforced.

In addition, I'm pretty sure uploaders can remove individual comments even without disabling them entirely. Because of this, I think the SponsorBlock comment feature should be visible even on videos where comments are already enabled. This will ensure SponsorBlock users will always be able to post comments for other SponsorBlock users which cannot be censored by the uploader; it will also ensure SponsorBlock comments remain visible if comments are later re-enabled on the video.

Finally, depending on how far you want to go with this, you could also add an option (I'd recommend enabled by default, unless the userbase as a whole prefers otherwise) whereby SponsorBlock will detect when you post a regular YouTube comment, and mirror it to SponsorBlock as well, which would become visible when/if comments are disabled or that specific comment is removed by the uploader. Or perhaps even automatically uploading all comments that are loaded for preservation; I'm not quite as sure whether or not that's a good idea though because it would probably also result in a lot of spam being mirrored.

**Comment by ajayyy** [comment]
Rejected, I suggest a reddit comments addon

**Comment by DRSDavidSoft** [comment]
I've been meaning to ask this feature too -- although I don't really think this fits the SponsorBlock extension, but both points about disabled comments make sense.

@ajayyy Sorry to ask, but do you currently use such an extension? Or can you make a suggestion? A basic [Google Search](https://www.google.com/search?q=youtube+reddit+comments+addon) returns some addons

**Comment by ajayyy** [comment]
I do not

**Comment by chirag127** [comment]
> requiring 13+ age to use this feature even if it isn't actually enforced.

I think 13+ is already a requirement to sponsorblock , Atleast it was the last time I had read the toc of sponsorblock.
