### ISSUE TITLE
[Bug] Ad skips cause the Settings pop up menu to open

### ISSUE THREAD

**Issue by hardcoregandhi** [ajayyy/SponsorBlock#1097]
I'm seeing an issue where any skips made by the extension are also causing the players settings menu (the bottom right cog) to open each time.

**Comment by hardcoregandhi** [comment]
My mistake, even manual skips open the settings menu, very strange.

**Comment by ajayyy** [comment]
Can't reproduce on my end

**Comment by ajayyy** [comment]
This is a conflict with auto hd

**Comment by hardcoregandhi** [comment]
Can confirm I had AutoHD installed and it stopped when I disabled AutoHD
