### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by bamper45** [ajayyy/SponsorBlock#1107]
Sorry if the problem is in python or something else, but I can't figure it out, not in Windows, not in debian with this. In both systems, it says so.
![Снимок экрана от 2021-12-25 23-27-44](https://user-images.githubusercontent.com/77186394/147391420-4bd816c5-f7d7-484d-b80c-86e8c040ede1.png)

**Comment by ajayyy** [comment]
This is for the browser extension, not the mpv plugin
