### ISSUE TITLE
[Feature Request] New Category - Video Introduction

### ISSUE THREAD

**Issue by GeneralNitin** [ajayyy/SponsorBlock#1109]
It would be nice to have an option for skipping the intro as well.

**Comment by ajayyy** [comment]
What intro?

**Comment by SameenAhnaf** [comment]
I think, the issue is referring to auto-skip chapters like "Intro", not just animation. Duplicate of https://github.com/ajayyy/SponsorBlock/issues/493 then.

**Comment by SameenAhnaf** [comment]
I think, the issue is referring to auto-skip chapters like "Intro", not just animation. Duplicate of https://github.com/ajayyy/SponsorBlock/issues/493 then.

**Comment by GeneralNitin** [comment]
For segment submission, maybe we can add a new category "Intro". Users can submit the segment and in the settings, options can be similar to what we have for sponsors [Auto Skip, Manual Skip, Disable, Show in Seek Bar].

**Comment by SameenAhnaf** [comment]
Shouldn't this be closed in favor of https://github.com/ajayyy/SponsorBlock/issues/409??
