### ISSUE TITLE
Doesn't load on embedded playlists

### ISSUE THREAD

**Issue by Synetech** [ajayyy/SponsorBlock#1114]
This is a pretty useful add-on, but it doesn't work for embedded playlists. I've tested both
`www.youtube.com/embed/playlist?list=PL…`
and
`www.youtube-nocookie.com/embed/playlist?list=PL…`
but it doesn't work for either. In both cases, it just doesn't get loaded at all. I'm not sure why, since both URLs match the manifest's access request section. 🤔 Loading an embedded video on its own does work however, as does loading a non-embedded playlist. It's only this one permutation of embedded and playlist that fails. 😕

![SponsorBlock Doesn't Work for Embedded Playlists--](https://user-images.githubusercontent.com/5210197/147805148-af0cc662-f4cb-4694-81fe-79678e9359b2.png)

**Comment by mchangrh** [comment]
embedded playlists have to be done through something like #1070 since the videoID is not accessible from the URL

**Comment by Synetech** [comment]
True, but it's pretty easy to get. This is (a simplified version of) what I use in my YouTube user-script to get the videoID of the currently-playing video in an embedded playlist:

```
function getCurrentVideoID() {
	"use strict";

	//Get title element and its hyperlink
	let str = document.querySelector("div.ytp-title-text > a.ytp-title-link");
	if (!str) return null;

	//Extract videoID from YT hyperlink
	let vid = (str.href).match(/^.*(?:(?:youtu\.be\/|v\/|vi\/|u\/\w\/|embed\/)|(?:(?:watch)?\?v(?:i)?=|&v(?:i)?=))([^#&?]*).*/);

	return id ? id[1] : null;
}
```

**Comment by mchangrh** [comment]
```
 document.querySelector("[data-sessionlink='feature=player-title']")?.getAttribute("href");
 ```

just need to override the `/embed/` path and figure out how to get it to bind to the video player
