### ISSUE TITLE
Suggestion: Extract timestamps from comments

### ISSUE THREAD

**Issue by schorlton** [ajayyy/SponsorBlock#1117]
Thanks for an awesome extension.

Frequently, concerts and other videos have timestamps in the top rated (or one of the top 10) comments. Is it possible to extract these at all? Perhaps I've missed this?

Thanks!

**Comment by ajayyy** [comment]
Not really useful until after #1001 is done

**Comment by schorlton** [comment]
Thanks for such a quick response :smile:

**Comment by mchangrh** [comment]
can be closed now that #1001 has been merged
