### ISSUE TITLE
[Feature Request] Sponsorblock Bookmarklet

### ISSUE THREAD

**Issue by TheAlphaReturns** [ajayyy/SponsorBlock#1121]
On my computer, the extension sponsorblock is blocked by my admin. I was wondering if it was possible to make it a bookmarklet, so that once you clicked on it, configurable sponsor segments would be automatically or manually skipped.

**Comment by ajayyy** [comment]
It is possible to use some of the YouTube frontends with SponsorBlock built in https://github.com/ajayyy/SponsorBlock/wiki/3rd-Party-Ports#youtube-frontends

**Comment by mchangrh** [comment]
third party bookmarklet by yours truly - https://github.com/mchangrh/sb.js

It probably won't be possible for SponsorBlock to be fully integrated since assets can't be loaded and there is no way to access background scripts
