### ISSUE TITLE
PWA Support

### ISSUE THREAD

**Issue by afonsojramos** [ajayyy/SponsorBlock#1123]
When I install Youtube as a PWA with Brave Browser (have not tested with others), Sponsorblock does not work. Additionally, Enhancer for Youtube also has some bugs, but it does work, so is this related to Brave or the extensions themselves?

**Comment by ajayyy** [comment]
Seems to work fine for me with Chrome's PWA

**Comment by afonsojramos** [comment]
Not sure what happened, but I just retried and now it worked 🤷
