### ISSUE TITLE
[Feature Request] New Category: Custom 

### ISSUE THREAD

**Issue by bachig26** [ajayyy/SponsorBlock#1127]
I would like to have an implementation of a new category called "_Custom_" to Segment submission option for a wider range of time addition.
As there are many categories that are missing and the useable category is limited at some point.

If a category for custom nature is to be implemented, it can be used to input user-defined texts or categories. I believe with this idea, there is a huge problem with an exponential increase in unwanted segments relative to the topic. 
If possible, we can add a secondary gateway to verify (like the "if...else" conditional statement) this with the guideline before submitting to avoid this issue.

**Screenshots**
![690XKZvh4G](https://user-images.githubusercontent.com/96393348/148558150-f566ec55-23e6-46bc-a314-6155dddabfc7.png)

**Comment by ajayyy** [comment]
#1001
