### ISSUE TITLE
Store downvoted segments locally

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlock#1128]
Permanently store videoID + partialHash of downvoted segments.

#787 #733 #668

**Comment by mchangrh** [comment]
.take

**Comment by ajayyy** [comment]
I don't think it should stay in the info bar since we want the server to return the other options after a refresh if there are overlapping segments. I don't think it would make sense to also show the bad one.

**Comment by ajayyy** [comment]
We should just be able to store that data, then add it to the query when fetching segments. No client side filtering needed

**Comment by mchangrh** [comment]
how do we do serverside filtering with byHash?

**Comment by mchangrh** [comment]
closed in https://github.com/ajayyy/SponsorBlock/commit/4d60dec7f997bb076bfe7dc9d2b7079b96df3e95
