### ISSUE TITLE
Will not let me submit segments

### ISSUE THREAD

**Issue by clazarow1** [ajayyy/SponsorBlock#1129]
Hello,
I am having a hard time trying to submit a segment for anything when it's supposed to be skipped. I keep on getting the error message of 400, but I don't know what it means. If anyone is asking what version I am using, I am using the YouTube Vanced application. Can anyone help me with it? Thanks.

**Comment by ajayyy** [comment]
This is for issues about the browser extension

**Comment by clazarow1** [comment]
How am I supposed to add issues to the YouTube Vanced app for this application anyway?
