### ISSUE TITLE
Will not let me submit segments

### ISSUE THREAD

**Issue by clazarow1** [ajayyy/SponsorBlock#1130]
Hello,
I am having a hard time trying to submit a segment for anything when it's supposed to be skipped. I keep on getting the error message of 400, but I don't know what it means. Can anyone help me with it? Thanks.

**Comment by mchangrh** [comment]
400 means bad request and I would assume that you're missing your private userID

see #717.

go to options > import/export your userID 

and set a random 32 character password.

**Comment by clazarow1** [comment]
Thanks!
