### ISSUE TITLE
Mark whole video as Sponsor

### ISSUE THREAD

**Issue by DeFaLT-dj** [ajayyy/SponsorBlock#1131]
You know there are some videos made totally for a sponsor advertising a product etc. unlike the ones that appear in normal videos for few seconds/minutes. So, if the whole 10-minute video is made for just sponsor there should be an option submit it as we submit segments because submitting whole video as segment isn't convenient on this situation. So, when we submit a video as a sponsor it will notify the user when they enter the video for this is sponsored video and would they like to continue to watch it. I would want to share this because some videos make sponsored videos like it is their opinions on the product etc. and you only know it is a sponsored video in the middle or the end of the video.

**Comment by ajayyy** [comment]
This was added in 3.7 (in beta right now)
