### ISSUE TITLE
Skip does not work stably

### ISSUE THREAD

**Issue by swg-wl** [ajayyy/SponsorBlock#1132]
I use chrome, and sometimes it just doesn't skip the sponsor section, despite the fact that the rest of the functionality looks fine. If I immediately rewind the video after that just behind that sponsor section, it will skip as it should. It happens I guess once per 20 videos and only with the first section in a video. I don't see any patterns when it happens, but I think it doesn't happen when I interact with timeline at least once, maybe some scripts doesn't load or something. The only extensions I use that also interacts with youtube is "Video Speed Controller" and "uBlock Origin"

**Comment by ajayyy** [comment]
Blocked on their end https://github.com/igrigorik/videospeed/issues/683
