### ISSUE TITLE
Not Auto Loading & Can't add segment using Position (only typing the timecode)

### ISSUE THREAD

**Issue by TheSimArchitect** [ajayyy/SponsorBlock#1136]
Something is funny. Even when a video has a sponsored segment it only shows there's one if you click on the button to open SponsorBlock pop up and actively refresh by clicking on the refresh icon. Otherwise it acts as if there is no sponsored segment in your database (I am using Chrome Beta, 64 Bits, Windows 11 Insider Dev).

When I am watching a video and I position the cursor on the time to start and end a segment the button changes from start to end but a segment from 0 to 0 is created instead of using the time codes.

It doesn't make a difference if I simultaneously use uBlock or not. Refreshing the page doesn't work either.

I used the secondary test server for a while and the issue was the same (on top of the fact I could not benefit from your database of already set sponsor blocks or help most of the users with my own additions, I actually made several that are "lost forever"...).

Also, even if I refresh and the blocks are listed on your pop up, they don't show up in the timeline with different colors like before and aren't auto skipped.

Sometimes refreshing helps, sometimes it doesn't. Really weird behavior. I have YouTube Premium.

Anybody else with the same problem?

**Comment by ajayyy** [comment]
This is from YouTube's new preview-on-hover feature. Reload the page, then it should work. 4.0 fixes this, but is still rolling out

**Comment by TheSimArchitect** [comment]
> This is from YouTube's new preview-on-hover feature. Reload the page, then it should work. 4.0 fixes this, but is still rolling out

Thanks! How do I force my browser to update to 4.0?

**Comment by ajayyy** [comment]
If on Chrome, it is still being reviewed

**Comment by TheSimArchitect** [comment]
> If on Chrome, it is still being reviewed

Oh, I didn't know! Thanks a lot!!! I wish you an awesome 2022!!!
