### ISSUE TITLE
SponsorBlock for Apple TV

### ISSUE THREAD

**Issue by dmunozv04** [ajayyy/SponsorBlock#1139]
Hello, I created [iSponsorblockTV](https://github.com/dmunozv04/iSponsorBlockTV), a SponsorBlock client for Apple TV. It supports specifying different categories and skipping them. It works like the chromecast ports, by connecting to the device from a computer.

**Comment by ajayyy** [comment]
Nice, added to https://github.com/ajayyy/SponsorBlock/wiki/3rd-Party-Ports
