### ISSUE TITLE
Auto skip doesn't work in Safari when autoplaying in a playlist

### ISSUE THREAD

**Issue by richardsimko** [ajayyy/SponsorBlock#1142]
If you play a video in a playlist the skip works as expected, however when YouTube moves on to the next video in the playlist it doesn't work for that video (Or any subsequent video) unless you manually seek in the video or select a new video in the playlist.

Let me know if there's any way to enable debug info or similar.

Here's an example: https://youtu.be/i9St4aTUVis?list=PL17i3ijKy9Rcoui9uZ-tSwDH2j-mbgLw7&t=716

The timestamp is set just before a sponsor segment, which will be skipped. That video then ends shortly after and the next video has a sponsor segment near the start which will not be skipped.

**Comment by ajayyy** [comment]
Cannot reproduce on Chrome

**Comment by richardsimko** [comment]
Yeah I also couldn't repro in Chrome. Again let me know if there's anything I can do to help troubleshoot. I'm happy to check out the code and step through it if you can give me some pointers on what might be going wrong.

**Comment by asportnoy** [comment]
I can also reproduce this in Safari. It also applies to both autoplay and selecting a different video from the sidebar.

I am using Safari version 15.4 (17613.1.16.1.3) on macOS Monterey 12.3 Beta (21E5206e) with SponsorBlock version 4.1.3

**Comment by asportnoy** [comment]
After a lot of testing, I have narrowed down the issue. Some difference in Safari causes the video's `play` event to fire before the background script `update` event, whereas in Chrome `update` fires first. This makes `startSkipScheduleCheckingForStartSponsors` to run when `switchingVideos` is still true, causing the function to not run. Temporarily disabling this condition makes skipping work again.

I'm not sure how to fix the event order but I figured this information should help you take care of it.

**Comment by ajayyy** [comment]
Hmm, this is odd as on other browsers, `play` gets called multiple times, which is why the `play` during `switchingVideos` is blocked. I wonder if this only happens sometimes on Safari, or if it always happens and we can get away with just removing that check on Safari.

**Comment by asportnoy** [comment]
Depends on why the check was needed in the first place. I was going to start a PR (https://github.com/asportnoy/SponsorBlock/commit/e69f8955a684ce043e5f39f1973404ee33c7f194) to remove it but I wasn't sure why it was added. If you think it's not needed then I can modify my change to only apply on Safari and submit it.

**Comment by asportnoy** [comment]
I can confirm that `play` only gets called once, so I will modify my change and PR as mentioned above.

**Comment by richardsimko** [comment]
It works great now, thanks for the fix @asportnoy
