### ISSUE TITLE
Doesn't skip or mark segments in the video anymore

### ISSUE THREAD

**Issue by vmx-kbabenko** [ajayyy/SponsorBlock#1143]
Hi @ajayyy 

I've seen a similar report in the chrome store and you've requested some more information from the person who reported it.
What would you need to solve the issue? Please let me know so I can provide more information.

Currently, I can see that segments are in the database, but in the video timeline there are no markings:

![image](https://user-images.githubusercontent.com/25222177/149676335-224a9b5d-633d-453e-95d4-f3df48522648.png)
![image](https://user-images.githubusercontent.com/25222177/149676346-688b0aa9-e618-4c38-99df-bee705ffb1f5.png)

This is true for all videos, no exceptions. 
I am using Chrome 97.0.4692.71.

And thank you for your hard work!

**Comment by vmx-kbabenko** [comment]
Oh, and as you've mentioned, I do see this new feature "preview on hover". So this might be related.

**Comment by ajayyy** [comment]
Does it work after refreshing on the video page?

**Comment by vmx-kbabenko** [comment]
Nope.

**Comment by ajayyy** [comment]
Does it still autoskip the segments?

**Comment by vmx-kbabenko** [comment]
Also nope. So it seems it can reach the DB, but does nothing with the content.

**Comment by ajayyy** [comment]
Can you try this with other addons disabled?

**Comment by vmx-kbabenko** [comment]
Interesting. In a chrome with separate profile this did work. No other addons there. 
Let me try to uninstall-reinstall it and see if that helps.

**Comment by vmx-kbabenko** [comment]
Oh yeah, that indeed worked.
Should've tried that as the first step.

Please mark as solved and maybe it will be helpful to others.
