### ISSUE TITLE
Make it work on mobile devices

### ISSUE THREAD

**Issue by vitonsky** [ajayyy/SponsorBlock#1149]
Hi, make this addon work on mobile browsers. I use mobile firefox nightly to use addons and i add your addon to my custom collections, but i not see this in my addons list. A guess you just did not set checkbox "android" in platforms list when publish addon in addons.mozilla.org Please, do it to we can use this on mobile devices

**Comment by ajayyy** [comment]
It does work like this, I use it in Firefox nightly
