### ISSUE TITLE
Segments/Timestamps wrong once original video has been edited

### ISSUE THREAD

**Issue by RadicalGDPRist** [ajayyy/SponsorBlock#1151]
I opened a livestream video shortly after the livestream had ended ("2 hours ago", screenshot 1). The video was showing a run length of 1h8m. That's when I'd added an Intro segment of 20min - it had been a streamed segment of "Show starting in 22 min" countdown (not YT premiere)

A few hours later I've decided to watch the video (in browser). Now the Intro segment skipped a large part of the actual video, because the livestream was edited to drop the empty part at the beginning. (screenshot 2) Run length: 41m20s

I suppose a solution to this is to

1. Save and compare video length, discard segmentation data if length differs etc.
2. Save note that the video has been altered, for archival/verification reasons

This issue is similar in spirit to #367

![1 - video page 1h](https://user-images.githubusercontent.com/96452325/150921854-0c854bb5-0063-4d4e-a59d-6975cf446aaa.jpg)
![2 - new page 40min](https://user-images.githubusercontent.com/96452325/150921857-f106c926-f1c0-4fd6-84af-aed8d0773ced.jpg)

Player: YT Vanced, v.16.16.38 build 01.51.00

**Comment by mchangrh** [comment]
already implemented in https://github.com/ajayyy/SponsorBlockServer/issues/219

maybe possibly implemented as https://github.com/ajayyy/SponsorBlockServer/issues/446

**Comment by RadicalGDPRist** [comment]
No, `b6c1ee1` isn't related because this was a saved video at the time of first access (no longer a running livestream) unless I get the terminology wrong.

219 and 446 mean that my early incorrect submissions will be dropped once a viewer downvotes or submits new segments? I.e. the first viewer will always see wrong segments and it is \*action required\* to correct them? I thought the server could send video's length along with timestamps for non-interactive correction for edited videos:

1. User EarlyBird submits segments for video when it is 15min long
2. User LaraLate retrieves segments list, at this time the video is only 10min (shortened using YT video editor or something)
3. Had the server sent *last known video length* to Lara, her client would be able to verify that the saved segment list still applies to video as the length has not changed. No input required. If the video length differs, segments are dismissed & the client can inform the server about new, changed video length

I hope the description makes sense.

**Comment by mchangrh** [comment]
I know for a fact that the server send `videoDuration` alongside the segments, but I assumed that the client filtered segments by matching `videoDuration`, I guess it doesn't. I'll try to PR

**Comment by ajayyy** [comment]
It used to but was removed due to causing issues with it checking at the wrong time when the duration isn't loaded properly

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/commit/5adcec2ca5a88e48ba77192d71464a5f5a2b8eb6

https://github.com/ajayyy/SponsorBlock/commit/de607d317f31737b4cd9aece4240f1c115cc4c7b

**Comment by mchangrh** [comment]
I think the best option would still be https://github.com/ajayyy/SponsorBlockServer/issues/446

this wouldn't fix videos from vanced with 0 videoDuration but not like client side filtering would solve that anyways

**Comment by mchangrh** [comment]
this issue should have been resolved
