### ISSUE TITLE
Mobile YouTube whitelist doesn't work

### ISSUE THREAD

**Issue by yoasif** [ajayyy/SponsorBlock#1153]
Steps to reproduce:

1. Follow instructions on https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/ to install Sponsorblock 
2. Go to https://m.youtube.com/watch?v=xf_ReluPZf4
2. Go to add-ons, Sponsorblock
3. Tap the "whitelist channel" link

What happens:

I see an error message saying that the channel id is not loaded yet. 

Expected result:

The channel is whitelisted. 

---

Additionally, if you whitelist the channel in the desktop view and switch back to the mobile view, the whitelist does not work in that view (it works in the desktop view).

**Comment by mchangrh** [comment]
Have you tried `Force Channel Check Before Skipping` ?

mobile YT seems to use different attributes for channel name & logo

**Comment by mchangrh** [comment]
fixed in #1155
