### ISSUE TITLE
Color progress bar on thumbnail video on page scroll with SponsorBlock colors

### ISSUE THREAD

**Issue by NewsGuyTor** [ajayyy/SponsorBlock#1157]
It would be great if the progress bar on the small video player that appears when you scroll down could be colored with SponsorBlock colors/segments. 

See the attached video:

https://user-images.githubusercontent.com/19603024/151676782-29eb3d28-f79d-4462-8e4e-dcbaef362b64.mp4

**Comment by ajayyy** [comment]
Are you sure that isn't from an extension?

**Comment by NewsGuyTor** [comment]
Wow lol, I just tested it in another browser with no extensions. 

Mind blown, I've had it for so long that I've always assumed it's how Youtube.com works natively, turns out it was an extension called Enhancer for YouTube that did it.

**Comment by cyb3rko** [comment]
Then close it I guess, right?
