### ISSUE TITLE
never skip for youtube.com/clip/

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlock#1159]
clips should never contain skip segments since it was linked to that specific time
it also seems to break the UI https://discord.com/channels/603643120093233162/603643256714297374/938019615735431198, might be because it highlights the full video

**Comment by HugoHead** [comment]
youtube.com/clip/ redirects to the a channel called "clips" 

what are you referring to?

**Comment by mchangrh** [comment]
> youtube.com/clip/ redirects to the a channel called "clips"
> 
> what are you referring to?

Example: https://www.youtube.com/clip/UgkxeLPGsmKnMdm46DGml_4wd2dpAOIFJ65l

**Comment by mchangrh** [comment]
.take

**Comment by mchangrh** [comment]
YouTube doesn't send any events for going from clip to full video, the videoDuration is actually the length of the full video & the URL is likely random, it doesn't render any base64 results. videoID change is not triggered

if this ever changes, in theory it is possible to get the videoID from the ytCommand object created

```
ytWindow.ytCommand?.watchEndpoint?.videoId
```
