### ISSUE TITLE
Feature suggestion: add multiple highlight support

### ISSUE THREAD

**Issue by ignat980** [ajayyy/SponsorBlock#1160]
There is this music video about making several songs, in which they go over the process of making the songs, and then showcasing the songs themselves. [https://www.youtube.com/watch?v=UssVoHJ440w](https://www.youtube.com/watch?v=UssVoHJ440w)

It wouldn't make sense to skip the production process by marking it as non-music or intermission, but on a re-watch would be useful to have the timestamps to skip to the songs themselves. Only "Highlight" makes sense as a category for this, but you can only have one highlight on a video... which doesn't make sense in this case. And I think any video could have a bunch of highlights, key moments, and so on, especially if it is long. This is usually done via YouTube's Chapters feature, but not every video uses it, as you see here.

Please add this option :)

**Comment by ajayyy** [comment]
#1001
