### ISSUE TITLE
Idea: Tooltips for segments & video labels

### ISSUE THREAD

**Issue by Oliver-Saer** [ajayyy/SponsorBlock#1161]
This might be an unpopular opinion as the majority of the people who are browsing this repo's Issues page have probably also taken the time to read the Wiki.  But if we're being realistic, the average user hasn't done that and probably has no interest in doing so.

So to make it more accessible, there should be tooltips for the different categories which gives a quick and simple explanation of what they entail.

For example, [this video](https://www.youtube.com/watch?v=pqZFcrQTZ_E) has been labelled with 'Exclusive Access'.  What does that mean to the average user?  Does it mean they have been granted exclusive access to that content?  Does it mean the creator has some kind of exclusive access?

In addition, if someone wants to contribute, they might be totally unaware that there even _exists_ a Wiki which explains these terms, and might interpret the labels in a way which contradicts the official explanations on the Wiki.

If we want to maintain quality submissions, the information needs to be as accessible as possible.  Without any barriers to entry being imposed on making submissions, it's just not good enough to say "well they should read the Wiki", because they won't and there is nothing you can do to make them.

**Comment by ajayyy** [comment]
There is a tooltip on exclusive access. Hover your mouse on it

**Comment by Oliver-Saer** [comment]
Aha, I see that now.  Perhaps this could also appear when you click it?

**Comment by ajayyy** [comment]
Tooltip improved in 4.1
