### ISSUE TITLE
[feature request] make it easy to set 00:00:00 starting point for segments that starts from the very start of the video (one click)

### ISSUE THREAD

**Issue by eladkarako** [ajayyy/SponsorBlock#1166]
<details><summary>TL;DR</summary>

autoplay videos are too common,  
which means the video will not wait until I'll click but start playing, making me loose the starting point.

sometimes I also notice that the whole starting point should have been marked,  
which means I should reverse the video and carefully and quickly stop it as soon as possible to mark the start at 0.

there is the edit features, mostly just the more advance users are aware of it, 
which means there are a lot of videos starting at some weird starting point such as 00:00:01.

editing the text using the mouse is not that great either,  
I often just hold a mouse and prefer to cut the rest,  
instead of having to use the keyboard too (lazy..).
the youtube native popup menu starts up first, then I have to click again to get the normal menu,  

I've added a button to quickly just return `0`. similar to `end` and `now` that already present and saves me a lot of time. compiled locally, works great and saves me some time. 
(if `end` is ⏭, than this is ⏮).

</details>

https://user-images.githubusercontent.com/415238/152660562-604b57a5-b26a-483f-bceb-477576bb8a06.mp4

this is from a kids science show with extra long intro https://www.youtube.com/watch?v=B-SQvmMhvFE

https://user-images.githubusercontent.com/415238/152660569-92beae0c-f686-4ecc-bc2b-b0c7a6e12cad.mp4

<hr/>

<details><summary>those are the (very simple) modifications, if it interests you. I avoid pull requests like fire 🔥🔥🔥.</summary>
 

`public/_locales/en/messages.json` (add just above `"bracketNow": {`)

```js
"bracketZero": {
    "message": "(\u2205\uFE0E)"
},
```

`src/components/SponsorTimeEditComponent.tsx` (add just below `className="sponsorTimeDisplay">`)

```html
<span id={"zeroButton" + this.idSuffix}
  className="sponsorNowButton"
  onClick={() => this.setTimeToZero(0)}>
      {chrome.i18n.getMessage("bracketZero")}
</span>
```

and add this one just above `setTimeToNow(index: number): void {`

```js
setTimeToZero(index: number): void {
  this.setTimeTo(index, 0);
}
```

</details>

**Comment by eladkarako** [comment]
edit:
stopping the youtube player getting right clicks from the sponsorblock container:
https://developer.mozilla.org/en-US/docs/Web/API/Event/stopPropagation
(too lazy to open another feature request  😜)

**Comment by mchangrh** [comment]
#880
#960

**Comment by eladkarako** [comment]
that issue was closed, and the only reasons is that "it can be done otherwise", 
the combination of 3-4 clicks and relying on rewinding the video to the start is not efficient.
that zero button ease things up a lot!
but you can feel free to close it if you mark it "nofix". I still add it locally ;]

**Comment by eladkarako** [comment]
thanks I'm closing this one. and referencing some of its resources in the one that is opened.
