### ISSUE TITLE
ADD Mark (entire) video as clickbait

### ISSUE THREAD

**Issue by allanlaal** [ajayyy/SponsorBlock#1169]
use case:

this would be the opposite to the skip-to-highlight feature.
sometimes the video doesn't actually convey whats marked in the title/thumbnail and is just ≥99.99999% filler

Lets have a category for videos like these, so users can have SponsorBlock skip them (default: noskip)

not to be confused with `Skip to Highlight`:
https://github.com/ajayyy/SponsorBlock/issues/813
https://github.com/ajayyy/SponsorBlock/issues/806
https://github.com/ajayyy/SponsorBlock/pull/690

**Comment by allanlaal** [comment]
a bonus would be to see the video thumbnail crossed out with a red X or marked in some other way in every List view

**Comment by mirror176** [comment]
Don't forget to report and downvote (may need Return Youtube Dislike by [Dmitry Selivanov](https://addons.mozilla.org/en-US/firefox/user/17129231/) to get the benefit of that acction) clickbait when its actually incorrect images/titles/descriptions being used to get content views.
  Clickbait Remover for Youtube by [Pieter van Heijningen](https://addons.mozilla.org/en-US/firefox/user/15188538/) lets you replace thumbnails with an actual video frame and modify all caps titles to not be.
  I like the idea of modifying the thumbnail to have a sponsorblock marker to indicate its a video of a category. The idea of doing it would be a bit different from the real sponsorblock goal; doing so from database entries will require reading different entries for the video you are about to watch (presuming autoplay disabled), for every video on the end recommendation, for every video listed on the right of the video (below for small screens), and for every video in clickable popups within the video (at least the ones that are not part of the video). I'd take it even if it was just the main video thumbnail before hitting play, but I get a timebar already at that point too.
  This reminds me that it would be nice if sponsorblock had a way to send instructions to mask out parts of the screen or change resolutions to cause cropping for further adblocking. Then you get into more advanced topics like 'its moving, we need keyframes to mark positions to smooth track from a to b without frame by frame edits', can we have a series of mathematical tricks applied to subtract the mask from the video to alter it into overlay-free content by reversing a translucent overlay, substituting generated content, etc. so a black stationary shaped area isn't put in place. That would get advanced enough its probably best left to video editing software+an editor to do but it would be cool.
