### ISSUE TITLE
Tests fails due to popup

### ISSUE THREAD

**Issue by asportnoy** [ajayyy/SponsorBlock#1191]
The npm test script fails due to a YouTube toast/popup covering the sponsorblock button. If you can close the popup before the script tries to click the button the test will pass.

https://user-images.githubusercontent.com/14863373/153792848-52a6dd8b-8c77-4061-8e96-343c2f38e8d7.mp4

**Comment by ajayyy** [comment]
this may be fixable by zooming out as well
