### ISSUE TITLE
using an alt shortcut in windows makes it so that keyboard shortcuts for extensions don't work

### ISSUE THREAD

**Issue by WeebPiston** [ajayyy/SponsorBlock#1197]
Steps to reproduce:
1. Play a video
2. Alt+Tab into a different application or Alt+Tab into the browser
3. Wait for a segment
4. Shortcut to skip segment doesn't work

It doesn't seem to me that this is an issue specifically with SponsorBlock because i tried with other extensions and got a similar result. I tried to reproduce it in firefox and it worked as intended. So it seems to be a problem with chromium (I tried it in Brave and Google Chrome and ran into the issue).

**Comment by ajayyy** [comment]
Fixed in 4.1.3

**Comment by WeebPiston** [comment]
the fix doesn't seem to be working when the player is fullscreen

**Comment by ajayyy** [comment]
Are you on 4.1.3? Chrome is still taking a while to distribute it.
