### ISSUE TITLE
Support embedded videos

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#12]

**Comment by OfficialNoob** [comment]
Could I have a go?

**Comment by ajayyy** [comment]
Go for it :)

**Comment by OfficialNoob** [comment]
iframe problem

**Comment by OfficialNoob** [comment]
I think this can be closed as option 1

**Comment by ajayyy** [comment]
Yea, option 1. Maybe add a message to the popup saying that it only works on YouTube.

**Comment by OfficialNoob** [comment]
Thats not to do with this issue please close it only has permission for youtube.com anyway

**Comment by ajayyy** [comment]
You want to be unassigned?

**Comment by OfficialNoob** [comment]
Its done embedded videos are support using the global popup is not per video however its not needed anyway would be better as settings

**Comment by ajayyy** [comment]
Which pull request?

**Comment by OfficialNoob** [comment]
I think you added support when you added the button to the player

**Comment by ajayyy** [comment]
It's not working yet, but I'm going to do this now. I just have to change
the way the notice works and change the url parsing code.
