### ISSUE TITLE
(FEATURE REQUEST) Add support to auto-queue multiple part videos.

### ISSUE THREAD

**Issue by imBigo** [ajayyy/SponsorBlock#1201]
I'm not sure if this would be possible but I think this could be a really nice QOL feature.
Often multiple part videos are not labeled as such in the title and/or are hard to piece together for the user since often the creator didn't make a special playlist for the series.

**Comment by ajayyy** [comment]
How would this differ from user-created playlists that YouTube offers?

**Comment by imBigo** [comment]
Technically I guess it would be basically the same. 

My issue is that finding such user-created playlist is often tedious and often gives lackluster results. A lot of times these playlists are not kept up to date and may not be in the right order.

It would be nice if we could have some sort of community effort to have "official playlists" that are in order. These playlists could then be loaded automagically if the user has this option enabled and/or add a title card with the part number as a title card just like you're doing with sponsored videos.

**Comment by ccuser44** [comment]
I disageee. Youtube playlista already do this. Besides this is a blocker / video skipper / whatever. Not a playlist extension
