### ISSUE TITLE
[feature request] YouTube starts playing before SponsorBlock has a chance to skip (stop autoplay workaround).

### ISSUE THREAD

**Issue by eladkarako** [ajayyy/SponsorBlock#1214]
a race between YouTube autoplay and SponsorBlock (usually autoplay wins 😥)

<details><summary>example</summary>

https://user-images.githubusercontent.com/415238/156748325-fe757277-e1d3-4f8e-bf40-b91ea7b367c7.mp4

</details>
<hr/>

<details><summary>possible workaround (stopping autoplay)</summary>
<ol>
<li>

Firefox and Edge can control autoplay using the UI.  
until a click/keypress calls to `.play` will be rejected.

</li>
<li>

Chromium has no autoplay control in the UI, but Windows builds would support a global policy (registry)

```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\Software\Policies\Chromium]
;"AutoplayAllowed"=dword:00000001
"AutoplayAllowed"=dword:00000000
```

see `policy_templates.zip` at  
https://github.com/Hibbiki/chromium-win64/releases/tag/v102.0.5005.63-r992738  

it would effect every website, every chromium browser, and every user on the machine.

</li>

<li>

a web-extension can inject `feature-policy` http header with `autoplay 'none';` with `declarativeNetRequest` permission.  
https://html.spec.whatwg.org/multipage/infrastructure.html#autoplay-feature  
it isn't well supported yet.  

</li>

<li>

custom autoplay polyfill. restrict 
`HTMLVideoElement.prototype.play` by default, and re-allow based on user interaction.  
https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play  

</li>
</ol>
</details>

**Comment by NDevTK** [comment]
Simple to implement via playbackRate if all you wanted was a delay until the times are loaded.

**Comment by eladkarako** [comment]
> playbackRate

an alternative. not a great one though.  

<details><summary>thoughts.</summary>

- due to video start playing, the first key-frame (I-FRAME) will always be shown (ads/sponsor).  

- blocking `play` would keep showing the whatever is in the `poster` attribute (or the cover image the custom player template is set to, a high resolution version of the thumbnail, mostly).

- there is a rate control as part of the UI, which means a user can change it manually: `0.5-2.0`,  
or for the player to override the current value based on stored configuration (although to be fair I don't think the rate value is "a sticky configuration",  
I think it resets to `1.0` for each single video playing.  
not 100% sure how it is being handled in playlists,  
but I believe it is stored as part of the player configuration for the current session,  
and the player is keeping refreshing the UI every 50ms,  
and its values are based on that short-term configuration for that session  
(this is way the player is so robust,  
and know to restore the playing position (for example) when you go back and forth from the video, or the page goes offline/online, the update is done by a background worker and can not easily be overridden).  

but mostly, to put it simple,  
the rate delay method collides with a standard feature,  
which is not a great practice.

- "messing around" with `.play()` has a better support through the native <del>video</del> object, which is as low level as you can get. `play` returns a rejected promise, just like a video is playing on Firefox with autoplay set to false, player state is kept "not playing".

- in both scenarios (play override and rate set to almost zero),  
optimal "restoring functionality back to normal" case will still be SponsorBlock acknowledge success/fail(timeout), if this "playing delay" "thing" is part of the SponsorBlock core, its fine,  
but otherwise - a custom event needs to be exposed on the page to allow "3rd-party extensions to SponsorBlock" (which is not a thing.. AFAIK) would be able to figure out if it is ok to "remove the play block" or "set the rate to 1.0" (or whatever the custom rate was before.

either way we look at it,  
the player playing process needs to depend on SponsorBlock,  
I.E. synchronous actions, with possible fallback in case of a timeout to a previously fetched data stored locally (session storage) - "SponsorBlock offline mode" (which isn't "a thing"),  
or, on the lack of it, just plain playing.


good brainstorming material.
a lot to think about.  

</details>

**Comment by NDevTK** [comment]
Probably worth checking why a video can load faster then sponsor times :)
Adding a delay would make the performance worse.

**Comment by ajayyy** [comment]
The kubernetes server deployment fetches stuff a lot faster, so this might be less of an issue once I'm done migrating. Right now, requests sometimes take up to a second at peak time, which causes this effect

**Comment by eladkarako** [comment]
it is also possible to pre-fetch stuff.

most of the navigation on YT is ajax based (polymer),  
you can listen to `ytd-app`, `yt-navigate-start` (custom) event.  

<img width="929" alt="2022-05-18_022523" src="https://user-images.githubusercontent.com/415238/168928329-40d1105f-d64c-41d0-8d76-9e6715301eab.png">

and you'll have 1-10 seconds to fetch whatever you'll like in the background, while the DOM renders.

store the data in a web-extension storage,  
instead of directly modifying the DOM (since it hasn't been updated yet),  
then when the page is ready, all is left to do is to read the data from the storage, 

if you wish, you can even probably update the player before the video-source had a chance to start preloading.

there is a bonus, in-case of a timeout, the existing data is just used seamlessly, and just like that you can make the web-extension super robust.

you can trigger an update as often as you'll like to.  

the storage acts as a middle-man.

**Comment by ajayyy** [comment]
Right now it is based on the URL, which does give it a lot of time before the DOM changes

**Comment by pc00per** [comment]
[An extension might help?](https://chrome.google.com/webstore/detail/youtube-no-buffer-stop-au/afgfpcfjdgakemlmlgadojdfnejkpegd/related?hl=en)

**Comment by SebTota** [comment]
Instead of pausing the video until we get the response from the API call, can we instead preload and cache the next videos sponsor details if AutoPlay is on and < 5 seconds is left in the video? I know this wouldn't solve all the issues of the response coming after the video starts, but it would at least solve the autoplay issue.

**Comment by eladkarako** [comment]
the response time is not the cause,  
it is because there are two async actions trying to happen in the same time,  
playing video and api response,  
microsecond delay of the api call will make the play go first,  
that is not a good design,  

the play should always be in-sync, I.E. after, the api call,  
in worst case, delay to amount of time pre-defined until the api call should be canceled and declared as not-available (max 5 seconds limit),  
instead of letting the network implementation throw timeout.

several ways exists to cache existing, previously fetched data,  
from plain cache headers with stale notifications, to local-storage keeping previous calls as a fallback to timeout.  

all those were suggested before and rejected.  
this is why I've suggested to add autoplay stopping as a generic solution. 

that said it doesn't seems to be any clear solution so I'm closing it for now,  
users of edge or firefox can define youtube.com to not have auto-play allowed,  
and it is good enough solution.
