### ISSUE TITLE
Total overlap of manual and automatic skip is not handled correctly

### ISSUE THREAD

**Issue by erkinalp** [ajayyy/SponsorBlock#1219]
Expected: When there are two segments with exactly same boundaries, one auto-skipping, and other manually skipping, auto-skip happens
Actual: It prompts for manual skip instead

**Comment by ajayyy** [comment]
Example?

**Comment by mchangrh** [comment]
it auto-skips just fine
https://www.youtube.com/watch?v=KPqtlI3aJIE
