### ISSUE TITLE
Allow to manualy skip video segments with a touch screen on m.youtube.com

### ISSUE THREAD

**Issue by Sitavi** [ajayyy/SponsorBlock#1229]
I can't click on the popup to manually skips segments using m.youtube.com and firefox on mobile.
![Screenshot_2022-03-15-11-41-48-366_org mozilla fennec_fdroid](https://user-images.githubusercontent.com/80586127/158361154-692a414b-4b2f-430e-a470-a32954de0e1d.jpg)
![IMG_20220315_114300](https://user-images.githubusercontent.com/80586127/158361179-703d7569-e137-4fb8-a683-d28f4400635d.jpg)

**Comment by ajayyy** [comment]
What's the issue?
