### ISSUE TITLE
[Feature Request] Make a userscript

### ISSUE THREAD

**Issue by AMTitan** [ajayyy/SponsorBlock#1231]
I think this would be helpful for people who want to use sponserblock in tampermonkey / greasyfork. This would also be helpful for people using qutebrowser and this is the reason I am asking for it.

**Comment by ajayyy** [comment]
One option is to use an alternative YouTube front end: https://github.com/ajayyy/SponsorBlock/wiki/3rd-Party-Ports#youtube-frontends

**Comment by AMTitan** [comment]
well I would prefer to have a userscript but I will use these as of now

**Comment by mchangrh** [comment]
third-party userscript clients

https://github.com/afreakk/greasemonkeyscripts/blob/master/youtube_sponsorblock.js
https://github.com/mchangrh/sb.js
