### ISSUE TITLE
[UI] setUsername button clips into username 

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlock#1235]
it seems like
```css
margin-right: 8px;
```
is somehow being overridden by another CSS rule, causing the pencil icon to clip into the username

![image](https://user-images.githubusercontent.com/15132783/159096914-49ad523c-127d-41d4-aeb9-92e54f24cc72.png)

**Comment by AlecRust** [comment]
This is fixed in #1237.
