### ISSUE TITLE
Time without skips on mobile

### ISSUE THREAD

**Issue by JustCauseWhyNot** [ajayyy/SponsorBlock#1236]
I've noticed on the mobile youtube site that the time after skips removed in the seekbar doesn't appear. Despite having the option enabled, and when forcing desktop site the time shows up properly. I'm using the mull web browser, and have sponsorblock loaded. To reproduce go to this link https://m.youtube.com, and load up any video with sponsorblock skips.

**Comment by mchangrh** [comment]
.take
