### ISSUE TITLE
[Feature Request] Anti Clickbait Title

### ISSUE THREAD

**Issue by KrimFandango** [ajayyy/SponsorBlock#1241]
A secondary togglable user-generated title that sums up the video.

Example:
Original title: How much RAM is enough for gaming?
Anti clickbait title: 8GB is enough for 95% of the game, 16GB is enough for all games (because that's what the video author said)

Original title: You won't believe who won this challenge
Anti clickbait title: Andy won with 15k score

This way people would click on the videos they actually want to watch
It can already use a lot of sponsorblock features

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/1211

**Comment by AdasAdasiek** [comment]
thats not a clickbait.
