### ISSUE TITLE
Support submiting segments for piped frontend for youtube

### ISSUE THREAD

**Issue by ghost** [ajayyy/SponsorBlock#1243]
I use [piped](https://github.com/TeamPiped/Piped) for watching youtube videos on the web (similar to invidious) and it would be really nice if i was able to submit segments while watching on piped (skipping segments already works).

**Comment by mchangrh** [comment]
The browser extension seems to pick  up the video and the times for it, the issue seems to be the submit popup not appearing

**Comment by ajayyy** [comment]
Not sure how to handle the fact that it will also be trying to auto skip at the same time

**Comment by BobIsMyManager** [comment]
I just disable the built in piped sponsorblock setting

**Comment by FireMasterK** [comment]
Hi, I'm interested in helping enable this from Piped's side, Piped's embedded SponsorBlock can be disabled by adding `&sponsorblock=0` or setting `sponsorblock` in the `localStorage`. If there is any runtime way to detect if the extension is installed, I could automatically disable the embedded version.

From my testing, the extension does not currently detect any video:
![image](https://user-images.githubusercontent.com/20838718/196068115-24773632-45cd-4f10-a5db-3f0e01905cad.png)

**Comment by mchangrh** [comment]
The way I do it with SB.js is to look for the SponsorBlock preview bar bushings, I'll try to dig up the specific code

**Comment by mchangrh** [comment]
It might not find it if 3rd party website support is not enabled

**Comment by FireMasterK** [comment]
> It might not find it if 3rd party website support is not enabled

I think you're right, after enabling that, it started skipping them correctly. However, the seekbar has no colored segments.

Piped manually generates some CSS for shaka-player like so:
https://github.com/TeamPiped/Piped/blob/67aaa00ff34c1de385473e7e0c194819273bca35/src/components/VideoPlayer.vue#L572-L623

**Comment by ajayyy** [comment]
Also no skip notice, so it is probably missing an attachment point for that too

**Comment by mchangrh** [comment]
Here's the code for sb.js extension detection

```js
if (document.querySelector("#previewbar")) // exit if previewbar exists
    return console.log("[SB.js] Extension Present, Exiting")
```
> [src](https://github.com/mchangrh/sb.js/blob/e2c25bd5f5190f340a93a9128879ea7d14bf9a3b/src/sb.js#L145-L146)

**Comment by ajayyy** [comment]
Right now there is no preview bar though since it doesn't attach

**Comment by FireMasterK** [comment]
> Here's the code for sb.js extension detection
> 
> ```js
> if (document.querySelector("#previewbar")) // exit if previewbar exists
>     return console.log("[SB.js] Extension Present, Exiting")
> ```
> 
> > [src](https://github.com/mchangrh/sb.js/blob/e2c25bd5f5190f340a93a9128879ea7d14bf9a3b/src/sb.js#L145-L146)

I feel like this may cause issues if Piped initializes the player before sponsorblock injects itself onto the page, is there any other way to do so?

**Comment by mchangrh** [comment]
> I feel like this may cause issues if Piped initializes the player before sponsorblock injects itself onto the page, is there any other way to do so?

there is a isVisible awaiter like there is for invidious

**Comment by mchangrh** [comment]
@FireMasterK what would be the best way to handle piped v sponsorblock conflicts? Maybe we can only trigger on ?sponsorblock=false links if the piped ad marker is present?

**Comment by FireMasterK** [comment]
We've got that, and the `sponsorblock` localStoage value too!

If the extension works properly in the future, I would consider disabling the embedded SponsorBlock implementation if the extension is detected.

**Comment by mchangrh** [comment]
I'm trying to work out conflict detection - I think if might be better for piped to handle it as SponsorBlock can only set the localStorage values and can't handle any url overrides

**Comment by mchangrh** [comment]
Just for future reference - here are the selectors I'm targeting for piped
Controls - `.shaka-bottom-controls`
Video Container - `.shaka-video-container`
