### ISSUE TITLE
How to dispute a segment? I think it was cut for political reasons

### ISSUE THREAD

**Issue by Voha888** [ajayyy/SponsorBlock#1244]
Lately I've started noticing that in the videos of Russian-speaking bloggers, parts related to the war in Ukraine are cut off. They were small pieces. But in Dmitry Bachilo's video, a significant part is cut off, which is designated as "intro-animation". Firstly, this is not true, and secondly, in this segment (the first 5 minutes of the video), he tells his position on the war in Ukraine - and it seems to me that this was done for political reasons by some users of this extension.

Link to the video https://youtu.be/tlKhvsMsqq0 (this is not an advertisement)

**Comment by ajayyy** [comment]
Discord or Matrix

banned them

**Comment by matthieugouel** [comment]
I just noticed this practice of using SponsorBlock to block segment for political reasons.

I wonder if it would be possible to detect this. 
I'm not familiar with the content of SB database but I guess it would be difficult, without relying on downvotes or Discord / Matrix reports.
