### ISSUE TITLE
channelID lookup optimizations

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlock#1249]
- [x] currently working on this

cc @zedseven

**Comment by mchangrh** [comment]
.take

**Comment by zedseven** [comment]
.take

**Comment by mchangrh** [comment]
## Selectors
### in-video
`.ytd-channel-name a`
- unreliable
- multiple results
- top results is hidden home screen

`.ytd-video-owner-renderer a`
- reliable
- specific to channel box
- reliable even in fullscreen and changing videos
### embed
- already reliable as-is

**Comment by zedseven** [comment]
To see the unreliability of the `.ytd-channel-name a` selector, open a fresh tab and in the Home tab select a video that's from a different channel than the first result in the Home tab.

Once the video is loaded, run `document.querySelector('.ytd-channel-name a')` in the console - you should get the custom channel URL for the first Home result, not the channel of the current video.

Running `document.querySelectorAll` shows this selects all Home nodes.

Also, somewhat unrelated, but it seems like the custom channel URL is only used in the Home tab. For the channel links on active videos, it seems to always be the channel ID. This means that user channel overrides that use the custom URL (likely) have never worked and will not work after this is fixed.

**Comment by zedseven** [comment]
The regex can also be more strict, handling trailing slashes and absolute/relative URLs as well. Using the capture group as the channel ID instead of replacing the non-channel ID parts, the following should work in all tested scenarios:
`\/channel\/(UC[a-zA-Z0-9_\-]{22})`

**Comment by zedseven** [comment]
Also the Invidious selector should probably select based on the `#channel-name` instead of `.channel-profile` - there were several instances of `.channel-profile` in my testing but only one `#channel-name`.

Something like `document.querySelector("#channel-name").parentElement.parentElement` should do the trick.
