### ISSUE TITLE
Late skip with changed playback speed

### ISSUE THREAD

**Issue by Danstiv** [ajayyy/SponsorBlock#1253]
This problem is observed when using the Video Speed ​​Controller extension, when changing the speed using youtube player settings, everything seems to work correctly.

### Steps to reproduce
1. Open any video with a sponsored insert (for example, [this](https://www.youtube.com/watch?v=gTkyBYRmIm8)).
2. Change speed for example to 2.2 using Video Speed ​​Controller extension.
3. Keep watching until sponsored insert.

### Actual behavior
Sponsored insert will be skipped a few seconds after it starts.

### Expected behavior
The sponsored insert will be skipped from the beginning.

### software
Windows 10 21H1 (x64) build 19043.1526
Google Chrome 96.0.4664.45.
SponsorBlock 4.2.
Video Speed Controller 0.7.1.

**Comment by ajayyy** [comment]
#359

If you use that extension, pause and unpause after changing the playback speed
