### ISSUE TITLE
Submission cache

### ISSUE THREAD

**Issue by RubenKelevra** [ajayyy/SponsorBlock#1254]
The submission server has had quite a lot of outages in the last time. Would be nice to have the add-on just store the submissions if the server respond with an error and just retry it after some hours again without user interventions.

**Comment by ajayyy** [comment]
It does keep submissions stored, but I don't want to autosubmit and there would be lots of duplicate segments that would need to be cleaned up

**Comment by RubenKelevra** [comment]
@ajayyy I think you misunderstood the request. :)

If the user is hitting "submit" it's currently submitted in a foreground process. So if it fails, the user has to try again manually.

It would be nice if a submit would just put it on a queue and submit the data in the background. So it's stored permanently in the add-on for submission and the user doesn't have to care about bad connectivity or a backend having a maintenance.

As the segment is showed instantly to the user, I don't think there's a chance that a user is recreating it again. Or if that's about possible erroneous retransmissions from add-ons to the server: This is impossible, as the server will forbid any submission with the same values :)
