### ISSUE TITLE
Error code 504

### ISSUE THREAD

**Issue by Mubelotix** [ajayyy/SponsorBlock#1255]
Alert message says "Error code 504, check status.sponsor.ajay.app for server status" when trying to submit segments.

Except it does this all the time. It has been a whole week since I have been unable to submit new segments.

**Comment by ajayyy** [comment]
Bad timing

**Comment by Mubelotix** [comment]
Can't we do anything to help with servers?

**Comment by ajayyy** [comment]
I'm waiting to find some time to work on it
