### ISSUE TITLE
[Feature request]Speed controls for some channels

### ISSUE THREAD

**Issue by chetanbasuray** [ajayyy/SponsorBlock#1262]
Hi,
There are some channels which are always really slow and I am generally speeding up the channels to 1.75x or 2x the normal speed when watching these channels and I was wondering if such a custom setting can be put into this extension. Then I could set up the channels I am watching at the speed and I would not need to do it everytime. If you are interested in a feature like this, let me know and I will be happy to help in any way I can.

**Comment by mchangrh** [comment]
I don't think this is in scope for SponsorBlock, you might be able to fork for your own use and take a look at the channel fetching like in #1258 but speed, especially on the scale of channels is way too subjective

**Comment by chetanbasuray** [comment]
Ok, in that case I will close the issue here
