### ISSUE TITLE
[Idea] Dead Air segment category 

### ISSUE THREAD

**Issue by Gloomy64** [ajayyy/SponsorBlock#1271]
I've noticed that there's no category for marking down segments of videos that are just dead air (nothing happening in the video/no audio) I think it'd be a very useful category to add especially for people like me who watch a lot of re-uploads of streams where the parts where the streamer goes AFK are left in and there's nothing happening on screen (no cam, no chat, no gameplay, no audio etc) for more than a few seconds.

**Comment by ajayyy** [comment]
Intermission
