### ISSUE TITLE
Two manual skip prompts for segments at the start of the video

### ISSUE THREAD

**Issue by DivyanshByte** [ajayyy/SponsorBlock#1281]
So If there is a non-music section for a music video in the database it will show two popups for it
![Screenshot 2022-04-13 at 3 52 11 PM](https://user-images.githubusercontent.com/57246976/163157893-abdc3629-c35a-46f9-85fd-7c16ee58d767.png)

Also pressing the enter button will cause only the above one to show unskip button

**Comment by mchangrh** [comment]
I think this might be related to #1263

**Comment by ajayyy** [comment]
Fixed the symptom https://github.com/ajayyy/SponsorBlock/commit/0c216792cf1737e13e358411902f4b77dce1725e

**Comment by DivyanshByte** [comment]
Thanks, Closing this issue
