### ISSUE TITLE
Allow per-category channel whitelisting

### ISSUE THREAD

**Issue by Oliver-Saer** [ajayyy/SponsorBlock#1282]
I'd like to propose a whitelisting system which allows you to whitelist certain categories for a given channel, but keep others blacklisted.

<details>
<summary>Use Case</summary>

For me personally, I'd like to whitelist LinusTechTips on Unpaid/Self-Promotion because the sly "lttstore.com" quips are quite funny and don't take up a lot of time.

But other people go on a several minute long tirade about their merch store or spend ages promoting their friends, so I wouldn't want this option globally not skipped.

Equally, LinusTechTips always have a sponsor spot which I want to be able to skip, so just whitelisting their whole channel isn't something I'd like to do.

</details>

<details>
<summary>Workaround</summary>

Just put Unpaid/Self-Promotion on manual skip, allowing you to pick and choose when to skip or not skip.  This does, however, make it a hands-on experience.

</details>

**Comment by ajayyy** [comment]
#1261
