### ISSUE TITLE
Mobile video player's seek bar does not show segments on videos with chapters

### ISSUE THREAD

**Issue by DeiDo** [ajayyy/SponsorBlock#1287]
Exactly what it says in the issue title. Other functionality is preserved, however.

Behavior on videos with chapters:
![Screenshot_2022_04_17_12_57_24_59_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/19535962/163709694-a96d7ecc-3ea0-4338-94aa-bf606d698e51.jpg)
Behavior on videos without chapters:
![Screenshot_2022_04_17_12_57_47_30_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/19535962/163709697-44687040-a2d0-4492-aeec-7c7afc320b4d.jpg)
Behavior on desktop video player:
![Screenshot_2022_04_17_12_56_50_83_4d38fce200f96aeac5e860e739312e76](https://user-images.githubusercontent.com/19535962/163709699-d65b3f49-a0eb-4a11-b348-e17662559fbd.jpg)

**Comment by ajayyy** [comment]
Looks like this is still rolling out. I don't see chapters on mobile YouTube on my end

**Comment by mchangrh** [comment]
mobile YT is a different selector - maybe we should have it fall back on the mobile progress bar instead?

**Comment by mchangrh** [comment]
.take

**Comment by mchangrh** [comment]
![image](https://user-images.githubusercontent.com/15132783/167747226-4603b060-c49e-40d1-bd3e-2c4d2ac1c549.png)

It looks a bit tall but that might just be a symptom of the mobile YT player

**Comment by ajayyy** [comment]
Fixed visual issues
