### ISSUE TITLE
Preview bar doesn't work on the "Invidious-style" player on Invidious

### ISSUE THREAD

**Issue by DUOLabs333** [ajayyy/SponsorBlock#1294]
I'm not sure whether this is in the scope of Sponsorblock, but for my private Invidious instance, the seek bar isn't colored correctly.

**Comment by ajayyy** [comment]
Which player? I think it only works on one of the players right now

**Comment by mchangrh** [comment]
#1144

**Comment by DUOLabs333** [comment]
Yeah, it falls on the invidious player.

**Comment by SkMyPP** [comment]
Why was this closed? Segments are still not shown on the default Invidious player.

**Comment by mchangrh** [comment]
.take
