### ISSUE TITLE
Submitted times did not reflect on user screen.

### ISSUE THREAD

**Issue by peter-pakanun** [ajayyy/SponsorBlock#1295]
Submitting something without said thing reflecting on screen is a bad UX.

Refreshing (with F5) didn't help, the user will have to wait until server-side algorithm acknowledges his/her time to be able to block/use said times.

But in my case, the said time was the first of the clip, accepted, and proceeded to make it work (after a while), just not instantly.

Maybe use local storage to cache it first or something?

Even if said contribute was not accepted, user should be able to 'block sponsor' with local rules.

**Comment by ajayyy** [comment]
This already should be the case, could you give the steps you did for it to not happen?

**Comment by mchangrh** [comment]
This was the original behaviour, when segments were submitted they appeared on the info panel immediately but now they require another manual refresh after submitting before they appear.

**Comment by mchangrh** [comment]
demo:

https://user-images.githubusercontent.com/15132783/166848800-bf14fd87-fca8-4867-b8c5-b44d020963a8.mp4

**Comment by ajayyy** [comment]
Odd, I've never seen that

**Comment by mchangrh** [comment]
4.2.1 & 4.3.1 on chrome
