### ISSUE TITLE
Dealing with blocked sections that contain necessary information?

### ISSUE THREAD

**Issue by Overwatching** [ajayyy/SponsorBlock#1296]
There are a few channels that I watch that I've been having problems with recently.

People are marking sections as "Unpaid/Self Promotion", and that is true. But those sections are vitally important to the actual content of the video.

Example:
  Channel: LockPickingLawyer
  StatementBlocked: "To open this I'll be using X and Y, which I sell on my store [store page]."

You often can't see what tool is being used, since hands and other things get in the way.
Blocking a section like this makes it impossible to picture what is going on inside the lock.
(and it only barely get's by the time filter by being 7 seconds total)

On the desktop, I usually flag the section. But I haven't encountered a mobile/Tv app that has the ability to do so. It's all or nothing with them.

**Comment by ajayyy** [comment]
Video link?

**Comment by mchangrh** [comment]
> Video link?

https://www.youtube.com/watch?v=7Ob1QiFtKHU

one example of the "using x and y that is sold on [store]"

**Comment by ajayyy** [comment]
The current skip there seems to be good, as it keeps the information

**Comment by ajayyy** [comment]
ooh, new types of issue closing, cool
