### ISSUE TITLE
Not immediately skipping sponsors at start

### ISSUE THREAD

**Issue by crazygamerdude17** [ajayyy/SponsorBlock#1297]
Something that has been bothering me for a bit, when a video has a sponsor immediately, for example, when a video starts with "this video is partially sponsored by ______", it plays about a second or 2 of it and THEN skips, it should skip immediately

**Comment by ajayyy** [comment]
This is probably just due to how long it takes to fetch the segments from the server.

**Comment by ajayyy** [comment]
One workaround would be disabling autoplay in your browser so that you have to manually click play

**Comment by NDevTK** [comment]
Duplicate of #1214
