### ISSUE TITLE
Auto-skip all segments when in YTM

### ISSUE THREAD

**Issue by nin0-dev** [ajayyy/SponsorBlock#1301]
Title says it all.

Basically if the user is in YouTube Music, all segments get auto-skipped to avoid unwanted intros/endings.

**Comment by mchangrh** [comment]
you probably want "Auto skip all segments when there is a non-music segment" under Behaviour

![image](https://user-images.githubusercontent.com/15132783/166620694-914c4c8f-49a7-43e5-aa35-a8c40d340354.png)

**Comment by nin0-dev** [comment]
Thanks!
