### ISSUE TITLE
[Feature Request] Customize skipping video segments.

### ISSUE THREAD

**Issue by zeref-dragneel** [ajayyy/SponsorBlock#1302]
Hello!
Sorry for your poor English. I hope you understand. Thank you.

I would like to ask for a feature that automatically skips a certain amount of time for all videos (e.g., 10 minutes). Add an on-off button to turn this function on and off on the extension's menu table.
Why? When I watch a TV game show, I don't want to see the MC segment that introduces players and players' introductions themselves. I estimate that the average time period is about 10 minutes. So when I watched that program, I just turned on the preset auto-skip feature.
I usually watch many episodes in a row, so if possible, ignore the end of the program, which is to sum up the score and results of the player and move on to the next episode. The next episode also omitted the same, with the player introduction and the score result of the program.

When I don't watch that show anymore, I can turn it off on the toolbar popup menu popup.

<img src="https://i.imgur.com/cEGFbSm.png" height="200">

****

Another requirement: can you update the scroll bar of the popup menu to be more compact, beautiful, and gentle?

<img src="https://i.imgur.com/K3MPkhQ.png" height="500">

Some examples:

- https://grsmto.github.io/simplebar/
- https://daylilyfield.github.io/svrollbar/
- http://yaireo.github.io/fakescroll/
- https://welisonmenezes.github.io/wm-blazor-overlay-scrollbars/themes
- http://manos.malihu.gr/repository/custom-scrollbar/demo/examples/complete_examples.html

**Comment by hyoretsu** [comment]
What you're looking for sounds outside of the scope of SponsorBlock. And what you actually wanted to do, skip the introductions and scores, sounds like an intro/outro, which is already implemented.

**Comment by zeref-dragneel** [comment]
> What you're looking for sounds outside of the scope of SponsorBlock. And what you actually wanted to do, skip the introductions and scores, sounds like an intro/outro, which is already implemented.

In short, I want to skip the first 10 minutes of all YouTube videos. Short videos under 10 minutes can be played by SponsorBlock. 👾

**Comment by ajayyy** [comment]
Out of scope
