### ISSUE TITLE
[Feature request] Automatically skip to highlight for specific channels

### ISSUE THREAD

**Issue by WoLpH** [ajayyy/SponsorBlock#1305]
Some Youtube channels always have a lot of crud in the beginning of the video that I don't care about. The Mr.Puzzle videos for example: https://www.youtube.com/watch?v=tZIjmwjKp-E

For these channels I would like to always skip to the main part of the video. It would be very useful if this would be configurable on a per-channel basis.

**Comment by ajayyy** [comment]
#1261
