### ISSUE TITLE
wiki.sponsor.ajay.app SSL certificate expired on May 11th

### ISSUE THREAD

**Issue by zopieux** [ajayyy/SponsorBlock#1316]
https://wiki.sponsor.ajay.app/w/API_Docs cannot be reached with its [current, invalid SSL certificate](https://www.ssllabs.com/ssltest/analyze.html?d=wiki.sponsor.ajay.app), which expired on 2022-05-11.

I would suggest using the wildcard certificate currently issued for the main `sponsor.ajay.app` website going forward.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlockServer/issues/470

**Comment by ajayyy** [comment]
Working on moving the deployment to kubernetes as the current deployment strategy in unsustainable (multiple load balanced nginx), and should be done soon™️, then it will be back to proper autorenewing
