### ISSUE TITLE
Skip to Highlight Button disappearing

### ISSUE THREAD

**Issue by Limboso** [ajayyy/SponsorBlock#1318]
When I have the setting "Keep Skip To Highlight Button On Player" enabled AND "Show Buttons On YouTube Player" disabled the Highlight button appears on the video and stays just for a few seconds before disappearing. Even when I hover the mouse cursor over that area the button won't come back. Is this how it's supposed to work or is it some kind of bug? Shouldn't the button keep visible on the player or at least reappear when I hover the mouse over?

**Comment by ajayyy** [comment]
This is the intended behavior at the moment. It will only stay if both of those settings are enabled.

**Comment by eevb** [comment]
I still can't make it not disappear, what exact settings I have to use to make the skip to highlight button not disappear like in previous versions of sponsorblock @ajayyy
