### ISSUE TITLE
Sound wave for the segment editor

### ISSUE THREAD

**Issue by Madis0** [ajayyy/SponsorBlock#1320]
The segment editor has plenty of tools for getting the visual content right. But what about sound? Visualizing the sound could help make smoother transitions, cutting full silence where necessary, avoiding cutting in the middle of the word and so on.

I suggest adding a visual sound wave next to the millisecond boxes, so the user can set the start and end from the textboxes or by dragging some knobs on the sound wave.

Perhaps the sound wave could be cropped and zoomed by the segment length (e.g. if you're editing a 5-second segment, the sound wave is displayed for the 15 second clip - 5 seconds to the left and right of the segment).

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/992
