### ISSUE TITLE
Consider respecting the system accent colour on Safari's toolbar icon

### ISSUE THREAD

**Issue by strafe** [ajayyy/SponsorBlock#1324]
I'm not familiar with extension development for Safari, but it would seem it's possible to provide a non-colour icon and allow the system accent colour to show that the extension is active.

- [Response from Apple since this seems to be somewhat undocumented?](https://developer.apple.com/forums/thread/651500)
- Examples of the uniform look when extensions allow the accent colour to theme them:
![](https://i.stack.imgur.com/5AeEn.png)

![](https://i.stack.imgur.com/aIvxn.png)

**Comment by mchangrh** [comment]
This seems like it should be [`theme-color`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color) or [`accent-color`](https://developer.mozilla.org/en-US/docs/Web/CSS/accent-color) but there is also no dynamic elements to the icon iirc (see #930)

**Comment by strafe** [comment]
@mchangrh I'm not sure what those have to do with this sorry. I did find [a write up](https://lapcatsoftware.com/articles/blues.html) that explains Safari has some sort of built-in feature that detects if an extension's icon is grayscale or not, if it is, then it will allow it to be tinted using the system's accent colour.  

This wouldn't require any additional functionality as the icon is only tinted when Safari considers the extension to be "active" (so when on youtube.com).

**Comment by mchangrh** [comment]
Ah, I thought that Apple would at least document it or have it behind a feature flag like they did with theme or accent colour (which were reported by users), but unfortunately it seems that it's not documented and up to trial and error.

Personally I find it quite odd since SponsorBlock leans quite heavily into the red theme - IIRC 1Password isn't deliberately blending in with a greyscale icon, they just also happen to feature blue as their theme, just a happy coincidence

**Comment by strafe** [comment]
1Password is using this in the screenshot I posted above. The Safari helper in 1Password 7 and below can be tinted with the system accent colour. Red example:
![CleanShot 2022-05-24 at 04 03 17@2x](https://user-images.githubusercontent.com/15663890/169940377-da01208f-6509-4465-9e2b-d619f5343527.png)

In fact they've just changed how thinks works in 1Password 8, and the new Safari extension borrows heavily from their Chrome extension and loses this functionality, [there's already a thread of people complaining](https://1password.community/discussion/128524/1password-for-safari-extension-icon-is-ugly).

**Comment by strafe** [comment]
I can't find the update that added this but it seems to be working now(?), thanks @ajayyy 
<img width="371" alt="image" src="https://github.com/ajayyy/SponsorBlock/assets/15663890/ea39c635-2d83-4917-bc89-1c56af1bef8c">

**Comment by ajayyy** [comment]
didn't do anything :P

**Comment by strafe** [comment]
Sad news everyone, after updating to Sequoia the icon is now red again when SponsorBlock is active :(
