### ISSUE TITLE
Improve efficiency 

### ISSUE THREAD

**Issue by bershanskiy** [ajayyy/SponsorBlock#1328]
SponsorBlock background currently registers `tabs.onUpdated` listener just to check for URL updates on two domains it is interested in (YouTube and YouTube no-cookie sites). This is an anti-pattern that is known to cause excessive background activations.
https://github.com/ajayyy/SponsorBlock/blob/024480513c7fc02b91eb9a90bad95de4926044ad/src/background.ts#L26

Fortunately, Chrome 102 (which is shipping today) has a much better alternative: [Navigation API](https://chromestatus.com/feature/6232287446302720). This API will actually allow extension to register listener in the content script directly (and avoid background context activation at all.) If you are interested, I can prepare a PR with this change. Also, (on YouTube specifically) older versions of Chrome and current versions of Firefox and Safari can have similar efficiency gains by registering listeners for YouTube-specific DOM events.

If you are interested, I can elaborate and prepare a PR.

**Comment by ajayyy** [comment]
Related: #1278

I would prefer to continue using URL as it is something that cannot be broken by a change on YouTube's side. The YouTube events are useful for extra info, but shouldn't be relied on.

**Comment by bershanskiy** [comment]
So are you interested in doing this for Chrome versions that support Navigation API?

**Comment by bershanskiy** [comment]
I created a draft PR implementing this change. It falls back to the existing code path if Navigation API is not available.
