### ISSUE TITLE
Should minimum NodeJS version be bumped a bit?

### ISSUE THREAD

**Issue by bershanskiy** [ajayyy/SponsorBlock#1329]
`package.json` specifies that NodeJS 12.20.0 is supported:
https://github.com/ajayyy/SponsorBlock/blob/4738c1897f41c307b2a4643e214f2b95e1365add/package.json#L68

but codebase uses optional chaining operator `?.` which was first introduced in NodeJS 14.0.0 ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility)):
https://github.com/ajayyy/SponsorBlock/blob/4738c1897f41c307b2a4643e214f2b95e1365add/webpack/webpack.common.js#L93

There are some other minor nits in the codebase like dependencies that require NodeJS version no older than 12.22.0.

Also, CI seems to use NodeJS 16.

**Comment by mchangrh** [comment]
optional chaining and ES16 stuff I assumed to be transpiled by typescript + webkit, It's easier to just lock it to 16 (but I know that 14 still worked a while ago ;))

**Comment by mchangrh** [comment]
.take

**Comment by ajayyy** [comment]
>  I assumed to be transpiled by typescript 

Most is, but not webpack js files

**Comment by mchangrh** [comment]
If we really wanted backwards compatibility, we could switch to babel instead of TS as a transpiler since it supports native TS and is marginally faster

**Comment by ajayyy** [comment]
For the browser extension, the target is a browser. Node is only used for dev
