### ISSUE TITLE
[FEATURE REQUEST] Add "Silence" segment

### ISSUE THREAD

**Issue by prephyte** [ajayyy/SponsorBlock#1334]
Right now there is no option for segments, where nothing is happening, e.g. speakers changing seats or approaches to the judge in court (JD AH court case). These segments are marked as "Intro animation", which is completely wrong for this type of segment. I ask you to add something like "Silence" segment, that would be dedicated to something like this. Thanks

**Comment by SameenAhnaf** [comment]
There's already a lot of browser extensions for skipping silence automatically. Does Sponsorblock still need to save these segments separately?

**Comment by prephyte** [comment]
> There's already a lot of browser extensions for skipping silence automatically. Does Sponsorblock still need to save these segments separately?

Well, they ARE saved already, just in the wrong category.
