### ISSUE TITLE
Latest release is 5.4.1 instead of 4.5.1

### ISSUE THREAD

**Issue by darkred** [ajayyy/SponsorBlock#1347]
The current latest version in [CWS](https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone) and [AMO](https://addons.mozilla.org/en-US/firefox/addon/sponsorblock/) is 4.4.5 . 

I've noticed in [Releases](https://github.com/ajayyy/SponsorBlock/releases) that the latest/today's release is 5.4.1 instead of 4.5.1 .
I thought to inform you, because, if it becomes published to CWS/AMO as it is (5.4.1), then if you decide to rename it afterwards, those that will have updated to it, won't be able to get any new versions < 5.4.1 .
Thank you.

For reference here is a s screenshot of https://github.com/ajayyy/SponsorBlock/tags : 
![2022-06-05_195439](https://user-images.githubusercontent.com/723651/172061574-507caf2c-0d66-42b5-892d-ac1c8b39bca9.jpg)

**Comment by ajayyy** [comment]
Thanks, looks like it's just the git tag fortunately

**Comment by ajayyy** [comment]
Fixed
