### ISSUE TITLE
After every Update of Sponsorblock, a "reinilization" of Invidiousinstances is needed if custom added.

### ISSUE THREAD

**Issue by solisinvictum** [ajayyy/SponsorBlock#1354]
Hey Guys,

because of https://github.com/ajayyy/SponsorBlock/issues/815 (wich isnt fixed until today), i use my personal invidious instance on a cheap 1$ VPS because a valid domain is needed. 

It works everything fine so far. I have only one Problem:

Everytime Sponsorblock gets updated (ungoogled-chrome, on firefox and official chrome same problem), i need to "reset" the invidious instances list, and then readd my instance.

If i dont do that after a update, sponsorblock dont work on my instance, i only get a "no videos found" message. 

This can reproduced by simply adding a publicly available invidious instance, wich isnt in the list already by default.

Thanks.

**Comment by ajayyy** [comment]
Does it still show the domain you added before clicking reset

**Comment by solisinvictum** [comment]
yes. but it seems that gets ignored.

you have then to click on "reset instances" and add the domain again.

Then it works again, until next update.

**Comment by ajayyy** [comment]
The same behavior happens on both chromium and Firefox? They use different user script and permission systems which is why I want to confirm

**Comment by Moth-Tolias** [comment]
i'm getting this too on firefox [i don't use chrome]. it's very frustrating.
however, you don't need to readd your instance every time; just toggle third party sites off and on again.

**Comment by solisinvictum** [comment]
> The same behavior happens on both chromium and Firefox? They use different user script and permission systems which is why I want to confirm

yes. this happens on every browser i tested (dont matter if on windows or linux). 



> i'm getting this too on firefox [i don't use chrome]. it's very frustrating. however, you don't need to readd your instance every time; just toggle third party sites off and on again.

i try that on next update of sponsorblock.

**Comment by solisinvictum** [comment]
> i'm getting this too on firefox [i don't use chrome]. it's very frustrating. however, you don't need to readd your instance every time; just toggle third party sites off and on again.

i can confirm that this works. simply disabling and then directly enabling third party sites, "fix" this without readding your custom intance.

But you have still to toggle this switch after every update. 

I can now confirm too, that this bugs happens on every browser i tested: Firefox, Chrome, Chromium, ungoogled-chromium, Vivaldi and Librewolf. 

(maybe the fix could be, to automatic toggle off and on (if it was on) the third party switch)

**Comment by ajayyy** [comment]
I can't reproduce this on Firefox, but I think I have a fix that will help

On chromium however, it doesn't look like it's possible to auto request the permission again after every update since it requires a "user gesture"

![image](https://user-images.githubusercontent.com/12688112/184967492-7d69fffa-5470-4e67-8d9b-2be06328a28b.png)

**Comment by ajayyy** [comment]
Should it open a page after every update with a button to refresh the permission?

**Comment by ajayyy** [comment]
> I can't reproduce this on Firefox, but I think I have a fix that will help

Nevermind, this restriction applies to Firefox too. I'll just check the state of permissions and make a page explaining it if it has lost it.

**Comment by solisinvictum** [comment]
Dont know if it helps you, but this addon https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean

Adds/Removes new Sites too often. But after a Update Firefox and Chrome for example gives a notifications that permission have changed for sites xyz and ask if you want to accept or deny that (the native notification from the browser, not a custom created one).

**Comment by MintMain21** [comment]
Still a problem in Firefox as of Sep 27 2022.

**Comment by Moth-Tolias** [comment]
same here, but only on windows. linux for whatever reason has no trouble.

**Comment by ajayyy** [comment]
It should be opening page asking you to give it back the permissions

Maybe the browser isn't actually telling it that the permissions have been revoked?

**Comment by Moth-Tolias** [comment]
> It should be opening page asking you to give it back the permissions
> 
> Maybe the browser isn't actually telling it that the permissions have been revoked?

oh, curious - i've never seen the page be opened at all, on either system

**Comment by MintMain21** [comment]
I'm sick of having to disable and re-enable the Invidious permission over and over again.

**Comment by ajayyy** [comment]
If the browser is not telling the extension that the permissions have been removed (https://github.com/ajayyy/SponsorBlock/commit/faeb5dede016f25710bc79b6b3fcdcd82f37e45b#diff-39b2554fd18da165b59a6351b1aafff3714e2a80c1435f2de9706355b4d32351R230-R242), I'm not sure a good way to prompt again
