### ISSUE TITLE
[Feature request] Implement SponsorBlock Within YouTube Shorts

### ISSUE THREAD

**Issue by Weather-OS** [ajayyy/SponsorBlock#1356]
SponsorBlock **Currently Does not work in YouTube Shorts Context** (Extension is not used/has no functionality for YouTube Shorts).

I'm currently researching SponsorBlock's Source code so I can manually add this feature myself, but it would take a while.

If You have an Opinions or anything you want to share about this issue's development, You can post it here. 

_I'll be pushing pull requests once my feature is in an experimental phase._

**Comment by ajayyy** [comment]
It should already work fine, it just doesn't have the preview bar

**Comment by Weather-OS** [comment]
Oh Sorry. I just realized this feature only works in the browser version of YouTube.

I'll close this issue.
