### ISSUE TITLE
Creating segments with keybinds and the popup open doesn't update or auto-close popup

### ISSUE THREAD

**Issue by shamshitty** [ajayyy/SponsorBlock#1359]
after making times for a submission, there's no button to actually submit the times anywhere. I'm just prompted to start and end more times.

![image](https://user-images.githubusercontent.com/68004605/173253794-93de6fe0-d690-4245-9d7f-39cc63c39930.png)
![image](https://user-images.githubusercontent.com/68004605/173253824-9483617f-9d03-4af0-8745-a542e5a4bf05.png)

and when submitting using the keybind, I get this error
![image](https://user-images.githubusercontent.com/68004605/173253871-10683cdb-5b9a-4884-ac05-dd8750c388b1.png)

**Comment by ajayyy** [comment]
Link?

**Comment by shamshitty** [comment]
[https://youtu.be/c_PP_Ih-R58](here)

**Comment by ajayyy** [comment]
The issue seems to be that keybinds don't automatically close the window like how clicking the player button does. The popup only is updated when you click the button on the popup
