### ISSUE TITLE
[Suggestion] Skip to Highlight from Popup

### ISSUE THREAD

**Issue by DivyanshByte** [ajayyy/SponsorBlock#1362]
It Would be cool to add a feature that would enable skipping to highlight from the popup.

The Button Could be added:
![Screenshot 2022-06-14 at 5 50 27 PM](https://user-images.githubusercontent.com/57246976/173575693-fb1d0c7a-af3c-495d-abc5-c5c301cafebb.png)
Next to upvote, downvote, copy to clipboard buttons.

**Comment by ajayyy** [comment]
This is implemented in #1001

**Comment by DivyanshByte** [comment]
Thanks!
