### ISSUE TITLE
Brave 1.39.122 not loading videoID correctly for all videos but initial

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlock#1367]
Issue raised in discord

[first](https://discord.com/channels/603643120093233162/603643180663177220/987226599134994462)
[second](https://discord.com/channels/603643120093233162/603643180663177220/987501528598319144)

Brave 1.39.122 does not load the videoID correctly for any other videos if it is the initial one

**Comment by ajayyy** [comment]
Maybe it's another addon interfering

**Comment by mchangrh** [comment]
Tried reproducing with extensions, still no success

**Comment by mchangrh** [comment]
possibly related to #892
