### ISSUE TITLE
Vulnerability to 51% attacks via DDOSing

### ISSUE THREAD

**Issue by navid-zamani** [ajayyy/SponsorBlock#1375]
By design, SponsorBlock is vulnerable to being corrupted by a large corporation, botnet or state.

All that is required, is to feed the server more false information than its legitimate users care to contradict. Making the false information dominant. (The same fallacy as in Bitcoin.)

This can and will be done as soon as SponsorBlock becomes in any way influential or dominant. As it will anger the organized crime (“advertisement“ is organized mental assault for the purpose of causing financial harm), especially Google itself, and certain governments (like the US, Russian, etc) and ideological propaganda organizations.
In fact, I myself would probably have no problem doing this, even without a botnet, given the current design. (IPs are easily faked. Only a fast connection is needed.)

So this bug here exists as a mental note, so a solution that prevents this problem can be developed and/or documented.

_(The only solution I currently know of, is a web of trust.
As in: Only individual relationships are trusted, and indirect chains of trust with statistically significant reliability do the rest. This makes anonymity impossible though, as unique personally verified IDs are required to make trust even possible. Indirect relationships may still be anonymized, depending on who is trusted. …
A solution that is probably not practical for this.)_

**Comment by ajayyy** [comment]
Is rather focus on constructive discussions instead of out of this world theories.

There exists a manually curated trusted user list right now that act as moderators on most large channels and there is a reputation system.
