### ISSUE TITLE
[feature request] 'SponsorBlockConfig.json' with date-time as part of filename

### ISSUE THREAD

**Issue by eladkarako** [ajayyy/SponsorBlock#1376]
similar to `my-ublock-backup_2022-06-28_17.22.38.txt`,  
or `session_buddy_export_2022_06_28_12_41_05.json`.  

I know that there are just a few handful of settings in the file,  
but it would help me correctly store it locally.

the format most useful is ISO string, 
which is the year, month and day followed by time,  
the effect is that sorting files by name is also meaningful date-wise,  
placing the older first newer last.

```js
(new Date()).toISOString()
//'2022-06-28T19:35:21.599Z'

(new Date()).toISOString().replace(/[\:\-T]/gi,"_").replace(/\..*$/,"")
//'2022_06_28_19_36_42'

(new Date()).toISOString().replace(/[\:\-]/gi,"").replace("T","_").replace(/\..*$/,"")
//'20220628_193720'
```

**Comment by mchangrh** [comment]
.take

**Comment by mchangrh** [comment]
I opted for `YYYY-MM-DD_HH.MM.SS` 
```js
new Date().toJSON().replace("T", "_").replace(/:/g, ".").replace(/.\d+Z/g, "")
```

I felt that it was the closest to ISO8601 without colons (because windows), since `-` is also the date separator and `_` instead being used to separate the filename, date and time. The trailing milliseconds were also removed to get closer to ISO8601.

**Comment by eladkarako** [comment]
I'm not a fan of the use of `.`,  
but I'll take it..  
thanks.
