### ISSUE TITLE
"Filler Tangent/Jokes" should NOT be a single category.

### ISSUE THREAD

**Issue by Overwatching** [ajayyy/SponsorBlock#1382]
"Filler Tangent/Jokes" should NOT be a single category.

Jokes are rarely, if ever, filler or tangent. Grouping them together means either not getting to skip actual filler/non-content so jokes won't be skipped, or missing all the comedy in order to skip non/content.

Examples:

Every livestream VOD I have checked has long non-content segments.
A channel like [Games Done Quick](https://www.youtube.com/c/gamesdonequick/videos) will have gaps between all the "actual" speedrun content to account for setup, announcements, interviews, and other things.
[This 51:52 minute speedrun](https://www.youtube.com/watch?v=zMjAD-zVXco) (+ 1-2 minutes of explanation) is a 1:20:00+ video. Since this is posted as a speedrun, and 30+ minutes of it don't matter after the event is over, those sections should clearly be skipped.

On the opposite side, [Last Week Tonight](https://www.youtube.com/user/LastWeekTonight/videos) is a comedy news show.
It is not a news show.
It is not a comedy show.
The news is required for the comedy/jokes to make sense.
The comedy is there to make the news sections more memorable, while keeping it from being a bad-news slog.
All of it is the "actual" content.

Why is "jokes" even in a category?
Can someone give an example of a joke that isn't actually part of the content?
And if you can, isn't that already just filler?

**Comment by ajayyy** [comment]
> Why is "jokes" even in a category?

Because it's something people wanted to skip

**Comment by Overwatching** [comment]
> Because it's something people wanted to skip

OK. What about the rest?

My post wasn't a rant. Those were all legitimate questions, posed because I thought them important to the project.

This was a recent-ish change, and it is already cutting out sections of videos that I want to watch, because they are (correctly) labeled as "jokes".
