### ISSUE TITLE
Add LBRY

### ISSUE THREAD

**Issue by erkinalp** [ajayyy/SponsorBlock#1385]
Decentralised protocol to share content using blockchain.

Applicable categories: 
- all (video&audio)
- sponsor, self promotion, exclusive access, interaction reminder, preview (other content)

**Comment by mchangrh** [comment]
duplicate of #515, #654 and #972

**Comment by stefanmm** [comment]
I made a simple plugin that loads and skips sponsored segments on YouTube videos imported to Odysee -  https://github.com/stefanmm/sponsorblock-odysee
It is very basic for now, so feel free to improve it.
