### ISSUE TITLE
Sponsor block isnt working on any video i try.

### ISSUE THREAD

**Issue by Lutitious** [ajayyy/SponsorBlock#1392]
I have tried librewolf and chromium, and alternative youtube clients nothing works,
![image](https://user-images.githubusercontent.com/25961265/176892176-44bdccd4-19ef-4cd5-8db0-dcbe1404df1d.png)
Here is what appears when i click info, it appears to be a server issue

**Comment by elams18** [comment]
Is it still down?? I'm trying to upload a block and it's showing 502 (bad gateway)

**Comment by Churba** [comment]
Yep, still down. Keep an eye on the status page Inf4ge linked in the comment above, it will tell you when servers are back up and working.
