### ISSUE TITLE
A connection error has occurred. Error code: 522

### ISSUE THREAD

**Issue by Monicon-X100F** [ajayyy/SponsorBlock#1397]
Hi there,

Sponsorblock has ceased to block sponsor segments on any youtube video, and is simply displaying 

"A connection error has occurred. Error code: 522"

I have uninstalled and reinstalled sponsorblock, with no success. 

I can still highlight segments and navigate the UI, but am unable to upload them.

I have provided the debug of my windows 10 PC and my laptop running Fedora.

I hope this helps!

{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:102.0) Gecko/20100101 Firefox/102.0",
        "platform": "Win32",
        "language": "en-GB",
        "extensionVersion": "4.6.2"
    },
    "config": {
        "submissionCountSinceCategories": 3,
        "serverAddress": "Default server address",
        "autoSkipOnMusicVideosUpdate": true,
        "minutesSaved": 887.4780932166664,
        "skipCount": 1457,
        "showPopupDonationCount": 5,
        "dontShowNotice": true,
        "categoryPillUpdate": true,
        "sponsorTimesContributed": 3,
        "invidiousInstances": 15,
        "exclusive_accessCategoryAdded": true,
        "disableSkipping": false,
        "isVip": false,
        "categorySelections": [
            {
                "name": "sponsor",
                "option": 2
            },
            {
                "name": "poi_highlight",
                "option": 1
            },
            {
                "name": "exclusive_access",
                "option": 0
            },
            {
                "name": "selfpromo",
                "option": 0
            }
        ],
        "unsubmittedSegments": {
            "wWxGXSnbofc": [
                {
                    "segment": [
                        31.606
                    ],
                    "UUID": null,
                    "category": "chooseACategory",
                    "actionType": "skip",
                    "source": 1
                }
            ],
            "ycRQqhB7SbU": [
                {
                    "segment": [
                        302.308
                    ],
                    "UUID": "byfOLb3MMFiCTFLVWXGnYw7EhuSYKGqoWoIa",
                    "category": "chooseACategory",
                    "actionType": "skip",
                    "source": 1
                }
            ],
            "d9wWR531-18": [],
            "hBYbodmCBUQ": [],
            "WoaHhxbYhmM": [],
            "89nzxZpNb4E": [
                {
                    "segment": [
                        25.99,
                        134.189
                    ],
                    "UUID": "B9MjEQwDsICwVrCHAgHbJzz5QlcjuoYfFvFC",
                    "category": "sponsor",
                    "actionType": "skip",
                    "source": 1
                }
            ]
        },
        "defaultCategory": "chooseACategory",
        "whitelistedChannels": 0,
        "forceChannelCheck": false,
        "showTimeWithSkips": true,
        "muteSegments": true,
        "fullVideoSegments": true,
        "trackViewCount": true,
        "trackViewCountInPrivate": true,
        "trackDownvotes": true,
        "noticeVisibilityMode": 3,
        "hideVideoPlayerControls": false,
        "hideInfoButtonPlayerControls": false,
        "hideDeleteButtonPlayerControls": false,
        "hideUploadButtonPlayerControls": false,
        "hideSkipButtonPlayerControls": false,
        "hideDiscordLaunches": 0,
        "hideDiscordLink": false,
        "supportInvidious": false,
        "minDuration": 0,
        "skipNoticeDuration": 4,
        "audioNotificationOnSkip": false,
        "checkForUnlistedVideos": false,
        "testingServer": false,
        "refetchWhenNotFound": true,
        "ytInfoPermissionGranted": false,
        "allowExpirements": true,
        "showDonationLink": true,
        "donateClicked": 0,
        "autoHideInfoButton": true,
        "autoSkipOnMusicVideos": false,
        "scrollToEditTimeUpdate": false,
        "darkMode": true,
        "showCategoryGuidelines": true,
        "categoryPillColors": {},
        "skipKeybind": {
            "key": "Enter"
        },
        "startSponsorKeybind": {
            "key": ";"
        },
        "submitKeybind": {
            "key": "'"
        },
        "colorPalette": {
            "red": "#780303",
            "white": "#ffffff",
            "locked": "#ffc83d"
        },
        "barTypes": {
            "preview-chooseACategory": {
                "color": "#ffffff",
                "opacity": "0.7"
            },
            "sponsor": {
                "color": "#00d400",
                "opacity": "0.7"
            },
            "preview-sponsor": {
                "color": "#007800",
                "opacity": "0.7"
            },
            "selfpromo": {
                "color": "#ffff00",
                "opacity": "0.7"
            },
            "preview-selfpromo": {
                "color": "#bfbf35",
                "opacity": "0.7"
            },
            "exclusive_access": {
                "color": "#008a5c",
                "opacity": "0.7"
            },
            "interaction": {
                "color": "#cc00ff",
                "opacity": "0.7"
            },
            "preview-interaction": {
                "color": "#6c0087",
                "opacity": "0.7"
            },
            "intro": {
                "color": "#00ffff",
                "opacity": "0.7"
            },
            "preview-intro": {
                "color": "#008080",
                "opacity": "0.7"
            },
            "outro": {
                "color": "#0202ed",
                "opacity": "0.7"
            },
            "preview-outro": {
                "color": "#000070",
                "opacity": "0.7"
            },
            "preview": {
                "color": "#008fd6",
                "opacity": "0.7"
            },
            "preview-preview": {
                "color": "#005799",
                "opacity": "0.7"
            },
            "music_offtopic": {
                "color": "#ff9900",
                "opacity": "0.7"
            },
            "preview-music_offtopic": {
                "color": "#a6634a",
                "opacity": "0.7"
            },
            "poi_highlight": {
                "color": "#ff1684",
                "opacity": "0.7"
            },
            "preview-poi_highlight": {
                "color": "#9b044c",
                "opacity": "0.7"
            },
            "filler": {
                "color": "#7300FF",
                "opacity": "0.9"
            },
            "preview-filler": {
                "color": "#2E0066",
                "opacity": "0.7"
            }
        }
    }
}

[Debug - Fedora 36, Firefox.txt](https://github.com/ajayyy/SponsorBlock/files/9092430/Debug.-.Fedora.36.Firefox.txt)

**Comment by trickypr** [comment]
Sponsor block's servers appear to be down (or at least cloudflare cannot see them). So I presume that is what is causing the errors.

**Comment by qfoxb** [comment]
site's down
