### ISSUE TITLE
Related "Sponsored videos" boxes

### ISSUE THREAD

**Issue by Golden-Serpents** [ajayyy/SponsorBlock#1399]
i'm going to be honest i have no idea if there's a way to remove it through an extension but i don't think it would be disagreeable that if it is possible to remove it (through user submissions or automatic removal - like an ad blocker) this extension would be a good one to include that feature. this is a first suggestion and i wouldn't even know where to start with contributing to finding a way for it to be removed. 
![image](https://user-images.githubusercontent.com/71458324/178606655-4565f00c-ccc9-4fa9-bfc4-bbd8f4916be8.png)

image description: a popup box in the space an advert would typically be  - or chapters of the video - (to the right of the video player with the top in line with the top of the player) showing other videos sponsored by the same company as the video being watched is sponsored by.

**Comment by ajayyy** [comment]
Can you send an example video?

**Comment by Golden-Serpents** [comment]
yup, this is the only video i've ever seen it on to be fair: https://www.youtube.com/watch?v=_QPPLacWr-4

**Comment by ajayyy** [comment]
I suggest submitting this to https://github.com/easylist/easylist and see if they're able to add it there

**Comment by Golden-Serpents** [comment]
ok cool thanks

**Comment by mchangrh** [comment]
adguard/ubo filter
```
youtube.com##ytd-engagement-panel-section-list-renderer
```

**Comment by ajayyy** [comment]
https://github.com/easylist/easylist/issues/12584
