### ISSUE TITLE
Leaderboard system

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#14]
Have people select a username and show the top contributors.

**Comment by OfficialNoob** [comment]
I would help but that would probably need a backend
... Tell me if you move to a serverless stack

**Comment by ajayyy** [comment]
I have some ideas for this one, so I am going to do it.

**Comment by mirror176** [comment]
My only concern with showing results publicly is if it leads to bad entries for chart presence. #22 could help and hinder under similar logic. This plugin concept and these ideas within lead to certain videos/channels possibly requiring administration steps if people on any end of the equation start to game the system.

**Comment by ajayyy** [comment]
The stats can currently be found at https://sponsor.ajay.app/stats

If people game it, they should get downvotes and the shouldn't get any recognition
