### ISSUE TITLE
Always give a user their own submissions?

### ISSUE THREAD

**Issue by afontenot** [ajayyy/SponsorBlock#140]
I watched a video where someone had previously reported sponsors. One of these was incorrect (starting ~15s too late). I downvoted and reported it, and added the correct times. Refreshing the page, I was surprised to see the same times as before. I thought my submission hadn't gone through, so I submitted again.

I eventually noticed that the behavior appeared to be random: some times when I refresh the page I get my (correct) times, sometimes I get the incorrect ones. I think this is confusing behavior unless it's clearly explained to users up front. If they submit a time, refresh the page, and don't see that time, they will assume something has gone wrong. 

Some issues with the status quo:

1. Users will assume their submissions have failed and resubmit them. (What happens in this case, if I submit two overlapping times? Confused about this.)

2. If multiple users randomly get the incorrect time, they will all assume the correct times are not already in the database and submit them. So you'll end up with dozens of "correct" submissions that overlap almost exactly. 

3. It's not clear to anyone what the actually reported times are for a given video. When I see "This video's sponsors are in the database", I assume that the times provided are *all* the times that are in the database, not a random selection of non-overlapping times. This leads to a variety of confusing situations. 

I think the best way to avoid this problem might be to show *all* the times in the database, so that ads will always be skipped for everyone (assuming at least one person has submitted correct values), and allow people to downvote incorrect entries. Anything that we know with ~90% confidence is a bad entry can be dropped. 

This would most likely increase the number of downvotes that good reporters get, so the number of downvotes an established reporter can get before it affecting their rating would likely need to be increased.

**Comment by ajayyy** [comment]
I want to make it so that when you report, it will give you another submission to check out. That will fix the double submission when people are correcting submissions.

Here is info about the pseudo random algorithm: https://ajay.app/blog.html#voting-and-pseudo-randomness-or-sponsorblock-or-youtube-sponsorship-segment-blocker

If all submissions disappeared after 1 vote, then it would be easy to abuse.

**Comment by ajayyy** [comment]
Right now the system works under the belief that seeing a sponsor is better than missing actual content because of an invalid timestamp.

**Comment by ajayyy** [comment]
It now will use your submission right away. If you reload though, it won't always use yours.
