### ISSUE TITLE
Notification says multiple segments skipped but only skipped one segment

### ISSUE THREAD

**Issue by ghost573** [ajayyy/SponsorBlock#1401]
>Version 103.0.5060.114 (Official Build, ungoogled-chromium) Arch Linux (64-bit)

When there are multiple segments for SB to skip next to each other for some reason only one segment auto skips while the other highlighted segment plays, if you hit the "enter" shortcut key then both segments will skip.

This didn't happen to me on Windows with ungoogled-chromium 103.0.5060.53-1 so I'm not sure if it's chromium or linux that's causing a problem, it's hard to explain because I'm sure no one else is having this issue.

https://www.youtube.com/watch?v=-I8_7CPmhzI this is a video I use to see if SB is working.

**Comment by ajayyy** [comment]
This was a regression bug
