### ISSUE TITLE
Sponsorblock isn't working on both desktop and vanced at the moment. 

### ISSUE THREAD

**Issue by magizhchi99** [ajayyy/SponsorBlock#1403]
Tried on Firefox desktop, Edge and chrome. And doesn't work on vanced as well. Just says no segments in this video. Says error 502.

**Comment by ajayyy** [comment]
working on it

**Comment by XcOM987** [comment]
Cheers for working on this, just to update it's also affecting SmartTube's SponsorBlock addon/integration.

**Comment by joshuaseltzer** [comment]
I’d have to guess that it is an API problem? This is also affecting the iOS port it seems (iSponsorBlock).

**Comment by ajayyy** [comment]
Everything should be good now
