### ISSUE TITLE
Sponsored segments on YouTube videos don't always get skipped automatically, even though my settings are configured for that.

### ISSUE THREAD

**Issue by camartinez1229** [ajayyy/SponsorBlock#1405]
Honestly, I've been observing this issue for well over a year now, but am just now getting around to posting about it. I did attempt to look for any posts about similar issues, but the only one I've come across so far, didn't have any resolution.

So basically, my title summarizes my issue. Seemingly randomly, sponsored segments will not get skipped randomly, and will just play, thus prompting me to have to advance the video myself. I've sometimes reloaded the video, which would sometimes make the sponsored segment(s) get correctly skipped. Usually I just press "L" or the right arrow on my keyboard to advance enough to pass the segment manually, however.

I observe this issue on both new (like posted within the past day) and older videos, and on a variety of channels. I do not have any channels whitelisted to prevent skips. There seems to be no rhyme or reason as to why this happens. Even the same videos may work properly one day, and then fail to do so on another day.

If it helps, I've posted my debug info below. I'm currently using a desktop Firefox browser, version 91 ESR. This version is still currently supported. Since my issue has gone on over a year, however, I do remember observing it on the previous major ESR version, 78, as well as some earlier 70s versions from before my switch to ESR. I would not be able to pinpoint when this issue first started happening.

I'm suspecting there might be a conflict with one of my other Firefox addons. I use "Enhancer for YouTube" and "Video Speed Controller", plus "UBlock Origin" to block ads, and various other addons. Being that my issue is very intermittent, I have not yet attempted to try to isolate any other addons as a potential cause.

Does anyone have any ideas about what's happening? Are there any specific troubleshooting steps I could try that might help me figure out the problem? Is there any buggy behavior here that can't be fixed without an update? Is there any other info I could provide to aid in figuring this out?

{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0",
        "platform": "Win32",
        "language": "en-US",
        "extensionVersion": "4.6.4"
    },
    "config": {
        "invidiousInstances": 11,
        "exclusive_accessCategoryAdded": true,
        "autoSkipOnMusicVideosUpdate": true,
        "categorySelections": [
            {
                "name": "sponsor",
                "option": 2
            },
            {
                "name": "poi_highlight",
                "option": 1
            },
            {
                "name": "selfpromo",
                "option": 1
            },
            {
                "name": "interaction",
                "option": 1
            },
            {
                "name": "intro",
                "option": 1
            },
            {
                "name": "outro",
                "option": 1
            },
            {
                "name": "preview",
                "option": 1
            },
            {
                "name": "music_offtopic",
                "option": 0
            },
            {
                "name": "exclusive_access",
                "option": 0
            }
        ],
        "barTypes": {
            "preview-chooseACategory": {
                "color": "#ffffff",
                "opacity": "0.7"
            },
            "sponsor": {
                "color": "#00d400",
                "opacity": "0.7"
            },
            "preview-sponsor": {
                "color": "#004200",
                "opacity": "0.7"
            },
            "selfpromo": {
                "color": "#ffff00",
                "opacity": "0.7"
            },
            "preview-selfpromo": {
                "color": "#bfbf35",
                "opacity": "0.7"
            },
            "interaction": {
                "color": "#cc00ff",
                "opacity": "0.7"
            },
            "preview-interaction": {
                "color": "#6c0087",
                "opacity": "0.7"
            },
            "intro": {
                "color": "#00ffff",
                "opacity": "0.7"
            },
            "preview-intro": {
                "color": "#008080",
                "opacity": "0.7"
            },
            "outro": {
                "color": "#0202ed",
                "opacity": "0.7"
            },
            "preview-outro": {
                "color": "#000070",
                "opacity": "0.7"
            },
            "preview": {
                "color": "#008fd6",
                "opacity": "0.7"
            },
            "preview-preview": {
                "color": "#005799",
                "opacity": "0.7"
            },
            "music_offtopic": {
                "color": "#ff9900",
                "opacity": "0.7"
            },
            "preview-music_offtopic": {
                "color": "#a6634a",
                "opacity": "0.7"
            },
            "poi_highlight": {
                "color": "#ff1684",
                "opacity": "0.7"
            },
            "preview-poi_highlight": {
                "color": "#9b044c",
                "opacity": "0.7"
            },
            "exclusive_access": {
                "color": "#008a5c",
                "opacity": "0.7"
            },
            "filler": {
                "color": "#7300FF",
                "opacity": "0.9"
            },
            "preview-filler": {
                "color": "#2E0066",
                "opacity": "0.7"
            }
        },
        "muteSegments": false,
        "isVip": false,
        "categoryPillUpdate": true,
        "minutesSaved": 1066.580534516669,
        "skipCount": 1351,
        "unsubmittedSegments": {},
        "defaultCategory": "chooseACategory",
        "whitelistedChannels": 0,
        "forceChannelCheck": false,
        "sponsorTimesContributed": 0,
        "submissionCountSinceCategories": 0,
        "showTimeWithSkips": true,
        "disableSkipping": false,
        "fullVideoSegments": true,
        "trackViewCount": true,
        "trackViewCountInPrivate": true,
        "trackDownvotes": true,
        "dontShowNotice": false,
        "noticeVisibilityMode": 3,
        "hideVideoPlayerControls": false,
        "hideInfoButtonPlayerControls": false,
        "hideDeleteButtonPlayerControls": false,
        "hideUploadButtonPlayerControls": false,
        "hideSkipButtonPlayerControls": false,
        "hideDiscordLaunches": 0,
        "hideDiscordLink": false,
        "supportInvidious": false,
        "serverAddress": "Default server address",
        "minDuration": 0,
        "skipNoticeDuration": 4,
        "audioNotificationOnSkip": false,
        "checkForUnlistedVideos": false,
        "testingServer": false,
        "refetchWhenNotFound": true,
        "ytInfoPermissionGranted": false,
        "allowExpirements": true,
        "showDonationLink": true,
        "showPopupDonationCount": 0,
        "donateClicked": 0,
        "autoHideInfoButton": true,
        "autoSkipOnMusicVideos": false,
        "scrollToEditTimeUpdate": false,
        "darkMode": true,
        "showCategoryGuidelines": true,
        "categoryPillColors": {},
        "skipKeybind": {
            "key": "Enter"
        },
        "startSponsorKeybind": {
            "key": ";"
        },
        "submitKeybind": {
            "key": "'"
        },
        "colorPalette": {
            "red": "#780303",
            "white": "#ffffff",
            "locked": "#ffc83d"
        }
    }
}

**Comment by ajayyy** [comment]
The issuenis video speed controller. #359
