### ISSUE TITLE
add XMR donation address

### ISSUE THREAD

**Issue by fugbixer** [ajayyy/SponsorBlock#1419]
https://sponsor.ajay.app/donate/

projects like this can use bounties for fixing certain issues or
to refund instances, website costs etc.

therefore please add a XMR (Monero) address for donations since it's more privacy friendly

Thank you!

**Comment by ajayyy** [comment]
`85vyiPD4yby5bfkN51kSuc9sjZCMmBaoE5t1MCvxX4SuQMamgK7D8LGYbhkm1XGkgPgYn1FBBa3MiDGANXigEUJcEWib6H8`
