### ISSUE TITLE
[Feature Request—Add a Flashing Lights category]

### ISSUE THREAD

**Issue by lloyd99901** [ajayyy/SponsorBlock#1428]
Just a thought, but I think that maybe adding a Flashing Lights category on the list of behaviours could be a good idea.
And if the “Skip Option” is on “Manual Skip”, give a 5-second warning before the flashing lights occur.

Example Pop-up message:
![paintdotnet_p2a4XGBAZV_'Untitled_-_paint net_4 3 10'](https://user-images.githubusercontent.com/12370535/182038855-a64b4a33-cc4a-4af3-984b-d0a9ab76c424.png)

**Comment by ajayyy** [comment]
#403
