### ISSUE TITLE
[Request for documentation] Is this compatible with <video> tags?

### ISSUE THREAD

**Issue by braco** [ajayyy/SponsorBlock#1435]
Does this extension work with this on safari?:

https://apps.apple.com/us/app/vinegar-tube-cleaner/id1591303229

**Comment by mchangrh** [comment]
The app is paid and there are no equivalent alternatives on other platforms. This was asked previously and I think the result was that it skipped without intervention but the UI did not display correctly since the preview bar does not exist.

**Comment by ajayyy** [comment]
They seem to be attemoting compatibility on their end, so check with them
