### ISSUE TITLE
New segment type: Artificially oversped/slow-motion segment

### ISSUE THREAD

**Issue by erkinalp** [ajayyy/SponsorBlock#1436]
Certain videos apply baked-in overspeeding to certain segments to mark the tangent or detail segments and the like.
Remedy: Undo overspeeding/slow motion, skip

**Comment by eladkarako** [comment]
I don't think the publisher have control over the player rate speed. 
it is probably how the video is encoded.

still, this gave me a cool idea,
an alternative to skipping by speeding up (⏩⏩FF) sponsored segments, 
should provide smoother user experience for those whom prefer it, 
and possibly still allow the publishers to be able to have analytics that says people were watching the sponsored segments (btw. you can set the rate to 5 or even 10+ programmatically),
for those who care about the publishers, that is.

**Comment by ajayyy** [comment]
> says people were watching the sponsored segments

YouTube factors in playback speed to watch time and retension calculations
