### ISSUE TITLE
If a sponsored segment is at the very start of a video, it is not skipped.

### ISSUE THREAD

**Issue by Xyphyn** [ajayyy/SponsorBlock#1437]
I assume it's because the video has loaded and started playing before sponsorblock has gotten the data.

![image](https://user-images.githubusercontent.com/80978739/184208597-8415585a-bb25-438d-a186-b53f3cf2c3a9.png)

However, if I go back to the start of the video and hit play, it skips the sponsored segment only _then_.

**Comment by ajayyy** [comment]
This is not the case in normal operation. Can you try to find reproducible steps, including specific plugins, usersscripts or styles.

**Comment by eladkarako** [comment]
https://github.com/ajayyy/SponsorBlock/issues/1214

**Comment by ajayyy** [comment]
@eladkarako this is not the same issue. The issue here is that it _still_ isn't skipping after it did load

**Comment by justgitup** [comment]
> This is not the case in normal operation. Can you try to find reproducible steps, including specific plugins, usersscripts or styles.

It happens to me with extention "Enhancer for Youtube" no matter which options are used. The thing is both extenstions with used to work together for months without a glitch.

After some thorough testing with older versions of Sponsorblock I found that 4.6.2 was the last version that didn't exhibit this issue. I can reproduce the issue consistently by switching from 4.6.2 to 4.6.3 (or later) and opening such a video in a new tab. Going back to 4.6.2 and doing the same fixing it again.

**Comment by eladkarako** [comment]
try browser w auto play blocked natively, set to block auto play, ff/edge and please update your results

**Comment by justgitup** [comment]
> try browser w auto play blocked natively, set to block auto play, ff/edge and please update your results
I have no issue with Firefox with both extenstions installed. It's only on Chrome that the Enhancer for Youtube with versions of Sponsorblock after 4.6.2 lead to segments not being skipped at the start. I'll just stick to using 4.6.2 on Chrome for now I guess.

**Comment by eladkarako** [comment]
interesting.

**Comment by justgitup** [comment]
This issue was solved in version 5.0.3 but unfortunetely version 5.0.4 

> > try browser w auto play blocked natively, set to block auto play, ff/edge and please update your results
> 
> I have no issue with Firefox with both extenstions installed. It's only on Google Chrome that the Enhancer for Youtube extension together with versions of Sponsorblock after 4.6.2 leads to segments not being skipped at the start. I'll just stick to using 4.6.2 on Chrome for now I guess.

This issue was solved in version 5.0.3 but unfortunetely is back in version 5.0.4
