### ISSUE TITLE
Whether you want the segment to be skipped should be Channel based

### ISSUE THREAD

**Issue by Dr-Sauce** [ajayyy/SponsorBlock#1438]
Some channels preview/recap are interesting but some channels aren't. You might want to watch the whole music video on some channels, but skip the non music section on other channels.

SponsorBlock should let us customize the segments settings per channel. In the settings there is a setting called whitelist channel, but that just disables all the segments for that channel. It doesn't let you customize the settings. 

Would be great if we could customize the settings per channel.

**Comment by justgitup** [comment]
So basically a whitelist per segment instead of just a global whitelist? I wonder how that would work in the Sponsorblock popup without it becoming quite messy.

**Comment by ajayyy** [comment]
#435
