### ISSUE TITLE
Allow manual skip on whitelisted channels

### ISSUE THREAD

**Issue by bo0tzz** [ajayyy/SponsorBlock#1442]
When watching a whitelisted channel, I want to disable autoskip but (occasionally) still manually skip segments. It would be nice to have an option that enables displaying the manual skip popup for all sections on whitelisted channels.

**Comment by ajayyy** [comment]
#435

**Comment by bo0tzz** [comment]
My bad, I should have found that. Thanks for this awesome tool!
