### ISSUE TITLE
I attempted to vote.

### ISSUE THREAD

**Issue by BEEDELLROKEJULIANLOCKHART** [ajayyy/SponsorBlock#1443]
![image](https://user-images.githubusercontent.com/42837531/185481278-f6d40745-9949-4aae-81f0-c472643ed547.png)

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@ajayyy, what is not planned? This surely depicts a bug.

**Comment by ajayyy** [comment]
Intentional while fixing issues with the server
