### ISSUE TITLE
Segment-skipping won't trigger (occasionally) at the very beginning of a video (see example listed)

### ISSUE THREAD

**Issue by GUImodder** [ajayyy/SponsorBlock#1449]
Hi,

I noticed this a few times already but today i finally got around to reporting it: I was watching this video and noticed it had a very brief "sponsored by xyz" at the very beginning. It also had another long segment at the middle of it but it was successfully skipped without issue. So I thought: strange...maybe the first part was not reported yet? 
When i went back to report the segment in question I reloaded the video by accident and lo and behold: The Intro sponsor was block this time around. WTF? 
I tried it a couple of times since and it was blocked every single time since...I don't know why it didn't trigger the skip the first time around. 
BTW: it wasn't the first time a skip didn't happen at the very beginning of a video. Maybe someone can explain to me why this happens sometimes and sometimes it works just fine. I'm using Brave on the latest version (in case anybody wonders...)

Links: 
https://www.youtube.com/watch?v=C_WDaHtFxW4

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/1437
