### ISSUE TITLE
Sponsorblock showing HTML code in overlay when upvote/downvote submission fails

### ISSUE THREAD

**Issue by VarvatosVex** [ajayyy/SponsorBlock#1452]
This happened just now.

Seems like it happened because the API server responded with a 404 page rather than the expected API response (JSON?), but it still gives me the heebie-jeebies that the webserver is pushing stuff directly to the overlay.
Feels like a prime candidate for malicious message injection in the event the domain or server gets hijacked.

What should happen is that the API server should return a status code or at best an integer, and based on that the overlay should print a predefined message (either success or fail). If the server for whatever reason returns garbage, the extension should default to "fail".

![image](https://user-images.githubusercontent.com/20911914/185771498-825f1003-1b5b-4804-99e4-c0bdfd1e7920.png)

**Comment by mchangrh** [comment]
4xx codes are also reserved for actual content
