### ISSUE TITLE
The server seems to be overloaded.. all the time. Error code: 502

### ISSUE THREAD

**Issue by rpgdev** [ajayyy/SponsorBlock#1457]
I've been getting this or a variation of this message for several weeks now. It seems like every time I try to submit a segment the server is overloaded regardless of time or day. It never used to happen but now it's all I get all the time. Maybe there's an issue with the way the server's responding? It's anyone else getting this _all_ the time as I am?

![image](https://user-images.githubusercontent.com/20094474/185964366-b4e55ed1-811b-4e71-af95-05720588a4e4.png)

**Comment by mchangrh** [comment]
yes.

**Comment by m1lhaus** [comment]
Yes, me too. I tried to submit for the first time today and this pops up.

**Comment by rpgdev** [comment]
Interesting because it stopped happening for me since yesterday or the day before. Fingers crossed.

**Comment by mchangrh** [comment]
Yes the server is having issues and we're trying to roll with the punches as they come.

**Comment by ajayyy** [comment]
![Screenshot_20220825-232240_Discord](https://user-images.githubusercontent.com/12688112/186810882-2fc8d349-4031-4a42-a584-9c8a46fddcb2.png)
