### ISSUE TITLE
Unable to enable SponorBlock for Invidious on Android

### ISSUE THREAD

**Issue by mativiters** [ajayyy/SponsorBlock#1462]
I use SponsorBlock addon on Android with FireFox version 103. I can open addon settings and open the tab "miccelaneous" and toggle on support for third-party websites, but the change is not saved.
Can this be solved? Perhaps by changing the extension to have this option toggled on by default.

**Comment by mchangrh** [comment]
If I recall correctly, this is an issue with Firefox not being able to request permission for additional sites because of limitations in android.

**Comment by ehelly** [comment]
This would be a much appreciated change. [Bypass Paywalls Clean](https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-clean) for instance has solved this by creating an [Android-specific version](https://addons.mozilla.org/en-US/firefox/addon/bypass-paywalls-clean-custom) that has default access to all sites. It would be pretty simple to implement as well.

**Comment by mchangrh** [comment]
.take

**Comment by ajayyy** [comment]
Now supported
