### ISSUE TITLE
SponsorBlock not working at all; sponsor.ajay.app unreachable

### ISSUE THREAD

**Issue by cheater** [ajayyy/SponsorBlock#1463]
SponsorBlock does not show any segments in the seek bar, it does not skip sponsors, and the website is unreachable. Did you forget to renew your hosting?

**Comment by ajayyy** [comment]
Do you live in Austria or Russia? If so, you should protest against government censorship, then change the Api url to "https://api.sponsor.ajay.app" in settings

**Comment by cheater** [comment]
Yes, in Austria. Can you please tell me more about the censorship thing? Thanks.

**Comment by cheater** [comment]
Setting the alternative URL fixed the issue btw, thanks.

**Comment by ajayyy** [comment]
https://news.ycombinator.com/item?id=32630757

**Comment by cheater** [comment]
thanks, that explains everything. the courts in Austria are a joke - not the first time I'm seeing something completely idiotic come out of them.

**Comment by Justicslul** [comment]
> Do you live in Austria or Russia? If so, you should protest against government censorship, then change the Api url to "https://api.sponsor.ajay.app" in settings

ты че ебанутый? какая цензура? Причет тут это.....
