### ISSUE TITLE
Let translate `<seconds left>s` into other languages too

### ISSUE THREAD

**Issue by farag2** [ajayyy/SponsorBlock#1468]
This `s` is here:
https://github.com/ajayyy/SponsorBlock/blob/c06b7857f8ba4da4862533416b0ffb157f06044a/src/components/NoticeComponent.tsx#L197

![изображение](https://user-images.githubusercontent.com/10544660/188426226-7a48b886-efd4-4648-a0ac-1edace074542.png)

So in Russian it should be looked like `133 с`, with a space and cyrillic [с](https://ru.wikipedia.org/wiki/С_(кириллица)).

**Comment by farag2** [comment]
Any progress?..

**Comment by mini-bomba** [comment]
#1715 seems to implement this

**Comment by farag2** [comment]
Awesome!
