### ISSUE TITLE
Ability to change keyboard shortcuts

### ISSUE THREAD

**Issue by hugoncosta** [ajayyy/SponsorBlock#147]
The shortcut to start/stop a sponsorship is shift + comma. This shortcut is already used by Youtube to lower the speed of the video. I'd propose using a different shortcut or adding the ability to either change it on a user-by-user basis or to simply disable the keyboard shortcut(s).

**Comment by ajayyy** [comment]
Sorry, this only occurs on international keyboards, so I didn't know about
this issue (semicolon is not shift plus comma on English US keyboard).

**Comment by ajayyy** [comment]
For now, I'll add a way to disable the shortcut in the settings menu. I'll try to do that today.

**Comment by hugoncosta** [comment]
Yeah that makes sense, I'm using a Portuguese layout on a 104 keyboard (we usually have the 105), maybe that has something to do with it. Thanks!

**Comment by ajayyy** [comment]
done
