### ISSUE TITLE
skip segment doesn't skip when watching video at any time other than the built-in default ones

### ISSUE THREAD

**Issue by idanontop** [ajayyy/SponsorBlock#1470]
The skip segment doesn't skip when watching video at any time other than the built-in default ones (e.g: 1, 1.25, 1,5, 2.0) which can be done using any other 3rd party extension to change the video playback speed (e.g: https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk)

**Comment by ajayyy** [comment]
the issue isn't the speed, it is the video speed extension itself. See workaround in #359
