### ISSUE TITLE
SSL Certificate for wiki.sponsor.ajay.app Expired

### ISSUE THREAD

**Issue by ggujjula** [ajayyy/SponsorBlock#1471]
Tested on: Firefox 104.0.2, Chromium 105.0.5195.52

Steps to reproduce:

1. Visit [https://wiki.sponsor.ajay.app/w/API_Docs](https://wiki.sponsor.ajay.app/w/API_Docs)

The SSL certificate issued by the server for `wiki.sponsor.ajay.app` appears to have expired recently.
As a result, pages like the API for SponsorBlock are not accessible.
Please renew the SSL certificate so we can access the documentation for SponsorBlock.

![Screenshot from 2022-09-10 23-24-02](https://user-images.githubusercontent.com/43194746/189515311-1896b35b-d31b-4bd7-8647-ea599b39a8fc.png)
![Screenshot from 2022-09-10 23-23-31](https://user-images.githubusercontent.com/43194746/189515324-d9b7af8c-a105-4d25-8ce7-0f0cb861b111.png)

**Comment by mchangrh** [comment]
resolved
