### ISSUE TITLE
Non-music segments skipped even if skipping of these is turned off

### ISSUE THREAD

**Issue by cheater** [ajayyy/SponsorBlock#1472]
My settings are like this:

![image](https://user-images.githubusercontent.com/195390/189527504-0df67f05-afd7-45b8-9f2a-8181269d71fe.png)

Yet, newly opened videos still do this:

![image](https://user-images.githubusercontent.com/195390/189527574-0f28443a-539d-4a7c-943f-74ae366ba583.png)

Am I missing some setting?

**Comment by cheater** [comment]
Please, I'm begging you... listening to songs that start one second after the musician starts playing the instrument is terrible. People reporting non-music segments are over-eager.

https://www.youtube.com/watch?v=QUcTsFe1PVs

**Comment by ajayyy** [comment]
You are misunderstanding, there are two segments there. One intro, one non music.

**Comment by cheater** [comment]
Ah, found it, it's in the info box, I looked in there, but it looks like it was empty because it took a short while to load, so when I looked, the list of segments wasn't populated yet...

... ok, so I get there are multiple segments:

![image](https://user-images.githubusercontent.com/195390/191146075-38456816-b493-4553-a9b2-33983cfbf521.png)

but situations like this are increasingly common. People are very over-eager on cutting down music. Could some sort of heuristic be added? For example, a setting such as: "Ignore all segments that overlap with non-music segments". The rationale is that if people double up non-music segments with intermission or intro segments, then it essentially disables the setting I have set which is that I don't want to skip non-music segments.

**Comment by cheater** [comment]
Let me explain the proposed setting a little more.

1. I only want to ignore skip-segments in music videos, therefore
2. if there is a "non-music" segment, that means we're in a music video, and
3. if there's a non-music segment, and other skip segments that exist that overlap with it, it's probably someone just doubling up the non-music segment with some other type of auto-skipped segment, which is annoying, so ignore those doubled-up segments

The idea is not to affect how normal videos (eg reviews, news, etc) act, just make music videos act differently. So let's say I want to skip intermissions in reviews and news. In music videos, if I still have non-music segments set to skip, then SponsorBlock can skip them. however, if I have set non-music to merely "display", and have intermission set to "skip", but have "Ignore all segments that overlap with non-music segments" turned on, and there's an intermission segment that overlaps with a non-music segment, then SponsorBlock shouldn't skip either of them, merely display them in the seek bar.

Non-music segments don't show up in non-music videos like reviews or news, so the behavior on such videos will not be affected.

**Comment by cheater** [comment]
Thanks, I see the segments now.

But it seems that it's really common that people double up non-music segments like that, and it's really annoying, because I don't want to skip parts of music, but effectively I am forced to. Maybe a heuristic for this could be implemented? I suggest a setting like "Ignore all segments that overlap with non-music segments".

Let me explain the proposed setting a little more.

1. I only want to ignore skip-segments in music videos, therefore
2. if there is a "non-music" segment, that means we're in a music video, and
3. if there's a non-music segment, and other auto-skip segments that exist that overlap with it, it's probably someone just doubling up the non-music segment with some other type of auto-skipped segment, which is annoying, so ignore those doubled-up segments

The idea is not to affect how normal videos (eg reviews, news, etc) act, just make music videos act differently. So let's say I want to skip intermissions in reviews and news. In music videos, if I still have non-music segments set to skip, then SponsorBlock can skip them. however, if I have set non-music to merely "display", and have intermission set to "skip", but have "Ignore all segments that overlap with non-music segments" turned on, and there's an intermission segment that overlaps with a non-music segment, then SponsorBlock shouldn't skip either of them, merely display them in the seek bar.

Non-music segments don't show up in non-music videos like reviews or news, so the behavior on such videos will not be affected.

You could even make a setting such as: "if video contains non-music segments, ignore all other types of segments in that video". Music videos usually don't contain interaction reminders, intermissions, etc, and the rare intro or outro is usually just silent. As someone who listens to music a lot I find that the little bit of silence at the beginning of a song can be really important to set the mood, like in that last video I linked to. Albums with classical or acoustic music often have a few seconds of silence at the start and end of every track, and it's an important part of the music actually.

I would really really appreciate it if you could implement one or the other. I think especially the second one could be not too difficult... I would hate to waste your time, but I hope this is something that doesn't need major effort.

**Comment by cheater** [comment]
BTW here's the info box before the segments have had a chance to load. I knew I wasn't making it up!

![image](https://user-images.githubusercontent.com/195390/191148154-20f61069-f720-4f63-a4e3-8369dda3a895.png)
