### ISSUE TITLE
Reload button should skip cache

### ISSUE THREAD

**Issue by Madis0** [ajayyy/SponsorBlock#1475]
**The problem**

I created a segment and it got stored in the server, but it did not appear for me.
Tried Ctrl+F5 and the SponsorBlock's popup's reload button several times.

Then I asked in your discord and a VIP cleared the cache for the video, then I was able to see the segments again.

Which brings me to the question - what's the use of the reload button if it doesn't skip the cache? I understand that you want to preserve your server's resources, but people are more likely to reload the entire page anyway, and that can continue using cached segments as it makes sense.

**The solution**

I would suggest the SponsorBlock-specific reload button to always skip cache when loading segments.
If you think that's too intrusive for the server, at least add a related method for the user to do it (e.g. by shift+click).

**Comment by ajayyy** [comment]
This defeats the purpose of cache
