### ISSUE TITLE
Seconds round up, causing 59.5s to round to 60s instead of 1m

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#148]
Youtube video https://www.youtube.com/watch?v=DsZtTpBk7s0 gave me a time of 3:60 instead of saying 4:00. I assume that means 3:60 represents a value of 3.59.xxx instead of 4.00.xxx but if so is only a neat trick and of limited use to guess more precise sponsor times as it doesn't do that for the rest fo the second representations.
  I would still like a way to see a detailed time of segments (make sure an attempt to resubmit more precise timings are useful instead of a headbashing due to imprecise start time use by sponsorblock addon). Those are likely only relevant for those creating the start/stop times

**Comment by ajayyy** [comment]
Maybe if you hover, it can show decimals. If we go that route, I think it should round down instead of up, so you don't see the minutes visibly changing with the new precision.

**Comment by mirror176** [comment]
If ti shows precision, I'd rather see it change to 3:59.557 then try to round off to 4:00.000 attempting to avoid a minute change as the rounding in that case would make it inaccurate and accuracy is why I would want precision shown/available. If I could see it now, I could know if I prefer a better edit because of the value in the database vs because of how it is processed by the currently inconsistent plugin start jump timing.

**Comment by skorokithakis** [comment]
I have come across this bug (I think) when trying to add times. I was on 5:46 and pressing "sponsorship starts now" set the sponsorship to 5:47, which was counter-intuitive (I'd expect it to round down to the second I was seeing). Maybe that could be the default instead?

**Comment by ajayyy** [comment]
Fixed in the beta version
