### ISSUE TITLE
Make SponsorBlock work on Invidious in Incognito Mode on Chromium

### ISSUE THREAD

**Issue by eq0cdk** [ajayyy/SponsorBlock#1480]
Currently, SponsorBlock does not work on Invidious in Incognito Mode on Chromium. According to @ajayyy, the tabs permission is required to make it work in Incognito on Invidious. So, the extension should prompt the user for the extra tabs or "Read your browser history" permission, since the user is already asked to allow extra permissions when enabling the option "Support 3rd Party YouTube-Sites". 

An explanation/warning regarding the extra permission should be added to the "Support 3rd Party YouTube-Sites" option.

Until this problem is fixed, I have to use Firefox, which works despite the fact that I have history disabled. 

P.S. The reason I need Incognito is because without it, the address bar becomes cluttered with my browsing history, making it distracting, and annoying when I want to select bookmarks.

>This **does not** work in incognito due to [a chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=825507). To make it work in incognito chrome, the tabs permission would be required. (This wasted waaay too much of my time trying to debug)

_Originally posted by @ajayyy in https://github.com/ajayyy/SponsorBlock/issues/181#issuecomment-569878195_

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/227
