### ISSUE TITLE
Very long macOS app name

### ISSUE THREAD

**Issue by rakleed** [ajayyy/SponsorBlock#1482]
The name of the macOS app is too long to fit and is automatically shortened in the Finder and Launchpad.

<details><summary>Screenshots</summary>

![Screenshot 2022-09-19 at 00 00 33](https://user-images.githubusercontent.com/19418601/190928708-6949d8ed-5205-4d7a-8db4-b21d53790d7c.png)

![Screenshot 2022-09-19 at 00 02 57](https://user-images.githubusercontent.com/19418601/190928710-263b3156-4c68-4708-aeeb-e7c851888706.png)

</details>

It should be shortened to `SponsorBlock` or renamed to `SponsorBlock for Safari`, as many other Safari extensions have this postscript.

![Screenshot 2022-09-19 at 00 28 04](https://user-images.githubusercontent.com/19418601/190928726-24db468d-fb2a-4d6a-b5ad-3801fef578c5.png)

**Comment by ajayyy** [comment]
Fixed in next version

**Comment by rakleed** [comment]
@ajayyy maybe you should still add "for Safari" to the name, as is done with other apps that are only extensions for Safari (as in the screenshot in the first message)?
