### ISSUE TITLE
[Feature Request] show level or percentage of Clickbait or View grabbers in YouTube feed

### ISSUE THREAD

**Issue by yashhebbarbail** [ajayyy/SponsorBlock#1488]
### Is your feature request related to a problem?
On YouTube, it can be irritating when you click a video, and it is a clickbait.

### What solution would you like?
Show level or percentage of Clickbait or View grabbers in YouTube feed. In the future, maybe hide videos based on threshold.

Thank you :smile:

**Comment by mchangrh** [comment]
Our current plan with #1211 is to basically replace thumbnail and title. Percentages are very subjective so maybe flags for replaced thumbnails and/or replaced title can be added as an indicator

**Comment by yashhebbarbail** [comment]
Sounds great! Since there is already an issue, I will close this.
