### ISSUE TITLE
Segment doesn't skip at the start when using third party extension (Enhancer for Youtube) with Google Chrome

### ISSUE THREAD

**Issue by justgitup** [ajayyy/SponsorBlock#1492]
Sponsorblock doesn't skip a segment at the start when using Google Chrome with Sponsorblock and Youtube Enhancer extensions are installed for Sponsorblock version 5.0.4. It did work for version 5.0.3 (and versions before 4.6.3)

This seems related to issue 1437 which was fixed with version 5.0.3.  https://github.com/ajayyy/SponsorBlock/issues/1437

**Comment by ajayyy** [comment]
I don't see any reason for 5.0.4 changing anything related to that, maybe it was just a fluke while you were on 5.0.3 and it wasn't fixed?

https://github.com/ajayyy/SponsorBlock/compare/5.0.3...5.0.4#diff-b769f60434f9ce6a59837e3786f8b1ef4d13930a04c73e4d525ffa17ad9f665c

**Comment by justgitup** [comment]
> I don't see any reason for 5.0.4 changing anything related to that, maybe it was just a fluke while you were on 5.0.3 and it wasn't fixed?
> 
> [5.0.3...5.0.4#diff-b769f60434f9ce6a59837e3786f8b1ef4d13930a04c73e4d525ffa17ad9f665c](https://github.com/ajayyy/SponsorBlock/compare/5.0.3...5.0.4#diff-b769f60434f9ce6a59837e3786f8b1ef4d13930a04c73e4d525ffa17ad9f665c)
I reverted back and forth between version 5.0.3 and 5.0.4 in Developer mode and the issue consistently returns with 5.0.4 and is resolved by going back to 5.0.3. I might have to try and see if I can determine which commit is responsible.
