### ISSUE TITLE
Broken buttons on YouTube clips

### ISSUE THREAD

**Issue by Kruchji** [ajayyy/SponsorBlock#1496]
When viewing any clip on YouTube (youtube.com/clips/...) all of the SponsorBlock buttons show up:
![image](https://user-images.githubusercontent.com/32173730/192166140-210ec702-60aa-4e4e-8790-7e00d5d3def5.png)

**Comment by ajayyy** [comment]
Could you link an example?

**Comment by Kruchji** [comment]
Sure, [here](https://www.youtube.com/clip/UgkxeYeJAIL1rujOoU0G_BWGQc856JUWn_RM) is one example (but it happens to me on any clip).

**Comment by mchangrh** [comment]
can repro - they're supposed to be disabled since it seriously messes up any segment marking, the side effect might be making all the buttons appear

**Comment by mchangrh** [comment]
found the problem

**Comment by mchangrh** [comment]
.take
