### ISSUE TITLE
Not binding to videos in /embed

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlock#1497]
Reported on discord multiple times

**Comment by mchangrh** [comment]
last change for embeds #1387 

might be new element with new UI?

**Comment by mchangrh** [comment]
@ajayyy 

https://github.com/ajayyy/SponsorBlock/commit/a9186a35e5c89e6f860047e0fcac2e776ea57825

this commit broke it, since the `video` element is not available in embeds before DOM is ready

**Comment by Ghostkeeper** [comment]
Thank you so much for fixing this! I wasn't aware of the details of when this bug occurred, but I'm glad you guys figured it out.

Love this add-on, it's the best.
