### ISSUE TITLE
Import a comment as chapters

### ISSUE THREAD

**Issue by Madis0** [ajayyy/SponsorBlock#1499]
Popular videos which don't have chapters on their own usually have a nice person in the comments who has listed the chapters. There should be an easy way to copy those over to Sponsorblock, for those who have access to chapters in the first place.

**Comment by bgiesing** [comment]
> There is an import button in the popup for this

Where? The popup has no import button at all on v5.0.5
![image](https://user-images.githubusercontent.com/7895463/192863830-d623a5a6-69aa-4d18-9a14-0ef245c63d67.png)

**Comment by ajayyy** [comment]
Do you have chapters enabled?

**Comment by ajayyy** [comment]
Alright, seems to be a bug that it does not appear when there are no segments found

**Comment by bgiesing** [comment]
> Do you have chapters enabled?

Yeah I have Chapters enabled and can submit them manually, just there's no import.

**Comment by ajayyy** [comment]
Will be fixed in the next version

**Comment by couleurm** [comment]
![image](https://user-images.githubusercontent.com/82747632/219211333-418bf402-3733-4e0c-8906-d5d1ac3be853.png)
Is it supposed to show up in there?

**Comment by ajayyy** [comment]
No, you copy the text into the import button in the popup
