### ISSUE TITLE
When creating a segment, the Start timestamp gets overwritten when pressing "Now" on the end timestamp

### ISSUE THREAD

**Issue by AcesFullOfKings** [ajayyy/SponsorBlock#1502]
(Macos 12.5, Firefox)

Replication: 
1. Create previous segment (e.g. chapter) and copy the end timestamp to clipboard. This end timestamp will be the start timestamp of the next segment.
2. Navigate to somewhere in the middle of the next chapter (some time after the starting timestamp you just copied)
3. Create new segment
4. Choose type from dropdown list in segment box
5. In Start box, select all and paste timestamp into textbox
6. Play the video until the frame of the end of the segment
7. Click "Now" on the **RIGHT**, next to the End timestamp box
8. The "start" timestamp that you pasted in now gets deleted and overwritten with the timestamp from step 2 when you created the segment. Why is that even saved outside of the text box?

This is annoying when chaining segments together, as I lose the starting timestamp I previously "saved" in the text box. And with the recent change where it takes some time for a submitted segment to show after a refresh, I can't even retrieve it from the end time of the last one in the database.

Solution:
Pressing "Now" on the End box should not affect the contents of the Start box.

**Comment by theonefoster** [comment]
Note - this only happens the first time. Subsequent presses of "Now" don't overwrite the Start time, as expected.

**Comment by theonefoster** [comment]
Another note - pressing "End" has the same effect.

**Comment by erkinalp** [comment]
Can also reproduce

**Comment by sup2069** [comment]
Can reproduce as well. Came here to create a ticket and saw this ticket.

**Comment by mchangrh** [comment]
This sounds like the input box isn't "saving" when times are pasted in. Typing it out or any other interaction seems to solve this, at least for me
