### ISSUE TITLE
[feature request] Seed playback speed by channel

### ISSUE THREAD

**Issue by MPW1412** [ajayyy/SponsorBlock#1503]
Hello, and thank you very much to all contributors!

I'd like so suggest a small handy feature: This plugin at least to my understanding has its focus on efficient content consumption and time saving.

It would be awesome to set the playback speed per channel. Some youtubers make content, that you'd want to watch at standard speed and for some channels you set the speed high. As SponsorBlock already has the feature to use the channel id as parameter, it might be easy to also preset the speed for each channel. Without syncing, just for your own browser.

Best,
Matthias

**Comment by mchangrh** [comment]
sounds out of scope for sponsorblock
