### ISSUE TITLE
Consider changing default "skip to chapter" keybind to be the same as YouTube

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#1508]
Split from  #1507

**Comment by Illuminati-CRAZ** [comment]
Would it be possible to accomplish this by having user-submitted chapters behave the same as normal chapters? I use another Youtube extension ([Tweaks for YouTube](https://chrome.google.com/webstore/detail/tweaks-for-youtube/ogkoifddpkoabehfemkolflcjhklmkge)) that can interact with chapters, so having the additional compatibility would be nice.

**Comment by joshinils** [comment]
> Would it be possible to accomplish this by having user-submitted chapters behave the same as normal chapters? I use another Youtube extension ([Tweaks for YouTube](https://chrome.google.com/webstore/detail/tweaks-for-youtube/ogkoifddpkoabehfemkolflcjhklmkge)) that can interact with chapters, so having the additional compatibility would be nice.

i would prefer that, having two separae keybinds that skip to two separate sets of timestamps is kind of weird

**Comment by ajayyy** [comment]
There's no way to "become" a normal chapter unfortunately, just do more acting like they belong

Looks like the way that extension detects chapters is by parsing the engagement panel on the right, so hooking into that and drawing chapters there probably would make that extension work.

![image](https://user-images.githubusercontent.com/12688112/198814392-08ed20ac-cbf1-4855-9af1-3849d6d7b0fa.png)
