### ISSUE TITLE
Sponsor check only called every 250ms

### ISSUE THREAD

**Issue by afontenot** [ajayyy/SponsorBlock#151]
When I'm marking a sponsor, I advance frame by frame to set the beginning marker exactly on the correct frame. This is how I know that SponsorBlock starts the skip too late. Even though I set the beginning time correctly, when previewing, I see that it doesn't skip until later. I try to set the times exactly right, so I end up having to edit the start up back 0.05s at a time until the cut is accurate.

This usually requires reducing the time the cut starts by 0.2 to 0.3 seconds.

Tested on the latest version of Firefox.

**Comment by ajayyy** [comment]
The end time should be perfect, but yea, the start time is only precise to 250ms. The way it checks the time is by polling for a time change on the video, and this only triggers every 250ms. There are ways to improve this, but I felt it didn't need to be a priority.

**Comment by afontenot** [comment]
Good to know! So if I set the skip to be frame accurate, and then back it up by 0.25 seconds, I'm guaranteed that the skip will occur in the correct window? I think I might start doing that.

Alternatively, you might consider checking to see if a skip starts in the *next* 250ms window, and if so, starting it now. That way you're guaranteed to start the skip in time. (You could of course start a timer to start the skip at exactly the right time, which I assume is at least one way of improving it that you're thinking of, but I guess that would be more work and maybe more resource intensive.)

**Comment by ajayyy** [comment]
Yea, that would be the solution. Then again, that could break if someone has 2x speed on. It's a hard balance to get it perfect. Right now, the system works under the idea that seeing a bit of the sponsor is better than missing a bit of the content (which I believe). So, going back 250ms just goes against that philosophy. 

I'd be curious about your opinion on that. Do you think it is better to not see any sponsor but maybe miss some content?

**Comment by afontenot** [comment]
> I'd be curious about your opinion on that. Do you think it is better to not see any sponsor but maybe miss some content?

Personally, yes. For example, I'd prefer to see uBlock occasionally break a page layout rather than occasionally show me an ad. Especially in this case, I think it's worth it, since you're guaranteed to miss less than 0.25s of content this way anyway. (Plus people like me who preview their skips before submitting are going to naively think something is wrong and reduce the start time *anyway*, which breaks your attempt to never skip early.)

If you want to avoid the timers you use breaking for different playback speeds, couldn't you just set the timer to `250 ms / multiplier`, so that you always get 4 calls to your check function every second? 

Or if you want to do the really fancy thing, and hit the skip precisely, every `check()`, see if there's a skip in the next window, and set a timeout on the skip function of `(skipTime - currentTime) / multiplier`, so that the skip function always gets called on the correct frame. In the skip function, add a check to make sure you're in the correct window, since the user might have navigated away in the ~0.25s since we started the timeout. (All this is pseudocode, of course, I haven't looked at how you do this. Also, you might need to target the frame before by subtracting 0.04s to make sure you hit it, given function overhead.)

**Comment by mirror176** [comment]
I'd recommend not marking edits to fit specifically to imprecise timing of sponsorblock if having an open database is a real goal. If it is just a pause transition, I remove more of the pause, especially if there is a sponsor-free pause after the sponsor that can be reliably used. Otherwise, when someday downloaders/players/reencoders offer to read sponsorblock data too, they will have their own accuracy which won't have the startup delay the same if at all and if present it will likely be more consistent.

**Comment by ajayyy** [comment]
Also remember that this could be used for even more precise stuff like training an ML algorithm.

**Comment by ajayyy** [comment]
To be clear, this was closed in January as this does **not** occur anymore. Skips are now as precise as the setTimeout function on the browser (closer to 5ms - 10ms)
