### ISSUE TITLE
sponsorblock will not skip sponsor if intro and a sponsor are back to back

### ISSUE THREAD

**Issue by RockL79** [ajayyy/SponsorBlock#1510]
if you have intro skipping set to automatic or manual in options and a video has a sponsor right after the intro, even if you do not skip the intro the sponsor will not be skipped. This video is the one I discovered the issue in; https://www.youtube.com/watch?v=JEgsG_wl0kc

**Comment by RockL79** [comment]
> what do you have sponsor set as?
> 
> there are no categories that skip automatically depending on their proxmimity to other categories.
> 
> all intros will follow what you have intro set as and same with sponsor

I initially had sponsor as automatic skip and intro as manual, but the same thing would happen if both were set to automatic.

**Comment by mchangrh** [comment]
oh. that's not the root cause

on first load, the two segments that start/end on the exact same time don't skip as one

**Comment by ajayyy** [comment]
they were not the same time. Second one was less than a millisecond later
