### ISSUE TITLE
Preview bar on music.youtube.com

### ISSUE THREAD

**Issue by EthanBnntt** [ajayyy/SponsorBlock#1525]
SponsorBlock does not skip non-music segments on music.youtube.com

**Comment by ajayyy** [comment]
It should work on there

**Comment by EthanBnntt** [comment]
Ok, SponsorBlock does skip non-music segments on music.youtube.com. It must have been a bug on my end. 

There doesn't appear to be support for displaying segments in the music progress bar on music.youtube.com, which I think should be supported. Should I open a separate issue for segments not displaying on music.youtube.com?

**Comment by mchangrh** [comment]
.take

**Comment by EthanBnntt** [comment]
Wow, that was fast. :D
