### ISSUE TITLE
Stats aren't loading 

### ISSUE THREAD

**Issue by androidacy-user** [ajayyy/SponsorBlock#1526]
Both in YouTube ReVanced and https://sponsor.ajay.app/stats/ never say anything besides loading.

Tested on multiple connections and devices.

**Comment by mchangrh** [comment]
Stats in revanced are pulled from another endpoint and work fine, that's specifically a revanced issue.

/stats/ is disabled for load management

**Comment by mchangrh** [comment]
Per-user stats aren't from the /stats page.

Personal stats not loading is a known revanced issue, bug them about it.
