### ISSUE TITLE
"Skipping is enabled" checkbox does not match the checkboxes on the settings page.

### ISSUE THREAD

**Issue by EthanBnntt** [ajayyy/SponsorBlock#1528]

**Comment by mchangrh** [comment]
The "skipping is enabled" checkbox in the popup is a global (temporary) toggle, independent of the per-category settings

**Comment by EthanBnntt** [comment]
Shouldn't it be red to match the toggles on the settings page?

**Comment by mchangrh** [comment]
Oh, I thought you meant the behavior of it, are you specifically saying that the green colour should be changed to match the red togges in the settings pages?

**Comment by EthanBnntt** [comment]
Yes, the styles are not consistent. The behavior is.

**Comment by EthanBnntt** [comment]
Should I try to fix it?

**Comment by EthanBnntt** [comment]
Fixed

**Comment by EthanBnntt** [comment]
I will close the issue when the pull request is merged or closed.

**Comment by EthanBnntt** [comment]
@ajayyy said he's not interested at the moment. Closing the issue as not planned.

**Comment by EthanBnntt** [comment]
Closed
