### ISSUE TITLE
Auto skipping is broken on Invidious instances.

### ISSUE THREAD

**Issue by SkMyPP** [ajayyy/SponsorBlock#1539]
I have all options set to automatically skip all segments, none of them work on any Invidious instance since the last update. This problem is exclusive to Invidious, already tested on YouTube & CloudTube with no issues.

Yet another update that makes SponsorBlock unusable with Invidious...

**Comment by ajayyy** [comment]
Try disabling and reenabling invidious support

**Comment by SkMyPP** [comment]
> Try disabling and reenabling invidious support

I've already tried it, forgot to mention it on the original post.

I tried disabling and enabling the addon and also enabling and disabling the "support for 3rd party youtube-sites" options; none of them worked.

**Comment by SkMyPP** [comment]
Closing this as it seems to have been resolved (At least for now...)
