### ISSUE TITLE
I've noticed that my username keeps getting reset, and I don't know why.

### ISSUE THREAD

**Issue by vizthex123** [ajayyy/SponsorBlock#1541]
I've exported my settings a couple times to back them up, but have never imported them again.

But, I noticed that every so often it resets my username. Not sure why.

**Comment by ajayyy** [comment]
check your private userID, is it blank? settings -> misc -> import/export private id

**Comment by vizthex123** [comment]
Nope, it has an auto-generated one.

**Comment by ajayyy** [comment]
What do you mean by reset?

**Comment by mchangrh** [comment]
> I've exported my settings a couple times to back them up, but have never imported them again.

username is not local, it's tied to your private userID, if you didn't reimport then it most likely means you're submitting / setting usernames under different "accounts" each time

accounts are **not** tied to usernames, usernames are **not** unique

**Comment by vizthex123** [comment]
> What do you mean by reset?

It just gets set to the default blank one, moreso annoying than anything. I think it might be cuz the servers keep crashing.



> > I've exported my settings a couple times to back them up, but have never imported them again.
> 
> username is not local, it's tied to your private userID, if you didn't reimport then it most likely means you're submitting / setting usernames under different "accounts" each time
> 
> accounts are **not** tied to usernames, usernames are **not** unique

Haven't touched my user ID, nor imported any settings.

I export them every so often as a backup, but I haven't had to re-import them yet.

**Comment by mchangrh** [comment]
oh the username showing up as blank is serverside, which would be tied to the servers breaking

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/1549
