### ISSUE TITLE
getTotalStats and getTopUsers APIs return 404

### ISSUE THREAD

**Issue by rredford6** [ajayyy/SponsorBlock#1542]
For an example see https://sponsor.ajay.app/stats/

**Comment by mchangrh** [comment]
intentional

**Comment by rredford6** [comment]
@mchangrh are you going to remove the stats page on the site?  Remove that endpoint from the docs?  Or just leave it in an unexplained broken state?

**Comment by ajayyy** [comment]
leave it in an unexplained broken state

**Comment by rredford6** [comment]
Can you at least provide the reason why the API was discontinued?

**Comment by ajayyy** [comment]
leave it in an **unexplained** broken state

**Comment by LofhJann** [comment]
Is there any reason apart from time restraints why leave it like this? Personally I find it quite confusing to have "Leaderboard" button that does lead to page with never-ending spinner. Is stats page considered WIP and will be fixed eventually or is it deprecated for good (in which case it absolutely should be removed imo)
