### ISSUE TITLE
Feature Request: A 'Greylist' setting for a secondary level of Blocking.

### ISSUE THREAD

**Issue by WolvenSpectre** [ajayyy/SponsorBlock#1543]
It would be great if you had a setting between fully blocked following the settings and Whitelist (which is off)

For example take this scenario.  Generally you have auto skip on 3rd party sponsors, however on some channels there is some sponsors you may choose to watch as they are products that interest you.  You could have said middle setting be manual skip.  

You could change your default Blacklist behaviour to manual skip for all channels but then most of the channels you would want to auto skip make you manually skip it.  Now if you had a setting that Whitelist could be set to other options than off you run into the problem that that is not what a Whitelist typically means and can make it more confusing for users.  Adding a Grey List may fix that and be more clear.

Just thought this or something like this could be helpful for having more granular control across peoples different interests on YouTube.

**Comment by ajayyy** [comment]
#435
