### ISSUE TITLE
Segments not properly submitting

### ISSUE THREAD

**Issue by embyveddii** [ajayyy/SponsorBlock#1545]
I have created a few segments that seem to be working, but oftentimes when submitting a segment, it disappears on reload or when creating a new one. Just tried to add a highlight and endcard segments on a video, and when starting the endcards one, the highlight one disappeared. When reloading the page to check, both are gone. I tried editing it in the video window and the extension window on my browser and neither worked. I'm using Firefox with Sponsorblock v. 5.1.1

**Comment by embyveddii** [comment]
Well i checked again just now and the segments do appear to be there, so there just seems to be a huge delay on it realising

**Comment by mchangrh** [comment]
there is a 30 minute nginx cache for all segments to help alleviate server load

**Comment by mchangrh** [comment]
"discarded" segments - nginx cache
"5xx" when trying to submit - server down

**Comment by embyveddii** [comment]
so how should I make sure it works in the future? or does it work every time and just doesn't appear right away?

**Comment by mchangrh** [comment]
the latter - if you don't get an error on submitting it was successfully sent, it'll just take 30 mins to appear on refreshes

**Comment by embyveddii** [comment]
That's good to know. Thanks for the help
