### ISSUE TITLE
Keep on getting this error while submitting

### ISSUE THREAD

**Issue by rakitanc** [ajayyy/SponsorBlock#1546]
![Screenshot from 2022-10-18 22-55-46](https://user-images.githubusercontent.com/64612555/196501971-35e4441c-1f39-4467-9b6b-4c2951dae2cc.png)

**Comment by Saiv46** [comment]
Submitting server is **down**

https://status.sponsor.ajay.app/

**Comment by Zamion101** [comment]
> Submitting server is **down**
> 
> https://status.sponsor.ajay.app/

When it's not?

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/1549
