### ISSUE TITLE
SponsorBlock stopped working on PC and SmartTube TV app

### ISSUE THREAD

**Issue by nefariouslegion** [ajayyy/SponsorBlock#1552]
Hello,
Recently it seems SponsorBlock has stopped working on my PC and my Google TV using the SmartTube app. I'm not sure if this is a SponsorBlock issue that needs to be fixed or if I need to do something on my end to fix it? It was working fine a couple days ago.

**Comment by nkoc6a15** [comment]
Server down

**Comment by nefariouslegion** [comment]
> Server down

ah ty. Yeah I found a link to server status on reddit after posting this. didn't know the link existed before posting. https://status.sponsor.ajay.app/
