### ISSUE TITLE
can we get a 'Popup' when the extention fails to connect to its db? 

### ISSUE THREAD

**Issue by alidan** [ajayyy/SponsorBlock#1555]
every so often sponsor block fails to load, I think it would be nice to have a pop up telling us if it was just a time out, the extension failed, or if it was a server issue. not sure how cumbersome this would be to add.

**Comment by rpgdev** [comment]
at this point I wouldn't be surprised if all of this performance issues are a ruse to eventually charge for sponsorblock. Good thing it's open source and can be forked.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/1553
