### ISSUE TITLE
 Error code: 502

### ISSUE THREAD

**Issue by baram82** [ajayyy/SponsorBlock#1556]
Firefox, windows 11 not working any idea what im doing wrong? fresh windows install.

**Comment by baram82** [comment]
A connection error has occurred. Error code: 502

**Comment by sup2069** [comment]
Read the pinned comment.

**Comment by baram82** [comment]
Nice found what I needed here.
https://status.sponsor.ajay.app/

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/1549
