### ISSUE TITLE
[tracking] YouTube @handle url handling

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlock#1557]
Currently for the ChannelID lookup we use a combination of innertube response and document scraping. For document scraping, we need to support the new channel IDs handles that roll out but also not catch the rich channelID markers in the description.

**Comment by mchangrh** [comment]
.take

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/commit/4af318403af9b3be702ff0098991dbd458dab01b
