### ISSUE TITLE
sponsorblock popup chosen times could be more useful at the top of the popup

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#156]
I really hate to suggest this due to personally hating (with reasons) 1. dynamic interfaces and 2. top-posting. So to come out and say it, I have to scroll down in windowed mode to see and edit my chosen times and scroll up to get back to the youtube video. It would be more helpful to have my times closer to the video and preferably near the previously found sponsors if I am editing or adding to what was already listed. Top-posting would be to keep the last or newest edit at the top so it won't get far from the video but would probably be best kept in chronological order and have a scrollbar for its listing within the popup as an option to avoid scrolling away from the video. It would be more relevant if future categorization of skippable content leads to many edits. If confusing I could try to make a drawing of what is meant by that.

**Comment by ajayyy** [comment]
![image](https://user-images.githubusercontent.com/12688112/69490338-1de7e580-0e54-11ea-8125-7098b3c2b111.png)
