### ISSUE TITLE
[Bug] preview thumbnail overlaps "Pull up for precise seeking" text

### ISSUE THREAD

**Issue by joshinils** [ajayyy/SponsorBlock#1563]
https://youtu.be/OGLdTJ14RRM
![image](https://user-images.githubusercontent.com/34302971/198818901-7851ae47-b2cf-4f96-a790-dd286704e33a.png),![image](https://user-images.githubusercontent.com/34302971/198818929-569a0c18-f554-415d-b79d-e7ee1aa4242d.png)
while seeking, the preview-thumbnail image that pops up gets raised when there is a named chapter, the "Pull up for precise seeking" text does not get raised by the necessary amount.

**Comment by ajayyy** [comment]
Fixed
