### ISSUE TITLE
Submitted times not showing up

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#157]
Submitted 3 times (last one looks like a glitchy edit that cuts off content and goes into a glitchy edit of their sponsor; could be a sponsor or bad edit but either way I thought it should be gone) and on review shows as if there are no edits. Thought I hit submit instead of clear and when checking I did it right I remarked+submitted times which again did not show. https://www.youtube.com/watch?v=AZNLCzL1WAg was the video. Any reason that my edit wouldn't load/show? Tried a shift+refresh and a new window to check.

**Comment by ajayyy** [comment]
I am very confused, this video specifically won't load any sponsors. There 56 submissions for this video in the DB (so many people are having the issue and thinking they have to submit).

Other videos are working fine.

**Comment by ajayyy** [comment]
Found the bug. It occurs when there are more than 4 sponsor spots.

**Comment by ajayyy** [comment]
Fixed in a6821209d12ca1bea29b633d0fbd1f818acca24b
