### ISSUE TITLE
[FeatureRequest] Offline mode, Import/Export Settings, & Fall back servers

### ISSUE THREAD

**Issue by Gigafrost** [ajayyy/SponsorBlock#1571]
With how often sponsor block seems to be going offline, I would love to suggest a few features to help maintain the amazing experience this app offers.

- An offline mode. Basically a cached version of Sponsor block that allows users to download on their PC or Shared server to use whenever there's a server outage.
- Export and import settings to allow us to quickly set configs for the app whenever we install on multiple browsers and computers.
- A backup server for users to use when the app crashes (which is seemingly often). On that note I'd suggest a better server in general for sponsor block. It doesn't seem all that reliable for this app's use case.

**Comment by ajayyy** [comment]
1. duplicate
2. already exists
3. duplicate
