### ISSUE TITLE
Fails to run on Shorts

### ISSUE THREAD

**Issue by avi12** [ajayyy/SponsorBlock#1573]
After running the extension locally on [this video](https://www.youtube.com/shorts/awPdKeIBKQg), I found out that the issue lies on https://github.com/ajayyy/SponsorBlock/blob/ef8c5f58c55ca25f2966cfbe5c73014d4db89964/src/js-components/previewBar.ts#L822-L823
Specifically, `this.getChaptersContainer()` returns `null`

**Comment by ajayyy** [comment]
https://greasyfork.org/en/scripts/439993-youtube-shorts-redirect
