### ISSUE TITLE
Rework the skipping code to compensate for the trigger delay

### ISSUE THREAD

**Issue by erkinalp** [ajayyy/SponsorBlock#1579]
This change would allow us to have perfectly back-to-back segments when the transistion within original content is clean and keep most skip segment boundaries outside crowd chapters.

**Comment by ajayyy** [comment]
It's not about the trigger delay, it's a property of video. You want to skip to _after_ the frame, but want to start skipping _before_ the frame happens

**Comment by erkinalp** [comment]
I was talking about 2-ish frame delay that happens in mobile and on Firefox.

**Comment by ajayyy** [comment]
making skips more accurate is more important on firefox. There is no fixed delay, it's a consistency thing
