### ISSUE TITLE
topics to consider to add (sub)categories

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#158]
This will likely be a multistep modification to the project so I'm listing ideas relevant to consider for this. Though I know there are other desired changes being sought after first, giving this some thought and beginning implementation sooner rather than later would be worth considering for database consistency to avoid having to rereview content or even fight over what should be skipped or not now as people decide what to call a sponsor and mark vs mark other things they may want skipped. I know of merch store placements that I would prefer always skipped but if you have an educational content creator with educational articles on his site which also acts as his store to sell 1st/3rd party products and/or services plug his site to support users with what they need/ask for then it really needs separate consideration (and later worth skipping if it was not more than 'I answer that on my site (begin generic site ramble)' when a regular now is fully aware of the site.

- Make a popup identifying a video as just a sponsored video (or subcategories later mentioned below); give user an option to warn or permit viewing if it is 100% sponsored content.

**Content categorization** This area gets more blurred the more one thinks about it; the structure below should likely be rearranged.
- [ ] third party
brief
irrelevant/relevant to content
funny
misleading that it was an ad
affiliate code

- [ ] first party
plugging other services and merchandise, relevant/not relevant to the presented content
product placement (https://github.com/ajayyy/SponsorBlock/issues/162#issuecomment-548251137)
begging for support

- [ ] other content
- titles
- credits
- previous content recap
- talk of other content: not yet released, first party, third party, etc.
- off topic content
- crying/breating/pausing/etc. (some last much longer than worth watching)
- deadspace
- objectionable content (offensive, disturbing, phobia, etc.)
- audio vs visual separation of objectionable
- contest
- social media - 1st party:like, subscribe, bell and 3rd party:follow us on, join our forum, etc.

- [ ] audio vs video vs both for reason of blocking
- Users not wanting to see objectionable content would likely not care about a seamless cut and would prefer to lose adjacent overlapping content to not be 'exposed' to what they do not like
- Audio could just be muted instead of content skipped as a preference in the player. Video if it could be blacked out could allow adjacent audio or freeze frame of a clean scene before/after (maybe with a dissolve transition) while audio plays in a player.

- [ ] User setting has a list of markable types of content for viewing
- Works like a whitelisted content until saying you do not want that
- Either requires limited categories for submissions, a default set of categories, or grows as content type is found (by videos the user has loaded or by a probe from the database)
- A database probe would likely help keep categories in check for typos, variants of the same meaning, etc. if any user could submit them; not as necessary if categories are chosen by the project but could be far less flexible then too.
- Need to think of how to present to the user when a new category of relevance is available to them to skip or not as a main/channel setting.

- [ ] subcategories

**nonsponsor categories opens doors to different issues**
- [ ] make sure overlap seeks from start to end of any combined jumps
- [ ] editors may need help being reminded if a cut is near another one so it can 'connect' without little slices being left between.
- [ ] Defaults should likely be to only check nonrelevant sponsors on first install but would be better to have a user make choices during install 
- Consider if they should be implemented each as their own category or truly give a tree-like structure so they can be turned on/off as groups
- Replace whitelisting a channel with category control
- Make sure UI expressing normal vs could-be-skipped vs will-be-skipped to user
- Though not a requirement, sponsorblock may consider a new name as it starts to break content up into more than just sponsored vs nonsponsored segments. - _ajayyy planning to not make a new name at this time due to brand recognizition._

**Comment by mirror176** [comment]
Unless this is going into a wontfix type category, I can try to better organize, expand, clarify and give examples.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlockServer/issues/27

https://github.com/ajayyy/SponsorBlockServer/pull/31

**Comment by ajayyy** [comment]
It is really hard to quantify such broad topics like this, but it is something I want to think about.

**Comment by Chess13234** [comment]
Titles/Credits are wasted time. Most people don't want to watch the same sequence over and over.
It contains nothing useful(useful info is usually put in the description), but can cover more than 10 seconds. Particularly bad are "closing sequences" that some youtubers put that span nearly a minute.

**Comment by ajayyy** [comment]
![image](https://user-images.githubusercontent.com/12688112/78467704-538fbb80-76dd-11ea-857c-598338838d6e.png)
