### ISSUE TITLE
K Anonymity is misleading

### ISSUE THREAD

**Issue by Nekromateion** [ajayyy/SponsorBlock#1591]
[K Anonymity](https://github.com/ajayyy/SponsorBlock/wiki/K-Anonymity) doesn't seem to be described well enough for all users to simply understand its obvious flaw.

In the wiki entry it says :
> This system allows the client to be lightweight and always get the latest segments on every video while still ensuring the server cannot predict which videos they are watching.

While this is accurate, the by default enabled option to send skipped segments to the server makes it essentially useless.

You might argue that users who care about their privacy would check these things, however I believe that this should not be something that the User has to find out for themsevles.

The wiki entry should mention that having that option enabled leads to making the anonymization useless for videos that have skip segments.

**Comment by ajayyy** [comment]
updated the wiki

**Comment by Nekromateion** [comment]
Perfect, thank you!
