### ISSUE TITLE
Check if server is up before selecting segments

### ISSUE THREAD

**Issue by floppyD** [ajayyy/SponsorBlock#1592]
It sucks when you spend some time selecting a segment just to find out that the server is down and you wasted your time. Some check that informs the user before he starts selecting would avoid that.

**Comment by ajayyy** [comment]
This already exists, are you not seeing it?

**Comment by floppyD** [comment]
@ajayyy Where exactly? It's not until I try to upload the segments that it tells me the server is down.

**Comment by OscarDogar** [comment]
> @ajayyy Where exactly? It's not until I try to upload the segments that it tells me the server is down.

I think this may help you.
- https://status.sponsor.ajay.app/
- Another option is to first see if when trying to load the segments there were no problems with the server.

**Comment by floppyD** [comment]
I know this page exists, and the feature I'm asking is exactly to avoid having to check it before selecting segments. Just ping the server or something when you hit the select segment button so you know it's offline.
