### ISSUE TITLE
Exclusive access segments

### ISSUE THREAD

**Issue by melissis** [ajayyy/SponsorBlock#1598]
This video by the channel `ThrillSeeker`: [HELLO WIRELESS VALVE INDEX, Goodbye Wired VR Headsets](https://youtu.be/QMMDaA6s3To?t=166)
has a segment that talks about and reviews a prototype product that he was allowed exclusive access to from a company. Not a sponsored segment, I would say, and most viewers would probably like to watch it. It is limited to a specific section of the video, but currently, the "Exclusive access" category only has Full Video Labels, not segments.
EDIT: Oh, wait, there are _two_ segments in the video (2:46 and 11:17) that has exclusive access stuff, but for two different products.

Suggestion: make it possible to add Exclusive access segments.

Question: if no, then what should we do in these situations? Add label even though it is only a distinct portion of the video, or not add the label?

**Comment by mchangrh** [comment]
> ... most viewers would probably like to watch it.

> This label should only be used when the creator showcases a product, service or location that they've received free or subsidised access to in the video that cannot be completely removed by cuts. [wiki](https://wiki.sponsor.ajay.app/w/Full_Video_Labels#Exclusive_Access)

this seems like a textbook use case for exclusive access - indicating possible bias for a video that doesn't need to have it explicitly removed .

**Comment by melissis** [comment]
> this seems like a textbook use case for exclusive access - indicating possible bias for a video that doesn't need to have it explicitly removed.

Some portions of the video have nothing to do with that, though (like 40% of the video), and the other parts do not and can not be biased from exclusive access.

**Comment by mchangrh** [comment]
the usage of exclusive access is only from segments that cannot be removed, not if the entire video contains over a certain percentage of "exclusive access" content.

**Comment by melissis** [comment]
Yes. So, when you put it like that, this video is not a clear case for the exclusive access label, because it's not over the entire video.
The structure of the video is basically this:
- Introduction (1 min)
- News story 1 (2 min)
- News story 2/review of product A (exclusive access) (video title refers to this segment) (5 min)
- News story 3 (1 min)
- News story 4 (30 sec)
- News story 5 (1 min)
- News story 6 (40 sec)
- Short review of product B (exclusive access) (40 sec)
- Question of the week (40 sec)
- Closing words and endcard (30 sec)

News story 2 shouldn't be marked as sponsor, as it's not a sponsor. It's just that the videographer got an exclusive demonstration of an upcoming product.
The rest of the video has nothing to do with product A.

**Comment by melissis** [comment]
Maybe reviews isn't Exclusive Access? It's pretty much industry standard to get a free review copy of whatever you're reviewing. And only YouTubers who are honest and discloses free/exclusive access would be the only ones who get punished with the Exclusive Access label.

**Comment by ajayyy** [comment]
We have done deeper research in the past to find the info even for badly disclosed videos. It's even _more_ important for those because of that malicious omision of information

**Comment by mchangrh** [comment]
No, I understood you perfectly fine. The presence of the segment and it being integral to the video means that it indicates Exclusive Access. 

> not if the entire video contains over a certain percentage of "exclusive access" content

1% or 50% or 100% doesn't matter. **Any** amount that can't be removed is enough for EA.

**Comment by melissis** [comment]
> **Any** amount that can't be removed is enough for EA.

Alright. Then it's clear.

**Comment by melissis** [comment]
> We have done deeper research in the past to find the info even for badly disclosed videos. It's even _more_ important for those because of that malicious omision of information

So what about, like, IGN's game reviews? One of the biggest gaming media companies. I doubt they buy their games. Presumably, every game developer just sends them early review copies without even asking.

**Comment by ajayyy** [comment]
> standard journalistic practice

Doesn't mean it is good


https://user-images.githubusercontent.com/12688112/206028679-9a1911b8-2d50-4849-a1d8-ed0707623a0d.mp4

**Comment by mchangrh** [comment]
People shouldn't expect deception.
