### ISSUE TITLE
blank plugin window and plugin does not work anymore

### ISSUE THREAD

**Issue by PtDragon** [ajayyy/SponsorBlock#1599]
Hello!
For me SponsorBlock does not work anymore.
Plugin window is blank, removing and installing back did not help.
What can I do to fix it?
System: Win 11 x64, FireFox Nightly x64.

**Comment by mchangrh** [comment]
Try creating a new firefox profile

**Comment by 71256988** [comment]
Having the same issue on Firefox 102.5.0esr.
Browser console has the following output:
![image](https://user-images.githubusercontent.com/113604627/206486905-7aef85e7-d9c1-4af8-8719-5d31a4dc70d2.png)

**Comment by 71256988** [comment]
Now works again as of today. Thanks!
