### ISSUE TITLE
[BUG] SponsorBlock disables Shorts Scrolling on Desktop using Chrome on Mac

### ISSUE THREAD

**Issue by deadcoder0904** [ajayyy/SponsorBlock#1602]
It probably updated recently. But from last 2-3 days or probably a week, I can't scroll shorts with <kbd>↑</kbd> & <kbd>↓</kbd> arrow keys or using the <kbd>↓</kbd> icon on bottom-right using mouse doesn't work either.

I get stuck on the first video & have to go back to start another short of the same channel. I went through the new Shorts tab & click ↓ ↓ ↓ but nothing happens.

Had to uninstall the extension to make Shorts work again.

Please fix it so I can re-install SponsorBlock again :)

**Comment by deadcoder0904** [comment]
It worked then but it doesn't again now after uninstalling so I guess SponsorBlock is not responsible for it.

I did check network requests but can't figure out which extension is the culprit.

Google doesn't show anything either.

Wish there was a way to figure out which extensions are running on a particular site :(

**Comment by ajayyy** [comment]
SponsorBlock is saving you from the hell that is YouTube shorts :)

**Comment by deadcoder0904** [comment]
well, i only use it to listen to a few entrepreneurial shorts which are great for ideas.

dw not doomscrolling all day with dancing or funny videos 😂 

wish, i could find which extension causes the bug but google search isn't helping either.
