### ISSUE TITLE
Wrong developer name

### ISSUE THREAD

**Issue by XiXiongMaoXiong** [ajayyy/SponsorBlock#1615]
Though this is not a serious issue or anything code related but I noticed that Google side panel shows YouTube as the name of this extension developer.

Sorry for my bad English.

![image](https://user-images.githubusercontent.com/23288867/206867540-46fa62f4-fe32-434d-b3cc-e1a01e4c9354.png)

**Comment by ajayyy** [comment]
Not possible to edit this on my end
