### ISSUE TITLE
Enhance whitelist to allow changing each category's skip rules

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#1618]
It would be more useful if able to adjust sponsorblock settings on a channel by channel basis instead of the broader off/on per channel. Interface could have a button to whitelist a channel which overrides settings to disabled as a group edit and another to remove overrides. Ability to store other 'presets' could be handy too. Would be handy to be able to see all channels/overrides without having to go to each channel to see/edit its state. This would resolve issues such as "I usually like jokes but not the ones this channel makes" leading to having to decide to alter auto-skip/manual-skip general settings when viewing a channel vs other content when you don't want to just disable SponsorBlock as a whole.
 This doesn't fix the issue of issue of categorizing the quality/type of an entry like offensive/dad/general/etc. jokes, self promo matching "I make this tool and sell it to solve a problem related to this topic", "buy some merch someone else makes and gives me a cut for", "support me with membership/donation through...". A side effect is if a channel consistently made categorized content fall into a single of such subcategories then we could block/unblock the category getting a desired effect.
  Admittedly I haven't used the whitelist feature and usually only change to skip or not if I am checking edits (both mine and others').

**Comment by mchangrh** [comment]
#1261

**Comment by vizthex123** [comment]
yeah, it'd be nice if i could be like "don't skip the intro on this channel's videos, but skip everything else"

**Comment by ajayyy** [comment]
#435
