### ISSUE TITLE
Don't skip by default

### ISSUE THREAD

**Issue by BitGrub** [ajayyy/SponsorBlock#162]
I've encountered a lot of false reports (especially on tech channels) and I'd much prefer the agency to start watching the sponsor and skip the ad if I choose to, rather than fast forward and then manually roll back to find out wether the user submitted report was malicious or not.

P.S. Malicious reports that end at the videos end are impossible to report (as far as I can see) because the report pop-up is bypassed entirely. Please correct me if I'm missing something.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/131

Which videos have these false reports? If you are referring to the ones on LTT that are merch spots, then those are intentional and some people want them. Hopefully when categories are introduced, this issue will be resolved.

About voting, it is also possible to vote in the popup.

![image](https://user-images.githubusercontent.com/12688112/67824811-cb5a1a00-fa9d-11e9-8c5e-ec3504fa13b3.png)

**Comment by BitGrub** [comment]
> 
> 
> #131
> 
> Which videos have these false reports? If you are referring to the ones on LTT that are merch spots, then those are intentional and some people want them. Hopefully when categories are introduced, this issue will be resolved.
> 
> About voting, it is also possible to vote in the popup.
> 
> ![image](https://user-images.githubusercontent.com/12688112/67824811-cb5a1a00-fa9d-11e9-8c5e-ec3504fa13b3.png)

It's funny you mentioned LTT because in his Galaxy Fold review, someone blocked the portion where they were showing of the screen and/or the middle crease because (I'm assuming) THEIR OWN Merch was on the phone's screen while they were showing it.

I would still very much prefer a "skip" button, rather than an "unkip"

**Comment by ajayyy** [comment]
What are the other instances this has happened?

**Comment by mirror176** [comment]
In non product placement form, smartereveryday video of lasers in water would be an example of fun to watch video still taking place during an ad so it'd be a reverse of video vs audio value...at least that's what I think I remember when submitting it a while ago.

**Comment by Ryonez** [comment]
Making this the default with #167 could work quite well I think.

**Comment by Ryonez** [comment]
Oh, he means a skip with the pop-up. That'd be pretty cool.

**Comment by ajayyy** [comment]
Yea, like the skip ad button on youtube, but with no timer.

**Comment by ajayyy** [comment]
Done :)
