### ISSUE TITLE
[Feature] Display which videos have already been 'sponsor-blocked'

### ISSUE THREAD

**Issue by Owehttamy** [ajayyy/SponsorBlock#1620]
I feel like it would be a great feature to display the SponsorBlock icon or something similar alongside recommended videos that already have segments flagged. This could help users who prefer a better viewing experience decide on their next watch, and would point out videos that may still need someone to flag them in the future.
It wouldn't be as necessary, but giving users the ability to mark a video as "sponsor-free" to verify that it doesn't have any segments to flag would be nice too. This way, certain creators without filler, sponsors, etc., don't potentially get punished by this change.

**Comment by ajayyy** [comment]
duplicate
