### ISSUE TITLE
5.1.11 broken in Safari

### ISSUE THREAD

**Issue by seaside98** [ajayyy/SponsorBlock#1626]
Commit https://github.com/ajayyy/SponsorBlock/commit/35b8a341629b46965c8019b4a9b375d8ecdd8055 added a regex lookbehind `(?<=^\s*\(.+)` which isn't supported in Safari. The extension crashes with `Invalid regular expression: invalid group specifier name`.

Safari Version 16.2 (18614.3.7.1.5)
SponsorBlock version 5.1.11

**Comment by ajayyy** [comment]
Good catch, I hate that invalid regex breaks the entire JS file (all browsers do this)
