### ISSUE TITLE
"Downvote and copy" modifies your unsubmitted segments

### ISSUE THREAD

**Issue by melissis** [ajayyy/SponsorBlock#1635]
EDIT: No, wait... it's mostly back to normal. I'm confused. Not sure what happened.

Here's what I did:
- Add a couple of "Chapter" segments and name them.
- Use the "Downvote and copy" feature on a Sponsor segment.

All my yet unsubmitted segments were changed into "Sponsor" and the names weren't restored when I switched them back to "Chapter".

I didn't expect it to change anything that I had made, only add.

**Comment by ajayyy** [comment]
You may be hitting a storage limit. Try going to options -> backup/restore and see how many unsubmitted segments you have

**Comment by melissis** [comment]
> You may be hitting a storage limit. Try going to options -> backup/restore and see how many unsubmitted segments you have

I am hitting storage limit. Didn't realize it could be the issue. I'll think about that before submitting an issue next time.

I have lots of unsubmitted chapter segments that I don't want to continue working with right now, and therefore not submitting yet, and just dealing with it.
Is there any way to increase the limit, in the about:config or something?

**Comment by ajayyy** [comment]
Not that I know of
