### ISSUE TITLE
3rd-party YT sites not supported on Firefox for Android

### ISSUE THREAD

**Issue by cazwacki** [ajayyy/SponsorBlock#1643]
After installing the extension on an Android browser, the add-on cannot request additional permissions. Thus the 3rd-party Youtube-Sites option cannot be enabled.

**Comment by ajayyy** [comment]
Firefox for Android does not implement optional permissions

**Comment by cazwacki** [comment]
Can a custom version of SponsorBlock exist with host permissions for all sites?

**Comment by mchangrh** [comment]
duplicate of #1462 implemented in #1469
