### ISSUE TITLE
Auto detect sponsor blocks from chapter names

### ISSUE THREAD

**Issue by mrx23dot** [ajayyy/SponsorBlock#1644]
eg video https://www.youtube.com/watch?v=kg58tzJDtE0

has **"Altium Sponsor"** labeled chapter, this could be automatically detected and skipped.
Something that matches: *sponsor*

No need for human labeling.

**Comment by ajayyy** [comment]
No, it is not precise and usually misses segues

**Comment by mrx23dot** [comment]
What about a user defined list of Section names to simply skip ahead?
So it would be up to the user (and his language) to define what to skip.

e.g. see this video
https://www.youtube.com/watch?v=e0OYAANYKug
it's full of useful section names
