### ISSUE TITLE
Is it possible to skip the same length at the end of all videos under a certain channel?

### ISSUE THREAD

**Issue by git-anish** [ajayyy/SponsorBlock#1648]
Hi,

I'm wondering if its possible to instruct the extension to skip the last X seconds of all videos under a particular youtube channel?

The use case for this would be a channel that uses the same self promotion clip at the end of all of their videos. It's repetitive to report each video (especially for smaller channels), rather it could be an automated suggestion that skips the last X seconds when the extension encounters that channel.

Thanks

**Comment by ajayyy** [comment]
no
