### ISSUE TITLE
Manifest v3 preparations

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#165]
https://developer.chrome.com/extensions/migrating_to_manifest_v3

> Are you making CORS requests in content scripts?
> 
> Move these requests to the background service worker.

https://developer.chrome.com/extensions/migrating_to_service_workers (might already be done)

**Comment by ajayyy** [comment]
Fixed in 2.0

**Comment by ajayyy** [comment]
Looks to be more work, but we will have to wait until it's implemented in Firefox

**Comment by thipokKub** [comment]
Hello, chrome will deprecated Manifest v2 by January 2023 (and Firefox, sometime in 2023). So I am wondering is there any plan for the upcoming few months?

**Comment by ajayyy** [comment]
I'm not too worried as this year's April fool's joke fork of this extension had to be in manifest v3, and I was able to do that in an hour, but it did involve disabling some things not needed for the joke.

**Comment by trcrsired** [comment]
Will sponsorblock continue working in V3?
