### ISSUE TITLE
Memory leak on open Youtube shorts at browser start

### ISSUE THREAD

**Issue by mubat** [ajayyy/SponsorBlock#1655]
When I start a browser with open Youtube shorts tab I have an infinite loading of the video when this extenstion is enabled. And after 1-2 minute I see "page crashed" error message.

Browser Opera 94.0.4606.76 on Windows

**Comment by mchangrh** [comment]
can you send a link to the youtube shorts tab? I have a suspicion youtube changed their shorts navigation event again

**Comment by mubat** [comment]
https://www.youtube.com/shorts/guTaIW4fSZ0

I have next extensions: AdNauseam, Ghostery, Google Translate, Tampermonkey.
Tested by disabling each extension and reload browser. After disabling "SponsorBlock for YouTube" Youtube shorts works normally.

**Comment by derech1e** [comment]
Same issue for me on chrome

**Comment by adrianjw** [comment]
same issue for me in chrome as well

**Comment by SquirrelsMcGee** [comment]
similar issue on chrome - i get this for all videos after 10 seconds of playtime, related videos, comments & description don't load, chrome task manager says >100 for cpu usage

**Comment by ajayyy** [comment]
Closing for now as there have been a few fixes in this regard since the last comment
