### ISSUE TITLE
[BUG]: Invidious list is not updating

### ISSUE THREAD

**Issue by ccuser44** [ajayyy/SponsorBlock#1665]
My pull #1660 added invidious instances which sponsorblock did not track, but it was declined. It was declined because the list "is updated automatically", but thats not the case.

When I use Libredirect Sponsorblock only works with a very small subset of Invidious instances

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/blob/master/.github/workflows/updateInvidous.yml

It is once a month from the json file.
