### ISSUE TITLE
Disable cloudflare logging/telemetry option

### ISSUE THREAD

**Issue by mctvcse839** [ajayyy/SponsorBlock#1667]
Hello I have been using your service with freetube and I noticed you have an option that is enabled by default that is used by cloudflare to error log requests.
For reference: https://github.com/FreeTubeApp/FreeTube/issues/3151

The domain is a.nel.cloudflare.com : https://support.cloudflare.com/hc/en-us/articles/360050691831-Understanding-Network-Error-Logging

This option can be disabled in the CF panel : 
![image](https://user-images.githubusercontent.com/124193980/216833729-ce044e42-52df-4144-a7c3-546cf75936b1.png)

Here is an exemple of a request from your domain : 
![image](https://user-images.githubusercontent.com/124193980/216828614-56ed2ed4-dfee-470e-8d26-7872a93b0f14.png)

Would be appreciated for privacy

**Comment by ajayyy** [comment]
Disabled :)

Also, if you want to avoid cloudflare entirely, you can switch the API domain to `https://api.sponsor.ajay.app`.
