### ISSUE TITLE
No longer able to add own Invidious instances

### ISSUE THREAD

**Issue by nerdfacenyan2** [ajayyy/SponsorBlock#1668]
Unless I'm missing something, the only way to add my own invidious instance is to fork the project and add the instance to ci/invidiouslist.json, which is fine for MacOS but prevents me from using the paid iOS app.

**Comment by ajayyy** [comment]
Before it wasn't possible to use invidious instances at all. I decided to go with the fixed system as a stopgap

**Comment by nerdfacenyan2** [comment]
No worries. Is there anything I can do to fix this in the short term? Would submitting a PR with my (admittedly small) Invidious instance included be enough?

**Comment by ajayyy** [comment]
Maybe I can add a seperate JSON for safari only so that it doesn't mess with defaults

**Comment by ajayyy** [comment]
So I gave in and spent way to long with trial and error but I got dynamic invidious domains working
