### ISSUE TITLE
Feature Request: On/Off Switch

### ISSUE THREAD

**Issue by Ryonez** [ajayyy/SponsorBlock#167]
A button that allows you to easily switch the block funtions on and off, for those time you don't want the add-on to interfere for a bit.

An advanced version could even offer a "Temporally Disable" feature, that would disable the block function for a set amount of time.

**Comment by ajayyy** [comment]
I recommend disabling the extension in the extension manager panel for now.

**Comment by Ryonez** [comment]
I've been doing that in the meantime. 

While that does work for biw, it's rather inconvenient, hence the feature request.

**Comment by ajayyy** [comment]
Done!

**Comment by Ryonez** [comment]
Sweet, thank you very much!
