### ISSUE TITLE
Grammar error (Russian)

### ISSUE THREAD

**Issue by osminogig** [ajayyy/SponsorBlock#1675]
https://github.com/ajayyy/SponsorBlock/blob/f4d80d88438ff31bc067ff480fd94112d972718d/public/_locales/ru/messages.json#L1144

"message": "Скрыть опции, **не доступные** без дополнительной платы" - **wrong**

"message": "Скрыть опции, **недоступные** без дополнительной платы" - **Right**

**Comment by mchangrh** [comment]
Do you mind making these changes on the crowdin? https://crowdin.com/project/sponsorblock

manual edits tend to cause issues

**Comment by osminogig** [comment]
[I'm not an expert, I did everything I could !)](https://crowdin.com/translate/sponsorblock/38/en-ru#2490)
