### ISSUE TITLE
Broken in Tor Browser since 12.0.3

### ISSUE THREAD

**Issue by m3thm4th** [ajayyy/SponsorBlock#1680]
The latest Tor Browser update (12.0.3 based on Firefox 102.8.0esr) broke the extension, used to work fine until 12.0.2

**Comment by ajayyy** [comment]
Sounds like corrupt extension files, try uninstalling and reinstalling

**Comment by judemont** [comment]
He's right I tried and it actually doesn't work on tor browser.

**Comment by cuzimhappyy** [comment]
seems broken in mullvad browser as well (it's based on tor browser, but without the tor network). the popup menu is blank, I cant interact with the settings menu, and segment skipping doesn't work.

**Comment by ajayyy** [comment]
@cuzimhappyy 

Change the following in about config
> if " webextensions.storage.sync.enabled " is set to " true" 
>
> then all is well in the world

**Comment by mfawaz24** [comment]
> this is also true on Mullvad Browser (another fork of firefox). It has some commonalities with Tor Browser so the root of the issue is probably the same. I'd suggest looking into the about:config changes made by the respective forks

update: setting webextensions.storage.sync.enabled to "true" seems to fix the issue.

any ideas as to why?

**Comment by ajayyy** [comment]
@mfawaz24 it allows the extension to use the storage.sync API, which many extension use to store their data
