### ISSUE TITLE
Create a new Github repository solely for tracking video issues

### ISSUE THREAD

**Issue by ccuser44** [ajayyy/SponsorBlock#1681]
@ajayy you should create a new Github repository solely used for Githubs issue tracker so people can submit video issues.

Issues like:

- Bad segments #1477
- Segments could be better
- Troll segments
- Video is locked by an admin
- Repeated vandalism on video
- Downvote abuse

And usually downvoting bad segments wont itself get rid of them (at least sometimes won't, the fact that this is unclear makes it worse as you dont know the appropriate course of action one should take).

This would create an easy way to keep track of these issues.
Many projects already use issue only Github repos.

And you could have a bot that closes all pull request so they wont be accidentally made.
Oh and be sure to disable as many features of the repo as possible as you can with github because its an issue only repo.

**Comment by ajayyy** [comment]
We use discord for this

**Comment by ccuser44** [comment]
> We use discord for this

@ajayy You should make the Discord channel a [forum channel](https://support.discord.com/hc/en-us/articles/6208479917079-Forum-Channels-FAQ) so each ticket can be tracked instead of it being just a stream of messages
