### ISSUE TITLE
Sponsorblock skips all segments in the video after encountering one

### ISSUE THREAD

**Issue by jvanbruegge** [ajayyy/SponsorBlock#1682]
This just happened for the first time for me, but watching [this video](https://www.youtube.com/watch?v=q0E3DZQzkKE), once the video encounters the **first** non-music segment, sponsorblock skips to after the **last** non-music segment, skipping a bunch of content in the process as well.

**Comment by ajayyy** [comment]
cannot reproduce

**Comment by jvanbruegge** [comment]
I just tried it again, it is still happening. I was mistaken tough, it is not the first one, but the second one (I missed that there was a small one right at the beginning).
I am on Firefox 110.0 on Linux and v5.1.13 of Sponsorblock
