### ISSUE TITLE
Allow saving of unsubmitted segments on mobile

### ISSUE THREAD

**Issue by DShip91** [ajayyy/SponsorBlock#1684]
You know how on desktop, if you create a segment but don't submit it, it'll save that segment allowing you to create skips just for yourself without breaking any rules? It would be nice if this feature came to mobile apps (ReVanced on Android and uYou+ on iOS). Is there any way to make tis happen?

**Comment by ajayyy** [comment]
You can use the browser extension in Firefox for Android, make segments on desktop, and if you are logged into your Firefox account, it should sync extension data.
