### ISSUE TITLE
QOL Suggestion: Hide YouTube's Auto-Generated Chapters

### ISSUE THREAD

**Issue by PasttaTypo** [ajayyy/SponsorBlock#1685]
YouTube's Auto-Generated Chapters will obscure community-made chapters thru SponsorBlock in the playback bar, and while scrolling with the little red bar.
![image](https://user-images.githubusercontent.com/125756085/221481121-8aacf926-c1bb-40f2-8dbf-23031bef2e44.png)
Here's a video (by [GenoSamuel](https://www.youtube.com/@genosamuel2.1)) with both custom chapters and YouTube's "chapters": https://youtu.be/nx2CgXqdxMw?t=1140

My suggestion is that chapters are "layered" so as to give creator-made and then community member-made chapters priority over algorithmically-made ones in that order, respectively. 
Like an onion.

**Comment by PasttaTypo** [comment]
Another stealthy feature implementation from the the SponsorBlock crew 👍, marking as closed so you don't have to.

**Comment by ajayyy** [comment]
15976777ed95699df46251f792d19f07a32ecb30
