### ISSUE TITLE
Feature Request: add segment to multiple videos

### ISSUE THREAD

**Issue by inktrap** [ajayyy/SponsorBlock#1698]
Sometimes videos of e.g. a playlist or series share the same intro or outro animation.

Example: this playlist: https://www.youtube.com/watch?v=eYm0uh4VEds&list=PLHGZsq10nFV_T6oRU4eGgwfyRm9y8czTN&index=1

It is very tedious to enter these for each video and it would be lovely if that could be done by some kind of bulk operation.

Another thing related to that would be changeable segments. If I'll realize I submitted a wrong segment I can only downvote myself, but I can't change or unsubmit a submitted segment. For my own segments an undo operation would be cool.

**Comment by ajayyy** [comment]
rejected

**Comment by inktrap** [comment]
why?
