### ISSUE TITLE
[Suggestion] Minor highlights moments

### ISSUE THREAD

**Issue by andradadad** [ajayyy/SponsorBlock#1702]
Skip to highlight is a feature that only shows 1 moment, but specially with very long videos, 3 hours for example have many highlights because the comments indicate minutes for the best moments in some channels, therefore creating tons of highlights.
To have an option to manually click "next highlight", even if it's not that important as the major/majors one, would benefit a lot as the feature is already implemented. A huge improvement to this already working feature.

**Comment by ajayyy** [comment]
Try out chapters
