### ISSUE TITLE
Feature Request: Block embedded sponsor panes within a video

### ISSUE THREAD

**Issue by JustinJayL** [ajayyy/SponsorBlock#1703]
I think it could be a good idea to support blacking out sponsored panes inside of videos, such as uploads of twitch streams. I'm imagining that picking out the panes within videos should be pretty simple, actually blacking out the section could be complicated.

This could be useful for any portion of the screen that is used for sponsored content along side actual video content, where you can't skip through the section.

Here is an example where the sponsor pane is in the top right:

![Example](https://i.imgur.com/FFiD2aP.png "Example")

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/538
