### ISSUE TITLE
SB Sometimes doesn't skip sponsors

### ISSUE THREAD

**Issue by realSZ27** [ajayyy/SponsorBlock#1716]
Quite frequently SB doesn't skip sponsors. It will play the sponsor and I will have to refresh the segments. After one segment is skipped, it does not persist to others and you have to refresh the page to get it back to normal.

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/99378252/231891418-216d4477-21a2-46e7-8fb9-62532618c804.mp4

</details>

OS: Windows 11 22H2 (build 22621.1555)
Browser: Firefox 111.0.1
Sponsor Block: 5.3.1

**Comment by ajayyy** [comment]
Check force channel check

And list other installed extensions

**Comment by Defirence** [comment]
> Check force channel check
> 
> And list other installed extensions

I've got "Force Channel Check" enabled, running the following extensions:

**Comment by ajayyy** [comment]
Try disabling force channel check

**Comment by Hustle-Ling** [comment]
same issue. tried with 'Force Channel Check Before Skipping' on and off, doesn't matter. have to refresh page in order for the ad to be detected and skipped. seems to mainly happen on more recent videos

win10, firefox 112.0 with the following extensions:
noscript
ublock origin
https everywhere
return youtube dislike
auto tab discard
google translate
canvasBlocker
random user-agent

**Comment by ajayyy** [comment]
Oh, it's probably this (https://github.com/ajayyy/SponsorBlock/commit/1ef6c1977facd3085942ab941b545d807da3f4bd). Has to do with the hover previews. Haven't had to time to do a release but hopefully I can soon

**Comment by ajayyy** [comment]
Release published, now being reviewed by the respective stores

**Comment by Andrea22331** [comment]
Oi boa noite sou nova aqui e não entendo direito eu tenho uma micro empresa e não consigo bloquear o acesso a sites como [xvideos](https://xvideosamador.blog/) na minha empresa será que esse app funcionaria no meu caso pois meu funcionários sempre arruma um jeito de burlar e acessar esses conteúdos
