### ISSUE TITLE
Stats API returns status 500 response code for Top Users endpoint

### ISSUE THREAD

**Issue by Defirence** [ajayyy/SponsorBlock#1718]
Issue: The Stats page returns an error 500 when querying the API endpoint with GET:

`https://sponsor.ajay.app/api/getTopUsers?categoryStats=true&sortType=0&category=all`

This is over HTTPS to PATH: /api/getTopUsers?categoryStats=true&sortType=0&category=all

It might be possible this catch-all error is due to the database overloading the CloudFlare cache, or possibly temporary rate limiting (?)

This results in an 'infinite loading' loop, the page is expected to show users, rank etc but it'll get stuck even with a hard/soft refresh.

**Comment by Defirence** [comment]
Either don't have permissions or forgot to add labels for this one:

`bug`
`Server`

**Comment by ajayyy** [comment]
It disables itsekf depending on server load
