### ISSUE TITLE
Add YouTube Kids support

### ISSUE THREAD

**Issue by Myzel394** [ajayyy/SponsorBlock#1720]
I just realized that Sponsorblock does not work on youtubekids.com - it would be cool if Sponsorblock was also available for YouTube Kids :D

**Comment by mchangrh** [comment]
oh I didn't realize youtubekids was a seperate domain

**Comment by mchangrh** [comment]
.take

**Comment by ajayyy** [comment]
Adding another domain without optional permissions is probably a no-go for this

**Comment by mchangrh** [comment]
will probably bundle it into invidious list, I'm more curious as to if polymer is reused and we can port it over, or if it's a completely different runner

**Comment by Myzel394** [comment]
@mchangrh Is polymer the YouTube player? If yes, do you use your own parser or do you use a library for that?
