### ISSUE TITLE
[Feature] Suggestions for new segment types

### ISSUE THREAD

**Issue by KiOrlando** [ajayyy/SponsorBlock#1725]
The following are my suggestions for types of segments that could be added:

1. Spoilers - Segments that contain potentially unwanted spoilers to movies, games, tv, etc.
2. Jumpscares - Segments that contain jumpscares or sudden loud noises that may cause problems for people with audio sensory issues.
3. Flashing Lights - Segments that contain flashing lights, would serve as a warning for people with photosensitive epilepsy.

Thank you for reading,

**Comment by ajayyy** [comment]
duplicate
