### ISSUE TITLE
Not visible segments in the timeline

### ISSUE THREAD

**Issue by szojusz** [ajayyy/SponsorBlock#1731]
I noticed today that I don't see segments on the timeline, and when creating a new one, I can't open the segment type selection menu.

In the pictures I present the same video on the first in the Chrome browser (without browser extensions) and the second in Brave (based on the chromium engine, for everyday use with a lot of browser extensions) and only in Brave you can see the segment of which I am the author. I created a segment in the material from a week ago and other users can also see it.

There is a point where the video loads, you can see segments on the timeline but they disappear as the image loads.
![image](https://user-images.githubusercontent.com/60299154/235243712-9a29bf16-bce5-455b-8e82-634929cb3a97.png)
![image](https://user-images.githubusercontent.com/60299154/235243750-2ab9d718-2191-4e81-93ff-01448e8a2889.png)

**Comment by RedAero** [comment]
It's theatre or cinema mode - disable it, refresh, and the segments stay, but if you switch cinema mode on they disappear.

**Comment by tadwohlrapp** [comment]
Yeah, same here. Seems like v5.4.2 breaks the extension. It still skips segments, but they're not shown in the timeline and the skip notice also doesn't show. Manually reverting back to 5.4.1 fixes it for now.

**Comment by ajayyy** [comment]
Yea I've pushed 5.4.3 to the chrome store which is just a rename of 5.4.1

**Comment by szojusz** [comment]
> It's theatre or cinema mode - disable it, refresh, and the segments stay, but if you switch cinema mode on they disappear.

It's true, only that I do not use a small player, because the interesting content (video) is small, and in cinema mode, however, it occupies a larger part.

Anyway, thank you for the information!

**Comment by dr2okevin** [comment]
I have a similar issue on Firefox ESR 102.9. No segments are visible in the timeline. No matter if cinema mode or not. They also don't get skipped. But I can see the list of segments on the info window, and I can skip to the end of a segment if I press the button there. I also get a tooltip info if I hover over a segment, but it isn't visible at any time.

**Comment by ajayyy** [comment]
Should be fixed in https://github.com/ajayyy/SponsorBlock/commit/45d45b006834fe3b774aa30f4d858c88399394c0
