### ISSUE TITLE
Latest version (5.4.2) causes video playing Tab to completely freeze (Chrome)

### ISSUE THREAD

**Issue by SquirrelsMcGee** [ajayyy/SponsorBlock#1732]
### Description
When using the latest version (5.4.2, installed using Chrome, any tab playing a video completely freezes after a few seconds 
Disabling SponsorBlock resolves this issue
Using an older manually installed version also resolves this issue (5.4.1, grabbed zip off released page and installed as unpacked)

### Hardware/Software Details
Ryzen 7 3700X
Nvidia RTX 2070
Windows 10
Chrome version 112.0.5615.138 (64 bit)

### Technical notes
Chrome Task Manager reports unusually high CPU usage
Screenshot below shows CPU for the playing tab stuck at 100, even though nothing is happening and the page is completely static/frozen at this point
![image](https://user-images.githubusercontent.com/8070535/235265439-b038dc59-267d-4e14-a0f1-8ecca8390aff.png)

Disabling SponsorBlock lets the video play, as well as lets the related videos and comments load
CPU Usage shown below (ranges between 9 and 30)
![image](https://user-images.githubusercontent.com/8070535/235265793-a6c5ddd6-64e0-4267-8bd5-f44136a30dc0.png)

**Comment by SquirrelsMcGee** [comment]
Tested disabling other extensions, only SponsorBlock had any effect on freezing
- uBlock Origin
- LocalCDN
- Clickbait Remover for Youtube

**Comment by mini-bomba** [comment]
Chrome extension was reverted to 5.4.1 (published as 5.4.3) - [Source message from discord](https://discord.com/channels/603643120093233162/680086149183963197/1101576953984716920)
