### ISSUE TITLE
PWA Requires Refresh To Make SponserBlock Work

### ISSUE THREAD

**Issue by Chromeyyy** [ajayyy/SponsorBlock#1734]
Hello. I use **Brave Browser** [Stable Version] and I installed YouTube as a **PWA** [Progressive Web App]. When I open the YouTube PWA and play any video, SponserBlock doesn't work straight away and always requires a **refresh**; sometimes the refresh doesn't even work. I also noticed that when using the default website from the browser itself and not the PWA, this issue seems to **not** occur. Hope this is fixed soon as I prefer using the PWA. **Thank you**

**Comment by ajayyy** [comment]
Version?

**Comment by Chromeyyy** [comment]
I just uninstalled and reinstalled the PWA, and now it seems to work fine. Wonder what was causing that issue though? Anyways, thanks and sorry to bother you.
