### ISSUE TITLE
Major loss of data in database

### ISSUE THREAD

**Issue by schmorp** [ajayyy/SponsorBlock#1736]
In the last few hours, practically all entries have been removed form the sponsorblock database. Here are the last four updates:

-rw-r--r--  2,301,904,344 2023/05/01 15:12:11 sponsorTimes_1682946600246.csv
-rw-r--r--  4,549,257,213 2023/05/01 16:12:53 sponsorTimes_1682950215199.csv
-rw-r--r--    235,532,804 2023/05/01 17:10:51 sponsorTimes_1682953816188.csv
-rw-r--r--        909,158 2023/05/01 18:10:32 sponsorTimes_1682957430207.csv

Something really bad seems to go on.

**Comment by ajayyy** [comment]
Files seem fine on the db-export machine. Seems like an issue when downloading

**Comment by ajayyy** [comment]
![image](https://user-images.githubusercontent.com/12688112/235486497-436426e1-b4b9-4303-805e-dbf5fe970905.png)

Actually I do see the 200 mb one, but it fixed itself in the next dump

**Comment by schmorp** [comment]
Just FYI: This was listed using rsync, so it is all server-side and not a local copy. And it seems to have "fixed itself" before, and then broke, suggesting whatever causes this is still intermittently there.

**Comment by schmorp** [comment]
Whatever it is, it keeps happening. For example, these are currently the last three updates on the server:

-rw-r--r--  5,269,738,719 2023/11/12 13:33:51 sponsorTimes_1699792321226.csv
-rw-r--r--  4,419,495,512 2023/11/12 14:34:12 sponsorTimes_1699795932398.csv
-rw-r--r--  5,270,031,100 2023/11/12 15:34:02 sponsorTimes_1699799532489.csv

The table size fluctuates wildly at times, and I don't think it should decrease by one GB and then icnrease again within two hours.
