### ISSUE TITLE
PWA Requires A Refresh To Make SponserBlock Work

### ISSUE THREAD

**Issue by Chromeyyy** [ajayyy/SponsorBlock#1737]
Hello. I use Brave Browser [Stable Version] and I installed YouTube as a PWA [Progressive Web App]. When I open the YouTube PWA and play any video, SponserBlock doesn't work straight away and always requires a refresh; sometimes the refresh doesn't even work. I also noticed that when using the default website from the browser itself and not the PWA, this issue seems to not occur. Hope this is fixed soon as I prefer using the PWA. Thank you.

I also want to note that if I have Brave open while using the PWA, this issue doesn't occur. I uninstalled the PWA and reinstalled and still the same issue. Only workaround is to refresh the page after playing any video or having Brave itself open alongside the PWA.

**Comment by ajayyy** [comment]
Stop spamming with issues
