### ISSUE TITLE
After installing SB youtube old layout is broken

### ISSUE THREAD

**Issue by WPFilmmaker** [ajayyy/SponsorBlock#174]
I don't know if it a coincidence, but after installing SB and removing it, youtube's layout is broken :(
I attach a screenshot in theater mode and normal mode. Both are broken:

https://imgur.com/UAnDJAE

https://imgur.com/A5q5Q0f

Am I the first to report this issue?Any idea on how to fix it?

Disabling adblock plus fixes the problem..so could it be that the two addons conflicted and now adblock plus screws up YT?

I don't think it is adblock plus fault per se as it was updated last  month ago (Oct 22, 2019) and I only began experiencing this issue only after removing SB...
(i know ublock origin is better but still...)

I am on Firefox 70.0.1 (64-bit) Linux.

**Comment by ajayyy** [comment]
I personally use the YouTube old layout and ublock origin and have no issues. Does this still happen after a refresh?

**Comment by WPFilmmaker** [comment]
Unfortunately it happens after refresh too yes:(
I will try ubo, although i was not interested in switching :)

**Comment by ajayyy** [comment]
SponsorBlock can't do anything if it is not installed, so it is probably just a broken update of Adblock Plus. Even though it isn't updated since October, the filter lists DO update.

**Comment by WPFilmmaker** [comment]
you are right, I will close this :)
