### ISSUE TITLE
Browser freeze/crash after skip

### ISSUE THREAD

**Issue by nategasm** [ajayyy/SponsorBlock#1740]
My browser appears to freeze/crash on this specific video.
https://www.youtube.com/watch?v=j6tbG6b6xRg

Tested on Firefox (5.4.1) and Edge (5.4.5), both resulted in same behaviour
Using the following settings:
Intro: Manual
Preview: Auto skip
Filler: Manual

Right after the intro plays and the preview is skipped the browser/UI freezes and eventually crashes
Video plays fine if I change Preview to anything other than auto skip. So it's probably due to the overlap of the segments

EDIT: Segments are now fixed, but they were previously like this
![image](https://user-images.githubusercontent.com/28376248/235906451-2f7f8c3d-7eb2-413d-a039-170e4af1db7c.png)

**Comment by krystofkrticka** [comment]
I also have this issue and, I was able to reproduce it on multiple videos. Everytime it skips the tab in which YouTube is open stops responding and after few seconds browser asks if I want to kill that tab because it froze.

**Comment by ajayyy** [comment]
Send video @krystofkrticka

**Comment by krystofkrticka** [comment]
@ajayyy I've had that issue with this video https://youtu.be/D24ueW8G0-w, but I might send much longer list of videos which did this. It's annoying especially in fullscreen.
