### ISSUE TITLE
Doesn't work on new layout (on Firefox at least).

### ISSUE THREAD

**Issue by C-Lunn** [ajayyy/SponsorBlock#1743]
Google has started rolling out an horrendous new layout. Unfortunately SB doesn't work with it. The browser popup recognises the segments but they don't get overlaid on the video element and don't get skipped.

![image](https://user-images.githubusercontent.com/54804081/236457245-07319674-e51e-4038-a583-322bcdd5dd73.png)

For now, refreshing the page is enough to restore the old layout for a while, but eventually the new one comes back.

v5.4.5 on FF 112.0.2 on W11.

Thanks.

**Comment by C-Lunn** [comment]
...and now it seems to work?!

**Comment by Synetech** [comment]
> Google has started rolling out an horrendous new layout.

You're preaching to the choir.

I'm sick and tired of YT constantly making unwanted changes that make the site worse and harder to use. They recently changed the subscriber-feed to only show six videos per row no matter how much space there is on the page, and then made it even worse and _completely unusable_ by removing the add-to-watch-later button and replacing it with the ability to hover the cursor over thumbnails for 5 seconds to initiate playing the video in the thumbnail (for some reason as if that's more useful than the previous preview function 🙄). Now, it takes TWICE as many clicks to add videos to the watch-later list, making it too much of a pain to bother watching YT anymore for power-users who watch over a hundred videos a day. 😒 Thanks for fighting my OCD and forcing me to have to quit, YT.

(Also, I've had enough over EVERY website copying YT's god-awful rounded-corners. 😠)
