### ISSUE TITLE
Thumbnails are hidden when SponsorBlock is enabled

### ISSUE THREAD

**Issue by unbeatable-101** [ajayyy/SponsorBlock#1744]
<img width="1154" alt="Screenshot 2023-05-05 at 08 37 30" src="https://user-images.githubusercontent.com/58151048/236459353-0b279c8c-aeac-4122-b64c-767a61ad3552.png">

This is with SponsorBlock 5.4.5, only happens when SponsorBlock is enabled, disabling fixes it upon reload.

**Comment by ajayyy** [comment]
Can you send the HTML by going to inspect element and copying the body tag.

**Comment by unbeatable-101** [comment]
It doesn't seem to be happening anymore, which is odd since I didn't change anything. I'll reopen and send the HTML if it happens ago
