### ISSUE TITLE
Website freezes

### ISSUE THREAD

**Issue by chocolateimage** [ajayyy/SponsorBlock#1747]
To reproduce:
* Open firefox
* Go to this video: https://www.youtube.com/watch?v=hbWy_BIp9aU
* Watch at 0:23

What happens:
The whole site freezes and firefox says that this extension is making it freeze, I click Stop and then I check the console.
244 of errors coming from "undefined" with the error: `Error: Attempt to postMessage on disconnected port`

**Comment by ajayyy** [comment]
Cannot reproduce

**Comment by chocolateimage** [comment]
> Cannot reproduce
i think to reproduce you need to set in the options everything to auto skip, i have it set to this:
![image](https://user-images.githubusercontent.com/45315451/236643093-b0b88844-cda2-4ce4-86cc-078bf6cf8ee2.png)

**Comment by ajayyy** [comment]
Can reproduce with Filler manual skip
