### ISSUE TITLE
Guidelines for using [Exclusive Access] or [Sponsored] "Full Video" tagging on a non-promotional video.

### ISSUE THREAD

**Issue by Overwatching** [ajayyy/SponsorBlock#1750]
As I understand it, the [Exclusive Access] or [Sponsored] tag on a video is to indicate that an entire video is 'promotional' content.
In other words, the video is an AD. It is marketing material.

There are many videos with these tags applied, that aren't promotional material, even if they might TECHNICALLY be a sponsored video, or get free access to a product.

These kind of videos are clearly not what this tag is intended for.

I'm going to use LinusTechTips videos here, because their channel has multiple examples of videos that are improperly tagged due to their "techy" nature lining up with the intended users of SponsorBlock, and them making a LOT of sponsored videos.

Example 1:
LTT has been doing videos talking about the ongoing discussion/debate/regulations/banning of "hacking" devices.
The point of these videos is the discussion of the capabilities of devices like these, and the controversy surrounding them.

First they did a video about the FlipperZero, which is not currently tagged as 'Exclusive Access'.
https://www.youtube.com/watch?v=nLIp4wd0oXs

Then they did a video about the O.MG Cable, which IS currently tagged.
https://www.youtube.com/watch?v=mPF9f-PLDPc

These videos are CLEARLY not about selling a product.
Anyone who might want to buy a device like this already knows about them (Or are a Nation State that makes their own anyway)
They are informing people that 'stuff' like this exists so we can talk about what they can actually do, and what is actually worth doing about them.
These videos are using a specific thing that someone HAPPENS to sell to inform a wide audience that "stuff" exists.

Also: The Flipper isn't flagged, even though it is the cheap device with actual 'fun' attached, that a viewer MIGHT be tempted to buy. While the O.MG cable IS flagged, even though it is a VERY low-volume device, with a HUGE price tag ($150 for a cable), with a very specific use-case that the average user will never EVER get to use. No one is going to buy an O.MG cable because of this video.

Example 2:

LTT made a video titled "You don’t need a new PC", which is co-sponsored by Acer and Intel.
https://www.youtube.com/watch?v=dc7CIkZcWYE

In this video, they buy a PC from 2017 (in 2023) that would presumably be considered 'junk' or 'e-waste', and show how it can still be used as a perfectly capable machine, even for light gaming, with a few cheap (NON-Acer or Intel) upgrades.
The machine they buy HAPPENS to be an old Acer model, and they joke about wanting to find one that lined up with their sponsor, but they specifically say this will work with anything old.
This video DOES have a pure AD inserted in the middle that is properly labeled. I'm not disputing that section.
But the 'Full Video' is not an AD.
It is, in fact, an anti-AD.
It is literally telling people that they don't need to go buy a new computer.

Example 3:
LTT did a video about building a desk to hide cables and wireless chargers in it.
https://www.youtube.com/watch?v=k_3NVXml470

The video is "sponsored" by LG. They were given a monitor to use by LG.
But most of the video is about them making the desk.
A desk that they are not selling.
A desk that doesn't even work very well.

----------

I love the idea of being able to flag an entire video to see that it is just an AD before I click on it.
But it is being used incorrectly on at least 1/3 of the videos I see it on.

I hope that giving users more guidance on what videos SHOULD be tagged with this will result in improvements and make the system more useful to us all.

I also understand that individual people's motivations will differ. There are things I have brought up in the past because we have had a differing opinnion about "why" something should be done.

We should clearly be establishing the "why" for our rules.
It is after all, "why" we use something. There is a purpose for the rules.

The Wiki currently says:
> When the creator showcases a product, service or location that they've received free or subsidised(sic) access to in the video that cannot be completely removed by cuts.
Which is a clear "what".
Some of the examples I used above DO qualify, if we are going to use the system without more information.
But (IMO) they are examples devoid of the "why" we are bothering to tag the video.

These videos are not ADs.
They are using a product to show something about an entire group of things.
Or, they are using sponsorship money to show something entirely different, that happens to have the product in there somewhere.

**Comment by ajayyy** [comment]
If they recieved the Flipper Zero for free it should be tagged

**Comment by Overwatching** [comment]
They did not receive the flipper or the O.MG for free. As far as I can tell.

**Comment by Overwatching** [comment]
That also doesn't address example 2 or 3.

**Comment by ajayyy** [comment]
For example 1, I suggest asking in the discord/matrix/https://chat.sponsor.ajay.app/ as the person that submitted it probably knows why it was labeled that way.

For example 2 and 3, I think you are misunderstanding the category. The category is about bias that can't be possible to remove. If there is a sponsor section we can remove, no label is needed. If there are mentions of the sponsor, or sponsor products in view, then you _need_ to know of the sponsor before watching, otherwise you won't know of the bias.

**Comment by ajayyy** [comment]
The label makes you aware that there is a sponsorship, so you should be careful about trusting opinions about related products in the video as they may be influenced.

**Comment by Overwatching** [comment]
Also, there is no way you actually read my entire post in the 90 seconds between me putting it up and you closing it.

You and I don't often see eye-to-eye, but this post is about having guidance that explains why something is being used.
It is not whether or not a specific video should be tagged.
It is about WHY a video get's tagged.

"Because it is sponsored" is not why.

"Because we want to inform people that an entire video is an AD before they view it" is a why.

**Comment by Overwatching** [comment]
> The category is about bias that can't be possible to remove via skips.

Okay. We agree.

How does receiving a monitor show bias about a table that they built and are not selling?

**Comment by ajayyy** [comment]
This issue list is for code issues, let's continue on discord, matrix or https://chat.sponsor.ajay.app/
