### ISSUE TITLE
Green segments shown incorrectly when uBlock Origin is enabled

### ISSUE THREAD

**Issue by madsbacha** [ajayyy/SponsorBlock#1757]
I'm experiencing an issue where the green segments are not calculated correctly (see images) when you also have the uBlock Origin extension enabled with default settings.

With uBlock disabled:
![image](https://github.com/ajayyy/SponsorBlock/assets/7096229/455a2f6f-8443-4b87-905d-8dba2deadb94)

With uBlock enabled:
![image](https://github.com/ajayyy/SponsorBlock/assets/7096229/8360d78b-9af1-4940-bc63-2a49fbfde786)

[Link to video from screenshot](https://youtu.be/GqPGXG5TlZw)

https://github.com/ajayyy/SponsorBlock/assets/7096229/6d1e209a-af31-4bcc-bcdb-a9de87fdffad

I have tracked down the code responsible for calculating the left and right css percentage values for the green segments and have confirmed that if i remove the following lines then the segments are shown correctly.

https://github.com/ajayyy/SponsorBlock/blob/20ab0768dff4f988ab697e09695630593968b1f7/src/js-components/previewBar.ts#L912-L940

From what i can see in the debugger it looks like an element in `existingChapters` have a `segment[1]` value that is way higher (nearly to the end of the video) than the subsequent "existingChapter" in the list, such that when it checks for
https://github.com/ajayyy/SponsorBlock/blob/20ab0768dff4f988ab697e09695630593968b1f7/src/js-components/previewBar.ts#L921
it evaluates to `false` and stops at that chapter even though it is not the correct chapter, as the next one in the list have a normal segment range and would have evaluated to `true`.

**Comment by ajayyy** [comment]
Try using ublock with default filters only

**Comment by ajayyy** [comment]
![image](https://github.com/ajayyy/SponsorBlock/assets/12688112/9fbf5d1c-bd42-4951-9797-f2a257462955)

I cannot reproduce on my end

**Comment by ajayyy** [comment]
Also try disabling all other addons/styles

**Comment by ajayyy** [comment]
Also can you send the html inside `ytd-engagement-panel-section-list-renderer`

**Comment by madsbacha** [comment]
> Try using ublock with default filters only

I only have the built-in `uBlock filters – Ads` filter enabled in ublock. When the `uBlock filters – Ads` filter is enabled it blocks the ad for the video. If the ad appears it works correctly but when the ad is blocked the green segments appear correct for the first few seconds but then changes to something incorrect after a few seconds (probably when the video sections/chapters have been loaded).

> Also try disabling all other addons/styles

It also happens in incognito with only ublock and sponsorblock enabled. 

> Also can you send the html inside `ytd-engagement-panel-section-list-renderer`

There are 5 different `ytd-engagement-panel-section-list-renderer`, so here's the parent element containing all 5:

https://gist.github.com/madsbacha/ded7cf7737f202269ce0bf2f4fa540a0

**Comment by ajayyy** [comment]
Looks like an issue with the chapters being formatted with `.` instead of `:`. My replace function only replaced the first one, not all of them.
