### ISSUE TITLE
No segments in the video timeline if video is open from Outlook (RSS Feed).

### ISSUE THREAD

**Issue by Sopor** [ajayyy/SponsorBlock#1761]
I have a couple of YouTube channel as RSS Feeds in Outlook and when i see new videos i press the `View article` and the video will open in my web browser.

The problem is that if i play the video SponsorBlock haven't loaded any segments when i look in the timeline, but if i play the video it will skip the segments as they were there.

To see the segments i have to reload the page.

This could be a slow server or something else, but i have noticed this behaviour for a long time now and i watch videos everyday and it happens way to often that after a refresh of the page i can see the segments in the timeline. If it was a slow server issue, it is strange that the skips work.

If i search on YouTube or Google and open a video, this behaviour is not there. It is only happening when i open links from Outlook.

I did found this issue #1738 and it could be related to it. I open several videos after each other and that will bring the videos to the background when i open the next video. I don't use autoplay.

Windows 10
Firefox 113.0.2
SponsorBlock 5.4.6

**Comment by ajayyy** [comment]
dulicate https://github.com/ajayyy/SponsorBlock/issues/1738
