### ISSUE TITLE
YouTube smart TV add-on Firefox bug

### ISSUE THREAD

**Issue by Nine3hundred** [ajayyy/SponsorBlock#1765]
When using this add-on 

https://addons.mozilla.org/en-GB/firefox/addon/youtube-for-tv/

Sponsorblock appears to remember progress from previous video and start next video at that point instead of the beginning.

**Comment by mchangrh** [comment]
> Sponsorblock appears to remember progress from previous video and start next video at that point instead of the beginning.

This is a feature of YouTube on TV, it just doesn't show the progress bar of your already watched videos
