### ISSUE TITLE
Feature-Request: settings option to set preferred resolution

### ISSUE THREAD

**Issue by readnotify** [ajayyy/SponsorBlock#1770]
My laptop picks 360 on *every* video, and it's driving me bananas changing it to 1080p every time.
Having this as an option in the chrome extension seems like a perfect match.  I already have a dozen other extensions - I would much prefer SponsorBlock added "preferred resolution" as a setting, rather than me installing yet-another 3rd party extension for just that one small thing.

**Comment by ajayyy** [comment]
Out of scope
