### ISSUE TITLE
updateInvidous.yml keeps failing.

### ISSUE THREAD

**Issue by vojkovic** [ajayyy/SponsorBlock#1771]
The workflow to update the invidious list keeps failing.

https://github.com/ajayyy/SponsorBlock/actions/workflows/updateInvidous.yml

**Comment by mchangrh** [comment]
.take

**Comment by mchangrh** [comment]
@ajayyy can you delete the `ci/update_invidious_list` branch, it seems to have borked on locales being submodules

**Comment by ajayyy** [comment]
done

**Comment by mchangrh** [comment]
that did the trick, the issue can be closed https://github.com/ajayyy/SponsorBlock/actions/runs/5275244013/jobs/9540507053

**Comment by vojkovic** [comment]
@mchangrh Not all instances are being found. For example, yt.oelrichsgarcia.de isn't being found, and instead got removed from the list.

**Comment by mchangrh** [comment]
that's because at the time of writing this, it's only been up for 2 days. The CI is intentionally picky about which instances to add

https://github.com/ajayyy/SponsorBlock/blob/f5706d9fe3ef2923b6011321fd308f1d9d9d009f/ci/invidiousCI.ts#L39-L49
