### ISSUE TITLE
Ignore short segments

### ISSUE THREAD

**Issue by Askejm** [ajayyy/SponsorBlock#1773]
Is it possible to ignore small segments? Sometimes segments will be like a few seconds. I used to have sponsor auto skip enabled but I disabled it when segments where something like the sponsors name was mentioned would be marked as a sponsorship segment. Even with it as a pop up its annoying as it will on some aggressively marked videos pop up all the time.

So, is it possible to ignore short segments? Is there a setting where I could stop (for example) <10 second segments from appearing?

**Comment by ajayyy** [comment]
There is an option already

**Comment by Askejm** [comment]
Where? I tried looking but couldnt find it

**Comment by ajayyy** [comment]
It's called minimum duration

**Comment by Askejm** [comment]
Oh found it! Sorry
