### ISSUE TITLE
Middle dot in comment replies gets messed up

### ISSUE THREAD

**Issue by mybearworld** [ajayyy/SponsorBlock#1774]
Consistently, when having this extension enabled, this happens.

![The middle dot being too low.](https://github.com/ajayyy/SponsorBlock/assets/130385691/ef12bc16-9641-45d5-9416-8b017c0314e7)

**Comment by ArthikVishwakarma** [comment]
I don't see anything here, can you elaborate a little

**Comment by mybearworld** [comment]
The dot between the profile picture and the text is too far below.
