### ISSUE TITLE
Add a skip option for movies/series spoilers

### ISSUE THREAD

**Issue by Ahmed-Lotfii** [ajayyy/SponsorBlock#1779]
Recently, I happened upon a video that spoiled a movie for me. Hoping to submit this segment and prevent others from the same thing, I searched for a spoiler feature in the "Options" but came up empty-handed. I reckon it'd be pretty helpful if there was a submission when a spoiler for a movie or series is coming up.

**Comment by erkinalp** [comment]
duplicate of #1336
