### ISSUE TITLE
New 3rd party apps and update info

### ISSUE THREAD

**Issue by maboroshin** [ajayyy/SponsorBlock#1780]
For https://github.com/ajayyy/SponsorBlock/wiki/iOS and 3rd Party Ports

You can add yattee as a SponsorBlock for iOS.

* https://apps.apple.com/app/yattee/id1595136629 For iPhone/iPad/Apple TV (iOS/tvOS), it is available from the App Store.
* For MacOS, it's from GitHub. https://github.com/yattee/yattee/releases

Details here : [Installation Instructions for yattee](https://github.com/yattee/yattee/wiki/Installation-Instructions)

----
For https://github.com/ajayyy/SponsorBlock/wiki/Android and 3rd Party Ports

Please add [clipious](https://github.com/lamarios/clipious).

----
For https://github.com/ajayyy/SponsorBlock/wiki/3rd-Party-Ports

[LibreTube](https://github.com/libre-tube/LibreTube) is missing.

----
For https://github.com/ajayyy/SponsorBlock/wiki/Opera

Currently Opera can natively use Chrome extensions : [[Solved]Install Chrome Extensions Is Missing](https://forums.opera.com/topic/58248/solved-install-chrome-extensions-is-missing/7)(Opera forums)

Sorry I see about https://github.com/ajayyy/SponsorBlockSite/issues/59.

**Comment by maboroshin** [comment]
For https://github.com/ajayyy/SponsorBlock/wiki/3rd-Party-Ports

Music streaming players for desktop (Win/Mac/Linux)

* https://github.com/nukeop/nuclear/
* https://github.com/Moosync/Moosync

**Comment by maboroshin** [comment]
@ajayyy Currently Opera only installs the SponsorBlock extension. "Install Chrome Extensions" has been built-in since Opera version 55 in August 2018.

For https://github.com/ajayyy/SponsorBlock/wiki/Opera

**Comment by ajayyy** [comment]
I'll just delete the page, it's not linked from anywhere
