### ISSUE TITLE
Crashes YouTube when opening any overlays

### ISSUE THREAD

**Issue by bgiesing** [ajayyy/SponsorBlock#1783]
With SponsorBlock enabled, any overlay popup (Save, Share, the link after you make a clip), completely crashes the YouTube website on Edge. Tested on Firefox, doesn't happen there, not sure about other Chromium based browsers.

Browser: Edge Dev 116.0.1923.0
Extension: 5.4.10
OS: Windows 11 23H2 25393.1

**Comment by ajayyy** [comment]
What do you mean by crash

**Comment by bgiesing** [comment]
The entire page locks up (can't click anything, can't scroll, etc.) and after a few seconds the browser pops up the "page is not responding, force quit?" dialog box.

**Comment by ajayyy** [comment]
Do you have the "Zoom to fill" extension?

**Comment by bgiesing** [comment]
Yes

**Comment by ajayyy** [comment]
That extension is causing the issue. Switch to an alternative and it should be fine
