### ISSUE TITLE
Server said this request was invalid Error Code: 400 Bad Request Problem

### ISSUE THREAD

**Issue by Loading617** [ajayyy/SponsorBlock#1789]
![Screenshot 2023-02-13 8 15 55 PM](https://github.com/ajayyy/SponsorBlock/assets/89672772/dc6fe056-2f3c-43a0-875a-9c315b4e158d)

**Comment by ajayyy** [comment]
Check if your userID is blank in options -> import/export -> import/export userID.

If it is, you can generate a new one from https://mchangrh.github.io/sb-idgen/ and set it there.

**Comment by mchangrh** [comment]
This also happens if you set your privateID instead of your username

**Comment by ajayyy** [comment]
Is your userid too short? Less than 30 chars
