### ISSUE TITLE
Error Code 400: POI cannot be that early

### ISSUE THREAD

**Issue by DarkblooM-SR** [ajayyy/SponsorBlock#1791]
![screenshot](https://i.imgur.com/Rkcisnw.png)

Hello,

Almost every time I try to submit a segment, it gives me this error, and I'm not exactly sure what it means.

Enlightenment would be appreciated.

Thanks.

**Comment by ajayyy** [comment]
This means that your highlight submission is starting too early

**Comment by DarkblooM-SR** [comment]
Why is it a thing?
