### ISSUE TITLE
Video Restarts instead of going to next video in playlist after skipping near end of video

### ISSUE THREAD

**Issue by OmegaRejectz** [ajayyy/SponsorBlock#1804]
Not sure which setting(s) are contributing to this. But sometimes when it skips near the end of the video instead of going to the next video it restarts the video from 0:00.
Via Watch Later Playlist. But I've also had this issue in custom playlists.

**Comment by ajayyy** [comment]
Instead of going to the next video?

**Comment by OmegaRejectz** [comment]
> Instead of going to the next video?

correct

**Comment by HumbleDeer** [comment]
I can't reproduce this as of now. 

Can you share more about what browser you're using, any other extensions you're using, and the likes?

**Comment by OmegaRejectz** [comment]
Fortunately it doesn't occur 100% of the time.

Firefox (115.0.2 (64-bit))
uBlock Origin
Bitwarden
Return YouTube Dislike
(SponsorBlock)
Stylus
BetterTTV

I haver Manual Skip enabled for everything except Sponsors, which I have
Auto Skip enabled for.

**Comment by ajayyy** [comment]
![image](https://github.com/ajayyy/SponsorBlock/assets/12688112/7515b826-e218-4d61-8888-bc53ddb1020a)

Maybe we need to apply the Safari fix to all browsers (skip to just before the end of the video)?

I worry this will introduce frame flashes though.

**Comment by ajayyy** [comment]
Decided to to a compromise and use this workaround when a playlist is open only

**Comment by OmegaRejectz** [comment]
> Decided to do a compromise and use this workaround when a playlist is open only

😊

**Comment by OmegaRejectz** [comment]
> Decided to do a compromise and use this workaround when a playlist is open only

Hey! Back again. I'm having another issue (related to it restarting the video).

Video length: 32 minutews
Sponsor placement(s) 0:00 & 17:00.
After it skipped the 17:00 ad it restarted the video from 0:00 (and then skipped the 10 second sponsor) instead of going to 20:00. Let me know what other info I can give to further clarify the issue if needed.

**Comment by ajayyy** [comment]
Can you make a new issue?

**Comment by OmegaRejectz** [comment]
> Can you make a new issue?

I can.
