### ISSUE TITLE
Swear word in italian translation

### ISSUE THREAD

**Issue by arrotinoD** [ajayyy/SponsorBlock#1806]
In the settings of the extension, the DeArrow promotion uses a swear along the lines of "F*ck clickbait" in the Italian translation, with a very wonky grammar too. I don't know if this is the case in english too but it sounds very bad and also kind of jarring to see when everything else is written so formal.

**Comment by ajayyy** [comment]
Thanks for letting me know! I can't figure out which one it is using google translate. Is it one of these?

> Sfancula il clickbait sostituendo titoli e anteprime per renderli più accurati

> Stanco del clickbait? Scopri la mia nuova estensione per migliorare i titoli e le anteprime

**Comment by arrotinoD** [comment]
Hi, _“Sfancula il clickbait sostituendo titoli e anteprime per renderli più accurati”_ is the one with the swear word and wonky grammar, _”Stanco del clickbait? Scopri la mia nuova estensione per migliorare i titoli e le anteprime”_ is the correct one

**Comment by ajayyy** [comment]
thanks!
