### ISSUE TITLE
The whole page hangs upon reaching a segment

### ISSUE THREAD

**Issue by p-himik** [ajayyy/SponsorBlock#1811]
On [this video](https://www.youtube.com/watch?v=L5w3wRE6pUw) there are two segments that start at the same time and the third that starts almost at the same time.
If segment autoskipping it enabled, the page will hang upon reaching that time. I suspect the extension keeps toggling between the two segments that start at the same time resulting in an infinite loop.

The segments, just in case they get changed:
```
Intermission          0:00.000 to 0:02.000
Endcards/Credits      1:48.700 to 2:13.141
Sponsor               1:48.700 to 2:13.141
Unpaid/Self Promotion 1:48.864 to 2:13.161
```

**Comment by ajayyy** [comment]
I can not reproduce this. What is your exact skip setting?

**Comment by p-himik** [comment]
![image](https://github.com/ajayyy/SponsorBlock/assets/4410314/694c1fe7-aba3-4b64-9fc9-62a3a3ac6ed0)
![image](https://github.com/ajayyy/SponsorBlock/assets/4410314/a9a0c918-79f2-47a5-92b4-218f4451d0f1)
Not sure how helpful it is, but when the YT page is hanging, pausing the scripts on the background page of the extension always lands on this line:
![image](https://github.com/ajayyy/SponsorBlock/assets/4410314/7c3686b7-814d-4350-8586-d4997110da25)
