### ISSUE TITLE
Report entire video as a sponsor

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#182]
Then show a warning before playing the video.

If the user tries to report over x% of it, they should get the option to report the whole video.

**Comment by Amunak** [comment]
At the same time if you want to implement this I'd just add a custom "sponsored content warning" *to the video preview* to places where it's displayed and then perhaps on the video page (next to title or something), but I would not pause or skip the video automatically - that could be extremely annoying. At least the full auto-skip / pause should be an option.

**Comment by ajayyy** [comment]
I really see no point to a full skip or auto pause.

**Comment by elypter** [comment]
you could improve accuracy if you measure the percentage after substracting intro/outro/community segments

**Comment by SameenAhnaf** [comment]
Shouldn't #42 be closed in favor of this? "Reporting over x%" notice is already suggested here.

**Comment by ajayyy** [comment]
@SameenAhnaf that issue is for normal segments too, not just #AD

**Comment by mchangrh** [comment]
implemented in #1122
