### ISSUE TITLE
Addon re-installs by self every time I launch Brave browser

### ISSUE THREAD

**Issue by jakche** [ajayyy/SponsorBlock#1825]
Hi,

Every time I close and then re open brave this addon reinstalls it self? This happens to 2 PCs so far.

Right now I am on v. 5.4.14 but this has been happening for quite some time.

**Comment by ajayyy** [comment]
What did you mean by this

**Comment by jakche** [comment]
Imagine this scenario: I watch a few YouTube videos, then I close my browser and shut down my PC. After a while, I return to my computer and open Brave browser. However, every time I do this, the SponsorBlock default settings page (which automatically opens when you install the plugin) appears again. Additionally, all the settings I previously customized are reset to their default values.

For example, I had some personal settings saved, such as auto-skipping joke content. Unfortunately, these settings get reset, and I'm forced to readjust everything once more.

**Comment by ajayyy** [comment]
This is probably a setting in your browser

**Comment by jakche** [comment]
> This is probably a setting in your browser

Strange behavior, since it's happening to 2 different PCs.

**Comment by ajayyy** [comment]
SponsorBlock uses the sync storage system, so it is probably related to that.

#180
