### ISSUE TITLE
SponsorBlock is broken on Invidious

### ISSUE THREAD

**Issue by SkMyPP** [ajayyy/SponsorBlock#1826]
Segments are shown on the seek bar but none are skipped. Using latest Firefox (116.0.2) and SponsorBlock (5.4.14)

Have tried on multiple instances, disabling/re-enabling the extension, disabling/re-enabling "Support 3rd party YouTube sites" option, resetting instances list and nothing works.

**Comment by ajayyy** [comment]
Should be fixed
