### ISSUE TITLE
Sponsor block does not work

### ISSUE THREAD

**Issue by Git-Forked** [ajayyy/SponsorBlock#1827]
Installed the Firefox addon, and it does absolutely nothing.  No sponsor segments are skipped.  The Settings page doesn't even work.

**Comment by ajayyy** [comment]
Sounds like a problem with your browser. Either https://github.com/ajayyy/SponsorBlock/issues/1680 or another issue

**Comment by Git-Forked** [comment]
It was actually a problem with your code, that you have since fixed.
