### ISSUE TITLE
Sometimes does not skip until segments are manually refreshed

### ISSUE THREAD

**Issue by ScrubN** [ajayyy/SponsorBlock#1830]
About a quarter of every video I watch that contains skippable segments do not automatically skip or even prompt me to skip.

When this occurs, the segments are still visually represented within the seekbar, but when opening the control panel it reports that the video is invalid until the refresh button is manually pressed. From there, the segments are reported correctly and rewinding the video to before the segment allows it to be properly skipped.

I have been occasionally having this problem for the last 1-2 months and I have been using the extension for much longer than that. There were no changes in any of my browser extensions when the problem began to occur.
I have been able to reliably reproduce it by middle clicking a video to open it in a background tab, waiting several seconds, then navigating to the tab so the video starts to play.

Browser: `Brave 1.56.20 Chromium: 115.0.5790.171 (Official Build) (64-bit)`
OS: `Windows 10 Version 22H2 (Build 19045.3324)`
Extension Version: `v. 5.4.15`

I do have a custom css style for youtube applied via Stylus, but I believe that it is unlikely to be related to the cause.

![image](https://github.com/ajayyy/SponsorBlock/assets/72096833/fbfd9a01-93ea-4ecd-9732-61dd6a9203b7)
![image](https://github.com/ajayyy/SponsorBlock/assets/72096833/86c50394-0ef8-445d-b839-f953549e6af5)
*Same video, with the refresh button manually pressed between screenshots*

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/1820
