### ISSUE TITLE
Feature request: New segment types:  Chat break, technical difficulties, AFK/dead-air time

### ISSUE THREAD

**Issue by cheintz** [ajayyy/SponsorBlock#1834]
Some users find these segments to be disruptive, and some creators are very prone to them. 

It should be clear that chat break segments should only be submitted if the primary purpose of the video is not a live Q&A.

**Comment by mchangrh** [comment]
already covered under [Intro](https://wiki.sponsor.ajay.app/w/Intermission/Intro_Animation)
>Livestream pauses with no content:
Looping animations
Chat window
Long break with no talking or nothing seemingly happening
