### ISSUE TITLE
New Feature Request

### ISSUE THREAD

**Issue by jakche** [ajayyy/SponsorBlock#1835]
![image](https://github.com/ajayyy/SponsorBlock/assets/70672583/583caf1e-b8f0-48f3-ba59-0cb90996f772)
When we submit new segments we have **End** **button** (underlined with blue). Can we also get **Beggining of video button** (underlined with yellow) so we do not have to manually put 0:00 as starting point of a segment, this would help a lot with intro segments.

**Comment by ajayyy** [comment]
dup #880
