### ISSUE TITLE
Skipping isn't working even though it's enabled

### ISSUE THREAD

**Issue by Karthikvenugopal** [ajayyy/SponsorBlock#1837]
I opened a youtube video in a new tab. The sponser part isn't being skipped.
The Youtube video isn't being detected by the extension unless I refresh in the extension. 
The sponser part is highlighted in the video but it doesn't skip
![image](https://github.com/ajayyy/SponsorBlock/assets/53857484/7226e0be-f84f-40a9-b9b8-12b1d583efe7)

**Comment by PrincipleOfLeastAction** [comment]
Possibly related issue? https://github.com/ajayyy/SponsorBlock/issues/1820 

I'm having this issue too on firefox. It may be related to 2x speed or opening it in new tab?

**Comment by Karthikvenugopal** [comment]
I was on Google Chrome btw

**Comment by GeekyGami** [comment]
It's also happening to me.
Seems to be an issue with being unable to skip if it hasn't buffered far enough.

**Comment by ajayyy** [comment]
Should be fixed in 5.4.17
