### ISSUE TITLE
Chapter voting buttons off-screen when chapter name is long

### ISSUE THREAD

**Issue by Apep-the-snek** [ajayyy/SponsorBlock#1839]
like/dislike icons get hidden by hovering the cursor over the chapter or like/dislike icons when the "Skip the Highlight" button animates into view, pushing the entire chapter text with the like/dislike buttons along with it, which subsequently get hidden by the "Start Segment Now" button. Essentially the same thing happens when you hover over any of the buttons on the right of the video frame with your cursor when the "Open SponsorBlock Addon" icon animates into view and hides the like/dislike icons as before. This makes it impossible by normal means to press the dislike button, except if i go into full screen.
https://www.youtube.com/watch?v=0cTpTMl8kFY - video tested on, go to the spot that is shown in this screenshot:
![image](https://github.com/ajayyy/SponsorBlock/assets/33030702/07fbc235-c62d-425e-9b0d-c3893e55edc9) just try timestamp: 17:00 if the image doesn't load.

**Comment by ajayyy** [comment]
I kind of prefer this behavior to cutting off the chapter name
