### ISSUE TITLE
Youtube chapter name stuck when using SponsorBlock

### ISSUE THREAD

**Issue by SharpThunder** [ajayyy/SponsorBlock#1848]
Hi people, thanks for the extension.

I have a problem, when using SponsorBlock, Youtube chapter names does not change and stuck with the first one like below.

![image](https://github.com/ajayyy/SponsorBlock/assets/8118323/cee808f2-4bda-4831-9f7d-2d015f4d4479)

I could not find an issue about this one so i opened new one if there is one please let me know.

**Comment by ajayyy** [comment]
Closing as stale
