### ISSUE TITLE
[Mobile] Only properly detects sponsor after reloading the page

### ISSUE THREAD

**Issue by Dwyriel** [ajayyy/SponsorBlock#1849]
When going into a video from the youtube home page or history page, Sponsorblock seems to load but doesn't apply the skip at the right time (showing a small green segment at the very beginning of the video, but skipping nothing at all), requiring a reload of the page for it to work correctly. 
It also works without problems when loading a video directly, rather than going through other youtube pages like home and history (first loading a youtube page already pointed to a video), or when going from one video to another (clicking on one of the recommended videos youtube shows below the video you're currently watching).

Here are two screenshots, one when first clicking the video from the home/history page and the other after a reload/direct load:
[before](https://github.com/ajayyy/SponsorBlock/assets/61030926/52d7eeb2-da79-4d1d-83c8-c0794bd176ed)
[after](https://github.com/ajayyy/SponsorBlock/assets/61030926/7e3d57c5-b947-4c21-9e6f-8ee604684c51)
[the video I used to test](https://www.youtube.com/watch?v=elf1yP_bMOE) (but it happens on other videos as well)

I've tested multiple times and it's consistent. I've also tested while only using sponsorblock (disabling every other extension), and with other extensions active (AdBlock and Violentmonkey), and the same behavior was present in both cases. I've completely closed and reopened the browser between tests to make sure no leftover code was being run.

I think this has been an issue since a few months ago (around june or so), I've been experiencing this since then, but at the time I just thought the videos didn't have an entry yet, and I've only stopped to test it properly now (since I tried to watch the same video on my desktop and on my phone). Around the same time ReturnYoutubeDislike stopped working on mobile, I think youtube changed the mobile page in ways that broke most extensions.

Pre-post edit: while writing this I also tested on my PC by changing my user agent to an android one and following the same steps I mentioned, and it also consistently happened. Only thing in common between the two devices is the chromium engine.

**Comment by yeapjf** [comment]
Can confirm this also happens on Android Firefox (Nightly v119). For me, disabling and re-enabling the add-on (via Add-on Manager) fixes it, but refreshing the page doesn't work.

Started happening around 2 weeks ago after an update.
