### ISSUE TITLE
[Suggestion] Rename "Preview/Recap" to "Content Preview/Recap"

### ISSUE THREAD

**Issue by levyd75** [ajayyy/SponsorBlock#1852]
`Preview/Recap` is an extremely useful category, but I keep seeing it misapplied to meaningful content not appearing elsewhere in the video or series of videos.

The confusion seems to stem from the word "recap" – which some users are interpreting in a broader sense than intended.

An example is [this video](https://www.youtube.com/watch?v=Lk4N2epJzgg), for which 0:00.000 to 11:21.000 has been tagged _Preview/Recap._ That portion of the video provides background information essential to understanding the subject – but it could be described as a "recap" of past events.

In other instances, a YouTuber will say something along the lines of "Before we cover the latest development, I think it's important to recap the controversies leading up to it."  In this context, "recap" refers to a topical summary, not the repetition of <s>footage</s> video content.  Nonetheless, well-intentioned users sometimes hear "recap" and tag the section `Preview/Recap.`

<s>I believe that the issue could be mitigated by replacing "Recap" with the less-ambiguous "Replay" in the category's name.</s>

<s>Updated to [mchangrh](https://github.com/mchangrh)'s excellent suggestion: `Series Preview/Recap`</s>

Per discussion, updated suggestion to `Content Preview/Recap`.

**Comment by mchangrh** [comment]
> In other instances, a YouTuber will say something along the lines of "Before we cover the latest development, I think it's important to recap the controversies leading up to it." In this context, "recap" refers to a topical summary, not the repetition of footage. Nonetheless, well-intentioned users sometimes hear "recap" and tag the section Preview/Recap.

IIRC the rules were slightly changed to allow for broader recaps rather than strict clip-for-clip replays: see the [wiki page](https://wiki.sponsor.ajay.app/w/Preview/Recap)

**Comment by levyd75** [comment]
> > In other instances, a YouTuber will say something along the lines of "Before we cover the latest development, I think it's important to recap the controversies leading up to it." In this context, "recap" refers to a topical summary, not the repetition of footage. Nonetheless, well-intentioned users sometimes hear "recap" and tag the section Preview/Recap.
> 
> IIRC the rules were slightly changed to allow for broader recaps rather than strict clip-for-clip replays: see the [wiki page](https://wiki.sponsor.ajay.app/w/Preview/Recap)

The wiki's description is as follows:

> For segments that show what happened in this or past videos of the same series, but do not provide additional information. If it includes clips that only appear here, this is not the right category. If the video that is recapped is not directly linked to the current video, but clips from the recapped video are shown, you shouldn't submit them either, because others have probably not watched the recapped video.

To be clear, people are mistakenly applying the category to sections containing information that the uploader **hasn't** covered previously (in the same video or a past video of the same series).  These are "recaps" only in the broader sense that they describe events that occurred before others mentioned in the video.

I think I understand your point regarding the word _replay_, though. Is there some other word that might work?

**Comment by mchangrh** [comment]
ah okay so it's just a misuse of the category altogether - I'm not sure what word would be a better description

**Comment by levyd75** [comment]
> ah okay so it's just a misuse of the category altogether - I'm not sure what word would be a better description

Yeah, I apologize for being unclear.

I realize that it's impossible to prevent such misuse entirely (and I expect to downvote incorrect segments from time to time), but this specific error is more clear-cut and problematic than most that I've encountered.  Large portions of videos are likely to be skipped by viewers who don't realize that they aren't actually recaps of information covered previously.

Of course, users who read the wiki will understand the category's purpose.  I just wish it could be made more obvious for those who don't bother.

**Comment by mchangrh** [comment]
Hmm, maybe `Series Preview/Recap` - That would differentiate it from other topics while not losing the essence of recap?

**Comment by levyd75** [comment]
> Hmm, maybe `Series Preview/Recap` - That would differentiate it from other topics while not losing the essence of recap?

This is an excellent suggestion; thanks!  I've updated the issue accordingly.

**Comment by ajayyy** [comment]
"Series Preview" is misleading, previews for the current video are allowed

**Comment by levyd75** [comment]
> "Series Preview" is misleading, previews for the current video are allowed

Good point. How about `Content Preview/Recap`?
