### ISSUE TITLE
Using homomorphic encryption for better privacy

### ISSUE THREAD

**Issue by sha-265** [ajayyy/SponsorBlock#1854]
I'm not an expert but I think homomorphic encryption is suitable and more private solution than "K-anonymity" that SponsorBlock using, suggested by @girst.

With the current solution the server owner still can figure out what video the user watching with high probability (for example according to the popularity of the videos in the list). 

Here is an good article to start with if you want to understand more about homomorphic encryption: 
https://blintzbase.com/posts/pir-and-fhe-from-scratch/

**Comment by ajayyy** [comment]
Very interesting system, definitely more complex to explain how it works to the user though

**Comment by sha-265** [comment]
> Very interesting system, definitely more complex to explain how it works to the user though

Does the user need to understand how it works? :)

**Comment by ajayyy** [comment]
After some discussion, I don't think it's worth implementing, but it is definitely a cool idea.

Main reasons are
- would require generating a separate blob store that is hard to cache, and will become out of date
- brute forcing using popular video IDs would allow figuring out where in the blob popular videos are leaking their requests
- harder to explain to non technical people
