### ISSUE TITLE
API on NewPipe (Android) not working

### ISSUE THREAD

**Issue by akasaka99** [ajayyy/SponsorBlock#1856]
I have installed NewPipe with SponsorBlock v. 0.25.2 on a Samsung S10 w/ Android 11, set-up SponsorBlock's official API to https://sponsor.ajay.app/api and turned on "Skip Sponsors" but no coloured marking are appearing at the bottom of the video showing the various sponsor segments like on  Invidious/YT and the segments are not skipped either.
Checked on an older phone LG and it does not work either there.

**Comment by ajayyy** [comment]
Ask them
