### ISSUE TITLE
"Unsubmitted Color" segments won't show a skip popup

### ISSUE THREAD

**Issue by github-account1111** [ajayyy/SponsorBlock#1857]
![image](https://github.com/ajayyy/SponsorBlock/assets/5728319/5c78f342-86d0-4fe2-8d74-a99ad68ad44c)

The whole segment is an ad, yet the skip popup only appeared for the smaller segment in toxic green and only skipped until the end of that toxic green segment. The faded green segment was simply ignored. Why's that? How do I make it not ignore it?

The settings label faded green as "Unsubmitted Color." Unsure what that means, and Google didn't yield anything useful.

**Comment by ajayyy** [comment]
That means it's a segment you created but did not submit. It's there to preview before submitting it for others to see

**Comment by github-account1111** [comment]
Must've done it by accident.
The one I created is in bright green or faded green?
Probably the former because the latter is way too precise.

So if I create a segment without submitting it, SB will ignore submitted segments and only show popups for this unsubmitted one?

**Comment by ajayyy** [comment]
The fades green. You might have clicked copy and downvote on a segment by someone else, turning it into an unsubmitted segment
