### ISSUE TITLE
[Bug] Segment at end causes endless loop of playing and pausing

### ISSUE THREAD

**Issue by Christopher-Hayes** [ajayyy/SponsorBlock#1859]
SponsorBlock correctly skips the segment. But, something about the segment ending when the video ends, causes the video to then play and pause repeatedly until I seek somewhere else in the video. 

I'm seeing it on this video: https://www.youtube.com/watch?v=WefPAy2lqrA

The video is `11:09.941` in length. (Checked with `<video>.duration`)
There's an "Unpaid/Self Promotion" segment from `10:37.207` to `11:09.941`.

## Video of bug

[trimmed_output.webm](https://github.com/ajayyy/SponsorBlock/assets/6013871/f540b4d4-3937-4d9f-bf94-8b194702a1c3)

## Versions

Version: `5.4.20`
Browser: `Firefox 118.0b9`

Didn't find any other issues that sounded like this. The only ones that sounded remotely similar were #1409 and #1240. But, those are more related to looping.

**Comment by Sopor** [comment]
I was going to report the same


https://github.com/ajayyy/SponsorBlock/assets/5789283/8575116a-939e-4981-8f86-ea1ec6dc886a

**Comment by mchangrh** [comment]
#1818 #1409 #1240 and [discord](https://discord.com/channels/603643120093233162/609441389423493128/1157770864205504562)

something about segments not reaching the very end of the video and looping when attempting to skip

**Comment by ajayyy** [comment]
I believe this will be fixed by https://github.com/ajayyy/SponsorBlock/commit/c8c141f5c9f0082863d9c3304c0cad17fe394b84

**Comment by Sopor** [comment]
> I believe this will be fixed by [c8c141f](https://github.com/ajayyy/SponsorBlock/commit/c8c141f5c9f0082863d9c3304c0cad17fe394b84)

@ajayyy I'm running version 5.4.24 of SB and do that version contain this fix?

I'm getting a similar issue that i haven't seen before, so i wanted to know before reopen/open an issue.

**Comment by ajayyy** [comment]
@Sopor no, I haven't released it yet
