### ISSUE TITLE
Better-sqlite3 and other improvements

### ISSUE THREAD

**Issue by phiresky** [ajayyy/SponsorBlock#186]
[better-sqlite](https://github.com/JoshuaWise/better-sqlite3) is faster than the more popular `sqlite3` node library especially when load increases. The reason is that sqlite3 is "asynchronous" even though all the computation still happens on the same thread. This means the only thing it being async does is it increases the overhead significantly. (The reason it's more popular is as far as I know only because node devs fear stuff that is synchronous without really understanding what happens behind the scenes.)

**Comment by phiresky** [comment]
I guess this is actually a https://github.com/ajayyy/SponsorBlockServer issue, though there seem to be other server related issues in this repo?

**Comment by ajayyy** [comment]
This actually is on my to-do list (after switching the DB to WAL mode), but
it's good to have a formal issue here for it. Thanks!

**Comment by ajayyy** [comment]
I think it is more popular due to being the first in the search results :)

**Comment by phiresky** [comment]
I was actually about to open another issue about WAL mode :) 

Here are some more suggestions for sqlite performance, apart from `pragma journal_mode = WAL;`:

1. `pragma synchronous = normal;` or even `off`. `normal` is still completely corruption safe in WAL mode. `off` *can* cause db corruption though I've never had problems. See here: https://www.sqlite.org/pragma.html#pragma_synchronous
3. `pragma optimize` _To achieve the best long-term query performance without the need to do a detailed engineering analysis of the application schema and SQL, it is recommended that applications run "PRAGMA optimize" (with no arguments) just before closing each database connection. Long-running applications might also benefit from setting a timer to run "PRAGMA optimize" every few hours._ https://www.sqlite.org/pragma.html#pragma_optimize
2. `pragma temp_store = memory;` not sure how much this one helps.
3. `pragma page_size = 32768;` this improved performance and db size *a lot* for me in one project, but that might only be true because i was storing somewhat large blobs in my database and might not be good for this project where rows are small. 

Then there's also auto_vacuum but I think that's only really useful if you delete rows regularily. It also slows down write queries unless you use `pragma auto_vacuum=incremental` and then run `pragma incremental_vacuum` sometimes.

**Comment by ajayyy** [comment]
I was having trouble getting Wal mode to do resyncs (putting it back in the main file, not sure what the name is) at a consistent rate. I also couldn't figure out how to trigger it manually.

Since I am hosting the .db file for download, I want to to be updated at least every few minutes.

**Comment by phiresky** [comment]
Not an expert, but as far as i know you can run `PRAGMA schema.wal_checkpoint`; to force it to write data to .db file right now. You can also change how often it resyncs normally with `PRAGMA wal_autocheckpoint = N` where N is the number of pages. That's not really a predictable time though since that means it will write changes to db after every N * 4096 bytes not after N seconds

**Comment by phiresky** [comment]
source:

https://www.sqlite.org/pragma.html#pragma_wal_checkpoint
and here:

> one wants to eventually transfer all the transactions that are appended in the WAL file back into the original database. Moving the WAL file transactions back into the database is called a "checkpoint". [src](https://www.sqlite.org/wal.html#ckpt)

**Comment by ajayyy** [comment]
Yep, I have to play around with it more since I couldn't get that command working

**Comment by phiresky** [comment]
Note that it won't actually delete or even truncate the wal file if you have more than one process that has the db open (probably unless you do `pragma wal_checkpoint(full);` but i don't think you want that)

**Comment by phiresky** [comment]
Another thing: Looks like you don't have any indices on the columns you're using frequently? That intentional?

e.g. doing
`create index sponsorTimes_videoID on sponsorTimes(videoID);`

reduces duration of
`SELECT startTime, endTime, votes, UUID, shadowHidden FROM sponsorTimes WHERE videoID = '7HXqkjWS2po' ORDER BY startTime`

from 15ms to 2ms for me.

**Comment by ajayyy** [comment]
Is there a disadvantage to this? Does it hurt write time?

**Comment by phiresky** [comment]
To indices? Yes, the index is (I think) a separate copy of the indexed column(s) in a B-Tree that needs to be updated on writes (though only on ones that change the indexed columns, which in this case should only be the first time a new video is added). For most applications the consensus is that it's definitely worth it. In this case it should be as well, since probably you have many many more reads than writes, especially since you also have tons of queries where no entries even exist that currently still take 15ms of your CPU time every time.

**Comment by ajayyy** [comment]
Okay, then I think that should be saved until after wal mode

**Comment by ajayyy** [comment]
https://stackoverflow.com/a/765696

**Comment by phiresky** [comment]
Yeah i actually did that to check if it was doing a full table scan before adding the index and to check if it was using it afterwards: 
![image](https://user-images.githubusercontent.com/2303841/70442085-dd17df80-1a95-11ea-83f0-2cab62105352.png)

> Does it hurt write time?

Actually from what I see it should improve write times a lot at least for `/api/postVideoSponsorTimes`, since that also does multiple SELECT queries that need to scan the whole sponsorTimes table every time that can be sped up with a sponsorTimes(videoId) index.

**Comment by phiresky** [comment]
Another thing you should probably do more for data integrity reasons than performance is add some keys to your database.

For example from what I see right now you have a race condition here: https://github.com/ajayyy/SponsorBlockServer/blob/master/index.js#L304-L308
Since you actually do the select first and then update so if you submit the same vote multiple times in quick succession you should be able to get multiple entries into that database.


Suggestion:


```diff
diff --git a/databases/_private.db.sql b/databases/_private.db.sql
index dfd672a..af89fa2 100644
--- a/databases/_private.db.sql
+++ b/databases/_private.db.sql
@@ -1,12 +1,13 @@
 BEGIN TRANSACTION;
 CREATE TABLE IF NOT EXISTS "shadowBannedUsers" (
-	"userID"	TEXT NOT NULL
+	"userID"	TEXT NOT NULL PRIMARY KEY
 );
 CREATE TABLE IF NOT EXISTS "votes" (
 	"UUID"	TEXT NOT NULL,
 	"userID"	INTEGER NOT NULL,
 	"hashedIP"	INTEGER NOT NULL,
-	"type"	INTEGER NOT NULL
+	"type"	INTEGER NOT NULL,
+	PRIMARY KEY ("UUID", "userID") -- only one entry per user and sponsor UUID
 );
 CREATE TABLE IF NOT EXISTS "sponsorTimes" (
 	"videoID"	TEXT NOT NULL,
diff --git a/databases/_sponsorTimes.db.sql b/databases/_sponsorTimes.db.sql
index 647d40c..6c94775 100644
--- a/databases/_sponsorTimes.db.sql
+++ b/databases/_sponsorTimes.db.sql
@@ -1,20 +1,20 @@
 BEGIN TRANSACTION;
 CREATE TABLE IF NOT EXISTS "vipUsers" (
-	"userID"	TEXT NOT NULL
+	"userID"	TEXT NOT NULL PRIMARY KEY
 );
 CREATE TABLE IF NOT EXISTS "sponsorTimes" (
 	"videoID"	TEXT NOT NULL,
 	"startTime"	REAL NOT NULL,
 	"endTime"	REAL NOT NULL,
 	"votes"	INTEGER NOT NULL,
-	"UUID"	TEXT NOT NULL UNIQUE,
+	"UUID"	TEXT NOT NULL PRIMARY KEY,
 	"userID"	TEXT NOT NULL,
 	"timeSubmitted"	INTEGER NOT NULL,
 	"views"	INTEGER NOT NULL,
 	"shadowHidden"	INTEGER NOT NULL
 );
 CREATE TABLE IF NOT EXISTS "userNames" (
-	"userID"	TEXT NOT NULL,
+	"userID"	TEXT NOT NULL PRIMARY KEY,
 	"userName"	TEXT NOT NULL
 );
 COMMIT;
```

Note that PRIMARY KEY implies UNIQUE which also automatically creates an index on that key (which improves performance for `SELECT where` that column.

**Comment by ajayyy** [comment]
Wouldn't this just cause a crash instead. That is what was happening in `postSponsorTimes` which uses `UNIQUE` when requests were too fast.

**Comment by phiresky** [comment]
you mean would the schema change just cause a crash instead? not sure, the INSERT query would be rejected but in this case since the callback is missing it would probably just be ignored. (not wanted since the code below that insert should only happen if the insert succeeded)

**Comment by ajayyy** [comment]
using `INSERT` with a duplicate `UNIQUE` value causes a crash. I can catch it though.

**Comment by jplsek** [comment]
Not sure if this is the right place to say this but, imo, the production database should _eventually_ be migrated to mysql (mariadb) or postgresql. Sqlite is not meant for large databases. It's [supposed](https://www.sqlite.org/whentouse.html) to be used for small projects or user applications. I suspect that the database is going to get much larger very quickly, and queries will get slower and slower. I'm not sure how many hits per day your database is queried, but you're probably going to be fine for a while. Again, not soon, but eventually.

**Comment by ajayyy** [comment]
@jplsek Right now the main draw to sqlite is being able to share a [single file](http://sponsor.ajay.app/database.db) to let others access the raw database. So, I do want to keep it sqlite for as long as possible.

**Comment by jplsek** [comment]
That's what a [database dump](https://mariadb.com/kb/en/mysqldump/) is for. :)

**Comment by phiresky** [comment]
@jplsek imo you're underestimating the scalability of sqlite. Sqlite works just fine for 10k+ selects per second and 100+ inserts per second. It also works fine for db sizes of 1GB+. The current DB has 33k videos and is 14MB in size. So if it grew to 1GB that would be space for 2.2 million videos. Also you're somewhat mistaken in that queries will get slower and slower if the db size grows.

If the server has enough RAM (and if the mmap pragma is set) select queries will stay pretty much the same performance regardless of the db size since it's just a lookup in RAM, same as now, and same as it would be for other DB engines. Afaik it's a btree lookup into the index (log(size)) + a linear search in the WAL log (const time). Inserts will get slower since it has to rewrite larger indices and table data, but this application is very much read-heavy.

Sadly the [speed](https://www.sqlite.org/speed.html) page is very outdated so it's not that useful to reference. [The "FS" page](https://www.sqlite.org/fasterthanfs.html) is newer but not as relevant.

A better reason to switch to eg PostgreSQL would be the pretty bad support for SQL in sqlite and the possibility for replication to different servers.

Also database dumps are pretty ugly most of the time you see them, since they either are borked csv files or in a internal database format only a specific db engine can understand (i've fought with scripts to convert MySQL dumps to csv or sqlite dumps but they never worked on the first try)

**Comment by phiresky** [comment]
One more thing i forgot @ajayyy: You should also set `pragma mmap_size= 30000000000;` cuz fast

**Comment by OfficialNoob** [comment]
Seems like a big number does it need to be set at 30GB
Still think a Redis database would be better.
As there is cluster support and its in ram (Still able to have data in a file as well)

**Comment by phiresky** [comment]
Na, redis is definitely not made for something like this. Even calling it a "database" is really misleading. It's a server that keeps a huge hashmap in RAM and dumps it to disk every 30 seconds.

**Comment by OfficialNoob** [comment]
@phiresky 
"Redis is an open source (BSD licensed), in-memory data structure store, used as a database, cache and message broker" from `https://redis.io/topics/introduction` This seems to mean that it maybe used as a database.

Also it does seem to have [transactions](https://redis.io/topics/transactions)
And for data structures: "It supports data structures such as strings, hashes, lists, sets, sorted sets"

It does not use tables like in SQL however that does not seem to be a bad thing.

It also seems like a "Append-only file" will run when "Redis receives a command that changes the dataset" instead of having to wait.

**Comment by phiresky** [comment]
I know what redis is, I'm using it for sessions, caching and message passing right now in a production site (3M keys and ~20 events per second). Including the .multi() thing which is stop-the-world-"transactions" and the to-disk serialization. It works ok. I'd still definitely not use it for this, though I'm not really willing to spend more time explaining why unless ajayyy decides to seriously consider it for this.

**Comment by OfficialNoob** [comment]
Is there a problem with persistence?

**Comment by OfficialNoob** [comment]
https://github.com/RedBeardLab/rediSQL (never used it)

**Comment by ajayyy** [comment]
After doing some testing, I feel confident to enabled WAL mode.

I took me long enough haha.

**Comment by ajayyy** [comment]
Hmm, the page limit didn't seem to work. The WAL file is growing fast.

**Comment by phiresky** [comment]
So you set wal_autocheckpoint to some lower value? 

I think the size of the WAL file is not necessarily indicative of the amount of unwritten data, since I think the WAL file is only truncated in some situations but not when the data is committed. For example, if you run `pragma wal_checkpoint(full)` the WAL file won't change size if other processes have the file open but still commit everything, only if you run `pragma wal_checkpoint(truncate)` it will block other processes and reset the WAL file to zero bytes.

**Comment by ajayyy** [comment]
@phiresky okay. I guess I can shutdown the server for a few seconds and do that when it gets too big

**Comment by phiresky** [comment]
@ajayyy you don't have to shut down the server to run `pragma wal_checkpoint(truncate)` i think. it will just lock out writes until done (<1s)

**Comment by ajayyy** [comment]
@phiresky oh okay, so reads are fine?

**Comment by phiresky** [comment]
Not sure actually. But even if they have to wait it's still better than shutting down the server right?

But also, you shouldn't have to run that at all, the WAL file size shouldn't really matter. I think you can check how many pages are actually uncommitted by looking at the second column of the output of `pragma wal_checkpoint`

**Comment by ajayyy** [comment]
In my experience, doing this crashes the server anyway. Maybe that is because the default timeout is very small though

**Comment by phiresky** [comment]
It crashes the whole server? It should at the most make the db reject read and write operations, whose errors should be handled in the code right? i.e. write (+maybe read) requests would fail but the server should stay up. With what error does it crash?

**Comment by ajayyy** [comment]
The errors are catched in my BetterSqlite PR, so this might not happen anymore

**Comment by ajayyy** [comment]
Enabling mmap was a great improvement.

**Comment by lieuwex** [comment]
> I was having trouble getting Wal mode to do resyncs (putting it back in the main file, not sure what the name is) at a consistent rate. I also couldn't figure out how to trigger it manually.

Sorry to reply to an old comment, but this sounds like a good use for the [SQLite Backup API](https://www.sqlite.org/backup.html).
