### ISSUE TITLE
[Suggestion] Option to overlay visual only ads

### ISSUE THREAD

**Issue by divi0001** [ajayyy/SponsorBlock#1860]
Hello.

Some ads are displayed only visually, sometimes just showing the name of the sponsor in the corner of the screen, sometimes showing a fake (non) clickable ad, like the ones youtube had like 10 years ago. So the ad is present in the screen, while the content is still playing out.
My suggestion is to add an option for marking visual only ads, where you can define a region and the time that the region is used by ads, so for people who don't want to see that, that region is shown with any image layered on the place the ad would've been.
I have attached a few examples:

![Capture](https://github.com/ajayyy/SponsorBlock/assets/106699019/22aa6f64-daba-49b8-aebf-1ea6fb24c703)
![Capture](https://github.com/ajayyy/SponsorBlock/assets/106699019/9125f390-f4bc-4b7f-8d93-fd3f292928c4)
![Capture](https://github.com/ajayyy/SponsorBlock/assets/106699019/7a13e556-7334-4e5a-8704-b1691cd5ca06)
![Capture](https://github.com/ajayyy/SponsorBlock/assets/106699019/d9ad34ec-a7aa-46af-b686-ceac8250ae69)
![Capture](https://github.com/ajayyy/SponsorBlock/assets/106699019/46a38190-ef6f-41f7-9e06-b545d30336f5)
The last one is the fake clickable
Thanks :)

**Comment by ajayyy** [comment]
#538
