### ISSUE TITLE
Add PokeTube Support

### ISSUE THREAD

**Issue by SudoVanilla** [ajayyy/SponsorBlock#1863]
I'm pretty sure this needs some configuring in the Invidious support that SponsorBlock claims support, as PokeTube pulls from some Invidious instances. 

Although, PokeTube uses the built-in player from the web browser, not the one Invidious uses. Not sure if that is important. 

As of now, there are only two instances of PokeTube running, according to their instances list. A third one in the making, with modifications.

Issue opened on PokeTube's Codeberg: https://codeberg.org/Ashley/poketube/issues/33

___

Also, I noticed Invidious support is buggy, doesn't really work on my end in LibreWolf.

**Comment by mchangrh** [comment]
If someone wants to add it, they can add selectors https://github.com/ajayyy/SponsorBlock/pull/1560

please open a separate issue for librewolf, lots of people have been having issues with *fox offshoots and a lot of privacy settings preventing normal operation
