### ISSUE TITLE
[Feature request] Annoying sounds category

### ISSUE THREAD

**Issue by adamsatyr** [ajayyy/SponsorBlock#1864]
I would like to suggest an "Annoying sounds" category, as example start of https://www.youtube.com/watch?v=zR6vzJPlKrg uses (for some reason) classic sound associated with headache which is actually painful to me.

So it would be nice to have this category to mute those kind of sounds.

**Comment by CheaterTim** [comment]
but how would you draw the line between an "annoying" sound and just a normal sound

**Comment by adamsatyr** [comment]
The one that can cause pain, high frequency noises, sudden change of volume to high pitched loud noise, repetitive commercial style music without people speaking over it.

**Comment by mchangrh** [comment]
related: #1310
