### ISSUE TITLE
Piped integration: website navigation bar is hidden

### ISSUE THREAD

**Issue by acidghost** [ajayyy/SponsorBlock#1865]
As documented by https://github.com/TeamPiped/Piped/issues/2987 this extension breaks the navigation bar in Piped.

Most of the info is there, I'll repeat my setup:
- Firefox 118.0.1
- macOS 13.6
- SponsorBlock v. 5.4.21
- Instance https://piped.video

Let me know if you need more details.

**Comment by mchangrh** [comment]
hmm, I can't reproduce it on firefox or chrome on windows and piped support was added in [July](https://github.com/ajayyy/SponsorBlock/pull/1798) If that was the case, then it should have popped up much much much earlier

**Comment by acidghost** [comment]
I just reproduced it in an incognito window w/ just SponsorBlock extension enabled.

Are you sure that you're using the same version of Firefox?

**Comment by mchangrh** [comment]
Repro'd on another machine with a fresh FF install, I think it might be maze-utils...

**Comment by mchangrh** [comment]
Found it, it's because of a conflicting css class

```css
<ul class="md:text-1xl hidden md:flex md:flex md:flex-1 md:justify-end md:children:pl-3"> </ul>
```

`.hidden` is overriden by an `@media display:...` property, but sponsorblock's css overrides it...

I'll ping kavin on matrix to discuss..

**Comment by ajayyy** [comment]
SponsorBlock shouldn't inject such a generic class name

**Comment by mchangrh** [comment]
Then we might need to refactor some other classes as well

**Comment by SandResidence** [comment]
I can confirm the error occurs and is *really* annoying
