### ISSUE TITLE
Fair/ethical Ads

### ISSUE THREAD

**Issue by louis-vgn** [ajayyy/SponsorBlock#1868]
I have been very hesitant to use this extension, the reason being ethical concerns. 

I know someone had the same remark #794. 

Following [NewPipe’s point of view on sponsors](https://newpipe.net/blog/pinned/newpipe-and-online-advertising/), which I think is relevant on many aspects, and without repeating the whole debate, it may be interesting to have a division of categories for sponsors. One for fair/ethical sponsorship and another for unfair/unethical sponsorship. That way, users are free to choose what to skip. 

## Possible Implementations

I see two ways this could be implemented: 

1. Creating multiple sub-categories, within the fair/ethical category, where there are different topics (e.g., relevant to channel, etc.), and have a separate category unethical sponsors. However, having multiple sub-categories seems to curbersome, maybe for code implementation, but mainly for users who submit segments, who would need to choose every time a specific category . Also, it would create too much of a debate regarding the subjectivity of what can be considered ethical. Hence, the second, and better, in my opinion, implementation;

2. It would be understood and implemented in a "*negative way*". By that I mean, rather than categorizing what is fair/ethical (as this may be extremely subjective), categorizing should work by what is utterly unethical (or even illegal, e.g., hidden sponsors, pomotion of illegal products, etc.). Thus, it removes the cubersome work for users submitting to choose which subcategory to put it into, and it allows everyone to choose whether to skip or not the fair/ethical choice.

The negative implementation **does not question** the whole purpose of SponsorBlock, as users who prefer to skip everything *still can*. However, it would enable, I believe, a lot of people in the community to help content creators by watching the fair/ethical sponsorship[^1].

I am not a developer. I have very little programming knowledge, but have used JS before. I would be keen (with some help) to technically implement this in the code if the idea seems sound and relevant to folks. 

[^1]: Watching sponsor segments raises the metrics of content creators, who can then show it to sponsors in order to negotiate a better compensation.

**Comment by ajayyy** [comment]
All add are unethical
