### ISSUE TITLE
Not working with Safari 17

### ISSUE THREAD

**Issue by metawops** [ajayyy/SponsorBlock#1869]
After downloading the latest (Release 5.4.22) SafariExtension.zip and issuing the command `xcrun safari-web-extension-converter /path/to/extension` I get this error:
```
Unable to parse manifest.json at file:///Users/stefan/Downloads/SafariExtension.zip
```
I'm on macOS Sonoma 14.0 and Safari 17.0 and Xcode 15.0.

**Comment by ajayyy** [comment]
You have not extracted the zip file

**Comment by metawops** [comment]
O.M.G. – how embarrassing!! Mea culpa! I'm so sorry & thanks so much!!

**Comment by ngn999** [comment]
We should update the document.
