### ISSUE TITLE
Spam of tangent/filler segments makes videos unwatchable

### ISSUE THREAD

**Issue by acidghost** [ajayyy/SponsorBlock#1870]
Some videos, especially by some creators (e.g. Linus Tech Tips), get spammed with tangent/filler segments so much that makes them unwatchable.

This is not a new problem any many people have pointed it out in the past. This has ruined entire videos for people (e.g. LTT's April's Fool videos) and I think it needs to be addressed sooner rather than later.

Take this as an example (https://youtu.be/VJFaXwnixxM, screenshot attached).

![Screenshot 2023-10-04 at 07 37 45](https://github.com/ajayyy/SponsorBlock/assets/1787979/c848fd6c-8f87-46cb-b486-438be250a83a)

How can the video be, in all seriousness, 95% filler and tangent jokes. LTT is also (mainly) an entertainment channel. There are jokes, for sure, but are 95% really tangential? I'm pretty positive that this is just a case of someone getting salty about the creator and "taking revenge" in this para-social way.

**Comment by ajayyy** [comment]
Disable filler
