### ISSUE TITLE
Some music mistakenly tagged as sponsor segments

### ISSUE THREAD

**Issue by rosa-martin** [ajayyy/SponsorBlock#1871]
I've noticed that in some YouTube music playlists (e.g. https://www.youtube.com/watch?v=Bgob-qyjhh4) some sections are mistakenly tagged as sponsor segments. Specifically in the aforementioned video, chapter beginning at 28:11 and chapter beginning at 49:53 are both showed as sponsor segments and are automatically skipped (even tho it's just music) .

I've also noticed that this seems to happen often to videos from the creator of the aforementioned video. 
![crop-it](https://github.com/ajayyy/SponsorBlock/assets/92361558/87c939a3-f487-4e8c-9f76-e8001dcff236)

**Comment by ajayyy** [comment]
Incorrect submissions can be reported on discord or matrix

discord.gg/SponsorBlock
