### ISSUE TITLE
[Feature Request]: Add a way to hide sponsor in video description

### ISSUE THREAD

**Issue by BenocxX** [ajayyy/SponsorBlock#1879]
When ever a content creator has a sponsor, they often refer the sponsor in the description of the video with a referral link.

It would be nice to be able to remove this section of the documentation. 

Maybe even remove a comment by the content creator referencing the sponsor?

**Comment by shashankdaima** [comment]
hey @BenocxX, its better to create a dialog when people click from description about suspicious amazon links, etc. while crowdsourcing brands that usually do sponsorships. Because it is quite impossible to detect that otherwise. lmk

**Comment by BenocxX** [comment]
English is not my primary language so sorry if there are misunderstandings.

What I was proposing was to add the ability to remove parts of the description (like we are currently removing parts of the video). For example here's the discription of a video:
```
Thanks to SoFi for sponsoring the video! Enter for a chance to win $10,000: [https://sofi.com/airrack](LINK) No purchase necessary to enter. See terms for info & free entry method. Terms: [https://www.sofi.com/airrackrules](LINK)

Special Thanks to Avilon Moto for hooking us up: 
[https://www.instagram.com/moto.avilon/](LINK)

In this video we... (REST OF THE DESCRIPTION)

Follow me on Instagram!
INSTAGRAM ▶️ [https://urlgeni.us/instagram/jBHg](LINK)

FOLLOW MY FRIENDS:
Beans: [https://www.instagram.com/samuelj_tho...](LINK)
Tyler:   [ / tylerblanchard ](LINK) 
Michelle:   [ / @msmunchie123 ](LINK) 

I’m hiring! Apply for jobs here [http://www.airrackjobs.com](LINK)

Outtro song ▶️ Axel Thesleff - Bad Karma
YouTube: [https://bit.ly/3k6Uadj](LINK)
Spotify: [https://spoti.fi/3odq3TN](LINK)
Instagram: [https://bit.ly/3lsccaz](LINK)
```

It would be cool to be able to mark part of the description has `sponsor`, `self-promo`, `non-paid promo`, etc...

Once the community flagged every part of the description, the final result would be this:
```
(Sponsor is hidden)

(Second sponsor is hidden)

In this video we... (REST OF THE DESCRIPTION)

(Self promo is hidden)

(Non-paid promo is hidden)

I’m hiring! Apply for jobs here [http://www.airrackjobs.com](LINK)

(Non-paid promo is hidden)
```

SponsorBlock does an amazing job at hidden sponsor in the video, but does nothing to hide sponsor in the description or comment section.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/649
