### ISSUE TITLE
Clarify that auto upvote can be disabled

### ISSUE THREAD

**Issue by TheFrenchGhosty** [ajayyy/SponsorBlock#188]
This project sound like a great idea, but I have a little privacy issue with it:

I'm quoting the website here: "Once the sponsorship is skipped, you can report this sponsorship and it will be recorded in the database. **If you don't report it, it will automatically be treated as an upvote.**"

If I understand correctly it means that every time a sponsor is skipped it will automatically report to the server that I used the time-code that is tied to X video. 

This is in my opinion really intrusive, I don't want to tell you that I watched X video and it would be nice if there was a way to not be "counted" in in any way that way the watched videos are kept private.

**Comment by ajayyy** [comment]
Please check the options, it is there :)

**Comment by ajayyy** [comment]
I'll keep this issue open to remind myself to add clarification on the website

**Comment by TheFrenchGhosty** [comment]
Well this is amazing then, I'm waiting for Invidious support then I will test it, thank for this project!

**Comment by Leseratte10** [comment]
But if I understood this correctly, then every client tells the server what video it is watching "by design" because each time you load a video you are asking the server for the sponsor time codes for that current video anyways, right?

**Comment by ajayyy** [comment]
@Leseratte10 Yes, the difference is that the vote requests send the userID along with it, so they aren't anonymous. When it requests for sponsor times, it only knows the IP address. This is not tracked, whereas the votes are tracked.

**Comment by TheFrenchGhosty** [comment]
Exactly, my point is that the requests will be tied together under a same ID, making them (technically) non-private.
