### ISSUE TITLE
Extension is detected by YouTube as an ad blocker

### ISSUE THREAD

**Issue by Neel-shetty** [ajayyy/SponsorBlock#1882]
Since the update where YouTube started detecting ad blockers and limiting the number of videos you can watch with an ad blocker on, this extension triggers the detection even tho the new update of uBlock Origin doesn't trigger it.
I turned this extension off with uBlock Origin on, and YouTube did not detect it. When I turned it on, it triggered YouTube's detection.
Browser - firefox 118.0.2
SponsorBlock version - 2.0.121

**Comment by ajayyy** [comment]
Can you try following all of the steps here (except disabling SB) https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by Neel-shetty** [comment]
> Can you try following all of the steps here (except disabling SB) [uBlockOrigin/uAssets#19976](https://github.com/uBlockOrigin/uAssets/issues/19976)

Yes I reported the issue after trying those steps, uBlock Origin is not being detected but SponsorBlock is.

**Comment by ajayyy** [comment]
Can you send the uBO debug info and sb debug info

**Comment by Neel-shetty** [comment]
My bad, its not an issue of Sponsorblock deeply sorry for wasting your time. 
Seems to be an issue with some other extension.

**Comment by j00ch** [comment]
> My bad, its not an issue of Sponsorblock deeply sorry for wasting your time. Seems to be an issue with some other extension.

Which one?
