### ISSUE TITLE
[Suggestion] Auto-Skip Native Ads

### ISSUE THREAD

**Issue by uSkizzik** [ajayyy/SponsorBlock#1887]
Okay so recently I got the new YouTube AdBlock detection thing and I disabled my adblocker.  
Today, I discovered that if a video has a highlight and I click the "skip to highlight" button while a YouTube ad is playing (the native ones with the yellow bar), it will skip the ad EVEN if the button to skip the ad is disabled.  
My suggestion is to add this ad skipping as a feature of the extension rather than just a byproduct of another one. I'm not sure if it's in the scope of the project but it's clearly possible.

**Comment by ajayyy** [comment]
Out of scope
