### ISSUE TITLE
Use Invidious API from currently used invidious instance

### ISSUE THREAD

**Issue by Perflyst** [ajayyy/SponsorBlock#189]
> The awesome Invidious API is used to grab the time the video was published.

Currently the overloaded invidio.us API is always used. It would make sense if the API of the invidious instance is used which is currently in use by the user.

Depends on https://github.com/ajayyy/SponsorBlock/pull/181

**Comment by ajayyy** [comment]
Ideally the invidious api use should be removed entirely since it causes unnecessary strain on their server, but I can't really think of a better way of getting the date a video is released when a browser is set to non english.

**Comment by afrmtbl** [comment]
@ajayyy Have you looked into `https://www.youtube.com/get_video_info?html5=1&video_id=...`?
It provides the `publishDate` and `uploadDate` keys under the `microformat` key.

I don't know how reliable it is or if it changes when using a different language though.
