### ISSUE TITLE
5.4.24 update problem for old browser

### ISSUE THREAD

**Issue by ruboard** [ajayyy/SponsorBlock#1891]
starting from version 5.4.24 it stopped updating for older browsers such as waterfox classic
I didn’t see anywhere that support has been discontinued!

**Comment by ajayyy** [comment]
Nothing was changed that could be related to that. The minimum Firefox version is still the same on AMO. Maybe they changed something on their end when they added support for specifying a minimum version of Firefox for Android supported.

**Comment by ajayyy** [comment]
I'll specify a minimum version of Firefox in the manifest, maybe that will help 0bb3528cded5a0eb1eb3de07390d8ee61f42666a

**Comment by ruboard** [comment]
unfortunately this didn't help. that would be too easy.
There are many extensions on the AMO website that do not have an install button due to compatibility, but there is a button to download a file and it works even though the minimum version of firefox 68 is specified.
For example:
![1](https://github.com/ajayyy/SponsorBlock/assets/79255903/41670a9f-ffda-4fae-83ea-bc66f6555261)
![2](https://github.com/ajayyy/SponsorBlock/assets/79255903/12a1ae9d-25a9-43fc-bf3e-4e484b51a929)

**Comment by ajayyy** [comment]
That version was published in August. Try to find an an extension that has an update published recently that works to see if it is a change on amo side

**Comment by ruboard** [comment]
uaswitcher. no problems with any versions and updates. last 20.10.23
https://addons.mozilla.org/ru/firefox/addon/uaswitcher/versions/

**Comment by decembre** [comment]
Same problem for me with Waterfox (based on firefox 57).

I see it when in my addon page i ask which addon have an update:
- I see your addon
- I update it, seems ok.

But if i reopen the addon pgae and do the same thing,
your addon is seen as not updated.

In fact, maybe it's not a problem with your addon:
I have the same problem with <a href="https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/">[User-Agent Switcher by Erin Schlarb](https://addons.mozilla.org/en-US/firefox/addon/uaswitcher/)</a>
For this on,e i can install the last version by dragging the 'Add to Firefox" button in the URLBar.

ut if i do the same thing with your, i got an error message:
"C'an't install: Addon corrupt"

**Comment by ajayyy** [comment]
Adding

```json
"gecko_android": {
    "strict_min_version": "79.0"
}
```

to the manifest causes it to be labeled as corrupt. This is needed to function on Firefox for Android. This seems like a bug in their web extensions implementation.

**Comment by decembre** [comment]
So you update it ?

**Comment by ruboard** [comment]
> to the manifest causes it to be labeled as corrupt. This is needed to function on Firefox for Android. Removing it does fix it. This seems like a bug in their web extensions implementation.

Is any solution possible?

**Comment by ajayyy** [comment]
Not supporting both android and waterfox at the same time

**Comment by decembre** [comment]
Haaa... i suspecded something like that :-(

**Comment by ruboard** [comment]
I disassembled .xpi, deleted the above lines, put it back together, the extension was installed.
Now all updates will have to be installed manually?

**Comment by decembre** [comment]
> I disassembled .xpi, deleted the above lines, put it back together, the extension was installed. Now all updates will have to be installed manually?

I trying to do the same thing using 7-Zip but fail...
Have you a link that explain how to do that ?

**Comment by ruboard** [comment]
I did it in winrar, but it's the same as 7-Zip

**Comment by decembre** [comment]
> I did it in winrar, but it's the same as 7-Zip renamed xpi to zip, edited it, and packed it back into zip and then renamed it to xpi

I did that and it work!
:-)

After different bad test, 
For info, here a working and detailed explanation:
- I take the original xpi
- Rename it to .zip
- Decompress it in a folder of the same name than the original .xpi (seen in the 7-Zip menu)
- Edit with Notepad++ its manifest.jon
- Remove in it and save it :
<code>,
    "gecko_android": {
      "strict_min_version": "79.0"
    }</code>
- Select all the items previously decompressed and ZIP it to the same name than the original XPI.
- Change its .zip extension to .xpi
- Drag it to Waterfox ...

And it's OK!
:-)
