### ISSUE TITLE
[Suggestion] Add shortcut(s) to submit intros/end cards with one click only

### ISSUE THREAD

**Issue by strecke** [ajayyy/SponsorBlock#1897]
Almost all videos have end cards from a certain point to the end of the video and many have intros from the beginning to a certain point. It would be extremely convenient for users and would make the extension even more accessible.
I imagine that either one click is necessary or two if the submission has to be confirmed.

**Comment by ajayyy** [comment]
If you change the category to endcard it automatically sets the end time. But if you have another suggestion to speed it up feel free to say

**Comment by doug-last** [comment]
Most channels with intro/end have them in all videos of that author, but i didn't found i way to upload the segments to all videos.
As example i regularly cut the last 26 seconds of every video i watch from the Brazilian channel "ancapsu", its the same segment in every video.
It could be done by a rule for the channel, by a bot, or by an vote confirming that the segment is indeed repeating to skip it

**Comment by InVItroVeritas** [comment]
We could have a “suggested Intro” for instance, that always skips the same number of seconds in the same channel. And it could be suggested to sponsorblock users watching the video.

Something like “this intro time has been suggested” (and the timing could either be done by a power user, a regular user, or something automated based on the intro submissions for that channel always being the same length) and the users presented with this would only need to preview it, check that it works for that video, and if it does, just press send. 

This would also turn a significant number of passive users who don't submit segments (or active users when they don't have the time, are not in a device that allows them to do it easily, etc) into active participators submitting segments. 

I follow a few channels where I know other people have sponsorblock and skip the segments, but if I don't submit them, more often than not one does, even though it's rather easy. 

I have a keyboard shortcut to type in the time for the intro, which is always the same. If I could pass that to other users, they could just confirm the “suggested intro” and that way the video wouldn't have to wait for me to submit the intro.

**Comment by ajayyy** [comment]
5.5 will have keybinds for submitting and focuses the category box to make it easy to select a category with the keyboard
