### ISSUE TITLE
Add option to prevent Sponsorblock from skipping Youtube ads

### ISSUE THREAD

**Issue by JoaoFelipe3** [ajayyy/SponsorBlock#1900]
I'm talking about ACTUAL Youtube ads, not sponsored segments. Add an option to not skip those, since Youtube now blocks your player in 3 videos if you use adblockers, and Sponsorblock is an ad blocker.

**Comment by ajayyy** [comment]
SponsorBlock is not an adblocker and does not trigger that warning. Other extensions, such as enhancer for YouTube do though
