### ISSUE TITLE
[Feature Request] Don't skip if segment is short.

### ISSUE THREAD

**Issue by rktfier** [ajayyy/SponsorBlock#1901]
The contributors on SponsorBlock are so effective in their tasks (Thank you to all of them), often times we get 1-3 second sponsor skips added to the database . Often when we watch videos and SponsorBlock does it's job, with every skip we got a few seconds wasted by the Youtube Player coming back alive and continuing the play. This in my opinion hurts the playback experience, as waiting 3 seconds for a 1 second segment is annoying.

**Comment by ajayyy** [comment]
This is in the settings
