### ISSUE TITLE
"Segments are still being loaded..." Sponsorblock not working on Firefox for Invidious

### ISSUE THREAD

**Issue by nickelswitte** [ajayyy/SponsorBlock#1902]
Hello,

first of all thank you so much for this amazing work.

I am using the newest version of Invidious, and Sponsorblock 5.4.25.

I have added the third party instance and tried turning on / off, restarting browser, etc.

When opening Sponsorblock, the message "Segments are still being loaded..." is on the top and does not disappear.

Thanks for the help!

**Comment by stijnb1234** [comment]
Server seems to be down.

**Comment by Maj-ew** [comment]
It's working on phone for me but not on chrome

**Comment by ajayyy** [comment]
Server issues fixed

**Comment by nickelswitte** [comment]
Fixed it. The problem was not on Sponsorblocks side, but my instance of [adguardhome](https://github.com/AdguardTeam/AdGuardHome) blocked it unintentionally.
Thanks!
