### ISSUE TITLE
Safari Extension not working

### ISSUE THREAD

**Issue by rtphokie** [ajayyy/SponsorBlock#1904]
While the extension works great on Safari, the Safari build (the official one, purchased from the Apple App Store) does nothing.

No highlights, no skipping, no SponsorBlock button in the video controls.

I've verified the extension is enabled.  I've verified the settings include at least manual skips in several categories.  I've restarted the browser.  Still nothing

**Comment by rtphokie** [comment]
> Make sure the icon at the top is not grey. If it is, click on it, and a permission prompt for access to the YouTube.com domain should appear

Thanks for the quick reply.  The top icon is not grey and claims it is enabled:

<img width="390" alt="image" src="https://github.com/ajayyy/SponsorBlock/assets/551185/f4a709db-e1d6-4883-af45-5f43652bb212">

**Comment by ajayyy** [comment]
Can you do a screen recording and show what appears on YouTube

**Comment by rtphokie** [comment]
And the YouTube video controls look like this 
![image](https://github.com/ajayyy/SponsorBlock/assets/551185/12199776-3728-427f-b671-422611560381)

**Comment by rtphokie** [comment]
All good now.

I disabled the extension, removed it, reinstalled it, and reauthorized it for youtube.com from the icon in the upper right and the problem went away.

**Comment by ajayyy** [comment]
Interesting, very odd
