### ISSUE TITLE
Automatic measure based on previous submissions

### ISSUE THREAD

**Issue by andradadad** [ajayyy/SponsorBlock#1908]
Most videos have the same kind of length of credits in the end because it's a ready final end/intro credit.
An experimental feature, like a suggestion for skips, would be possible, @ajayyy ?

Not only for the submitter in edition, but, an actually feature that after let's say five manual submits, a common template for credits either in the end or the beginning would be seen automatically if set on config.

If it's not actually the initial seconds or the last then it would require a lot more resources, but, perhaps it's not that complicated with a dedicated server for it.

**Comment by ajayyy** [comment]
Too inaccurate, but we do have some people running frame based fingerprinting right now.

**Comment by andradadad** [comment]
@ajayyy This would actually have been an improvement if it had been implemented, ajayyy. Years ago.

Reconsider a "custom" 00:00:30-00:00:45, etc, fixed time to cut locally for the user.
