### ISSUE TITLE
Creating Chapters: Text Issues

### ISSUE THREAD

**Issue by PasttaTypo** [ajayyy/SponsorBlock#1909]
When creating chapters for submission, sometimes the last letters/symbols of an inputted chapter name won't be submitted.
_[Example = "Part 1: The Beggini"]_ 
This inaccuracy is not represented in the input field until the submission window over the player is closed and re-opened, and seems to be happening at random; made sure to test with U-Block Origin & other knick-knacks disabled/re-enabled.

Temp "fix" for users w/ this issue:  Add keystrokes by adding extra letters then deleting them after the end of your chapter title until the full names look correct on the video player near the seek bar and double-check any submissions by reloading the submission window and checking for unforeseen tyypos before submitting.

**Comment by freshgum-bubbles** [comment]
Can confirm this happens on Firefox, SponsorBlock v5.4.29.

**Comment by PasttaTypo** [comment]
Pretty sure this was quietly fixed recently, not experiencing the issue personally anymore, so marking this issue as closed.

**Comment by PasttaTypo** [comment]
Pretty sure this was quietly fixed recently, not experiencing the issue personally anymore, so marking this issue as closed.
