### ISSUE TITLE
Certificate Chain not shipped by website

### ISSUE THREAD

**Issue by pstn** [ajayyy/SponsorBlock#191]
The website https://sponsor.ajay.app/ only ships the let's encrypt certificate, but not the entire chain. This can be fine when the correct certs happen to be installed but if the local certificate store for example doesn't yet have the LE certs trusted, the x-signing certs are needed.
This can be achieved 
* with nginx set `ssl_certificate` to the `fullchain.pem` file in the folder containing the domain certs, not to `cert.pem`
* with apache: Add a `SSLCertificateChainFile` line that points to the `chain.pem` file in the cert folder.

Sorry for reporting this here but I didn't find a more suitable place.

**Comment by ajayyy** [comment]
I have caddy, so I have to look into how to do it or look into using certbot

**Comment by ajayyy** [comment]
Should be good now

**Comment by pstn** [comment]
Yes! Thank you very much!
