### ISSUE TITLE
Sponsor icon does not always show up.

### ISSUE THREAD

**Issue by Xuser641** [ajayyy/SponsorBlock#1912]
The icon on thumbnails of videos with a sponsored segment in the video, don't always show up. At first I thought this was a configuration problem with another extension - uBlock Origin. However, turning it of and reloading the page didn't fix the issue. Example image attached, from https://www.youtube.com/@GoodTimesWithScar/videos
Interestingly, Exclusive Access icons, do seem to appear. 
![Temp002](https://github.com/ajayyy/SponsorBlock/assets/81908864/2c8478ae-80ed-4faf-9067-0d0197e6e78c)

**Comment by mchangrh** [comment]
the icon is not for sponsor segments, it is for [full video sponsors](https://wiki.sponsor.ajay.app/w/Full_Video_Labels) and exclusive access can only full video segments
