### ISSUE TITLE
During Buffering it will start a second audio stream that is at 100% volume

### ISSUE THREAD

**Issue by Malavolence** [ajayyy/SponsorBlock#1916]
1. Open a video of which the opening seconds are skipped due to sponsorblock
2. YouTube will skip those seconds, however:
3. It will play a second "audio stream" that is at 100% volume

that can only be stopped by reloading, after which it is gone for that one video

Browser: Version 115.0.5790.99 (Official Build, ungoogled-chromium) (64-bit)
Windows 10 Version 22H2 (Build 19045.3693)
Youtube related extensions:
- Sponsorblock 5.1.8
- Enhancer for YouTube™ 2.0.117.10
- Return YouTube Dislike 3.0.0.9
- uBlock Origin 1.52.2
- Youtube-shorts block 1.3.4
- Tampermonkey (adblock bypass, age restriction bypass)

**Comment by ajayyy** [comment]
Browser, os, extension version?

**Comment by rustyshakelford2** [comment]
Was this resolved? I am experiencing the same issue and had to temporarily disable the extension. 

Chrome Version 119.0.6045.160 (Official Build) (64-bit)
Windows 10 22H2
SponsorBlock 5.4.27

**Comment by ajayyy** [comment]
What other extensions do you have

**Comment by rustyshakelford2** [comment]
I can confirm the "Youtube AdBlock Ban Bypass" userscript is causing this. 
https://greasyfork.org/en/scripts/477498-youtube-adblock-ban-bypass/feedback
