### ISSUE TITLE
Data dumps sometimes stopping early 

### ISSUE THREAD

**Issue by schmorp** [ajayyy/SponsorBlock#1918]
This is a followup to https://github.com/ajayyy/SponsorBlock/issues/1736, which has been closed without fixing it. As further reported there, the problem is ongoing, and it is getting worse and worse. For example, here are the last three updates (this is the server-side lisating):

-rw-r--r--  4,863,991,425 2023/11/24 09:35:44 sponsorTimes_1700814824149.csv
-rw-r--r--  4,078,312,118 2023/11/24 10:36:12 sponsorTimes_1700818451866.csv
-rw-r--r--  3,388,217,798 2023/11/24 11:36:13 sponsorTimes_1700822053747.csv

The normal size of this table is around 5.3GB. The situation is so bad that it has become almost impossible to get a pristine copy of the database via rsync anymore.

This is also not good for the load on the server - when normally I could rsync once per week, now I have to retry almost every hour to eventually get something that might be correct (I basically rsync until I get a file that is the same size or larger than my local copy, each intermediate rsync being wasted bandwidth).

**Comment by ajayyy** [comment]
It now will not use dumps that are not complete
