### ISSUE TITLE
UI/ UX Design Improvements

### ISSUE THREAD

**Issue by devmattrick** [ajayyy/SponsorBlock#192]
Hi! I'm making this issue to gauge interest in some PRs to improve the overall design of the extension and possibly the website? I can work on them if there is interest in it.

**Comment by ajayyy** [comment]
What kind of improvements are you thinking?

**Comment by devmattrick** [comment]
Here's what I had in mind:
![image](https://user-images.githubusercontent.com/5848320/70845381-d45f3a80-1e02-11ea-84a7-cfab8cf88efd.png)

You can view an interactable version [here](https://www.figma.com/proto/LsUgAu4mjLDsoBovxIQ1OR/SponsorBlock?node-id=3%3A22&scaling=min-zoom).

**Comment by ajayyy** [comment]
This looks nice! It makes it look a lot more standardized like other adblockers.

Do you have a plan on where to put the timestamp editing part?

**Comment by ajayyy** [comment]
Closing in favour of https://github.com/ajayyy/SponsorBlock/pull/440
