### ISSUE TITLE
Handle 409 duplicate errors when multiple segments are submitted and only one is a duplicate

### ISSUE THREAD

**Issue by joshinils** [ajayyy/SponsorBlock#1920]
I'd like for the window for editing segments that there be a hint which segment has already been submitted, if there are more than one segment open.
This would make it easier to delete that specific segment and upload the remaining, instead of blindly deleting segments hoping it was the right one (if it was only one).

I'd also like for non-submitted segments to be uploaded anyway, and for the upload not to abort and not upload any at all, is that a good idea?

**Comment by ajayyy** [comment]
I'm not sure I understand. Segments are automatically removed from that menu when they are submitted

**Comment by joshinils** [comment]
Ah, I mean when I get an error, then no segments are submitted.
I forget the exact wording, but it shows 'segment has already been submitted' and I have to submit it again after deleting the duplicate segment.

sometimes this happens after submitting a single segment fails and i create more and then try to submit them all again (including new ones). but then the previously failed segment has only failed on my end, but actually got through, so i locally still have a copy of it, which i need to remove before i can submit the remaining.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlockServer/commit/e041b9c9300d700918e94411c653b01e3cfd4075
