### ISSUE TITLE
Auto-Segment with llms!

### ISSUE THREAD

**Issue by fire17** [ajayyy/SponsorBlock#1921]
Hi guys
Let me start saying I love sponsorBlock very much and I regularly commit new segments 💜

It just dawned on me (while watching an ad and about to segment it) that obviously today we can easily get an llm to mark out sponsors. I mean you guys already have all the data (time stamps and labels) needed to finetune a model to perfection. Thou I'm pretty sure most models especially the main apis can do this out of the box. 

Wonder if you guys gave this a thought, and if so what is the status update? You can do a robust solution, but even an option for users to enter their api key and just query with the captions of the video when it is loaded. 

Wish to see this on ReVanced ❤️
Thx and all the best!

**Comment by ajayyy** [comment]
Captions are not accurate enough to work completely on their own, but there are automation discussions in the #automation channel on discord to discuss using these for other things such as moderation or helping to create submissions.

**Comment by fire17** [comment]
The quality of generation (depends on the model) is constantly improving and if would have access to data you guys already have it would be super easy to train to match the same output with high quality and accurate segents.


step 0: enable experimental segmenting
step 1: user opens video that is not yet segmented, (optional step) clicks on the sponsorblock shield icon
step 2: system asks big context llm, "are there any sponsors in this video? + {video captions}"
step 3: if respond is yes, use a smart prompt (including examples from real submitted data) that outputs from when to when there is a sponsor, and relvant category.
step 4: User sees the video immediately skip to the end of sponsor, and the user can to review / correct / submit the ai generated segments if they are good.

Once it gets good enough, i would not mind spending api credits to never watch another sponsor again, and helping the community.

I imagine this happening in reVanced, and in my opinion would make SponsorBlock 100 times better UX
@ajayyy hope you can reconsider and open this feature request, id love to help the the ai side of things

PS- do you have a ranking board of the channels with the most sponsors segments? 
all the best
