### ISSUE TITLE
Request:  Use local storage for settings, and not sync storage.

### ISSUE THREAD

**Issue by Git-Forked** [ajayyy/SponsorBlock#1925]
Please use local storage for settings, and not sync storage. 
Other add-ons have no issues doing this. 
This is the only add-on I've ever used that asked me to enable sync storage to save local settings. 
Using sync storage is a privacy hazard. 
Some people do not want to sync their settings on the "cloud" (someone else's computer).
Don't force people to give up privacy to use your extension.

**Comment by ajayyy** [comment]
#180 

My understanding is that if you enable sync storage, but don't actually log in, if doesn't sync anywhere
