### ISSUE TITLE
Feature request: better skip settings for specific channel

### ISSUE THREAD

**Issue by eirnym** [ajayyy/SponsorBlock#1926]
Currently given channel can be excluded completely or segments are marked, but never skipped (automatically or manually).

Please, improve local settings to make segments manually skippable when hey were "automatic skip". 

With this new setting all skippable segments become skippable only manually. Thus if a sponsor block I'm still able to skip it semi-automatically, but I'm able to listen such blocks if I'd like to.

New settings example:
* Channel can be completely excluded from downloading `sponsor block` segments. - currently implemented
* Skipping may be set to 3 levels:
  * **Skipping is turned off** - currently implemented
  * **Skipping settings are lowered** - new setting (automatic becomes manual, manual skip is .. still manual)
  * **Skipping is enabled as defined for all channels** - currently implemented
* global settings as they are currently

**Comment by ajayyy** [comment]
#435
