### ISSUE TITLE
[Enhancement] Ignored segments: Redemption™

### ISSUE THREAD

**Issue by aaronliu0130** [ajayyy/SponsorBlock#1927]
Randomly make ignored segments pop up, tell the user it was ignored, and ask the user if they think it's good a bit more prominently to maybe attract a few likes on the worthier segments

Since most segments never get likes, worthy segments get ignored quite a bit

**Comment by ajayyy** [comment]
Most downvoted segments are bad

**Comment by aaronliu0130** [comment]
Maybe an opt-in setting? I guess it's too risky to have everyone see them but the threshold being -2 makes it quite easy for segments to get buried if someone just downvotes a couple of other segments in the same video without watching them when one segment was bad
