### ISSUE TITLE
Bug: Badge on video disappears when hovering over a Short

### ISSUE THREAD

**Issue by avi12** [ajayyy/SponsorBlock#1928]
https://github.com/ajayyy/SponsorBlock/assets/6422804/899106f6-ec37-48a1-bb78-e6f66bf53bf7

Version: 5.4.28

**Comment by ajayyy** [comment]
This seems like the proper behavior. If you want to watch the video, you don't want a badge covering it

**Comment by avi12** [comment]
It doesn't happen with a regular video though

**Comment by avi12** [comment]
https://github.com/ajayyy/SponsorBlock/assets/6422804/ae545938-5638-49eb-88c6-2948bdcd699d
