### ISSUE TITLE
Feature Request: New category "skit"

### ISSUE THREAD

**Issue by KaiserSoft** [ajayyy/SponsorBlock#1929]
Recently funny skit segments have been classified as "Recap", "Sponsor" or "Intermission" even though they a funny skits in a video. 
Some people may not like them but they are neither a Recap, Intermission or a Sponsor. They are part of the video.
When I down vote I get "yelled" at by the UI and I have to manually click on "Continue voting" to stop the segment from being skipped.

Please add a new category for people who don't like to see this type of content. Thanks

Latest example: https://www.youtube.com/watch?v=s2j_h2jizSE 

The entire skit was flagged as "Intermission".

**Comment by ajayyy** [comment]
Only the intro is labeled, not the skit
