### ISSUE TITLE
Mirror sqlite database locally

### ISSUE THREAD

**Issue by WebFreak001** [ajayyy/SponsorBlock#193]
to preserve anonymity while using this extension it would be great if the whole database would be mirrored locally by the extension and then lookups were done on the local database instead of using an endpoint sending the video id for each watched video.

To save bandwidth on synchronization the server could offer an endpoint giving updates or changes since a specified timestamp. If entries in the DB are never modified and only appended this is a trivial change but otherwise would require some engineering.

Maybe at least locally having a simple list of only all video IDs in the DB first would save a lot of requests. The extension could then only do a network request to look up the sponsorship times when a video with the given ID is found in the local list. Additionally to that it could be combined with ajayyy/SponsorBlockServer#25. This could also be stored with less memory usage.

see also: #137

**Comment by ajayyy** [comment]
See https://github.com/ajayyy/SponsorBlock/issues/161.
AKA, only use local DB for older videos to keep real-time behavior.

**Comment by ajayyy** [comment]
https://github.com/Synthetica9/sponsorblock-dbdiff

**Comment by ajayyy** [comment]
sb-mirror
