### ISSUE TITLE
Low storage limit for unsubmitted segments, and silent failures when reached

### ISSUE THREAD

**Issue by JH2535** [ajayyy/SponsorBlock#1933]
Sometimes when listening to music I record a segment to be skipped. I don't submit it because usually it gets downvoted and removed. (I also don't enable the "Non-Music Section" as sometimes they aren't cut perfectly, or cut out parts that I feel are important)

I like that it could automatically skip the segment for me (without submitting).  This has worked for a while but I've noticed the segments I've been recording which haven't been submitted have started to vanish.

edit: I'm using firefox - and after some testing it looks like the segment is being added to options > backup/restore > show segments so long as there are less than 56 unsubmitted segments. When I add a 57th it doesn't store but it does persist in ram. If I close firefox and re-open the 57th segment is gone (the rest are still there).

I tried removing one of the segments down to 55, and then adding a new 56th one and it does add to the list (the new 56th one does persist after restarting firefox). There is something funky going on.

**Comment by ajayyy** [comment]
Right now it uses the browser extension sync storage which has a small limit

**Comment by JH2535** [comment]
Are there plans to allow us to give you "unlimitedStorage" permissions? As seen here https://developer.chrome.com/docs/extensions/reference/api/storage (I don't know if I linked the right docs, I saw chrome.storage used a lot in the config, unsure what goes on withe firefox)

**Comment by ajayyy** [comment]
First the storage would need to be moved to local storage instead of sync
