### ISSUE TITLE
Sponsor don't skipped.

### ISSUE THREAD

**Issue by gut1414** [ajayyy/SponsorBlock#1939]
See here (sponsored video with another previous element in start of video): https://www.youtube.com/watch?v=QjvdasWysAk

I noticed a bug with SponsorBlock, at least on Google Chrome, but it is possible elsewhere.

I noticed that the segments that I want to skip, for example, a sponsor, do not skip automatically, because there is another segment, manually skipped just before.

If a manually skipped segment immediately precedes another segment that can be skipped automatically, the following element does not skip automatically, which is why I took on the sponsorship of this video (which is unpleasant, for a well-known VPN).

The only solution was to put the previous segment, and, therefore, all similar segments, in automatic jump (I had to configure an automatic jump for the summary elements, to better watch this video).

**Comment by omaralwardian** [comment]
Same problem. Sponsor block fully enabled to skip everything except highlights and no segments appearing in seek bar, no skipping of segments and now it says API timeout.

**Comment by PasttaTypo** [comment]
In case some of you don't know, you can skip to the end of a segment if auto-skip doesn't work using CTRL + Right Arrow. Also works for navigating chapters (both sponsorblock & description), for some reason YT doesn't list this in their [keyboard shortcut list.](https://support.google.com/youtube/answer/7631406?hl=en) 🤷‍♂️

**Comment by ajayyy** [comment]
Closing for now, can reopen if still an issue
