### ISSUE TITLE
Submit not possible

### ISSUE THREAD

**Issue by stijnb1234** [ajayyy/SponsorBlock#1942]
Get error 502 server seems overloaded when trying to submit.

**Comment by Scotty-Trees** [comment]
Just tried to submit my first one and ran into this error as well on Firefox v121 on Fedora 39 Gnome running v5.4.29 of Sponsorblock. Check the server status page, everything is fine and green, but still unable to submit. Please help Obi Wan Kenobi, you're our only hope. 

```
 Error Code: 500

Check status.sponsor.ajay.app for server status.
```

**Comment by sonnenfell** [comment]
Error code 503 - https://status.sponsor.ajay.app/ shows no problems

<img width="483" height="308" alt="Image" src="https://github.com/user-attachments/assets/ee599b5e-e247-4776-8c6e-e228911fc768" />
