### ISSUE TITLE
[suggestion] Seperate category for sponsors that also have relevant information

### ISSUE THREAD

**Issue by thepwrtank18** [ajayyy/SponsorBlock#1945]
For example: https://youtu.be/UdEELggaY5Q?t=1070

The sponsor here, AnyDesk, has actively partnered with the YouTube channel to help him with his cause, and the Sponsor segment explains how they helped. While it is sponsored, the contents of that segment is relevant to the video in question.

If there's a separate category for those sponsors, you can choose to not auto-skip those types of sponsors, for example.

**Comment by ajayyy** [comment]
Full video label
