### ISSUE TITLE
Sponsorblock not working on the mobile version of youtube (m.youtube.com)

### ISSUE THREAD

**Issue by mckellenjaundice122** [ajayyy/SponsorBlock#1947]
I have tested on two android devices plus the mobile site on PC, and i can confirm sponsorblock refuses to show up or skip segments while using the mobile site. On android i have tested using two browsers, kiwi browser and firefox, both of them have the same result, the highlight button does not show up, neither do the segments in the seek bar or auto-skipping working. 

Both android devices are up to date with both their browsers and OS, android 12 and 13 respectively. On an additional note, if i attempt to turn off and on the extension while on the video page on mobile, i am only able to get this glitch shown in this screenshot, which is the only sign of life i can get from sponsorblock on the mobile site. I would also like to add that the extension works on both devices if i use the desktop version of youtube, but it is much more cumbersome and difficult to use than (m.youtube.com)

First screenshot is the glitch in question from above.
Second screenshot is what the seekbar should look like, and the way it displays and functions properly on the desktop version of the site.
Third screenshot is what sponsorblock looks like on the mobile site. Nothing at all is shown from the extension.

![Screenshot_20240109-155243~2](https://github.com/ajayyy/SponsorBlock/assets/143659680/d81e5c2c-8cb1-4e97-9d88-30082b1bd4f1)
![Screenshot 2024-01-09 155843](https://github.com/ajayyy/SponsorBlock/assets/143659680/6470e13e-d024-459d-af58-1f0743be0a45)
![Screenshot 2024-01-09 155818](https://github.com/ajayyy/SponsorBlock/assets/143659680/e1b80ed1-7617-4d85-ae67-ebe133cdadf0)

**Comment by whindsaks** [comment]
Now broken again?

**Comment by ajayyy** [comment]
@whindsaks in which way?

**Comment by whindsaks** [comment]
> in which way?

While it seems to paint the progressbar, there are no controls to add segments etc.

**Comment by ajayyy** [comment]
@whindsaks submitting segments in not supported on mobile
