### ISSUE TITLE
Database down

### ISSUE THREAD

**Issue by TTSKarlsson** [ajayyy/SponsorBlock#1953]
https://sponsor.ajay.app/database seems to be down (error codes 500/504/cloudflare archive), are there redundancy in the form of other addresses?

This is not a feature request.

**Comment by skorphil** [comment]
Yeah, plugin not working

**Comment by ne0rrmatrix** [comment]
It does not work on chrome for me. Went and checked on firefox which works fine. Sponsor block is also not working in patched youtube app on android and revanced youtube app is also having issues. 504 errors on any chrome browser.

**Comment by pixelnull** [comment]
> It does not work on chrome for me. Went and checked on firefox which works fine. Sponsor block is also not working in patched youtube app on android and revanced youtube app is also having issues. 504 errors on any chrome browser.

504 in firefox and ajay.app was down but looks ok now

**Comment by elgntfx** [comment]
> It does not work on chrome for me. Went and checked on firefox which works fine. Sponsor block is also not working in patched youtube app on android and revanced youtube app is also having issues. 504 errors on any chrome browser.

firefox v.121.0.1
SponsorBlock v5.4.29
doesn't work

**Comment by RomeoAlphaEkko** [comment]
not working, 
chromeVersion 120.0.6099.217 (Offizieller Build) (64-Bit)
SponsorBlock v. 5.4.28

**Comment by somewhat69** [comment]
not working here too on yt revanced and browser

**Comment by feeebl** [comment]
Same problem here, Firefox 120.0.1 on Windows 11.

**Comment by everypizza1** [comment]
Also getting an error on Revanced

**Comment by nokia8801** [comment]
Can also confirm it is not working here.

- Firefox 121.0.1 with SponsorBlock 5.4.29
- mpv v0.37.0 with [mpv-sponsorblock](https://github.com/TheCactusVert/mpv-sponsorblock) v2.0.0

**Comment by inobrevi** [comment]
It would be nice to have an docker image that would take care of that. And/or maybe a P2P solution?

**Comment by ZongerX** [comment]
Opera GX 
LVL5 (core: 105.0.4970.76)|
Not working too. Code 503

Seems like server is down, maybe someone ddos plugin?
