### ISSUE TITLE
Bad automatic video quality with Sponsorblock enabled

### ISSUE THREAD

**Issue by MrKoddy** [ajayyy/SponsorBlock#1956]
Hello,

After noticing that my YouTube videos always defaulted to 480p or 360p, I started looking into why. I tried it in private browsing without Sponsorblock activated, and YouTube in automatic mode detected 720p automatically in small player and full HD or QHD in full screen automatically.

The extension is therefore causing problems in YouTube's automatic video quality selection.

**Comment by ajayyy** [comment]
That test does not confirm it is SponsorBlock causing it. It could be an a/b test or something associated with your account cookies.

**Comment by MrKoddy** [comment]
It is the only one extension which does this issue. In private browsing it is the only extension I disabled so I can test the automatic quality video of YouTube

**Comment by ajayyy** [comment]
As explained previously, you have to test on your main profile

**Comment by MrKoddy** [comment]
Indeed it is not sponsorblock my bad, another google extension which has nothing to do with YouTube
