### ISSUE TITLE
issue with preview requirement and endcards/credits submission while in queue/playlist

### ISSUE THREAD

**Issue by cracklingice** [ajayyy/SponsorBlock#1959]
When attempting to submit an endcards/credits submission in a queue, the preview requirement causes the next video to start playback, resulting in it being impossible to submit this type while in the queue.

**Comment by PasttaTypo** [comment]
You can **loop** the video (right click YT video then "loop" in pop-up) to prevent YouTube from jumping to the next video at the end.

_Neat YT Tip: Looping is useful for the Watch Later feature, so once you're done watching for the time, you can choose the "remove watched videos" option without it removing a video that auto-started that was counted as "watched"._

**Comment by cracklingice** [comment]
Thank you for the workaround.  As an in code fix, I would propose if preview = ture and segment end = video end then pause video instead of skip.
