### ISSUE TITLE
Options - Disabled options impossible to enable

### ISSUE THREAD

**Issue by nathanbrauer** [ajayyy/SponsorBlock#1960]
## Platform:

- Windows 11
- Chrome Version 120.0.6099.225 (Official Build) (64-bit)
- SponsorBlock v. 5.5.1

## Steps to reproduce:

1. Install fresh new instance of SponsorBlock (or uninstall, then reinstall)
2. Open Options page (`chrome-extension://mnjggcdmjocbbbhaepdhchncahnbgone/options/options.html`)
3. Note defaults: "Sponsor" set to "Auto Skip" and "Unpaid/Self Promotion" set to "Disable"
4. Change the following....
    1. "Sponsor" to "Disable"
    2. "Unpaid/Self Promotion" set to "Manual Skip"
5. Refresh Options page
6. ## Actual results:
    1. "Sponsor" is set to "Disable"
    2. "Unpaid/Self Promotion" is set to "Disable"
7. Change 
    1. "Sponsor" to "Manual Skip"
    2. "Unpaid/Self Promotion" set to "Auto Skip"
8. Refresh Options page
9. ## Actual results:
    1. "Sponsor" is still set to "Disable"
    2. "Unpaid/Self Promotion" is still set to "Disable"

**Comment by nathanbrauer** [comment]
I see this might be fixed in 5.5.2 (c996680a585a2c8e8a9bbebf841e70b884c7f063), not yet available in the Chrome Web Store....

**Comment by ajayyy** [comment]
Yep, please wait for Google to review it
