### ISSUE TITLE
Add "Phobia" tag for segments with common phobias, like arachnophobia or needles.

### ISSUE THREAD

**Issue by EthanBnntt** [ajayyy/SponsorBlock#1965]
I think it would be really neat if we could filter out common phobias. Just an idea, though.

**Comment by 71256988** [comment]
Feels rather out of scope for this project, in my opinion.

I think making a separate addon for various phobias would be a better solution instead, since 98% of the code for this project could easily be repurposed for that rather than adding a brand new category useful to relatively few users.
