### ISSUE TITLE
SponsorBlock no longer works after I installed DeArrow

### ISSUE THREAD

**Issue by minihoot** [ajayyy/SponsorBlock#1971]
Ever since I installed DeArrow, SponsorBlock hasn't been working and opening it just shows this.
![image](https://github.com/ajayyy/SponsorBlock/assets/70825884/88608b52-24f3-4816-addd-e446d7f947d7)

**Comment by ajayyy** [comment]
This is an issue with the browser somehow corrupting the extension files. Uninstalling and reinstalling should fix it

**Comment by minihoot** [comment]
ok, thanks
