### ISSUE TITLE
iSponsorblock (uYouEnhanced) "Hide Start/End Button in Video Player" what does this do?

### ISSUE THREAD

**Issue by hi-im-karma** [ajayyy/SponsorBlock#1973]
What does this do? I have enabled and disabled it and don’t notice what is changing. Someone mind explaining it please?
![image](https://github.com/ajayyy/SponsorBlock/assets/73917917/5c04add9-867f-4264-a135-3883f6caa9d5)

**Comment by ajayyy** [comment]
This repo is about the browser extension
