### ISSUE TITLE
Successfully submitting segments at videos don't reflect update.

### ISSUE THREAD

**Issue by omaralwardian** [ajayyy/SponsorBlock#1976]
I just noticed right now.

 I submitted a segment of sponsored content in a video after I made the adjustments and reviewed, then made the submission, and I received the toast saying that it was successfully submitted.

I went back about 10 minutes later and rewatched the video for another reason and noticed that the segment still appeared and was not highlighted in the seat bar nor was it automatically skipped as I haven't set up in Youtube-ReX. 

The submission even is reflected in my total amount of submissions on the sponsorblock details area in the application.

Any idea why this may be the case? Let me know if you need further details I am happy to provide anything I can. Thanks.

**Comment by HanYaodong** [comment]
You can use this site: [https://sb.ltn.fi/](https://sb.ltn.fi/) to check if you submission is indeed saved to the database or not.
