### ISSUE TITLE
Not skipping/muting segments, despite showing the popup saying it has done so.

### ISSUE THREAD

**Issue by moosetwin0** [ajayyy/SponsorBlock#1978]
This has been happening on and off for at least a week:

I apologize for not being able to get a video recording of this, but when I took this screenshot, audio was still playing despite it saying that it was muted.

![image](https://github.com/ajayyy/SponsorBlock/assets/82544732/b70ac596-112f-462c-ba71-2e676cffcbb3)

This has also happened for segments when they were supposed to be skipped, where it just plays them despite showing the popup.

This is happening on the Firefox browser, extension version 5.5.5 (latest one on the Firefox Add-Ons page)

Extensions list:
- DeArrow
- SponsorBlock (duh)
- Return Youtube Dislike
- Hide shorts for Youtube
- uBlock Origin
- DuckDuckGo Privacy Essentials

**Comment by moosetwin0** [comment]
It's happened again:
![image](https://github.com/ajayyy/SponsorBlock/assets/82544732/8eb63c69-3c52-4652-90f3-def79552058f)

**Comment by ajayyy** [comment]
Try taking a backup, then fully resetting settings

**Comment by moosetwin0** [comment]
> Try taking a backup, then fully resetting settings. Also make sure "Force Channel Check Before Skipping" is off.

I'll try that, and re-open the issue if it persists. Thanks!
