### ISSUE TITLE
[Visual] Height/Width of SB Popup on Watch Page

### ISSUE THREAD

**Issue by PasttaTypo** [ajayyy/SponsorBlock#1980]
### In SponsorBlock settings I've set Hide Clutter in Segment List Popup: _On_. 

><img src="https://github.com/ajayyy/SponsorBlock/assets/125756085/a521b623-0d3d-4cbf-b08b-a17156889605" width="200" />
>
 >Expected result: On the watch page, the height of the pop-up should resize down to hide empty space.

><img src="https://github.com/ajayyy/SponsorBlock/assets/125756085/d25ec08e-940e-49a4-903f-b1c53dcb2b70" width="200" />
>
>How it looks: (this issue doesn't apply to the pop-up by clicking the extension button near the address bar on Chromium browsers)

Also, the width property isn't filling the length of the container to match other YT sidebar elements, Changing the width from its default 374px value to 100% looks a lot better.

**Comment by ajayyy** [comment]
Because it is using an iframe to render now, I'm not sure if there is a good way to fix the height issue unfortunately

**Comment by PasttaTypo** [comment]
closing the issue cause ajayyy too busy watching vimeo to close it himself

**Comment by ajayyy** [comment]
Still good to have open imo
