### ISSUE TITLE
Not blocking...

### ISSUE THREAD

**Issue by YesTrustMe** [ajayyy/SponsorBlock#1981]
I love SB but it's not blocking YouTube ads/sponsors on many YT sites these days especially in Asia. For instance, the creator is promoting a VPN provider in the middle or near the end of the media. Here is just one of many YT creators who's doing this: https://www.youtube.com/watch?v=yfxDkzXVJeg

This occurring with YT on all Windows browsers and also on Android/Firestick devices via SmartTube player.

If you can fix or provide a workaround, that would be helpful. Please and thank you.

**Comment by HanYaodong** [comment]
SB里所有跳过的片段都是用户标记的（播放器里的下面的小按钮），而不是系统自动生成的。只能说汉语的sponsor block用户还是太少了，200k播放都没有人标记。
