### ISSUE TITLE
Sponsorblock automatically voting without any consent or action from the user

### ISSUE THREAD

**Issue by MilesFarber** [ajayyy/SponsorBlock#1984]
![image](https://github.com/ajayyy/SponsorBlock/assets/24918282/257bca8d-6b2c-4e5c-a4b4-84e7236c47df)

There is no way to undo the vote either. I don't even know WHAT it voted.

**Comment by ajayyy** [comment]
Looks like you accidentally pressed the vote button

**Comment by MilesFarber** [comment]
"Hey your extension did something even though i didn't press anything, how do i fix this?"
"Looks like you pressed something"
"k"

**Comment by ajayyy** [comment]
Please provide reproducible instructions
