### ISSUE TITLE
[Feature] See your submitted segments and filter by SponsorBlock Marker in Backup/Restore

### ISSUE THREAD

**Issue by Loading617** [ajayyy/SponsorBlock#1987]
I would love to see when you would go in the backup/restore section in SponsorBlock to view your segments by SponsorBlock Markers and Submitted Segments

**Comment by ajayyy** [comment]
Check out https://sb.ltn.fi/

You can get your userID by clicking the clipboard button next to your username in the popup

![image](https://github.com/ajayyy/SponsorBlock/assets/12688112/eea4406e-5983-4349-95a0-75e984d2af6d)
