### ISSUE TITLE
Feature request: {Synergy with HARPA AI | integrate AI in SponsorBlock} to automate time range detection

### ISSUE THREAD

**Issue by andraz** [ajayyy/SponsorBlock#1989]
As you can see from the image, the AI has successfully identified the precise start and stop timestamps for the sponsor clip. This is truly remarkable and opens up a world of possibilities for SponsorBlock. By integrating this feature directly into the extension, we could streamline the submission process and make it even more efficient.

![image](https://github.com/ajayyy/SponsorBlock/assets/8480981/944368fd-f7e7-41ad-979d-1cef73785635)

Imagine this: as soon as SponsorBlock detects a fresh video with 0 segments in the database, SponsorBlock could automatically analyze the transcript using AI, preemptively detecting potential sponsor segments before the first user submission. This would prompt SponsorBlock users to perform a quick sanity check, verifying the accuracy of the detected sponsor.

If the detection is correct, they can then submit the timestamps for the benefit of the entire community. Not only would this save time for the submitter, but it would also ensure that sponsors are skipped for the submitter itself.

But why stop there? With further development and fine-tuning of the AI prompts, we could potentially detect a wide range of other segments that users might want to skip, such as self-promotion, long rambling intros, extended pauses, off-topic tangents, user engagement tricks, Patreon thanks, outros, etc...

I firmly believe that this idea has the potential to take SponsorBlock to new heights. By harnessing the capabilities of AI and integrating it seamlessly into the extension, we can create a more engaging, efficient, and user-friendly experience for our entire community.

**Comment by ajayyy** [comment]
Did you just chatgpt your issue 💀 

no, we need segments to be precise to audio
