### ISSUE TITLE
502/504 error on particular video

### ISSUE THREAD

**Issue by SanariSan** [ajayyy/SponsorBlock#1991]
I'm getting 502 and 504 errors, but only on this particular Mehdi's video. Has asked a friend of mine to check and he also reports the same behavior. Other videos getting segments as usual. 

https://www.youtube.com/watch?v=1EPx9slOH1A

![image](https://github.com/ajayyy/SponsorBlock/assets/76019273/5f858afc-97f7-40de-86c8-393e8c4e630a)
![image](https://github.com/ajayyy/SponsorBlock/assets/76019273/579f97df-f483-4cc1-b6da-908c1841d18c)

**Comment by enduro** [comment]
Confirm. Here is another video: https://www.youtube.com/watch?v=3VzC50RSiL0
Mac M1, Brave Browser

**Comment by ajayyy** [comment]
thanks for reporting. Should be fixed now

SB now does sharding based on the video ID, so the server that was assigned to those specific videos wasn't working

**Comment by c-bejar** [comment]
I'm getting the same error on this video here:
https://www.youtube.com/watch?v=hRzIZZoKrxE

**Comment by kotarou3** [comment]
I also got a 504 for https://www.youtube.com/watch?v=504iV6_BCRE, as well as a cloudflare 504 when trying to visit https://sponsor.ajay.app/ directly

**Comment by ajayyy** [comment]
Should be fixed
