### ISSUE TITLE
error code  504 

### ISSUE THREAD

**Issue by rtzon59** [ajayyy/SponsorBlock#1998]
getting this error just in the recent hours from youtube

**Comment by lucassilvas1** [comment]
I'm getting 502 instead:
![image](https://github.com/ajayyy/SponsorBlock/assets/52336985/81a1dbf8-db09-4fbb-8232-266662513e59)

**Comment by SanariSan** [comment]
same here, for example this video
https://www.youtube.com/watch?v=pPeCNrNTr3k

**Comment by rtzon59** [comment]
service is up again

**Comment by Timmyfox** [comment]
Still down for me. Mostly getting 504 errors but also the occasional 503.

**Comment by DannyDarth** [comment]
Been down for the 2nd day now for me same error code 504.

**Comment by qawasx** [comment]
Its down as usual. Its always down weekends. and most weekdays too.

**Comment by iripu** [comment]
I am also getting this constantly day and night. Thinking about not submitting anymore and hide the buttons.

**Comment by Trolann** [comment]
From discord:
![image](https://github.com/ajayyy/SponsorBlock/assets/72931206/575105b3-7194-4329-a649-44ed450674a3)

**Comment by qawasx** [comment]
what a lazy ass dev lol

**Comment by iolqc** [comment]
+1

**Comment by magizhchi99** [comment]
> what a lazy ass dev lol

Something you're using for free BTW. Beggars can't be choosers.

**Comment by StateofDisarray** [comment]
> what a lazy ass dev lol

entitlement issues aside, this comment gives me an idea. the dev could introduce a premium tier that runs on a separate instance with more reliability and higher bandwith etc, which could cost a some dollars a month, alongside the free tier. and then the people who submit reliable sponsorship info could get access to the premium tier for a duration or whatever. the only difference would be that you'd just have faster dev support if something goes wrong, and you'd contribute something for the value youre getting.

not only would they get some monetary compensation for their work, but we would also avoid issues like the servers going down for a day

Idk about y'all, but this thing is definitely worth a subscription for me.

**Comment by loopeey** [comment]
Thats troll, he works for a vpn marketing.

Anyway 502-503 is on a video for an hour now.

**Comment by NicoTheCinderace** [comment]
> what a lazy ass dev lol

Alright then, let's see **you** try and maintain a similar sort of app for days on end.

**Comment by pijcab** [comment]
Error 502 here too, saw the discord update from ajay tho.

It's all good we will wait like adults  👍

**Comment by ajayyy** [comment]
finally, peace

thanks for your patience :)

there are still some intermittent issues I'll look into soon

![image](https://github.com/ajayyy/SponsorBlock/assets/12688112/09d1c5fc-589f-4bee-a8e6-7cfdd45ab55a)
