### ISSUE TITLE
"No youtube video found" error.

### ISSUE THREAD

**Issue by Evonos** [ajayyy/SponsorBlock#1999]
on this video https://www.youtube.com/watch?v=OiWRoeeiQCQ

I get a "No youtube video found" error in the extension
on microsoft edge version 5.5.9 of sponsorblock.

**Comment by iolqc** [comment]
same I get a "No youtube video found" error in the extension, i refreshed the page with F5 and then pressed refresh arrow on the extention on chrome and got the message "A connection error has occurred. Error code: 503" so i guess its a server problem right?

**Comment by tamamo-chan** [comment]
Same, however, I received error code 502 instead.

**Comment by NickAcPT** [comment]
It seems that the server is returning ```Bad Gateway: Could not connect to backend``` for many of the endpoints not cached by cloudflare.

**Comment by Trolann** [comment]
see #1998
