### ISSUE TITLE
API returning 502.

### ISSUE THREAD

**Issue by shubham399** [ajayyy/SponsorBlock#2001]
Is there a downtime of the server?

```
curl https://sponsor.ajay.app/api/skipSegments\?videoID\=f1f7pcKDCMI

```
<img width="733" alt="image" src="https://github.com/ajayyy/SponsorBlock/assets/17530162/70a586dc-25a6-4387-8ec2-d3d45f47f4df">

<img width="896" alt="image" src="https://github.com/ajayyy/SponsorBlock/assets/17530162/708ed78b-6072-4e8e-b0cf-9b73f276130e">

**Comment by edmunek** [comment]
also, any chance that once uploading failed, it would remember the fragment so it could be uploaded once the server is back online (instead of trying to mark the fragment to miliseconds again?)
