### ISSUE TITLE
'Preview' submission button should ignore submitter's personal preference, if set to 'Manual', 'Show' or 'Disabled', so that intended Skip can be correctly previewed.

### ISSUE THREAD

**Issue by mamapapaxp** [ajayyy/SponsorBlock#2002]
My personal preference, as a frequent submitter, is to upvote and strengthen my fellow cohort's submissions - when accurately timed and labelled.
Consequently, unless the segment is a regular, expected chunk of a channel's video output (in which case I naturally quickly hit the manual 'Skip' button, per my preference) then I actually wait to see if the segment is indeed as titled and of 'approximately' correct length. (What happens if it isn't is a separate issue that I wish the devs would provide a solution for, as downvoting or changing the category does not seem to be in any way slowing down the mammoth pace of bad submissions, but I digress.  :)

The problem is that when I am the one doing the submitting, the brilliant 'Inspect' button works wonderfully - allowing the frame perfect selection of the BEGINNING of a segment - but the 'Preview' button is respecting my personal playback preference, and not skipping from the start point to the end point of the submission unless I briefly pop into SponsorBlock's settings and change them back to the default. This, of course, has to be un-done after submission and then repeated the next time I come to submit...

This could be remedied by making the 'Preview' button work in a fixed 'Skip' (or 'Mute' or 'Full Video', as selected) mode, without respecting or even checking the submitter's playback preference.

**Comment by ajayyy** [comment]
This sounds like a bug. It is supposed to always auto skip unsubmitted segments

**Comment by mamapapaxp** [comment]
Odd, I just submitted three segments at once and I didn't notice that the first segment DID indeed correctly skip... and so did the third! It is definitely glitching (now that you have confirmed it is intended to do it, I can safely use the term) on the second one however.

(Side note, I must be going 'snow-blind' from the repeated submission process, if I only notice when it glitches and not when it is working properly. Ouch.)

If it is working as expected for you, in a similar 2 or 3+ segment situation, I will update browser and addons, etc. and try again.

I try to avoid Chrome updates as long as possible to give other addon devs the time to work around whatever G**gle deliberately broke this time. (poor uBlock Origin and YouTube Auto Like immediately comes to mind.)
