### ISSUE TITLE
SponsorBlock not working on Youtube. Cannot identify video. Not blocking sponsors.

### ISSUE THREAD

**Issue by ScarletMcLearn** [ajayyy/SponsorBlock#2006]
Not working on Youtube. Cannot identify video.

![image](https://github.com/ajayyy/SponsorBlock/assets/17823921/0dc01640-20c1-48c7-b2ee-ee105a022e01)

https://pasteboard.co/b6Ym9L7dIqiL.png

**Comment by Leah96xxx** [comment]
Confirmed I also have this issue. Refreshing the tab does nothing, and refreshing the extension will find the video but fail to skip sponsors.

**Comment by ajayyy** [comment]
still doing this?

**Comment by PasttaTypo** [comment]
> still doing this?

Yeh, I've had a few 504 Connection Errors and segments not loading in after refreshing randomly. I do know my submissions haven't been visible on the SB Browser since yesterday.

**Comment by ajayyy** [comment]
504 is different, I mean it saying "No video found"

**Comment by Leah96xxx** [comment]
Still saying "No video found" for me. Extension appears to be up to date

**Comment by ajayyy** [comment]
Is this a new issue, or did you recently install the extension?

**Comment by Leah96xxx** [comment]
It's a new issue. I've had Sponsor Block installed for months.

Just restarted my browser altogether and it seems to be fixed now.

**Comment by ScarletMcLearn** [comment]
I restarted my browser - Edge, Chrome - but still not fixed.

**Comment by BigBOSSo** [comment]
Same thing for a few days. Google chrome

![image](https://github.com/ajayyy/SponsorBlock/assets/19314407/70ee6ce2-8a30-4466-822c-84f969262c00)

**Comment by ScarletMcLearn** [comment]
Same here. No change.

**Comment by ajayyy** [comment]
>  I've had a few 504 Connection Errors

This is different and is a server issue

**Comment by ScarletMcLearn** [comment]
This is still not working

**Comment by itsmevictor** [comment]
I have the same issue: "Segments still loading". 

Otherwise, thank you for the great extension :-)
