### ISSUE TITLE
(Bug) Videos skipping 5 seconds ahead, even if there are no SponsorBlock segments associated with it

### ISSUE THREAD

**Issue by raw-binary** [ajayyy/SponsorBlock#2007]
I've had an issue on Desktop for a few months now that happens whenever SponsorBlock is enabled. On some random videos, there is a chance that the video skips forward by 5 seconds, usually happening near the start of the video. There are no SponsorBlock segments associated to those sections whatsoever, and their content is normal and doesn't warrant skipping. It even happens on videos that don't have any marked segments at all.
What's annoying is that attempting to rewind back 5 seconds to the section it skipped will usually result in the video freezing on that timestamp and not buffer at all (or get stuck in an infinite loading cycle), or just skip ahead 5 seconds anyway.

**Comment by ajayyy** [comment]
Are you sure this is not YouTube remembering your last playback position?

**Comment by raw-binary** [comment]
I'm sure. It happens on videos that I have not watched before.

**Comment by WD40andTape** [comment]
I can confirm this bug. Sometimes it won't happen for a week, and sometimes it'll break the whole Youtube experience and I'm forced to disable the addon.

Let me know how I can help collect debugging information next time it occurs. Firefox 125.0.3 64-bit, Windows 11 Pro 64-bit Version 10.0.22631 Build 22631.

**Comment by ExNought** [comment]
I also seem to have an issue, I can only guess is this one. This seems to happen more if the video has chapters. But also really inconsistent. Currently I suspect a combination of those chapter marks and something happening with streaming from yt, as I noticed the buffer not continuing before this happens.


Firefox 126.0 (32Bit) with Sponsorblock 5.5.9 and honestly a bunch more addons like ublock and umatrix

**Comment by ExNought** [comment]
I am quite confident this is NOT caused by your addon at the moment. I used YT without your plugin since my last post and while I saw a reduced amount of the stated issues, they are not gone! So I am currently suspect that the algorithm has an issue with Firefox, as this seems limited to that browser (e.g. my Brave works well too)

**Comment by WD40andTape** [comment]
Perhaps an adblocker issue, given YouTube's increasingly aggressive adblocker detection? Has anyone experienced this who does _not_ use an adblocker?

**Comment by ExNought** [comment]
Actually I do. On YT I have Adblock disabled since I am one of those few people paying :)

I disabled uMatrix and Privacy Badger right now and look how it develops. Anyway I am still pretty sure this isn't SponsorBlock.

**Comment by WD40andTape** [comment]
Seems like a Firefox issue:

https://reddit.com/r/firefox/comments/18ataow/youtube_videos_are_slowly_becoming_unwatchable_in/
https://reddit.com/r/firefox/comments/17bhudb/constant_buffering_freezing_on_youtube_with/k5t8no4/

And from my personal experience, I'll consistently have this problem with a video, but switching to Chrome (also with uBlock Origin and SponsorBlock) solves it.

In my opinion, this can now be closed @ajayyy.
