### ISSUE TITLE
explain file in database ?

### ISSUE THREAD

**Issue by Rexadev** [ajayyy/SponsorBlock#2008]
https://sb.ltn.fi/database/ - 

Index of /database/
~[../](https://sb.ltn.fi/)~
~[LICENSE](https://sb.ltn.fi/database/LICENSE)                                            21-Jan-2022 14:53                 282~
~[LICENSE.txt](https://sb.ltn.fi/database/LICENSE.txt)                                        21-Jan-2022 14:53                 282~
[categoryVotes.csv](https://sb.ltn.fi/database/categoryVotes.csv)                                  20-Apr-2024 06:41            37372773
[lockCategories.csv](https://sb.ltn.fi/database/lockCategories.csv)                                 20-Apr-2024 06:41            23985408
[ratings.csv](https://sb.ltn.fi/database/ratings.csv)                                        20-Apr-2024 06:41              924650
[sponsorTimes.csv](https://sb.ltn.fi/database/sponsorTimes.csv)                                   20-Apr-2024 06:41          5737989345
~[thumbnailTimestamps.csv](https://sb.ltn.fi/database/thumbnailTimestamps.csv)                            20-Apr-2024 06:41             2836067~
~[thumbnailVotes.csv](https://sb.ltn.fi/database/thumbnailVotes.csv)                                 20-Apr-2024 06:41             3334286~
~[thumbnails.csv](https://sb.ltn.fi/database/thumbnails.csv)                                     20-Apr-2024 06:41            14390329~
~[titleVotes.csv](https://sb.ltn.fi/database/titleVotes.csv)                                     20-Apr-2024 06:41             7035253~
~[titles.csv](https://sb.ltn.fi/database/titles.csv)                                         20-Apr-2024 06:41            36575046~
[unlistedVideos.csv](https://sb.ltn.fi/database/unlistedVideos.csv)                                 20-Apr-2024 06:41             6468526
[userNames.csv](https://sb.ltn.fi/database/userNames.csv)                                      20-Apr-2024 06:41            30257903
[videoInfo.csv](https://sb.ltn.fi/database/videoInfo.csv)                                      20-Apr-2024 06:41           745143275
[vipUsers.csv](https://sb.ltn.fi/database/vipUsers.csv)                                       20-Apr-2024 06:41                7092
[warnings.csv](https://sb.ltn.fi/database/warnings.csv)                                       20-Apr-2024 06:41              894142

These are for DeArrow

1. [thumbnails.csv](https://sb.ltn.fi/database/thumbnails.csv)
2. [thumbnailVotes.csv](https://sb.ltn.fi/database/thumbnailVotes.csv)
3. [thumbnailTimestamps.csv](https://sb.ltn.fi/database/thumbnailTimestamps.csv)
4. [titleVotes.csv](https://sb.ltn.fi/database/titleVotes.csv) 
5. [titles.csv](https://sb.ltn.fi/database/titles.csv)

**Comment by Rexadev** [comment]
thumbnails.csv
[thumbnailVotes.csv](https://sb.ltn.fi/database/thumbnailVotes.csv)
[thumbnailTimestamps.csv](https://sb.ltn.fi/database/thumbnailTimestamps.csv)
[titleVotes.csv](https://sb.ltn.fi/database/titleVotes.csv) 20-Apr-2024 06:41 7035253
[titles.csv](https://sb.ltn.fi/database/titles.csv)

**Comment by ajayyy** [comment]
What's the issue?

**Comment by ajayyy** [comment]
If you are looking for segments for specific videos, use sponsorTimes.csv

The other ones aren't needed in most cases

**Comment by Rexadev** [comment]
@ajayyy I want to know what those files are for ?

**Comment by HanYaodong** [comment]
> @ajayyy I want to know what those files are for ?

If you want others to answer your question, you should ask nicely...
