### ISSUE TITLE
Sponsorblock 5.5.9 not displaying "Unskip" button for auto-skipped sections

### ISSUE THREAD

**Issue by ToxiClay** [ajayyy/SponsorBlock#2010]
In previous versions, there's been a floating popup that allows me to "unskip" an auto-skipped section if I want to. That's been missing recently, and I'm not sure what might have happened to it.

If I have the section set to "Manual Skip," the "unskip" button is there.

**Comment by ajayyy** [comment]
Check out this setting

![Screenshot_20240423-192749_Firefox_Nightly](https://github.com/ajayyy/SponsorBlock/assets/12688112/199f3e70-5702-46f8-a366-61c0e98354e7)
