### ISSUE TITLE
A sent segment is not saved if there is a foreign segment before it

### ISSUE THREAD

**Issue by BigBOSSo** [ajayyy/SponsorBlock#2011]
The problem appeared about 2-3 weeks ago. I used to send an ad segment on top of someone else's segment and it worked. And now if someone sent it incorrectly, I can’t send my segment (It is not saved in the database)

**Comment by ajayyy** [comment]
It is saved, it just might not be shown until the other one is downvoted

**Comment by HanYaodong** [comment]
> It is saved, it just might not be shown until the other one is downvoted

I feel like prioritizing showing the users' own segments  makes more sense. At least we can see that our work has been recorded.

**Comment by ajayyy** [comment]
Right now it is not possible was queries are anonymous
