### ISSUE TITLE
"No Video Found" Error & SB Pop-Up Glitch

### ISSUE THREAD

**Issue by PasttaTypo** [ajayyy/SponsorBlock#2013]
I reloaded the same video w/ no extensions or ad-blockers enabled, and out of 23 attempts, I found that I get "No Video Found" roughly 65% of the time. This shows only in the pop-up and doesn't affect sections/chapters from skipping or showing in the YT scrollbar.
I tried this with other videos, some with playlist id in URL, and most times I get the same error. Now, this can be _fixed_ by hitting the reload icon in the pop-up, and everything is still accessible, but once I get "No Video Found" on a video, it seems to follow through clicking any links to videos or the next videos in a playlist within that YouTube instance until I reload the tab. And then it's just a coin flip to see if the problem happens again. (Presume one side of the coin takes some steroids)
There's also the issue that follows where the tabs to switch between segments and chapters don't function properly without hitting the reload button after changing sections, **see video at the bottom**.

I've tried reinstalling SponsorBlock and no dice. This has been a consistent problem for me on Chromium-based Vivaldi (current v. 6.7.3329.17) for a while, but I don't recall having the same issue on Firefox Android.

https://github.com/ajayyy/SponsorBlock/assets/125756085/ee6dc957-2b6d-4b21-b7f9-8b31d062a6a2

**Comment by ajayyy** [comment]
Interesting. Tried this several times and cannot reproduce it in chrome

**Comment by PasttaTypo** [comment]
Still getting this issue in Vivaldi at the same rate, it's probably browser-specific after using the same set-up. Imported .json files to extension in Edge to compare with the same SB user setup, and it loads fine there.

**Comment by ajayyy** [comment]
Update not pushed yet

**Comment by PasttaTypo** [comment]
@ajayyy After update, same issue. It's likely an issue specific to Vivaldi, because this doesn't happen on Edge or Firefox.
