### ISSUE TITLE
MUTING

### ISSUE THREAD

**Issue by craxton** [ajayyy/SponsorBlock#2014]
instead of skipping "segments" 
its now just muting sound and letting
those segments play out.
I tried a few things with no resolve. 
and i couldnt find any info to see if this
has been "a new feature" for whatever reason.

**Comment by craxton** [comment]
> instead of skipping "segments" its now just muting sound and letting those segments play out. I tried a few things with no resolve. and i couldnt find any info to see if this has been "a new feature" for whatever reason.

had this happen on 3 vids, now it seems fine.
but those three vids seem to do the same thing
they werent over ten min. (ten on the dot)
not sure if thats why or not.

**Comment by ajayyy** [comment]
This is a type of segment you can skip. It has existed for several years
