### ISSUE TITLE
Idea for custom categories

### ISSUE THREAD

**Issue by ProgrammerWhoPrograms** [ajayyy/SponsorBlock#2015]
Have independent servers possible with each server defining it's own categories just like the current sole server has the current categories.
Each category's name must be unique to the server it lives on, but does not have to be unique across the entire application.
Categories could be addressed with a format that includes the server such as `sp://$server/$category` for easy addition by users (where 'sp' stands for 'SponsorBlock'). E.g. `sp://sponsor.ajay.app/sponsor`.
Aside: after the server is typed, auto complete could show the available categories on that server on supporting clients.

**Comment by mchangrh** [comment]
This has been discussed extensively in the discord, might be worth it to write it up into an issue on GH to combine the floating ideas together

**Comment by ProgrammerWhoPrograms** [comment]
@ajayyy Just double-checking something. Are you closing this issue because you want #2016 to be the canonical issue or because you really are not planning on adding this feature?
