### ISSUE TITLE
SponsorBlock and DeArrow don't work

### ISSUE THREAD

**Issue by cheater** [ajayyy/SponsorBlock#2026]
Win 10 64-bit

FF 126.0.1 (64-bit)

SponsorBlock 5.6
DeArrow 1.6

Nothing happens. It's like the addons became uninstalled.

Unlike the [last time I reported a similar issue](https://github.com/ajayyy/SponsorBlock/issues/1463), `sponsor.ajay.app` is reachable in the browser.

Going to the settings for SponsorBlock, they don't display any settings at all, just the header. Clicking on the other buttons doesn't select them at all.

![image](https://github.com/ajayyy/SponsorBlock/assets/195390/74b17c76-7f87-4963-92ed-5afd3c2d932d)

Same with DeArrow but it looks like the build is broken too.

![image](https://github.com/ajayyy/SponsorBlock/assets/195390/5df1a72b-5f85-4b52-a283-ad22131f489d)

The addons not working started happening in the last few days. I don't know if the broken settings pages are new or not.

**Comment by cheater** [comment]
While I don't have DeArrow on mobile, I have SponsorBlock on mobile (Firefox Nightly) and it works on that using wifi from the same internet connection as my desktop.

**Comment by cheater** [comment]
I turned off all my extensions in firefox except for DeArrow and SponsorBlock, and then I refreshed the same video I just tested on mobile, and the addons still don't work.

**Comment by cheater** [comment]
The previously discussed country wide [block list](https://netzsperre.liwest.at/) doesn't seem to have any new entries for this year at all

**Comment by cheater** [comment]
just noticed that the bar buttons show

![image](https://github.com/ajayyy/SponsorBlock/assets/195390/a4b7da96-9624-492c-87e3-3e768d19b79a)

when I click on "show popup", I get an empty pane

![image](https://github.com/ajayyy/SponsorBlock/assets/195390/8449310d-3792-4be1-b791-cde12ddf8378)

**Comment by ajayyy** [comment]
Try uninstalling and reinstalling

**Comment by cheater** [comment]
Didn't help, both are still non-functional

**Comment by Sinaaaa** [comment]
Seems like  Youtube changed something. I'm experiencing the same on Firefox. I'll test on my laptop later with Brave..

**Comment by cheater** [comment]
Yeah, the worrying thing is that it still works on mobile. Which means maybe YouTube/Google are targetting these specific addons.

**Comment by Sinaaaa** [comment]
> Seems like Youtube changed something. I'm experiencing the same on Firefox (Linux). I'll test it on my laptop later with Brave..

Works in Brave, how strange.

**Comment by 71256988** [comment]
What error message(s) do you get in the console (Ctrl+Shift+I -> console) when you load a Youtube page? Are you able to reproduce the issue in Firefox on a different device?

**Comment by mikkelens** [comment]
It works for me with a similar configuration:
- Win 10 (64-bit)
- FF (Developer Edition) 127.0b9 (64-bit)
- SponsorBlock 5.6
- DeArrow 1.6

**Comment by Sinaaaa** [comment]
> What error message(s) do you get in the console (Ctrl+Shift+I -> console) when you load a Youtube page? Are you able to reproduce the issue in Firefox on a different device?

It just started working today. o_O

**Comment by cheater** [comment]
it still doesn't work for me. i see a bunch of errors in the console, but nothing related to sponsorblock or dearrow.

**Comment by cheater** [comment]
@ajayyy i was wondering if you had any questions? can i test something to help you debug this?

**Comment by cheater** [comment]
please, this is driving me mad already 🙏 week in hell

**Comment by 71256988** [comment]
Pinging him isn't going to help if there is nothing to help troubleshooting. 

That said, are you having able to replicate this issue on another PC with Firefox or is it only on that computer?
