### ISSUE TITLE
Broken Pop-Up using the Chrome extension in Vivaldi Browser

### ISSUE THREAD

**Issue by PasttaTypo** [ajayyy/SponsorBlock#2027]
_*Continuation of https://github.com/ajayyy/SponsorBlock/issues/2013_
Edit: Only occurring when signed in to YouTube

On v. 6.7.3329.39 of Vivaldi browser and 3.0.0.16 of SponsorBlock, opening the pop-up menu with segment timecodes will usually show a "No Video Found" error, and the reload icon has to be clicked to restore functionality to the menu, whether opened on the YouTube watch page with the SB "i" icon, or in the toolbar extension icon.
After the recent update, it's gotten worse to where the reload button has to be clicked multiple times for segments to show in the pop-up, and sometimes they don't show until refreshing the tab. Also from #2013, moving between the chapters and segments sections will show the same error with the same behavior. At least everything else, including segments appearing on the scrollbar and skipping has no issue.
Seems to be specific to Vivaldi, because with the same user setup, the pop-up works fine on Firefox.
_(Tested on Vivaldi without any other extensions or mods active)_

**Comment by ajayyy** [comment]
Is this still an issue?

**Comment by PasttaTypo** [comment]
> Is this still an issue?

I can't replicate the glitch anymore, so it seems to be fixed.
