### ISSUE TITLE
YouTube player integration doesn’t work on iOS 17.5.1

### ISSUE THREAD

**Issue by COOLIRON2311** [ajayyy/SponsorBlock#2029]
No colored segments on the seek bar and auto skip doesn’t work. Manually skipping segments via extension’s menu does work.

**Comment by COOLIRON2311** [comment]
Everything works fine if one requests the 'Desktop’ version of YouTube though.

**Comment by ajayyy** [comment]
Skipping still should work, but the preview bar doesn't currently work on iOS mobile at the moment

**Comment by COOLIRON2311** [comment]
> Skipping still should work, but the preview bar doesn't currently work on iOS mobile at the moment

It works sometimes for me. For example in [this](https://youtu.be/cQUlbFmjDcM?si=UPOsmsS4WXpE6MxY) video the sponsored segment isn't being automatically skipped although the info about it is present in the extension's menu.

**Comment by RandomGuy28** [comment]
Not sure why this is closed, but I have the same issue, the skip works but the preview bar doesn't.

[Debug log.txt](https://github.com/user-attachments/files/18136305/Debug.log.txt)

**Comment by ajayyy** [comment]
@RandomGuy28 that's because YouTube changed their class names again. A fix was released but might still be in review
