### ISSUE TITLE
No widgets in youtube player and blank plug-in window

### ISSUE THREAD

**Issue by DivinorWieldor** [ajayyy/SponsorBlock#2030]
Hello!

I recently noticed that my extension has stopped working. I'm not sure when this happened.

The sponsorblock widgets (start recording button) that are normally within the youtube player's footer widget bar have disappeard. Suspecting this was due to a silent crash, as it sometimes happens with firefox plugins, I turned SponsorBlock off and on. This didn't help. Following this, I attempted to open the plugin to see if it worked, but the plugin window does not show any information.

My problem is very similar to  #1599, besides the error messages they got. I might not have been able to find those though.

What can I do to fix this? 

One thing I can do to try and alleviate this is delete and re-download the plug-in, but I'd prefer to keep my userID if possible. Is it possible to retrieve my userID from wherever it is stored?

system information: firefox 126.0.1, windows 10

**Comment by ajayyy** [comment]
how often does this occur?

**Comment by DivinorWieldor** [comment]
In my four years of usage of this extension, this has only occurred once; at the time of my posting.

**Comment by ajayyy** [comment]
It might have just been the extension updating then
