### ISSUE TITLE
Ads in youtube seem to be included in the video's duration now

### ISSUE THREAD

**Issue by mini-bomba** [ajayyy/SponsorBlock#2035]
Initially reported [on discord](https://discord.com/channels/603643120093233162/603643180663177220/1250212284333035602)
In that case the two preroll ads that played have extended the `<video>` element's duration by 40 seconds, which caused all segments to appear mistimed by those 40s.
Additionally, the segment overlay wasn't rendered on the video, was likely removed after the first ad has ended.

**Comment by ajayyy** [comment]
Added some protection against it causing bad submissions https://github.com/ajayyy/SponsorBlockServer/commit/ec1e6d63a4d15bffbeed7dde852eba761162d6ca

**Comment by Theta-Dev** [comment]
I would like to check out how these new server-side injected ads work. However I could not get them to appear, even though I was using an US VPN and opened the site multiple times while resetting cookies.

Can anyone who is experiencing this new feature send me the value of th `__Secure-YEC` cookie to reproduce the A/B test?

**Comment by xtf0** [comment]
Could a (key-)frame comparison from the start of the known video or section determine it? Are the hover previews extractable to use it for that?

**Comment by lofi-nomi** [comment]
> Could a (key-)frame comparison from the start of the known video or section determine it? Are the hover previews extractable to use it for that?

Seems unnecessary there is already code to get the API reported duration and the client reported duration, simply finding the difference and using it as an offset seems way easier if both are reliably provided

**Comment by maryball2** [comment]
Just commenting to mention a behavior I noticed. If there's a highlight added to the video pressing enter while and ad is playing will skip the ad entirely. I've recreated it on a couple videos but first noticed it here.

https://www.youtube.com/watch?v=5VGLPP70Xtw

**Comment by NaunidhDua** [comment]
> I would like to check out how these new server-side injected ads work. However I could not get them to appear, even though I was using an US VPN and opened the site multiple times while resetting cookies.
> 
> Can anyone who is experiencing this new feature send me the value of th `__Secure-YEC` cookie to reproduce the A/B test?

@Theta-Dev I believe it is select Google Account's that are experiencing it, not certain locations.

On the one google account of mine that is experience the server side ads, I did not have the `__Secure-YEC` cookie at all, even after refreshing and during seeing an ad.

Let me know if you want anything else tested.

**Comment by Theta-Dev** [comment]
Ah, ok, I think this cookie is only set for European users. You can also get the visitor data from the source code of the YouTube page (right click the YouTube page, select View source, search for `VISITOR_DATA` and get the value right next to it).

The visitor data should start with `CG` and be about 24 characters long.

**Comment by NaunidhDua** [comment]
I am in Europe, but the UK, so not sure if its that changes things.

`"VISITOR_DATA":"CgtReGZvNktQR0hoUSjqgcOzBjIKCgJHQhIEGgAgRA%3D%3D"`

**Comment by Theta-Dev** [comment]
Thank you, but I could not reproduce the server side ads on my side, even when using an UK VPN.
