### ISSUE TITLE
[FEATURE] Searchable database for discount codes.

### ISSUE THREAD

**Issue by Dani3I** [ajayyy/SponsorBlock#2037]
### Feature proposition:

**Idea:**
Add option to submit discount codes and other discount/limited offers from sponsors. Then, it would probably be best to create an additional web page that would allow users to search for discount codes for service they are looking for.

**Implementation and things to consider:**
- Users who watch sponsor segments and are submitting it to your database would have additional option to report that sponsor segment that they are looking at have discount codes (or maybe add that as entirely separate option).
- Selecting that option would reveal to them few options to check (in no particular order):

1. type of discount: is it code limited by time/amount; or limited (time/amount) discount for all people; or special offer for people who meet certain requirements.
2. What is the end date (if needed).
3. What is the code (if available) - so people who search for codes wouldn't even need to open that video.
4. additional notes (what are requirements etc).
5. link to redeem code (although idk if it is good idea because it would require that people who are submitting codes are not malicious).
6. How good is offer (eg. 50% discount for month subscription for first time users)
7. Sponsor require/don't require your personal data (for example your address and credit/debit card info for registration).
8. name of sponsor (and preferably with search so there wouldn't be duplicates like "ABCVPN" "ABC VPN" "ABC (vpn service)" etc.)

- People who search for coupon codes would be able to mark offers as ended (for example for offers which didn't had specified end date or those which are limited by amount instead of time).
- maybe rating system for people who search for coupon codes

- One thing to consider is that some sponsors who sponsor some videos might offer malicious services. So even though discount codes would be valid the service itself would be malicious. I think that It isn't super big deal when people would go to search website and look for websites they are interested in, but If ranking system would be implemented then some people would go to search website and sort by "biggest discount" and find some service that is malicious or service that is trying to mimic some other popular service. So I think that there should be warning before using this feature that people should find redeem websites by themselves and check websites by themselves.

- Automatic sponsor recognition from subtitles. When some sponsor segment is already submitted then some algorithm would search for some of the popular company names. There would be problem with videos with no subtitles (so a lot of non-english languages) and also problem with recognition if sponsor segment have, or don't have coupon codes. Although It could help with user submissions because it could automatically fill name of the sponsor.

**Few words:**
Since this extension is already collecting info from users about sponsor blocks then I think that it might be good to add little checkbox to say "there is coupon code" to give users discount codes for services when they are actually looking to buy them. It would require some more development though, because as I wrote above, It would require to make website to search for these "good offers" (although it is also possible that this project could serve only as database so someone other would be able to create website to search through that database). I am not sure If all features I wrote above should be implemented, or if all of those should be mandatory to fill when submitting (I think that mandatory probably would only be name of sponsor) - these are just some of my ideas.

**Comment by ajayyy** [comment]
No
