### ISSUE TITLE
[Question] Soundwave masking

### ISSUE THREAD

**Issue by Droogfein** [ajayyy/SponsorBlock#2041]
Hi,

Would it be possible, in the scope of extension development (not familiar with it) to run a routine which takes non-selected parts of videos with injected ads, takes the soundwave of the legit video parts and storing it as a mask on the sponsor block server, which then gets sent out to users and recognizing which parts of a video do not match the soundwave signature of the legit parts client-side? Is that too computationally intensive for the client browser or for the server?

Best,
Droog

**Comment by ajayyy** [comment]
#2035
