### ISSUE TITLE
Can I create custom segments and keep them local-only?

### ISSUE THREAD

**Issue by OutshineIssue** [ajayyy/SponsorBlock#2042]
I want to block parts of videos that don't fit into any of the current segment categories, they aren't sponsor, or fillers... it's just that I don't like them, so there's no point in creating something in a random category and uploading it for everyone else since no one would understand it and downvote it. Can I create something custom and keep it to myself?

**Comment by ajayyy** [comment]
Yes, didn't submit it

**Comment by OutshineIssue** [comment]
Can I set a name other than 'Unsubmitted'? I realized this can be used to tag songs in a concert video too.

**Comment by OutshineIssue** [comment]
@ajayyy 👀
