### ISSUE TITLE
sponsorBlock being flagged as an ad blocker

### ISSUE THREAD

**Issue by 3DC001** [ajayyy/SponsorBlock#2049]
I know this is an issue the probably cant be solved by you guys but I still want to talk about it
I don't know what youtube is flagging as an ad blocker but when I turn the sponsorblock extension off the popups for using an ad blocker went away, I dont know if other people are getting this happen to them too or if its just me but this seams a bit too far for youtube and I will probably have to stop using sponsorblock soon when I cant close the pop up anymore

**Comment by ajayyy** [comment]
Disable all other extensions and then install only uBlock Origin and SponsorBlock and see how it goes
