### ISSUE TITLE
[Feature] Add housekeeping category

### ISSUE THREAD

**Issue by lemenn** [ajayyy/SponsorBlock#2050]
I don't see a relevant category to submit for content (usually towards the end of a video) where a creator covers changes to their channel, their content moving forward, etc. I've considered preview/recap but often these previews/recaps of channel content changes don't apply to the video itself but more generally to the channel and the youtuber. Also I don't include announcements on how to support a creator as part of this housekeeping category but more so of an unpaid/self promotion. Filler doesn't apply either imo as this content can be relevant to some and not just jokes/humor.

If we could get a separate category that covers general housekeeping matters related to a channels content moving forward that would really fill a missing category niche.

**Comment by ajayyy** [comment]
Better fit for chapters
