### ISSUE TITLE
Integrating the ReturnYoutubeDislike API to fetch/add YouTube dislikes

### ISSUE THREAD

**Issue by brackson** [ajayyy/SponsorBlock#2051]
In 2021, the dislike feature was [removed from YouTube](https://blog.youtube/news-and-events/update-to-youtube/). Someone made a browser extension called [ReturnYoutubeDislike](https://returnyoutubedislike.com/) to restore this functionality.

ReturnYoutubeDislike [has an API](https://returnyoutubedislike.com/docs) that can be used to add and fetch dislike counts. Some people, like me, might already be using this extension on top of SponsorBlock. I think it could be a good idea to integrate this into SponsorBlock for a few reasons.

1. Removing the dislike counts was widely criticized
2. Dislike counts on YouTube can be a valuable indicator on the quality of a video and its content
3. For something like ReturnYoutubeDislike to work, it needs a large pool of users with the ability to dislike videos

SponsorBlock at its core is pretty similar to ReturnYoutubeDislike as well. They both give valuable information about videos that YouTube doesn't. Implementing this on top of SponsorBlock seems like a win-win to me. Wouldn't mind working on a PR for this if people think it's a worthy feature.

**Comment by ajayyy** [comment]
ReturnYoutubeDislike is already a browser extension

**Comment by brackson** [comment]
@ajayyy It's an extension that not a lot of YouTube users know about. My rationale was that more people interacting with the API = net positive for everyone, so it might be worth adding that functionality to SponsorBlock by default.
