### ISSUE TITLE
Thanks for helping me make YouTube Transcripts Awesome

### ISSUE THREAD

**Issue by therohitdas** [ajayyy/SponsorBlock#2054]
Namaste Ajay Bhaiya,

I hope you're doing great! I just wanted to share how I'm using your awesome API in my project, [YouTube To Transcript](https://youtubetotranscript.com/).

About My Site:

YouTube To Transcript makes it super easy to extract transcripts from any YouTube video. With the help of your API, I was able to add a crucial feature that every other such tool does not have:

**Clean Unwanted Sections: With your API, I can let user cut out sponsored segments, intros, outros, or anything else that's not needed. This makes the transcript cleaner and helps fit it within the context window of ChatGPT or other LLMs.**

Thank you so much for creating such a fantastic API! It's been amazing to integrate it into my project and see how much it helps my users. I'm excited to keep improving and your API will definitely be a big part of that journey. 
I have not yet figured out how to use POI yet but I am experimenting.

If you want to see the UI in action, here's the transcript page for a [youtube video](https://youtubetotranscript.com/transcript?v=1WEAJ-DFkHE&current_language_code=en)

https://github.com/ajayyy/SponsorBlock/assets/43847374/f8435321-f500-4375-a31f-49a7f20521f3

If someday you use this tool, I will be honoured.
[**Youtube To Transcript**](https://youtubetotranscript.com/)

**Comment by ajayyy** [comment]
cool
