### ISSUE TITLE
Chapter Navigation Hotkeys Not Working As Expected

### ISSUE THREAD

**Issue by ddouglas87** [ajayyy/SponsorBlock#2055]
When 'Render segments as chapters' in SponsorBlock settings is turned on chapters become visible in the video navigation bar.  However, pressing ctrl+→ (right arrow) and ctrl+← navigates forwards and backwards to the preexisting chapters.  Navigation keybinds do not jump to the SponsorBlock created chapters.

E.g.:

![Initial Position](https://github.com/user-attachments/assets/411673b9-053b-4bc7-8d83-0ddefd734fc0)
![ctrl+right_arrow](https://github.com/user-attachments/assets/27cd460b-0505-4964-97b1-c37a1817933c)
![ctrl+left_arrow](https://github.com/user-attachments/assets/a9106c01-05c6-441f-b60d-310f395ec174)

The first picture is the initial position, then after pressing ctrl+→ is the second picture, then after pressing ctrl+← is the third picture. Source video used in example: https://www.youtube.com/watch?v=HYHZyyogdyo This behavior is reproducible in other videos I've tried.

Tested on Firefox 128.0 (64-bit) and Chrome Version 126.0.6478.126 (Official Build) (64-bit).  Both browsers have the same behavior.

**Comment by ajayyy** [comment]
This depends on what you set as your keybinds in the sponsorblock options

![image](https://github.com/user-attachments/assets/3be8201b-41af-4375-8a04-edfa9cc5932f)

**Comment by ajayyy** [comment]
The sponsorblock one also skips over skippable segments like sponsors and selfpromo, so that might be what is happening here

**Comment by ddouglas87** [comment]
> The sponsorblock one also skips over skippable segments like sponsors and selfpromo, so that might be what is happening here

I don't quite follow.  There is an option to turn sponsors into chapters.  There is the option to go forward and backwards chapters.  When going forward and backwards chapters it's not respecting the sponsor chapters as if those chapters do not exist.

**Comment by ajayyy** [comment]
That's not how the feature is supposed to work. That setting is just for _displaying_ as chapter blocks on the player. The skip to next chapter specifically skips over skippable segments so that you avoid seeing them

**Comment by ddouglas87** [comment]
What's the point of having chapters if you can't skip to them or past them?  imo that's the primary usecase for chapters.
