### ISSUE TITLE
[Feature] Add "hybrid" sponsor catagory

### ISSUE THREAD

**Issue by itai25** [ajayyy/SponsorBlock#2057]
Some sponsor segments run while the video content continues playing in the background. Auto-skipping these may cause the viewer to lose out on context or just part of the content. Separating these types of segments to a different category allows the user to specify different skip options for them.
Personally, this is the only reason I check the seek bar highlights every skip in case I missed something.

This can also possibly replace mute sections, as I believe that this is the reason that mute sections were added and it seems that people do not quite understand that and don't use them often, of course adding a mute option in skip settings will allow people to who prefer these sections to be muted to do so.

**Comment by ajayyy** [comment]
Use mute segments
