### ISSUE TITLE
SponsorBlock unusable on iPad mini 4

### ISSUE THREAD

**Issue by gnppn** [ajayyy/SponsorBlock#2063]
Hi,

I've been using SponsorBlock on Safari with Vinegar for a while but the past few weeks, I've been unable to watch YouTube videos because of the extension. The webpage loading blocks with some parts there (either title, comments, related videos...) but the video player itself doesn't appear (black box). Safari then displays a header signaling that the page is taking too much time to load and tries again to load it; it resembles an overload of JS.

Disabling Vinegar doesn't change a thing, disabling SponsorBlock fixes the problem.
I fully reinitialized my iPad and the problem is the exact same.

Browser: Safari
System: iPadOS 15.8.2
Other extensions: Vinegar

Is it fixable?

Thank you in advance,

Guénaël

**Comment by ajayyy** [comment]
Vinegar compatibility should be fixed now
