### ISSUE TITLE
Cannot submit with my Private ID (error 500)

### ISSUE THREAD

**Issue by gitols** [ajayyy/SponsorBlock#2066]
I've been having problems doing submissions recently and I am constantly receiving error 500 messages without any explanation or notice and that has been quite frustrating to find out why. I finally pinpointed it to the cause being my private ID so I was wondering why that is and how to avoid that. I have been downvoting some submissions which while not done malicious are clearly inaccurate leaving small but annoying segments in. I've always used the directional keys (< and >) to push frame perfect submissions that result in seamless transitions so I'm a bit confused why this happened if this indeed was the reason.

**Comment by ajayyy** [comment]
What's your username?

**Comment by ajayyy** [comment]
I do think this is fixed now though, but let me know if it still happening for you
