### ISSUE TITLE
Issue with skipping segments when having many Youtube tabs open in Chrome

### ISSUE THREAD

**Issue by gitols** [ajayyy/SponsorBlock#2067]
I have been having trouble with Sponsorblock version 5.7 often not skipping segments under Chrome despite the segments having been retrieved and I suspect it might be because of having lots of tabs opened in a session. I'm talking about probably a couple of hundred tabs with mostly Youtube videos.

I cannot figure out why skipping stops working while they do work if I open a new profile or in incognito alongside the hundreds of tabs with the same extensions enabled or disabled. Disabling and Enabling the Sponsorblock extension or reinstalling it solve it. Reopening Chrome with a single tab does work and version 5.6.1 always works where 5.7 fails. Is there something that has changed with Sponsorblock version 5.7 that could explain this behavior?

**Comment by ajayyy** [comment]
Are you on an old version of chrome maybe? The change in 5.7 was to switch to Manifest v3 which is buggy on many versions of chrome
