### ISSUE TITLE
SponsorBlock and DPI bypass - issues (unable to connect)

### ISSUE THREAD

**Issue by noideastowork** [ajayyy/SponsorBlock#2075]
SponsorBlock doesn't work when DPI bypass is turned on. It is unable to connect to the server.

You may know that YouTube has started to be blocked ("slowed down") in Russia, so a large number of users have started using DPI bypass tools. So I can assume that the problem may affect many people. However, it may depend on how the provider has set up their system. 

This is observed both in the browser extension and in the ReVanced app.

Any ideas on how to fix this?

**Comment by mchangrh** [comment]
the default endpoint goes through CloudFlare which I would assume is blocked

try `api.sponsor.ajay.app` instead to bypass CF

**Comment by noideastowork** [comment]
Yes, thank you! It really works. 

Plus, now I understand why this is happening! Special thanks for the explanation.
