### ISSUE TITLE
[Website] Opera goes to Chrome

### ISSUE THREAD

**Issue by lorenzoalali** [ajayyy/SponsorBlock#2076]
On [the main website](https://sponsor.ajay.app/#:~:text=check%20out%20DeArrow-,Download,-3rd%20Party%20Ports) the Opera button redirects to the Chrome extension.

<img width="1136" alt="screenshot" src="https://github.com/user-attachments/assets/06af469b-00dd-4cb9-9fac-4e2b62232aef">

There is the same problem on [DeArrow](https://dearrow.ajay.app/#:~:text=more%20peaceful%20experience.-,Download,-3rd%20Party%20Ports), this time both for Edge and Opera.

**Comment by ajayyy** [comment]
On purpose, you can download from there
