### ISSUE TITLE
STOP ASKING TO PREVIEW

### ISSUE THREAD

**Issue by huachuman** [ajayyy/SponsorBlock#2077]
For many of the videos I am the only one who will ever submit these segments. And these aren't unpopular channels either. Some have hundreds of thousands of views per video.

The fact that anybody is submitting segments at all is honestly a miracle.

Stop asking me to preview the segment. I know I did it right. I can check it if I want. But please, stop making the process more annoying. It's making me not want to submit segments anymore because it's so annoying.

You're just adding extra steps to something I'd rather not have to do myself in the first place.

The more streamlined the process, the more segments get submitted.

**Comment by mchangrh** [comment]
quality > quantity

**Comment by FelixFourcolor** [comment]
Please share your publicID so that we can check your work. It is not humanly possible to time segments accurately without previewing.

**Comment by huachuman** [comment]
This is nonsense thinking. 

When there are NO SEGMENTS, and videos NEVER GET segmented, then quality does not matter because anything is better than nothing.

You people are obsessed with perfection and do not understand what real life is like.

What an utterly ridiculous bunch of buffoons.

**Comment by ajayyy** [comment]
who would have thought the person with horrible ai generated art as their profile picture wouldn't care about quality

**Comment by huachuman** [comment]
LMFAO speak for yourself

**Comment by wdpk** [comment]
If your segments are fine as you claim them please

> share your publicID

**Comment by mchangrh** [comment]
Share your PublicID, I'm 4/4 on "don't make me preview my segments are fine" but their segments are bad enough to get tipped

**Comment by huachuman** [comment]
Unfortunately for you I'm not dumb enough to submit my public ID to you pack of jagoffs so you can criticize the 0.1 seconds my segments are off to support your poorly designed forced "preview" feature, which will never in any reality on this earth significantly improve the quality of submitted segments.

I'm all for quality, but this will never make a difference in quality. At least not as much as implementing proper features that would actually help submitters find and fine tune segments.

It's lazy programming.

**Comment by NoMoreAngel** [comment]
> I'm all for quality, but this will never make a difference in quality. At least not as much as implementing proper features that would actually help submitters find and fine tune segments.

And those would which features? There are already features that let you time to 0.001ms in the extension. So judging your submission that is 0.1 seconds off wouldn't even be needed if you actually did use the features :)
