### ISSUE TITLE
Missing check if video element exists

### ISSUE THREAD

**Issue by MRuy** [ajayyy/SponsorBlock#2078]
setupVideoListeners() in content.ts is not checking that getVideo() is returning a valid video element.

The Browser Vivaldi can disable autoplay for selected websites that will "block" the video element.

https://github.com/ajayyy/SponsorBlock/blob/3738b180ddaa75d23f027272dd072dda4bc8e105/src/content.ts#L849

**Comment by ajayyy** [comment]
That function should only be called after a valid video is found

**Comment by ajayyy** [comment]
But it does seem to be failing for some people on brave apparently too #2056

On my end, brave still leaves the video element when autoplay is off. It is just paused instead.

**Comment by DerEingerostete** [comment]
> But it does seem to be failing for some people on brave apparently too #2056
> 
> On my end, brave still leaves the video element when autoplay is off. It is just paused instead.

Brave user here.
It seems like this is the exact problem I am currently facing (in regard to #2056). It's a bit hard to debug the compiled script, but I every time I load a video I get this error:

```
content.js:2 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at content.js:2:242259
    at content.js:2:244897
```

This seems to be confirmed by the fact that the debugger is showing the variable as ``null`` too.
My Brave version is ``Version 1.71.88 Chromium: 129.0.6668.42 (Official Build) beta (64-bit)`` and the extension is version ``5.9``

If there is any way for me to help, let me know, and I'll try my best

**Comment by ajayyy** [comment]
Unable to reproduce it on vivaldi either but I'll give this fix a shot
