### ISSUE TITLE
Deleting Existing Segments

### ISSUE THREAD

**Issue by HaikenEdge** [ajayyy/SponsorBlock#2080]
I was watching ["Friendos"](https://www.youtube.com/watch?v=7oPe80mdcZg), an SNL digital short, when I noticed that somebody had added and uploaded multiple automatically-skipping non-music segments to the video. However, this is an SNL comedy skit and not just a music video, and the non-music segments are where the humor is, so skipping them kind of misses the point of the video in the first place.

However, I can't find a way to delete the automatically-skipping non-musical segments, which I actually want to watch without having to manually rewind to them.

**Comment by portex7000** [comment]
dislike the segments, that should get rid of them atleast for you
