### ISSUE TITLE
Missing segments

### ISSUE THREAD

**Issue by toothlessgodzilla** [ajayyy/SponsorBlock#2085]
Hello. The segments I've submitted aren't appearing on any videos anymore, even though the extension popup still lists 65 submissions and shows that the number of "saved hours" has increased over the last night. I can still see segments created by other users on random videos.

I suspected someone may have disagreed with the segments I've submitted for a specific video and then somehow got all my submissions shadowbanned, including commercial breaks in political debates. 

ID: fe504671942b531c86568e9ea133e2042b3b5867917dc562a3f943b066e0d9c3

**Comment by ajayyy** [comment]
You are not banned

**Comment by PasttaTypo** [comment]
Some of your recent segments were auto-removed on https://www.youtube.com/watch?v=gB9mCEaCPIc because the video duration changed.
You should use the [public SB database viewer](https://sb.ltn.fi/) (updates usually every hour) to check if your segments are showing before opening a Git issue.
