### ISSUE TITLE
Do not provide the watch id for a video that is not public

### ISSUE THREAD

**Issue by OfficialNoob** [ajayyy/SponsorBlock#209]
# Description
I think videos that are not public should not be exposed to the server. (or public as db is public)
This should affect both private and unlisted videos.

# Suggested options
- Prompt user
- Do not send request to server
- Use a substring of a hard to compute hash when no times are submitted

# Detection
`let Public = (document.getElementsByClassName("style-scope ytd-badge-supported-renderer")[2].innerText === "");`

**Comment by ajayyy** [comment]
I use unlisted videos for debugging purposes, so this will have to be optional.

**Comment by OfficialNoob** [comment]
A prompt would probably be the easiest to add.
However "a substring of a hard to compute hash when no times are submitted" would
probably be a nice feature to have.

**Comment by OfficialNoob** [comment]
https://github.com/ajayyy/SponsorBlock/pull/210
