### ISSUE TITLE
Support vorapis extension

### ISSUE THREAD

**Issue by elisenlebkuch** [ajayyy/SponsorBlock#2092]
Add 2014 player classnames to support [vorapis/v3](https://github.com/VORAPIS/v3).

**Comment by ten4dinosaur** [comment]
very [basic support patch](https://gist.github.com/ten4dinosaur/7f0fb7a191fbc236fbd2ee14fff000f2)

**Comment by ajayyy** [comment]
@ten4dinosaur Finished up your patch, thanks for the help to start off

7e824df73dfb7465d3fd63108d98be5bd625aa74
