### ISSUE TITLE
Blank toolset on videos and blank addon when clicked

### ISSUE THREAD

**Issue by X13X** [ajayyy/SponsorBlock#2096]
Wtf is going on??

Every Saturday I make sure to cut out sponsors from "certain people" on their videos...

And yet nothing is shown today....no toolset for me to submit a query, no toolset when I click on the sponsor block add-on widget.. no nothing.

Wtf is happening??

**Comment by X13X** [comment]
HELOOOOOO

**Comment by hayleyxyz** [comment]
> HELLOOOOOO!!!
> 
> I cant do anything with sponsor block! I can't choose an option, I cant choose a time ... I cant do anything.. So wtf is happening?
> 
> The #1 app on firefox... and noone has anything to say about this?

Be patient; your messages are 7 minutes apart. This is an OSS project, it will take a little while for devs to find the issue and fix it. This happens with projects that rely on the structure of proprietary sites/services they don't control. Sometimes the service changes, and it beaks the extension.

Disable the extension for now and wait for updates.

**Comment by X13X** [comment]
That's fine... as I don't want a rush fix...

I just want to know if this is happening to others.. as I don't see anyone else talking about the issues I'm facing.
