### ISSUE TITLE
feature request: Hide sponsored descriptions or pinned comments

### ISSUE THREAD

**Issue by apathetica** [ajayyy/SponsorBlock#2097]
Idk if this is the right place for this, but I thought it is worth saying 

Youtubers tend to put sponsor affiliate links and promotions in the descriptions of their videos, as well as pinned comments. I think it would be nice to implement something to hide these.

Maybe you could just make a filterlist for certain keywords, like "use code ___" or "__% off", or something similar, as implementing another user submitted system may be excessive.

**Comment by ajayyy** [comment]
#649
