### ISSUE TITLE
Seek bar not red for played/location

### ISSUE THREAD

**Issue by jamesdeluk** [ajayyy/SponsorBlock#2099]
With SB, no hover:

![image](https://github.com/user-attachments/assets/be73fa72-771b-47ed-97d9-77838d181ffa)

With SB, with hover:

![image](https://github.com/user-attachments/assets/0d919854-8901-4e2d-a9a4-d518d67b4094)

Without SB, no hover:

![image](https://github.com/user-attachments/assets/79ebb62a-d768-4ffb-a5d9-cb2917237f7a)

Without SB, with hover:

![image](https://github.com/user-attachments/assets/0dec5446-3fe5-4870-bfc3-c112a1aeb0a1)

Any idea why this is?

If there are no sponsor segments, the red appears as normal.

Latest version of Firefox on Windows 11.

**Comment by ajayyy** [comment]
Can you try disabling other extensions as well?

**Comment by jamesdeluk** [comment]
I've systematically gone through them all; SB seems to be the only one that causes the issue.

I've also noticed it doesn't happen every time; more times than not the bar is grey, but occasionally it's red. I can't figure out the common reason though.

**Comment by jamesdeluk** [comment]
Saw something interesting today. Sometimes (?) the section turns red after being played:

![image](https://github.com/user-attachments/assets/9f222421-8d87-419f-90e9-9be604b1af5f)

**Comment by chk1** [comment]
This video has the same issue that OP describes, no red color in the elapsed part, no matter how many times I refresh: https://www.youtube.com/watch?v=w5txssFShY8

![image](https://github.com/user-attachments/assets/4090a379-872c-4490-bde9-715af2272d10)

Youtube today switched me to a new desktop design, which can be identified by the gray header bar and seek bar color that turns slightly pink towards the end. May or may not be related to this, I've not seen any other videos that have this issue yet. 

![image](https://github.com/user-attachments/assets/4c029cc9-a21f-40ad-9b94-4be3a60ccbfc)

My only other Youtube addon is Return Youtube Dislikes, which does not affect the behaviour, but I can reproduce it by disabling Sponsorblock. When I resize my browser window, and the player redraws some UI (?), the red color re-appears sometimes.

Using Firefox 131.0.3
