### ISSUE TITLE
Segment from Video A Loaded in Video B 

### ISSUE THREAD

**Issue by julysfire** [ajayyy/SponsorBlock#2101]
Not sure exactly how this happened but after I submitted a segment for one video, I went back to the Youtube Homepage and loaded into another video.  The segment was an Intro/Intermission segment that obviously did not fit well with Video B so I downvoted it and then saw in Discord that the segment I downvoted was the one I submitted in Video A.

**Video A**
https://www.youtube.com/watch?v=Ao724hS7Iv0
(Hey don't judge, I'm boring)

Submission: 09ccf15955850bcf4af60a53a0ec19cfa642c6ab73f01e36644fb864157bc2bb7

**Video B**
https://www.youtube.com/watch?v=kg96CGnXqWs

**Screenshot from Youtube**
![image](https://github.com/user-attachments/assets/676b8709-e346-451d-9a54-1b823edd1b6f)

**Self downvote**
https://discord.com/channels/603643120093233162/659061830936952862/1283950092868517981

Not sure if this was just a fluke or what so thought I would report it just in case.  Feel free to reach out if you need any more information.

**Comment by ajayyy** [comment]
How did you get to the next video (clicking a link? etc.)

**Comment by julysfire** [comment]
> How did you get to the next video (clicking a link? etc.)

I clicked "YouTube" at the top of the page to go back to the homemade and then I clicked the link to the next video from the homepage (One of videos in the first two rows).

**Comment by CaelTheColher** [comment]
This also happened to me, but it seems to be just segments from random videos and not ones submitted

So for example I got segments in [this video](https://www.youtube.com/watch?v=IpArwqdX2Mw) (which coincidentally is also a Big A video, but I have also gotten misplaced segments in videos from other channels), that are actually segments from [this video](https://sb.ltn.fi/video/YaOvtL6qYpc/) which I haven't watched prior to this, and reloading the page seems to make the misplaced segments go away.

I don't know if this helps but segment ids were:
14b88b40023a706539e2ed0f6cc001b7379edc917de4b2252d46f2ec302135e86
65d105afc810cd3e96fe98e675cc9911901356f64b75f073038b13fb2ffe08646
d4d4c73135b222fa1823bd64a2a523a70c96aadd23ed5386726ea0f917c07a8b7

**Comment by ajayyy** [comment]
What browsers are you on? If this happens again, could you click the "copy debug info" button at the bottom of the popup?

**Comment by ajayyy** [comment]
5.9 includes a potential fix for this. Let me know if you still experience this after updating (it will take some time to roll out on the extension stores)
