### ISSUE TITLE
Can't upload sponsor block [Status 500]

### ISSUE THREAD

**Issue by SrMilton** [ajayyy/SponsorBlock#2103]
![image](https://github.com/user-attachments/assets/101afb4a-3eda-433c-ab8f-6833314a2e7b)

All services are online

![image](https://github.com/user-attachments/assets/c1c9da80-a14f-4c17-a827-8f57f0cb2b52)

Video URL: https://www.youtube.com/watch?v=d7gDMHtSBHQ

**Comment by X13X** [comment]
Same here

**Comment by SrMilton** [comment]
It's working again
