### ISSUE TITLE
ABP Japanese Filters blocking Sponsorblock ("Segments are still being loaded")

### ISSUE THREAD

**Issue by Alf3rez** [ajayyy/SponsorBlock#2104]
Hi, I know that this is something that is probably not solvable by this side, but I think that could be helpful for others to know that if Sponsorblock isn't loading segments with classical **"Segments are still being loaded"** message (I was facing this issue in Vivaldi browser) the guilty was ABP Japanese Filters list in the adblocker list, for some reason is impeding Sponsorblock of doing its work.

[k2jp ABS Japanses Filters](https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt)

At least if it has nothing fixable, somebody has not to blown his mind looking for a solution to the issue or even worse, resetting all browser settings to discover that is not fixed.

Thank you for your work.

**Comment by ajayyy** [comment]
It looks like that filterlist is abandoned. You should report this issue to ABP and switch to ublock origin.
