### ISSUE TITLE
Server side ad injection protection trigged with YouTube Premium

### ISSUE THREAD

**Issue by testsnake** [ajayyy/SponsorBlock#2108]
I'm aware the server side ad injection can break the extension, however I use YouTube Premium. Despite this, the submission protection was still triggered.
It seems to happen at random and I'm not sure how to consistently recreate this.

![image](https://github.com/user-attachments/assets/c5bc6dc0-de5c-4ad2-b285-2247ed5c41a7)

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/commit/7ba6fee9e5b3381ec1ffe0058499274d783c779e
