### ISSUE TITLE
Video is muting an interaction reminder despite being set to skip it

### ISSUE THREAD

**Issue by jvluso** [ajayyy/SponsorBlock#2110]
As title, I have turned off all video muting because I don't like or want that to happen. There is an interaction reminder in the video, and it is being muted not skipped.

debug info:
{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0",
        "platform": "Win32",
        "language": "en-US",
        "extensionVersion": "5.8.1"
    },
    "config": {
        "autoSkipOnMusicVideosUpdate": true,
        "chapterCategoryAdded": true,
        "minutesSaved": 584.6823201333328,
        "categoryPillUpdate": true,
        "showZoomToFillError2": false,
        "categorySelections": [
            {
                "name": "sponsor",
                "option": 2
            },
            {
                "name": "exclusive_access",
                "option": 0
            },
            {
                "name": "chapter",
                "option": 0
            },
            {
                "name": "selfpromo",
                "option": 2
            },
            {
                "name": "interaction",
                "option": 2
            },
            {
                "name": "filler",
                "option": 0
            },
            {
                "name": "preview",
                "option": 0
            },
            {
                "name": "intro",
                "option": 0
            },
            {
                "name": "outro",
                "option": 0
            }
        ],
        "invidiousInstances": 40,
        "showDeArrowPromotion": false,
        "showPopupDonationCount": 4,
        "skipCount": 1263,
        "isVip": false,
        "permissions": {
            "sponsor": true,
            "selfpromo": true,
            "exclusive_access": true,
            "interaction": true,
            "intro": true,
            "outro": true,
            "preview": true,
            "music_offtopic": true,
            "filler": true,
            "poi_highlight": true,
            "chapter": false
        },
        "defaultCategory": "chooseACategory",
        "renderSegmentsAsChapters": false,
        "whitelistedChannels": 0,
        "forceChannelCheck": false,
        "sponsorTimesContributed": 0,
        "submissionCountSinceCategories": 0,
        "showTimeWithSkips": true,
        "disableSkipping": false,
        "muteSegments": true,
        "fullVideoSegments": true,
        "fullVideoLabelsOnThumbnails": true,
        "manualSkipOnFullVideo": false,
        "trackViewCount": true,
        "trackViewCountInPrivate": true,
        "trackDownvotes": true,
        "trackDownvotesInPrivate": false,
        "dontShowNotice": false,
        "noticeVisibilityMode": 3,
        "hideVideoPlayerControls": false,
        "hideInfoButtonPlayerControls": false,
        "hideDeleteButtonPlayerControls": false,
        "hideUploadButtonPlayerControls": false,
        "hideSkipButtonPlayerControls": false,
        "hideDiscordLaunches": 0,
        "hideDiscordLink": false,
        "supportInvidious": false,
        "serverAddress": "Default server address",
        "minDuration": 0,
        "skipNoticeDuration": 4,
        "audioNotificationOnSkip": false,
        "checkForUnlistedVideos": false,
        "testingServer": false,
        "refetchWhenNotFound": true,
        "ytInfoPermissionGranted": false,
        "allowExpirements": true,
        "showDonationLink": true,
        "showUpsells": true,
        "showNewFeaturePopups": true,
        "donateClicked": 0,
        "autoHideInfoButton": true,
        "autoSkipOnMusicVideos": false,
        "scrollToEditTimeUpdate": false,
        "showChapterInfoMessage": true,
        "darkMode": true,
        "showCategoryGuidelines": true,
        "showCategoryWithoutPermission": false,
        "showSegmentNameInChapterBar": true,
        "useVirtualTime": true,
        "showSegmentFailedToFetchWarning": true,
        "allowScrollingToEdit": true,
        "deArrowInstalled": false,
        "showDeArrowInSettings": true,
        "shownDeArrowPromotion": false,
        "cleanPopup": false,
        "categoryPillColors": {},
        "skipKeybind": {
            "key": "Enter"
        },
        "skipToHighlightKeybind": {
            "key": "Enter",
            "ctrl": true
        },
        "startSponsorKeybind": {
            "key": ";"
        },
        "submitKeybind": {
            "key": "'"
        },
        "actuallySubmitKeybind": {
            "key": "'",
            "ctrl": true
        },
        "previewKeybind": {
            "key": ";",
            "ctrl": true
        },
        "nextChapterKeybind": {
            "key": "ArrowRight",
            "ctrl": true
        },
        "previousChapterKeybind": {
            "key": "ArrowLeft",
            "ctrl": true
        },
        "closeSkipNoticeKeybind": {
            "key": "Backspace"
        },
        "payments": {
            "licenseKey": null,
            "lastCheck": 0,
            "lastFreeCheck": 0,
            "freeAccess": false,
            "chaptersAllowed": false
        },
        "colorPalette": {
            "red": "#780303",
            "white": "#ffffff",
            "locked": "#ffc83d"
        },
        "barTypes": {
            "preview-chooseACategory": {
                "color": "#ffffff",
                "opacity": "0.7"
            },
            "sponsor": {
                "color": "#00d400",
                "opacity": "0.7"
            },
            "preview-sponsor": {
                "color": "#007800",
                "opacity": "0.7"
            },
            "selfpromo": {
                "color": "#ffff00",
                "opacity": "0.7"
            },
            "preview-selfpromo": {
                "color": "#bfbf35",
                "opacity": "0.7"
            },
            "exclusive_access": {
                "color": "#008a5c",
                "opacity": "0.7"
            },
            "interaction": {
                "color": "#cc00ff",
                "opacity": "0.7"
            },
            "preview-interaction": {
                "color": "#6c0087",
                "opacity": "0.7"
            },
            "intro": {
                "color": "#00ffff",
                "opacity": "0.7"
            },
            "preview-intro": {
                "color": "#008080",
                "opacity": "0.7"
            },
            "outro": {
                "color": "#0202ed",
                "opacity": "0.7"
            },
            "preview-outro": {
                "color": "#000070",
                "opacity": "0.7"
            },
            "preview": {
                "color": "#008fd6",
                "opacity": "0.7"
            },
            "preview-preview": {
                "color": "#005799",
                "opacity": "0.7"
            },
            "music_offtopic": {
                "color": "#ff9900",
                "opacity": "0.7"
            },
            "preview-music_offtopic": {
                "color": "#a6634a",
                "opacity": "0.7"
            },
            "poi_highlight": {
                "color": "#ff1684",
                "opacity": "0.7"
            },
            "preview-poi_highlight": {
                "color": "#9b044c",
                "opacity": "0.7"
            },
            "filler": {
                "color": "#7300FF",
                "opacity": "0.9"
            },
            "preview-filler": {
                "color": "#2E0066",
                "opacity": "0.7"
            }
        }
    }
}

**Comment by ajayyy** [comment]
This is a type of submission. If someone finds an interaction reminder where the visuals are still required to watch the video, they can submit it as "mute" only

**Comment by jvluso** [comment]
is it currently possible to disable that in the settings or is it something that you'd be interested in me making a pull request that could create an option to ignore those submissions?

**Comment by ajayyy** [comment]
You can disable mute segments in settings

**Comment by neekless** [comment]
> You can disable mute segments in settings

Disabling that just makes it not mute nor skip. How make I make it just skip all muted segments?
