### ISSUE TITLE
Getting Google Adsense pop-ups before video 

### ISSUE THREAD

**Issue by xbright09** [ajayyy/SponsorBlock#2112]
any way of fixing the google adsense popups before the video starting i don't now if its server side or the addon is broken

**Comment by ajayyy** [comment]
what do you mean by this?

**Comment by xbright09** [comment]
> what do you mean by this?

oops sorry for bad post 
![d2ba5aebabbc2388dd6364f11ab9ce4c](https://github.com/user-attachments/assets/9df74a43-5553-48af-a833-d97d71bba189)

**Comment by ajayyy** [comment]
SponsorBlock is not an adblocker. Install ublock origin

**Comment by xbright09** [comment]
> SponsorBlock is not an adblocker. Install ublock origin

i have it installed do you know why this is happening sorry for the post then
