### ISSUE TITLE
Submitting Multiple Segments not working on Livestreams

### ISSUE THREAD

**Issue by bellehop** [ajayyy/SponsorBlock#2113]
Submitting more than one segment on livestreams does not work, correctly. For example, during a livestream there is a break or an intermission, and you submit an Intermission category segment, if you submit another segment (e.g., another Intermission category), the second segment is submitted successfully, but the previous segment disappears and is unsubmitted. This pattern continues with each subsequent segment submission.

**Comment by ajayyy** [comment]
The extension shouldn't allow submitting on active livestreams. Are you submitting from the extension?

**Comment by bellehop** [comment]
My mistake.
