### ISSUE TITLE
Free is sponsored... Right?

### ISSUE THREAD

**Issue by truthsword** [ajayyy/SponsorBlock#2115]
YouTuber says " ... they sent me this <device> free because I'm an affiliate, but this video is not sponsored". Or "they sent me this <device> but have not seen this video prior to posting". 

Both of these are "sponsored" ??? Seems so to me. Maybe they didn't get cash, but they received a device that has value.

Am I right?

**Comment by ajayyy** [comment]
For full video labels, we have the category of "Exclusive access" for this purpose
