### ISSUE TITLE
Seek bar color segments not showing

### ISSUE THREAD

**Issue by lemollie** [ajayyy/SponsorBlock#2116]
I'm using Firefox version 130.0.1 on an Android version 12. SponsorBlock is version 5.9.

![Screenshot_20240927-033743](https://github.com/user-attachments/assets/1b7b8307-ac95-4563-9685-58770dcc5daf)
![Screenshot_20240927-033757](https://github.com/user-attachments/assets/bed52266-556e-49aa-8af5-4a1ceb8a6523)

Here are my current colors for all segments I choose to skip.

![Screenshot_20240927-034011](https://github.com/user-attachments/assets/510c9f3d-b80f-4bb2-a935-084ae519aeab)

**Comment by ajayyy** [comment]
Already fixed in a newer version, you'll have to wait for mozilla to approve it

**Comment by ajayyy** [comment]
Looks like I only fixed it for chaptered videos, next version will fix it for other videos
