### ISSUE TITLE
CTRL+ENTER is not working for me anymore on Edge.

### ISSUE THREAD

**Issue by gir489returns** [ajayyy/SponsorBlock#2119]
I am using v.5.9.2 and I get the notification to press CTRL+ENTER to skip to the highlight, like for example this clickbait-ass video: https://youtu.be/0aGNAxN5Z-o But when I press it, nothing happens. If I manually go to the shield icon and click and the skip button, it does skip to 15:30. But pressing CTRL+ENTER does nothing.

![image](https://github.com/user-attachments/assets/c2c59771-626c-4ead-8b61-24b7a7cc3f43)

**Comment by ajayyy** [comment]
This is fixed in 5.9.3

**Comment by gir489returns** [comment]
It says on the Edge store it was last updated yesterday, but that the version is still 5.9.2.

**Comment by ajayyy** [comment]
Yes you have to wait for Microsoft to review it

**Comment by ChromiaCat** [comment]
Regular enter is fixed, numpad enter is still broken.
