### ISSUE TITLE
502 error - server issues.

### ISSUE THREAD

**Issue by VileAce** [ajayyy/SponsorBlock#2146]
Starting yesterday, I have been getting many errors when submitting segments.  Below is the initial error.

The server seems to be overloaded. Try again in a few seconds. Error Code: 502

Check status.sponsor.ajay.app for server status.

After trying to submit the segments again I get the following error

The server seems to be overloaded. Try again in a few seconds. Error Code: 502

Check status.sponsor.ajay.app for server status.This has already been submitted before Error Code: 409

Segment has already been submitted before.

When I reload the page about 50% of the time my submitted segments are there.  The rest of the time the submitted segments are not there.

I did test both with all my extensions and in incognito/private mode (I use Firefox), with only SponsorBlock allowed in private mode.

I do not use a VPN or proxy.

Using 132.0.1 (64-bit) and SponsorBlock v. 5.9.5.

Let me know if you need more information.  I can run my dev monitor and trace the traffic to see where the error is stemming from if you need it.

**Comment by ramazansancar** [comment]
Same issue

**Comment by ramazansancar** [comment]
Even though it gives 502 and 429 errors, it sometimes sends :D

![image](https://github.com/user-attachments/assets/b23ec3d7-2ca8-4162-9f43-204fc7384f80)

**Comment by ajayyy** [comment]
should be fixed

**Comment by VileAce** [comment]
Still occurring as of 8:30pm ET 11/7/24.
