### ISSUE TITLE
Stopped working for whatever reason. Firefox, Windows 10

### ISSUE THREAD

**Issue by odoniset** [ajayyy/SponsorBlock#2158]
Hi, sorry I'm not tech-savvy at all, wanted to ask the question on discord but it says the invite-link no longer works...

A few weeks ago some YouTube browser extensions stopped working, both at the same time. SponsorBlock and Return Dislikes. ‘Enhancer for Youtube’ works though. 

I tried to reinstall the extensions but it didn’t help.
I didn’t install any new extensions for the past years. I have only Ublock, translators,  privacy badger, decentraleyes extensions.

I really don’t want to reinstall the browser itself (Firefox, win10), because I will have to manually restore all of my data. I know there’s a sync option but the last time I tried it, it doesn’t sync everything, I had to spend hours manually restoring a lot of the stuff, so I hate to reinstall this browser. 
Is there anything else I can try to do? What can even be the reason of these two extensions’ failure?

**Comment by Bruno-JA** [comment]
I have the exact same issue with sponsorblock, segments are no longer skipped automatically, even thought i can see the timestamps.

Also running **Firefox version 132.0.2 (64-bit)** on **Windows 10 22H2**

**Comment by Bruno-JA** [comment]
> Try disabling "Enhancer for Youtube", it's probably the same incompatibility reported in #2138 after a recent update to that plugin.
> 
> If that works to fix your issue, it might be a few days before it's resolved. Keep the plugin disabled for a bit to work around it until a patch fixes the issue.

Yep, disabling *enhancer for youtube* does solve the issue. But checking #2138 and reading what *TheDoubleD* commented, disabling autoplay does not solve the issue for me, as i already had that option unmarked. 

Is there a github repo or any way to report this issue to the *Enhancer For Youtube* developer? i can only find the extension website, but there isn't anything usefull there.

**Comment by Aescfue** [comment]
It also work if you reload the video page with cache clean control + f5

**Comment by engineeror** [comment]
happening with brave as well, not just windows.  
hard refresh also works for me. or in settings set `Sponsor` to `Disable` then back to `Auto Skip` then normal refresh

**Comment by GenocideStomper** [comment]
> or in settings set `Sponsor` to `Disable` then back to `Auto Skip` then normal refresh

This only works for me until I restarted Firefox.

**Comment by engineeror** [comment]
i meant those are my workarounds that i keep doing. they don't resolve the issue permanently

**Comment by ajayyy** [comment]
8ce15e69fbd7a5b7058a3650a2dc903189700afc
