### ISSUE TITLE
Sometimes "Skip" button is replaced by "go back" while teh segment is still playing

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [ajayyy/SponsorBlock#2160]
![изображение](https://github.com/user-attachments/assets/f5a189f6-52a3-4ac7-87eb-e7c40776726e)

In the image above, the widget that appears when watching a segment that you can skip, has a "Go back" (Назад) button instead of "Skip" (Пропустить). Clicking it will move you to the start of segment, just as the button's text suggests. When using enter, the segment gets skipped properly.

I'm using Firefox 132.0.2 on Linux via flatpak and SponsorBlock 5.9.6, had this problem for a while but didn't report as I usually use Enter to skip.

I did look for similar issues but haven't found one.

Debug information: https://gist.github.com/JohnTheCoolingFan/86d528dea7261dc54e790cdf39e0f322

**Comment by Aspireve** [comment]
Heyy Hi!!
Could I try sorting this issue. I just had a look at the code and understood what might be wrong with it

**Comment by ajayyy** [comment]
@Aspireve sure!

**Comment by TheNoFace** [comment]
It happens to me, and it's been around for some while. It shows `Unskip`button first, not `Skip`. If I tries to skip using keyboard shortcut, it skips normally, but if I press `Unskip` button, it just turns into `Reskip` button and do not skip the segment.

It happens only on Firefox, Chrome version works as intended.

- Initial popup
![image](https://github.com/user-attachments/assets/e94e4b1f-85f1-4211-b4e4-73dfe8fa700d)

- After pressing unskip button manually
![image](https://github.com/user-attachments/assets/d0b0f33a-eb5d-41ef-bc47-03eac23d6ab3)

- Versions
  - Firefox 133.0.3
  - Sponsorblock 5.10.1

**Comment by ajayyy** [comment]
It only happens before the video starts?

**Comment by TheNoFace** [comment]
> It only happens before the video starts?

It happens on every segment popups, including manual skip and automatic skip.

**Comment by ajayyy** [comment]
Found the issue

**Comment by JohnTheCoolingFan** [comment]
Thank you for the fix!
