### ISSUE TITLE
Feature suggestion: Option to not download sponsored content into memory

### ISSUE THREAD

**Issue by thepwrtank18** [ajayyy/SponsorBlock#2161]
For data plans that intentionally throttle sites such as YouTube, every byte counts. It would be nice for an option for anything sponsored (or otherwise labeled) to not be downloaded to memory, downloading what's after instead. That way, there wouldn't be any data wasted on something you don't want to watch, and the transition between the video before and after the sponsor is smoother and doesn't have buffering.

**Comment by nuenuewei** [comment]
AFAIK this isn't technologically possible. Youtube's streaming system does divide the video up into chunks, but the granularity isn't very high, even if you skipped a chunk it wouldn't align with the segment, and skip too much or too little.

**Comment by ajayyy** [comment]
#543
