### ISSUE TITLE
Currently not skipping segments (Firefox)

### ISSUE THREAD

**Issue by manusoftar** [ajayyy/SponsorBlock#2163]
The last week (November 25th to November 30th and counting, 2024), SponsorBlock is not skipping the segments, it detects the segments but it just don't skip them...

I'm running it on Firefox v133.0, I really don't know if this is something general because Youtube made something to render SponsorBlock useless or if it is something specific of Firefox.

In any case, let me know if I can provide any additional information to find out why it is not working on my end.

Thanks.-

**Comment by smthotherwise** [comment]
Same issue on my Firefox, v133.0 on Linux Mint

**Comment by ajayyy** [comment]
Please wait for 5.10

**Comment by manusoftar** [comment]
> Please wait for 5.10 or disable enhancer fr YouTube if you have it installed

I will try disabling enhancer which I do have. Also, it would be nice if SponsorBlock would also skip "normal" ads like adblock for youtube does so we wouldn't need to have multiple extensions installed to be able to propperly enjoy youtube.

**Comment by ajayyy** [comment]
Use ublock origin

**Comment by smthotherwise** [comment]
Disabling Enhancer for Youtube fixed this issue. Thank you!

**Comment by berbunda** [comment]
I have not Youtube enhancer. I try disable ublock origins, delete "youtube shorts disabler"
All of there did not help - segments is not loadning
Firefox 133.0.3

**Comment by Krzysiu** [comment]
> I have not Youtube enhancer. I try disable ublock origins, delete "youtube shorts disabler" All of there did not help - segments is not loadning Firefox 133.0.3

It happened to me, possibly Firefox error. I suggest reinstalling extension (addons>remove it>RESTART FX {!)>install extension again). Just keep in mind you'd lose settings.
