### ISSUE TITLE
Out of curiosity, does "Hide options not available without extra payment" actually do anything?

### ISSUE THREAD

**Issue by jeffreymcclain** [ajayyy/SponsorBlock#2167]
I noticed in the SponsorBlock Chrome extension's options, at the bottom of the "Interface" section there is a toggle for "Hide options not available without extra payment". I was just curious if that option actually does anything currently since afaik SponsorBlock is FOSS and thus completely free to use without any paywalled "premium" features, or maybe that option had a use in the past or is intended for a future version?

<img width="1490" alt="image" src="https://github.com/user-attachments/assets/2606ab11-c335-473c-bb72-1cb6c8c70361">

P.S.:  Did you graduate from university in January like it mentions on your donation page https://sponsor.ajay.app/donate/ ? If so, congratulations! Also on a tangential note, you might want to update the first paragraph on your donation pages (your own website, GitHub donations, Liberapay, etc) to mention that you've graduated and any other career or life updates you'd like to include, since the current phrasing "In January 2024, I will be graduating" on those pages is a bit ambiguous as to whether or not you've actually graduated, since that date is in the past now. Anyways love your extension and wish you the best of luck with your endeavors!

**Comment by ajayyy** [comment]
This option will hide any mentions of [DeArrow](https://dearrow.ajay.app/). In the past the "chapters" category was a paid feature, which is when the option was initially added.
