### ISSUE TITLE
Clarify "interaction reminder" as "like/comment"?

### ISSUE THREAD

**Issue by Heralda** [ajayyy/SponsorBlock#2170]
The app has a category called "interaction reminder". But it lists "subscribe" as the only type of interaction reminder it refers to.

However, a lot of videos contain reminders similar to "interact with the video, comment and like as if your grandmother's life depended on it" every 1-4 minutes. I've tried to report these as "interaction reminders", but because the "interaction reminder" specifically, and only, lists "subscribe" as what qualifies as an interaction reminder, these reported segments quickly get downvoted.

Either clarifying that all interaction reminders (like/comment) qualify, or creating a separate category for like/comment interaction reminders would dispel any ambiguity.

**Comment by Krzysiu** [comment]
It's the name of the category, it doesn't say "subscribe and nothing else". There's help button ("(?)"), next to the dropdown and it opens the wiki on https://wiki.sponsor.ajay.app/w/Interaction_Reminder_(Subscribe) which states that it includes "Short reminders to Like, Subscribe, Follow, Interact, or watch to the end".
