### ISSUE TITLE
[Add request] Technical issue/s

### ISSUE THREAD

**Issue by baelrayneVessdren** [ajayyy/SponsorBlock#2171]
Many thanks for this great Expansion. Works great and is a huge quality of life increase. 

Would like to request a category "Technical issue/s". Have been watching a video recently and the creator had some microphone issues for the first 2-ish minutes. Would like to report those and be able to skip them.

Many thanks for your continued support.

Best regards

**Comment by ajayyy** [comment]
You can use "intermission"
