### ISSUE TITLE
Feature: Category for relevant sponsored segments

### ISSUE THREAD

**Issue by jasondyoungberg** [ajayyy/SponsorBlock#2177]
Sometimes I'm watching a video and I'll have to go back because a bunch of useful and relevant information was skipped over because there's a sponsorship. One example is [this video](https://youtu.be/PVpP9gcnIcE?t=11m1s), where he explains how gamma spectroscopy works, while also being sponsored by a device that does this. I would like to be able to see these parts of videos without having to manually rewind every time.

**Comment by PatrickKennedy** [comment]
I don't think a new segment type is necessary, at least for that video, these segments entirely eliminate the "look at this product and all it's *amazing* features" aspect of the explanation:

11:27.197 - 11:47.479 Sponsor
12:25.041 - 12:27.473 Sponsor
12:39.367 - 13:04.178 Sponsor
13:16.239 - 13:22.727 Sponsor
13:34.577 - 13:46.820 Sponsor
14:29.881 - 14:35.243 Sponsor

> If it's considered relevant, then it will not be marked. In this case, it's not considered relevant

Not really sure how we know it's not considered relevant given a locked segment eliminates the whole community driven aspect
