### ISSUE TITLE
Fix help page CORS errors

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#218]
The help page uses a lot of external images currently which produces many errors. Caching them would use a lot of storage however. Maybe just load the help page from https://sponsor.ajay.app/help?

**Comment by jplsek** [comment]
Not sure what you mean by loading the help page, just add a link to it.

**Comment by ajayyy** [comment]
The help page is opened on install.

**Comment by OfficialNoob** [comment]
https://sponsor.ajay.app/help seems to be English only is there any way to specify the language to be used like https://sponsor.ajay.app/help/en-US/

**Comment by ajayyy** [comment]
That is a good point.

**Comment by jplsek** [comment]
Gatsby (from my PR) seems to have internationalization support. We could see about moving the help page to SponsorBlockSite and using that.
