### ISSUE TITLE
[Feature Request] Channel specific/Blacklist/Group auto-skipping rules

### ISSUE THREAD

**Issue by Irmitya** [ajayyy/SponsorBlock#2180]
Most channels, I want to skip paid advertising automatically. 
Some channels you do want to see the ads or at least not automatically skip them, which you can say that by adding them to your whitelist. 

Most channels, I don't want to skip their unpaid/self-advertisements. 
SOME CHANNELS, I want to skip all their advertisements! 

To my knowledge my only option to auto-skip unpaid adverts for just "some channels" is to auto-skip all channels and then whitelist/un-skip everyone else. 
If there's already a way to do this, that'd be great but my request is to have a method to 
"not skip certain segments by default" 
but "always skip certain segments from certain channels"

**Comment by mark-addams001881** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a new configuration option 'autoSkipSelfPromoChannels' to store the list of channels where self-promotion segments should be auto-skipped.

You can review changes in this commit: https://github.com/mark-addams001881/ajayyy-SponsorBlock-2180/commit/7e344bfdac3a6769ff58f8d4d211cd46f3ecd4ee.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ajayyy** [comment]
#435
