### ISSUE TITLE
Add information about being open source to Chrome Web Store

### ISSUE THREAD

**Issue by tomasz1986** [ajayyy/SponsorBlock#223]
First of all, thank you very much for this extension.

This is not really a very important issue, but I think that the current description available at the Chrome Web Store,

>Skip over sponsorship on YouTube videos. Report sponsors on videos you watch to save the time of others.

>SponsorBlock is an extension that will skip over sponsored segments of YouTube videos. SponsorBlock is a crowdsourced browser extension that let's anyone submit the start and end time's of sponsored segments of YouTube videos. Once one person submits this information, everyone else with this extension will skip right over the sponsored segment.

is a little bit too short and does not do enough justice to how good the extension actually is :wink:. Nevertheless, I also believe that it would be beneficial to clearly state there that the extension is open source with a possible link to the GitHub repository.

I cannot speak for others, but I specifically install only open source extensions, and this kind of information could be very valuable to similarly minded people.

**Comment by ajayyy** [comment]
Good idea, I can copy some of the description from the website
