### ISSUE TITLE
Better explain that report = downvote

### ISSUE THREAD

**Issue by marekdedic** [ajayyy/SponsorBlock#231]
Hi, originally, I didn't get that reporting in the floating window is the same as voting in the add-on window. "Report" sounds much more serious than a downvote.

**Comment by ajayyy** [comment]
Maybe I should just revert to the old system of having an upvote and downvote button on the popup.

**Comment by marekdedic** [comment]
I like the system of no action = upvote. Just my 2 cents...

**Comment by ajayyy** [comment]
That is what is currently in place, but it isn't really working. Really bad
submissions are getting 300+ upvotes still because people don't check

**Comment by marekdedic** [comment]
Oh, is that the case? I would expect bad submissions getting a lot of upvotes (because people don't vote at all or just miss the floating button when taking a sip of tea and can't be bothered to go to the menu in the add-on (my case :D)), but also a lot of downvotes...

Maybe different weight on "no action" and explicit upvote? Like no action being +1, explicit upvote +3? Just throwing ideas...

**Comment by ajayyy** [comment]
I have done that for now. I have slowly raised the weight. Downvotes are now -10. I also opened a channel on Discord that shows all of the downvotes. Users that I set as VIP can remove all votes with one downvote, so they can monitor that channel.

**Comment by haluzpav** [comment]
"Report" sounds to me like "The system was abused and requires human check" or "Person who did this should be punished". In reality I'd just want to shift the skip by a second or two.

**Comment by marekdedic** [comment]
Yeah,
that's what I was aiming at with #232...

**Comment by ajayyy** [comment]
I am planning to switch back to upvote/downvote

**Comment by ajayyy** [comment]
Done
