### ISSUE TITLE
Old YouTube Fullscreen videos don't change URL

### ISSUE THREAD

**Issue by 3ICE** [ajayyy/SponsorBlock#233]
Submitting a 0:00-7:14 sponsor time skipped that length of time in the up next video (autoplay is always re-enabled in incognito mode)
^says it all.
A refresh fixed it.

**Comment by ajayyy** [comment]
I don't understand what you are saying.

**Comment by 3ICE** [comment]
Yes! Very good catch. IIRC Since 2016 full screen behaves differently when navigating — it doesn't reload the page only replaces all its contents. And the URL bar doesn't even update until you exit full screen at which time the page also reloads. Horrible.
Anyway, to clarify further:
I submitted a new sponsor time from within an incognito window for a livestream (archive).
I then kept watching the same video for an hour.
At the end, YouTube Autoplay redirected me to the up next video (I hate that feature!)
And this next video also displayed a purple bar as if I had submitted sponsor for that video as well.
And yeah, it started playback from the 7 minute mark as that's what I submitted (but for the LAST video not this one)
My new userID on sponsor.ajay.app / SponsorBlock is simply: 3ICE
It says I have one submission, so it wasn't duplicated in the DB, only locally.

**Comment by ajayyy** [comment]
Same issue as https://github.com/ajayyy/SponsorBlock/issues/150

Here was the first try to solve this: https://github.com/ajayyy/SponsorBlock/pull/125

**Comment by ajayyy** [comment]
@3ICE By the way, you might like https://chrome.google.com/webstore/detail/stop-youtube-autoplay/npcghnpganhnghapekiicaeiobnhbbfa

**Comment by ajayyy** [comment]
This seems to not occur on the new YouTube

**Comment by ajayyy** [comment]
old youtube is gone :(
