### ISSUE TITLE
Extension skips time from different videos

### ISSUE THREAD

**Issue by Geroyuni** [ajayyy/SponsorBlock#24]
Demonstrated [here](https://www.youtube.com/watch?v=BCDX7WvVtK8). A reload fixes it, could be to do with youtube's 'dynamic' loading of pages

**Comment by ajayyy** [comment]
Fixed in https://github.com/ajayyy/SponsorBlock/commit/45f0d65f69ed6078094759a43fbd10cfa3ec9e56. Thanks for the report!

**Comment by ajayyy** [comment]
Fixed again in https://github.com/ajayyy/SponsorBlock/commit/a2312a10be29fcb99eba9993294384ea560624ba
