### ISSUE TITLE
Options button doesn't work on info menu (in the YouTube site)

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#240]
```
chrome.runtime.openOptionsPage is not a function
    at HTMLButtonElement.openOptions (chrome-extension://mnjggcdmjocbbbhaepdhchncahnbgone/popup.js:834)
```

**Comment by OfficialNoob** [comment]
Does chrome.runtime.openOptionsPage only work in a background script?

**Comment by ajayyy** [comment]
No, it works in the popup.

**Comment by OfficialNoob** [comment]
Maybe it would work if you sent a message to the background script

**Comment by ajayyy** [comment]
It can only happen on user input, so I don't think that would work. Maybe
the issue is that there is an await somewhere?

**Comment by OfficialNoob** [comment]
https://github.com/ajayyy/SponsorBlock/pull/244
