### ISSUE TITLE
-1 Sponsor Skips on the Pop-Up

### ISSUE THREAD

**Issue by OnurKader** [ajayyy/SponsorBlock#256]
Hello I've noticed that the pop-up says I've skipped minus one sponsors since December 5th.

**` You have skipped -1 sponsors since December 5th.
You have saved yourself 11h 15.3 minutes since December 5th`** 

The time skipped looks correct

![Screenshot_Sponsor](https://user-images.githubusercontent.com/33760623/73412946-3a941400-4302-11ea-912a-45dc754afe56.png)

Thank you for such a great extension 💙

**Comment by ajayyy** [comment]
Ah darn, it seems there was some code that reset the sponsor skip count for no reason.
