### ISSUE TITLE
MapIO should use the SB.localconfig map

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#258]
Otherwise it can get out of date.

**Comment by OfficialNoob** [comment]
MapIO does use SB.localConfig

**Comment by OfficialNoob** [comment]
this.map = SB.localConfig[this.id];

chrome.storage is used to store and sync the data

**Comment by ajayyy** [comment]
It does this at the beginning

**Comment by ajayyy** [comment]
Every time get is called, it uses the cached one

**Comment by OfficialNoob** [comment]
I think MapIO is created on every get anyway so I dont think it would make much difference

**Comment by OfficialNoob** [comment]
should this be closed?

**Comment by ajayyy** [comment]
No
