### ISSUE TITLE
When I enable the addon it maxes out my network, over 40MiB/s

### ISSUE THREAD

**Issue by T7000** [ajayyy/SponsorBlock#267]
When I toggle the addon in firefox I see my network usage go way up in task manager. I was investigating and using task manager because Firefox was eating all my ram this morning...

![image](https://user-images.githubusercontent.com/16760518/74098614-8de43e80-4b1a-11ea-932f-5c74de25a2c8.png)

**Comment by T7000** [comment]
Here's a video https://streamable.com/xcion

**Comment by T7000** [comment]
Doesn't happen when I install 1.2.5

**Comment by ajayyy** [comment]
Closing since the other one has more discussion.
