### ISSUE TITLE
SponsorBlock suddenly using a lot of resources

### ISSUE THREAD

**Issue by ideaman924** [ajayyy/SponsorBlock#268]
Hello! I just noticed that my laptop was running quite hot, with Firefox writing a lot of data to the internal disk. Firefox had no YouTube tabs open, so I was quite surprised when I found SponsorBlock using all of the resources:

<img width="319" alt="Screen Shot 2020-02-09 at 6 56 09 PM" src="https://user-images.githubusercontent.com/13326074/74100054-e09b1600-4b6d-11ea-8f13-fd80a2e01f10.png">

Firefox Task Manager:

<img width="1660" alt="Screen Shot 2020-02-09 at 6 57 01 PM" src="https://user-images.githubusercontent.com/13326074/74100064-f9a3c700-4b6d-11ea-8093-3c8aaea8432a.png">

None of the tabs I had open were YouTube, and none of the tabs had any YouTube embeds and what not. What's going on?

EDIT: I disabled the plugin and now Firefox is hardly using any resources. What was SponsorBlock doing in the background?!

**Comment by AntiSol** [comment]
I'm also seeing this issue. Suddenly waterfox is constantly writing ~10MB/s to disk and using ~30% of a processor core. Disabling sponsorblock and restarting the browser returns things to normal. Enabling sponsorblock causes it to start spamming disk and cpu again. 

This started at a similar time as this issue was raised, an hour or two ago. 

I first noticed that the browser became extremely slow and unresponsive while watching youtube videos.

I suspect this and #267 are the same issue.

Waterfox 2020.01.1 / Ubuntu 16.04

**Comment by AntiSol** [comment]
Here's a screengrab showing me enabling sponsorblock and seeing the resulting disk writes (I circle the 2 I/O meters at the start of the video). 

This disk activity will continue indefinitely, writing terabytes of data if left for long enough. I haven't been able to determine which file it's writing to, waterfox has lots of files open.

![sponsorblock](https://user-images.githubusercontent.com/351169/74101631-eb66a280-4b8f-11ea-8047-b599ac39d6e9.gif)

this doesn't happen if I install 1.2.5.

**Comment by surrodox2001** [comment]
In my case, I'm seeing CPU spikes and memory leaks (from Sponsorblock probably) crashing my browser.

Crash report: https://crash-stats.mozilla.org/report/index/4f0904da-5a9c-4f00-acae-24bdd0200209

**Comment by RenaudBompuis** [comment]
Experiencing the same issue: constant high CPU and disk activity and random freezes.
Persists even when there is no page loaded and all other add ons are disabled.
Firefox 72.0.2 (64-bit) on Win10

**Comment by ricliu89** [comment]
I'm experiencing the same issue as everyone else. It seems Firefox attempts to write to the file: storage-sync.sqlite in profiles but fails?

**Comment by ajayyy** [comment]
Are you guys all using Firefox?

**Comment by surrodox2001** [comment]
Yes

**Comment by ajayyy** [comment]
My theory is that the config code is doing some infinite recursion due for some reason.

**Comment by ajayyy** [comment]
1.2.5 has been rereleased as 1.2.7 as a temporary solution.

**Comment by ricliu89** [comment]
![Sponsorblock_diskusage](https://user-images.githubusercontent.com/28044827/74104117-02869f80-4b52-11ea-84fe-ef2e0425ed45.png)
Here's a screenshot of the disk activity that happens when Sponsorblock is enabled. There are many many more further below I did not capture.

**Comment by ajayyy** [comment]
I discovered the issue.

**Comment by AntiSol** [comment]
Thanks! :)
