### ISSUE TITLE
Add release notes to AddOn settings

### ISSUE THREAD

**Issue by valsu** [ajayyy/SponsorBlock#270]
First, let me say thank you for this great extension!

Would it be possible to add the current release notes as shown on
https://github.com/ajayyy/SponsorBlock/releases
to the version notes tab in the Firefox AddOns settings?

**Comment by ajayyy** [comment]
Is this the same one as on the Addon Store? I do put them there.

**Comment by valsu** [comment]
I'm using Firefox with German localization. There seems to be an issue with the changelog not showing if using a locale other than English, both in the extension's settings (version info):
![2020-02-09_21h02_02](https://user-images.githubusercontent.com/12234737/74108975-afc3dc80-4b7f-11ea-946e-6a8eb0a62395.png)
and the Firefox Addons website:
![2020-02-09_21h04_45](https://user-images.githubusercontent.com/12234737/74109000-d7b34000-4b7f-11ea-80dc-3fbd9b0a80c1.png)
I checked and this doesn't happen with other extensions, they show the English version info even with German locale enabled (for both UI and website language).

**Comment by ajayyy** [comment]
This is even worse than I thought as it's even invisible on American English or British English. It is only visible for Canadian English.

**Comment by ajayyy** [comment]
https://discourse.mozilla.org/t/amo-bug-release-notes-not-shown-on-en-gb-install-pages/53608

**Comment by ajayyy** [comment]
This is an AMO bug. It will only show either the native language's changelog or US English. Mine are in Canadian English. I can't find an easy way to switch them to American English without manually going to the settings after each update and copy-pasting.
