### ISSUE TITLE
Constant high Energy Impact

### ISSUE THREAD

**Issue by campbellkerr** [ajayyy/SponsorBlock#271]
Have noticed recently that the addon is consistently showing between medium and high "Energy Impact" (10 to 38) in FF task manager, Even after a restart of the browser. Anyone else with this issue? Screenshot is of a high example:

![image](https://user-images.githubusercontent.com/38451588/74142062-3ba33a80-4c4c-11ea-9d49-58f989c3a079.png)

**Comment by ajayyy** [comment]
Please update to 1.2.8
