### ISSUE TITLE
Youtube tabs no longer recognized

### ISSUE THREAD

**Issue by bergerr** [ajayyy/SponsorBlock#272]
SponsorBlock has stopped recognizing that I'm watching a Youtube video. I've checked on multiple videos, and the option to add a new skip is gone, instead there is just the text 

> No YouTube video found at this tab. If you know this is a YouTube tab, close this popup and open it again. If that does not work, try reloading the tab.

Skips still load correctly and other users can add new skips, but I can't. I can mark times and everything else, but just the options to submit and vote on times is missing.

Things I've tried to fix it:
- refreshing the tab
- closing and reopening the tab
- closing and reopening Firefox
- turning off uBlock

<img width="1241" alt="Screen Shot 2020-02-10 at 1 18 06 PM" src="https://user-images.githubusercontent.com/2348127/74177993-b6f7f280-4c32-11ea-95ff-efbdfc32298d.png">

**Comment by ajayyy** [comment]
Are you ok version 1.2.8?

**Comment by bergerr** [comment]
Yes. Last update was February 10th.

**Comment by ajayyy** [comment]
Good catch. Fixed

**Comment by ajayyy** [comment]
For now, use the popup in the corner (click the extension's icon in the browser toolbar).
