### ISSUE TITLE
Editing times adds 00 to the minutes

### ISSUE THREAD

**Issue by bergerr** [ajayyy/SponsorBlock#273]
When using version 1.2.8 and editing a time using the button in the browser toolbar after saving the time the minutes will have 00 appended to them. 

<img width="320" alt="Screen Shot 2020-02-10 at 5 18 16 PM" src="https://user-images.githubusercontent.com/2348127/74195628-955b3300-4c53-11ea-9768-f9b11acf4f47.png">
<img width="302" alt="Screen Shot 2020-02-10 at 5 18 22 PM" src="https://user-images.githubusercontent.com/2348127/74195630-968c6000-4c53-11ea-8af6-f728734ed460.png">

**Comment by ajayyy** [comment]
Thanks for finding this. Fixed.
