### ISSUE TITLE
Issue with detection youtube videos.

### ISSUE THREAD

**Issue by TacoRat** [ajayyy/SponsorBlock#276]
![image](https://user-images.githubusercontent.com/56605422/74243408-b3ee1800-4cad-11ea-8c1a-95fbaf1c7999.png)
As seen the plugin doesn't seem to detect my video with a sponsor. or any video at all.

**Comment by ajayyy** [comment]
1.2.9?

**Comment by TacoRat** [comment]
Yes. version 1.2.9

**Comment by baltoaca** [comment]
I also have the same issue with 1.2.9 on Firefox.
I downgraded to 1.2.8 and the videos are detected correctly!

**Comment by TacoRat** [comment]
Downgraded to 1.2.8 Issue has vanished.

**Comment by ajayyy** [comment]
Firefox doesn't support the regex I used. I have now changed it to something that works in Firefox.
