### ISSUE TITLE
SponsorBlock no longer skipping segments?

### ISSUE THREAD

**Issue by ideaman924** [ajayyy/SponsorBlock#282]
This is a weird bug... SponsorBlock doesn't seem to be working at all. I can see the green segments on the playback bar, the addon page opens as usual, but the segments aren't getting skipped at all. I've tried refreshing the browser (Firefox lets you purge everything, including preferences and addons, and strart fresh), going into settings of SponsorBlock and making sure auto-skip is enabled, but nothing is working. Any ideas?

Operating system: macOS Catalina 10.15.3
Firefox version: 73.0.1
SponsorBlock version: 1.2.13

**Comment by ajayyy** [comment]
![image](https://user-images.githubusercontent.com/12688112/74954581-50f93100-53d1-11ea-896b-060d79b73f85.png)

Have you clicked that?

**Comment by ideaman924** [comment]
I clicked it twice and it seems to be working again. Sorry about the false alarm, probably Firefox being weird again. Thank you!
