### ISSUE TITLE
Set a hotkey to skip ads.

### ISSUE THREAD

**Issue by VSuhas22** [ajayyy/SponsorBlock#299]
Basically what the title says,
add an option to assign a key to skip the sponsor block.

**Comment by ajayyy** [comment]
For manual skipping?

**Comment by VSuhas22** [comment]
Yes, exactly. Instead of moving the mouse and clicking the prompt it would be nice to just press a button and skip it.

**Comment by ajayyy** [comment]
Do you have any ideas on a good default?

**Comment by VSuhas22** [comment]
I suppose 'S' could be a good default,
just cause Netflix uses the same button to skip intros.

**Comment by ajayyy** [comment]
Okay, I'll see if that has any conflicts

**Comment by Joe-Dowd** [comment]
Doesn't seem like there's a conflict (as far as I was aware at the time I checked to blacklist existing bindings)
https://github.com/ajayyy/SponsorBlock/blob/master/src/options.ts#L355

**Comment by pdonias** [comment]
FYI, 'S' is a default keybind in [Video Speed Controller](https://chrome.google.com/webstore/detail/video-speed-controller/nffaoalbilbmmfgbnbgppjihopabppdk) but I don't know if you want to avoid conflicts with other extensions as well.

![Capture_2020-05-27_17:13:18](https://user-images.githubusercontent.com/10992860/83038901-c6fadd00-a03d-11ea-8147-10ed42551288.png)

**Comment by prediscover** [comment]
how about " \ "? it's near the semicolon and quote keys.

**Comment by garbb** [comment]
I also believe that this keybinding would be a good feature.
I would mention that by default in firefox, the "/?" key is bound to quick search already, and in many websites including github it is bound to activate the search bar in the website, so this key may not be a good one to choose.

**Comment by NtTestAlert** [comment]
Maybe add a section in config to set own hotkeys?

**Comment by ajayyy** [comment]
I went with Enter

**Comment by git-anish** [comment]
> I went with Enter

hey, any chance this gets ported to safari? the current maintainer has no contact info and hasn't merged any new updates from your repo since the initial release

I understand its an unofficial port

**Comment by ajayyy** [comment]
@git-anish As said in https://github.com/ajayyy/SponsorBlock/issues/312, I don't have a Mac. 

By the way, this isn't released in chrome or Firefox yet either, since it will be released as a beta first before being published.

**Comment by pxeger** [comment]
I don't know if Enter is a good idea because if a button or link happens to be focused already (e.g. by pressing Tab by accident) that button will be clicked instead of (or as well as?) the manual skipping. Still, I could just reassign it (assuming it will be configurable like the other keys)

**Comment by ajayyy** [comment]
Yes, it is. I submitted this one to the store yesterday, so it should roll out soon

**Comment by VSuhas22** [comment]
Not sure if this can be fixed but, the skip key doesn't work while the video is not in focus (like you are in the comments or just alt-tabbed into the video)
It only works if the video is already clicked on once.

**Comment by ajayyy** [comment]
This is on purpose to avoid affecting text-boxes
