### ISSUE TITLE
[Fix in place] Sponsors staying from old videos

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#303]
1.2.22

https://discordapp.com/channels/603643120093233162/603643299961503761/690647076983275583

**Comment by ajayyy** [comment]
Check added: https://github.com/ajayyy/SponsorBlock/pull/308/commits/a9993d5d807b35bbf3515c1f2213d7295001f8d7

**Comment by DuckOfDuckness** [comment]
Still present in 1.2.26
If the video page is kept open, the old segment eventually goes away. I assume that's the new check doing its thing, but just a little too slowly.

**Comment by ajayyy** [comment]
New check added: https://github.com/ajayyy/SponsorBlock/pull/322/commits/c31d30821b7b1d2dd078d38f3e0c08e6ffb5db39

**Comment by ajayyy** [comment]
Seems to be only preview segments

**Comment by ajayyy** [comment]
More details: https://github.com/ajayyy/SponsorBlock/issues/667
