### ISSUE TITLE
Option to report bad times

### ISSUE THREAD

**Issue by bubblineyuri** [ajayyy/SponsorBlock#305]
Someone put in a sponsor marker on a video where no sponsoring happens. I thought I could report this, but I didn't find an option for it.

Here's the corresponding video: https://youtu.be/vqduGTChT5U

The intro was kinda skipped and this completely ruined the experience since it blends in perfectly into the rest of the video. How could someone destroy such a master piece.

**Comment by ajayyy** [comment]
You can click report on the notice:

![popup](https://sponsor.ajay.app/new_notice.gif)

If this is disabled, it can be reenabled in the options panel.

You can also click the downvote button in the popup (click the extension icon in the top right or the info button on the player).
