### ISSUE TITLE
Sponsors aren't blocked after video is Looped

### ISSUE THREAD

**Issue by garyking** [ajayyy/SponsorBlock#306]
Watch a video on YouTube, and enable Loop, by right-clicking on the video, and selecting Loop (the first option). When the video finishes, it will Loop.

On the first viewing, the sponsors are skipped, as expected. But on the second viewing, sponsors are not skipped.

If necessary, find a video that has sponsors at the very beginning of the video, like [this one](https://youtu.be/sbdH_JZaJLA).

**Comment by ajayyy** [comment]
I cannot reproduce this

**Comment by garyking** [comment]
Okay, so I just opened the video, Looped it, and jumped to the end. Then it looped as expected, and it did indeed skip the sponsor. I can only assume that the issue only occurs if you play the entire video first, which I know will be difficult to reproduce, without actually playing the entire video first. So I'll just close this for now.

**Comment by ajayyy** [comment]
I can try that with some short test videos

**Comment by ajayyy** [comment]
Which browser?

**Comment by ajayyy** [comment]
I think this is caused by another issue where sponsors in general are not getting skipped sometimes. I have not been able to reproduce this issue myself though but many have reported it.

**Comment by garyking** [comment]
I'm using Chrome 80 on MacOS 10.14.
