### ISSUE TITLE
Feature request: Show sponsor name or setting to allow x seconds of sponsor to play

### ISSUE THREAD

**Issue by gitlover4ever** [ajayyy/SponsorBlock#309]
I find myself constantly going unskipping and re-skipping as sometimes sponsors can be relevant and sometimes provide useful coupons. For that reason, I would like to either be able to see what the name of the sponsor I skipped was or have a setting to allow x seconds before skipping so I know if it is something useful

**Comment by ajayyy** [comment]
You can disable auto skip in the options.
