### ISSUE TITLE
Buttons sometimes not displayed

### ISSUE THREAD

**Issue by twifty** [ajayyy/SponsorBlock#310]
I have created an extension which adds a button to the video player, very much like what SB does with its "Starts now" and "Open popup" buttons. I have noticed that while my button is always added to the bar, SBs buttons are sometimes missing. This appears to be a race condition between the two extensions.

My button is added as:
```js
const button_bar = player.getElementsByClassName("ytp-right-controls")[0]
if (button_bar)
  button_bar.insertBefore(this.__elements.button, button_bar.firstElementChild)
```

While I don't mind changing my code to play nice with SB, this issue must lie within SB itself and conflicts with other extensions may occur.

**Comment by ajayyy** [comment]
Do you know what is causing it?

**Comment by ajayyy** [comment]
Here is the code: https://github.com/ajayyy/SponsorBlock/blob/master/src/content.ts#L938

**Comment by twifty** [comment]
I haven't figured it out yet. It's one of those bugs which refuses to reproduce until you don't expect it. I'll keep my eye on it though.

**Comment by twifty** [comment]
Closing this as it's not really a problem within SB.

In some instances, when another extension (mine in this case) throws an error, or does anything to prevent itself from running correctly, it can prevent other extensions from being loaded. This may be specific to browser/build/error. In this case my error was being swallowed by a Promise.

If this issue comes up again later, make sure users have disabled all other extensions.
