### ISSUE TITLE
Safari extension

### ISSUE THREAD

**Issue by fristys** [ajayyy/SponsorBlock#312]
Is there any chance for a Safari version of SponsorBlock?

**Comment by ajayyy** [comment]
I don't have a Mac to test, so I would not. Does safari support userscripts (tampermonkey) though?

**Comment by fristys** [comment]
> I don't have a Mac to test, so I would not be able to. Does safari support userscripts (tampermonkey) though?

[Looks to be the case](https://www.tampermonkey.net/?browser=safari) .

**Comment by ajayyy** [comment]
https://github.com/avast/topee

**Comment by ajayyy** [comment]
It looks like Apple forces you to pay 100$/year to publish extensions, which is outrageous.

**Comment by 2600box** [comment]
A tamper monkey script would be excellent. I guess most users only use the extension passively?

**Comment by yashendra2797** [comment]
Safari from the next version will also have support for WebExtensionAPI. SponsorBlock could always be like Tampermonkey, and charge $2 in the App Store.

**Comment by ajayyy** [comment]
It doesn't support all the web extension APIs though, but that might not matter for SB. But still, it would require paying 100$/year, converting the extension every time, and buying a mac.

**Comment by yashendra2797** [comment]
Understandable. Is a Userscript for Tampermonkey possible? Any way macOS users could help you out?

**Comment by ajayyy** [comment]
@rakalix has uploaded it to the AppStore: https://github.com/rakalix/SponsorBlock#sponsorblock-for-safari-macos

**Comment by WoodpeckerBaby** [comment]
@rakalix It's broken on macOS Big Sur since November and there is no way to submit issues in the Safari repo. People have been taking about this on reddit. 

This button doesn't do anything and the Safari extension doesn't load. I had to force quit the app. 

<img width="520" alt="Screen Shot 2021-01-01 at 5 49 27 PM" src="https://user-images.githubusercontent.com/14303318/103436700-cbcde200-4c59-11eb-8689-c07a58c7d004.png">

**Comment by ajayyy** [comment]
Working on uploading my own since that one seems to have been abandoned

**Comment by ajayyy** [comment]
Uploaded (Mac only for now)

https://github.com/ajayyy/SponsorBlock/wiki/Safari

**Comment by ln-12** [comment]
Is there a chance to add iOS browser support with the new web extensions?
https://developer.apple.com/videos/play/wwdc2021/10104/

**Comment by ajayyy** [comment]
@ln-12 it supports iOS
