### ISSUE TITLE
Categories for sponsor segments

### ISSUE THREAD

**Issue by Phantom784** [ajayyy/SponsorBlock#314]
I think it'd be useful to allow sponsorships to be categorized, as there are different sorts of segments that different users may or may not want to skip. For example:
 - Channel promoting their own merchandise/Patreon
 - Promoting another YouTube channel as a collaboration
 - Intro/title segments (not really a sponsorship, but some people may want to skip these).

Open to suggestions on categories, though it's probably best to keep it simple.

**Comment by Joe-Dowd** [comment]
This is in progress

**Comment by ajayyy** [comment]
Current category list: ![](https://media.discordapp.net/attachments/650803943152156673/695443175208124497/categoryselection.gif)

Check out the #category-planning channel on [Discord](https://discord.gg/QnmVMpU) for discussion.
