### ISSUE TITLE
Sponsorblock makes firefox unable to load any websites

### ISSUE THREAD

**Issue by Gomam0n-afk** [ajayyy/SponsorBlock#320]
When installing the addon , everything seems fine until i restart the browser , the icon for sponsorblock disapears and leaves an empty button instead , then i'm unable to connect to any website until i uninstall sponsorblock.
more info :
firefox version : Version 68.7.0esr (64-bit) on : ubuntu 19.04 (happens on windows too and on standard firefox releases as well)

i use the following extensions next to it : 
uMatrix , uBlock Origin , WebRTC Control , ViolentMonkey , Decentraleyes
and also a custom user.js you can find here : https://pastebin.com/gRj24nPt

**Comment by ajayyy** [comment]
Version?

**Comment by Gomam0n-afk** [comment]
> Version?
Latest as of 3 days ago , i reported this on the same day i installed the plugin , unless there was an update inbetween 3 days ago and now , it should be : "1.2.24"

**Comment by ajayyy** [comment]
I think you have some other conflicting extension. SponsorBlock doesn't have enough permissions to change anything but YouTube (and Invidious only if you enable the option)

**Comment by Gomam0n-afk** [comment]
> 
> 
> I think you have some other conflicting extension. SponsorBlock doesn't have enough permissions to change anything but YouTube (and Invidious only if you enable the option)

How could i resolve this conflict ? i maybe can try unblocking it from Umatrix , if i find anything i'll write a small tutorial on how to do it for any other people that needs it.

**Comment by ajayyy** [comment]
Maybe try disabling each extension and seeing which one, if any, is causing the issue

**Comment by Gomam0n-afk** [comment]
After testing , i can confidently say none of my extensions were the problem , i ended up changing from Firefox to GNU IceCat (a firefox fork) and use a new user.js (the one from ghacks) , everything is now working fine.

There must be something going on with my own user.js , as another extension , ClearURLs ended up having the same problem.

**Comment by ajayyy** [comment]
Very weird, thanks for posting your solution.
