### ISSUE TITLE
Uploading a sponsored segment when there already is one on the video seems to fail

### ISSUE THREAD

**Issue by arantes555** [ajayyy/SponsorBlock#325]
Hello,

I have noticed recently that when I try uploading a sponsored segment in videos, often it does not seem to do anything anymore. Like I don't even get the (purple I think it was?) segment appearing in my time bar, and when I reload the video it is just not there at all.
I believe it happens most often when there already is another segment uploaded for the same video. Like someone reported the sponsor at the end, but not in the intro. Not sure it is the cause though.

BTW, thank you very much for this incredible extension!

**Comment by ajayyy** [comment]
Are you using the submit button in the popup or on the video player?

**Comment by arantes555** [comment]
@ajayyy I have tried both

**Comment by ajayyy** [comment]
It disappears from your "preview" segments and nothing gets submitted? Do you have a username set. If so, can you send it and I can see if the submissions are in the database. Also send a video it happened on if you know.

**Comment by arantes555** [comment]
Happened to me minutes before I opened this issue on the video https://www.youtube.com/watch?v=MALzcZDkNF0
I tried submitting the segment at the beginning of the video like 3 times, and nothing.

I do not have a username yet, sorry. I will set one now.

**Comment by arantes555** [comment]
The username set right now is d975d15beee3722189bb4cad971a8fbe6df8ae6353e6a1734e042562fa3f342e

**Comment by ajayyy** [comment]
I see a submission there now

**Comment by ajayyy** [comment]
Do you still not see it? Maybe it is some caching issue in your browser. What browser are you using?

**Comment by arantes555** [comment]
@ajayyy so do I now, but after the submissions that seemed to do nothing, I reloaded to make sure and nothing. Now I do see it.

I am using Chrome 80 on macOS.

I will post here again if I see the issue happening again. I will make sure to try a force-reload of the page before.

**Comment by ajayyy** [comment]
Yea, that is odd. I checked the DB, and there are two submissions by you on that video

**Comment by arantes555** [comment]
@ajayyy I guess it is just a UI bug that sometimes make the submission not appear in the timeline + a weird cache thing then.

**Comment by arantes555** [comment]
@ajayyy just happened again on https://www.youtube.com/watch?v=AFT1BkbEtfc (with the segment at the beginning of the video again)

There is definitely a UI issue, the purple bar does not appear and I have zero feedback that the submission was sent, everything just disappears completely.

Also, I have tried reloading the video multiple times after the upload, and the sponsored segment does not appear. I have also tried to load it in another browser (which also has the extension), and I do see the existing segment at the end but not the one I just posted.

It may be nothing, but I just noticed that in both instances the segment I submitted started at 0.0s.

If there is anything else I can do to help debug, let me know!

My username is now `arantes` btw.

**Comment by ajayyy** [comment]
The segment is appearing for me

**Comment by arantes555** [comment]
Still nothing for me. I just see the one at the end.

**Comment by ajayyy** [comment]
Do you have some local network caching or firewall installed?

**Comment by arantes555** [comment]
@ajayyy Nope, normal local home network, normal mac laptop, nothing funky going on.

**Comment by arantes555** [comment]
@ajayyy I took it upon myself to go check the network logs, and I see:
```json
{"sponsorTimes":[[0,12.139779],[267.565,317.7]],"UUIDs":["2173b99c4e8429ec07c9fe6ee82d9da304476a917f5bd029d0292f528a96ff04","5845234f0b6690fd006cb272b924eb549561317fe4fb7d0e426549c96a0d16a5"]}
```
So it does look like the segment at the beginning is given by the server, it just does not appear in the interface. Neither in the player itself, nor in the extension's floating popup.

**Comment by ajayyy** [comment]
What other extensions do you have installed?

**Comment by arantes555** [comment]
@ajayyy :
- uBlock Origin
- Vue.js devtools
- Go Back With Backspace

**Comment by ajayyy** [comment]
I found an issue. It seems the hidden segments list is not cleared properly (when you downvote a segment). That shouldn't affect things when you reload though so it might just be a separate bug.

**Comment by arantes555** [comment]
@ajayyy I have probably used the "unskip" button on this video (and I believe it acts as a downvote?), but I have even tried quitting and re-opening the browser.

I want to note that on this particular video, when I reload, the existing sponsored segment at the end, sometimes it is until the very end, sometimes not. I guess they are 2 "competing" versions of the segment with close numbers of votes, and I get assigned one randomly. So it is definitely reloading the segments.

**Comment by ajayyy** [comment]
The unskip button does not downvote.

I see no possible way that the request can get data and the [code](https://github.com/ajayyy/SponsorBlock/blob/1.2.24/src/content.ts#L591) can remove one arbitrary segment. 

Are you on the beta version of normal release?

**Comment by arantes555** [comment]
Normal I think, currently on 1.2.24

**Comment by arantes555** [comment]
God damn it ... It was shorter than my "minimum duration" ... I reduced it in the options, and now it shows. I think the segments I submitted all were, hence the funky behaviour.

Very sorry to have wasted your time on this one.

**Comment by ajayyy** [comment]
I completely forgot that was a thing. I knew that option would lead to problems
