### ISSUE TITLE
SponsorBlock Chrome extension in Microsoft Edge Store

### ISSUE THREAD

**Issue by EndlessBernkastel** [ajayyy/SponsorBlock#341]
Please also put the Chrome extension on Microsoft Edge store. While we can also use the Chrome extension, this helps with sync.

**Comment by ajayyy** [comment]
Chrome web store extensions don't sync?

**Comment by Restia666Ashdoll** [comment]
On edge, extensions from Edge store will sync.

**Comment by StrangePeanut** [comment]
Came here to open an issue on this. The number of Edge users is growing rapidly. This extension should be made available in the Microsoft Store!

**Comment by ajayyy** [comment]
I'd rather not add another store process to deal with, but now that I am doing beta updates and more rarely releasing normal updates, it wouldn't be too much trouble. Plus, the chrome web store has been pretty sketchy recently

**Comment by StrangePeanut** [comment]
@ajayyy By that logic it’s a bit weird to see Firefox and Opera featured on the site but not Edge which is the second most used browser after Chrome now. It would be nice to bring the extension to many more people!

**Comment by ajayyy** [comment]
Because you can. Install chrome web store extensions on edge

**Comment by ajayyy** [comment]
The opera link just links to chrome web store because I got a lot of people that didn't know it ran chrome extensions

**Comment by ajayyy** [comment]
I filled out the submission to the edge store, but their system is really a mess. They want me to reupload all my images, description etc. for each language (20+) before I can even submit... I think I am going to wait until their system is better developed.

**Comment by NDevTK** [comment]
Chrome extensions only work for the new version of edge.
https://www.microsoft.com/en-us/edge
https://support.microsoft.com/en-us/help/4538971/microsoft-edge-add-or-remove-extensions

**Comment by Restia666Ashdoll** [comment]
Yes we know that. EdgeHTML is abandoned.

**Comment by ajayyy** [comment]
As an update, I emailed about that issue and they said that it is something that plan on fixing in the future, so I'll wait until that is fixed (language issue)

**Comment by ajayyy** [comment]
Well, I did it anyway. I picked the top 12 languages and included them to have _a little_ less work, but it still took too much longer than it should have

**Comment by ajayyy** [comment]
Download: https://microsoftedge.microsoft.com/addons/detail/sponsorblock-for-youtube-/mbmgnelfcpoecdepckhlhegpcehmpmji

**Comment by EndlessBernkastel** [comment]
Thanks for taking your time
