### ISSUE TITLE
Use Weblate

### ISSUE THREAD

**Issue by comradekingu** [ajayyy/SponsorBlock#343]
Hello, I am not a fan of the tracking and profiling Crowdin does. Nor do I find it to be a good tool. Would be nice to see this on Hosted Weblate, along with the likes of https://hosted.weblate.org/projects/invidious/ :)

**Comment by ajayyy** [comment]
There has been a lot of translation activity since I launched it last week, so I think I am going to keep it. Before, there were very few translations.

If it is possible to use both at the same time, that could be done.

**Comment by comradekingu** [comment]
Crowdin has a very clunky UI for getting anything done, and things get held up in their voting system.
It has no community of people helping each-other, and there just isn't anything there for working with the source strings, or sorting out the string-base.

With fewer translators on Crowdin, and good ones fewer still. ~300 translations in 11 days is boils down to this, 9 drive-by translators, you, and then coverage in simplified Chinese. I couldn't tell you what kind of quality that amounts to.

The thing is, nobody checks all the strings to see whether the translation is consistent on Crowdin, because doing so is the same clunky UI as the rest. Instead people do 30-40 translations at a time.

How about trying Hosted Weblate instead, and we will see who does better?

**Comment by ajayyy** [comment]
I'll try when I have some time. I do agree, I really don't like how strict they are about the open source pricing.

**Comment by ajayyy** [comment]
Update: I signed up a day after making that comment but have received no response.

**Comment by comradekingu** [comment]
@ajayyy I'll ask the guy working on that sort of thing what happened :)

**Comment by ajayyy** [comment]
Thanks! It's not rush though, let them take their time

**Comment by ajayyy** [comment]
No response, going to stick with crowdin

**Comment by comradekingu** [comment]
@ajayyy I will ask in the chat what is going on. Other projects added later got in, so must have been left off.

**Comment by ajayyy** [comment]
Hey, thanks. Actually, I think I'll stick with crowdin now since the Vanced project is going to use the Crowdin translation memory to be able to reuse translations.

**Comment by comradekingu** [comment]
@ajayyy that is just a bad idea overall. All the YouTube and similar projects are already on Hosted btw.
Translators shouldn't have to use SponsorBlock to be on he platform it uses. That seems the wrong message to send.

**Comment by comradekingu** [comment]
@ajayyy You can set up shop yourself at https://hosted.weblate.org/hosting/ now.
I can't fix the nb_NO translation since I have stopped using Crowdin because of their terms.
To be fair it is nowhere as bad as the general Crowdin quality.

In the interest of blocking invasive trackers, advertisement, etc. it makes a lot of sense.

**Comment by comradekingu** [comment]
@ajayyy It pains me that a libre software plugin is doing this disservice to its audience.
Crowdin has no community, evident from just 16 languages nearing completion.
This is with millions of users.
Moreover, the "no" locale is wrong for Norwegian Bokmål, and therefore doesn't work. It should be "nb_NO".

**Comment by comradekingu** [comment]
@ajayyy
Fast forward to 2024 there are 10 languages with coverage, three of which are reviewed.
For something that has only 4k words, half a million users on FF-browsers and enjoys a "recommended" badge that is not good.
To make matters worse translations in my language are not even used, because Crowdin employs the wrong locale by default.

This is the only big libre software project to use Crowdin in the interim, and all the other projects that reference SponsorBlock are on Weblate.

It is very hard and tedious to coordinate fixes made to other projects in a consistent manner when they should just not propagate from here.

I really want to help both myself and others in showing you how well you can actually do with translation.
It is a fairly easy process to set that up on https://hosted.weblate.org/hosting/ and I can help if you add "kingu".
The offer does require mentioning WL in the README, which I think is fair.
