### ISSUE TITLE
Support links from embeds

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#36]
They produce links like this:

> https://www.youtube.com/watch?time_continue=470&v=uqKGREZs6-w
> Notice the extra query: `time_continue=470`

This would require changing the regex a bit.

**Comment by Karrq** [comment]
/u/LandKingdom checking in

**Comment by OfficialNoob** [comment]
Done: https://github.com/ajayyy/SponsorBlock/pull/37
