### ISSUE TITLE
Using YouTube keyboard shortcuts to jump forward into a sponsor, doesn't skip it

### ISSUE THREAD

**Issue by garyking** [ajayyy/SponsorBlock#361]
Scenario: You have a video like [this one](https://youtu.be/qz64WP9Wb94?list=WL) and right before the sponsor segment, you hit the "L" key, to jump forward ten seconds. Let's say for this video, that you do that at the 1:10 mark.

Then the sponsor won't get skipped.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/124
