### ISSUE TITLE
sponsor.ajay.app server outage

### ISSUE THREAD

**Issue by benplumley** [ajayyy/SponsorBlock#364]
The main server for the leaderboard page and for serving the sponsorship times to the client seems to be down from certain locations currently. The DNS resolves fine, but the server doesn't seem to respond to requests.

This behaviour seems location-specific - I've fetched it from 173 locations and got 109 errors, with the page loading fine from the remainder.

**Comment by benplumley** [comment]
Getting slightly more information from it now than earlier: 
![image](https://user-images.githubusercontent.com/7894368/83920087-ee575580-a773-11ea-8b5f-64328ea186eb.png)

**Comment by ajayyy** [comment]
Friday afternoon :/. Enabled cloudflare, should be good now. It caches for 2 hours which is why I don't always have it enabled.

**Comment by ajayyy** [comment]
It wasn't location specific, but just overloaded. So, it only responded to some requests

**Comment by ajayyy** [comment]
It doesn't help that the extension retries very quickly after failing creating a ddos like event. Maybe I should raise the timeout before retrying
