### ISSUE TITLE
Forcing ads at the start of the video

### ISSUE THREAD

**Issue by ToRRent1812** [ajayyy/SponsorBlock#365]
Using Opera GX with Ublock Origin, somehow SponsorBlock forces me on every single video to watch an unskippable ad before video launches and instead of playing the video after, the player just stops and I can replay the ad again with a press of a button. I'm pretty sure it shouldn't work like that.

**Comment by ajayyy** [comment]
I don't think SponsorBlock is able to do that. Try disabling Opera's built-in adblocker and tracking blockers (uBlock will do the job anyway)

**Comment by ToRRent1812** [comment]
I have them disabled.
