### ISSUE TITLE
Submitting during premiering sets start/end to the wrong place due to the countdown

### ISSUE THREAD

**Issue by Zeicon** [ajayyy/SponsorBlock#367]
As the title says: I just submitted sponsor times on a premiering video, but realized that the video is 2 minutes longer due to the 2 minute countdown at the start, before the actual video. That is not accounted for when submitting. After refreshing - and the premier being over - it was basically shifted 2 minutes ahead.

I'm not sure that you can just subtract 2 minutes and it being accurate.

So I suggest deactivating the upload for premiere videos, while they are premiering.

**Comment by ajayyy** [comment]
I'm thinking of recording the video duration on submit and comparing it to the video duration when skipping. This would also solve the issue where someone deletes a portion of their video (due to copyright or other reason). However, submissions do work in livestreams, and this would break that. I think it would be worth it though

**Comment by ajayyy** [comment]
Is the text time displayed accurate? Or, does that include the countdown too? That could be used to determine if there is something weird going on with the video's time.

**Comment by Zeicon** [comment]
Yes, it does include the countdown. It did show the time as 3:40, while the time in the actual video should have been roughly 1:40 after the video was fully premiered/page refreshed.

**Comment by ajayyy** [comment]
Are you sure this is a real countdown and not just something the YouTuber
is doing? They might be adding the countdown, and then removing that part
of the video right when the premiere is over.

**Comment by Zeicon** [comment]
I've never actually premiered a video myself, but I've seen the same one on multiple videos I watched during a premiere - it's this one: https://www.youtube.com/watch?v=B4dnPVZ2MV0
Maybe they do some wizardy and switch the "livestream source" after it is over.

**Comment by ajayyy** [comment]
Are the countdowns always exactly 2 minutes?

**Comment by chk1** [comment]
I don't think it's always the same offset or length. On this [video from today](https://www.youtube.com/watch?v=En8UXiFjtCE ) there was one submission that happened during the premiere, it was off by about a minute (has since been downvoted and replaced with another sponsor tagging).

**Comment by ClawhammerLobotomy** [comment]
> Are the countdowns always exactly 2 minutes? I tried making my own premiere, and I don't see an option to change it.

It does not seem like they are always 2 minutes. I was waiting for a premier and when it started, it was only 1 minute long. The video did not start 1 minute late either. The countdown started at exactly 1 minute for me.
[The video if it helps anything.](https://www.youtube.com/watch?v=pKJErsN-ylU)
