### ISSUE TITLE
Breaks Iridium

### ISSUE THREAD

**Issue by NoLooseEnds** [ajayyy/SponsorBlock#373]
It seems like SponsorBlock breaks [Iridium](https://github.com/ParticleCore/Iridium/), at least the quality settings. After installing my youtube videos no longer defaultet to 1080p.

**Comment by ajayyy** [comment]
I don't see how it would conflict with that

**Comment by NoLooseEnds** [comment]
It seems like it works again after a browser restart. Should have done that before I mase an issue.
