### ISSUE TITLE
Do highlights at the start on the video counts as Into Animation?

### ISSUE THREAD

**Issue by Uoipka** [ajayyy/SponsorBlock#374]
That is a common practice with this type of thing there youtubers cut "interesting 15sec" moment from the video and put it in at the start of the video.
https://www.youtube.com/watch?v=efEbDxnZSVc
example first 13 sec is a cut and video starts only after

Should we count this as Into Animation or it's a diffirent thing?
Tbh I love to skip this type of thing

**Comment by ajayyy** [comment]
Nope. Some others have thought about that idea as well. If someone can think of a nice and concise name for that category, it can be added. I want all the categories to be objective though, nothing subjective (such as offtopic, tangent, etc.)
