### ISSUE TITLE
Database license?

### ISSUE THREAD

**Issue by pandark** [ajayyy/SponsorBlock#375]
I don't see a license for the database. Shouldn't there be one? Either a copyleft one such as the [Open Database License](https://www.opendatacommons.org/licenses/odbl/) or something close to the public domain such as [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by ajayyy** [comment]
There actually is one. It is in the readme table on the production database. It's also linked on the API docs.

**Comment by pandark** [comment]
Ah, yes, sorry.
I checked a few places but I have obviously read too quickly. On the website and this repository, it says "publicly downloadable". Maybe it could be better to either add the license there too, or remove the direct link and link to the API docs to find the download link instead (?)
I can do it if you think it's worth it. If not, I'll just leave this closed issue alone 😄.

(I'm not a fan of the NonCommercial clause, for several reasons, but I think it's already a bit late for it to be worth discussing at this point of the project 🙂)

**Comment by ajayyy** [comment]
Yea, that's why I added the clause "unless you have explicit permission from Ajay Ramachandran". So, if anyone needs it commercially, they just need to contact me and give a good reason for it.

I debated it a lot, but decided to add it just in case I need to use it.

**Comment by ajayyy** [comment]
I have updated the website and readme. Thanks!

And just to clarify, the non commercial clause is to have _some_ leverage against someone reuploading the extension with malicious tracking or ads code.
