### ISSUE TITLE
Android Accessibility Services (for default YouTube app)

### ISSUE THREAD

**Issue by thesuperzapper** [ajayyy/SponsorBlock#376]
I might be off base, but I wonder if it would be possible to use the Android System Accessibility Services APIs to create an Android app which would seek inside the offical YouTube app, utilising the SponsorBlock database?

**Comment by ajayyy** [comment]
I did try this for a bit, but got into a lot of trouble. If you are curious, you can read through the #android-hooking channel on discord to see what happened.

Getting the video ID seems almost impossible. The only way I could think of is to open up the "stats for nerds" page, but that obscures the video. Intercepting the requests, even after spoofing the ssl certificate, results in gibberish.

**Comment by thesuperzapper** [comment]
@ajayyy have you actually tried to use newpipe? Its a terrible experience (assuming you're not crazy anti google tracking), there are many important features missing, most notably the ability to log in and see your subscriptions/recommendations. 

Also, it might be possible to see the name of the currently playing thing from the media api?

**Comment by ajayyy** [comment]
Seeing the name isn't needed, seeing the actual url/video id is

**Comment by ajayyy** [comment]
https://en.reddit.com/r/Vanced/comments/hf1jad/other_i_added_sponsor_block_support_to_youtube/
