### ISSUE TITLE
feature request: ability to disable sponsorblock for certain channels

### ISSUE THREAD

**Issue by AntiSol** [ajayyy/SponsorBlock#377]
Hi. Thanks so much for sponsorblock, it's awesome.

I was very happy to see the introduction of categories as there were a bunch of things that weren't strictly sponsors that bugged me (self-promotion in particular), but this has caused me a bit of a problem because for certain channnels I want to see things like end credits, but for most channels I don't. So I'd suggest adding the ability to disable sponsorblock for certain channels.

Being able to disable the whole thing on a per-channel basis would be a step in the right direction, but even better would be more fine-grained controls which would allow users to disable/enable sponsorblock on a per-category-per-channel basis, giving me the ability to say e.g "skip categories X and Y by default but for videos on this channel skip only category Z".

Thanks for your time :)

**Comment by ajayyy** [comment]
"channel whitelisting" is already a thing (click the green button) and I do plan to replace it with channel overrides in the future

**Comment by AntiSol** [comment]
Well don't I feel dumb for not looking before raising an issue? Thanks :)
