### ISSUE TITLE
Remove keybind restriction as not all locales have the same key bindings

### ISSUE THREAD

**Issue by pandark** [ajayyy/SponsorBlock#379]
For me, the keys `;` and `:` decrease and increase the video reading speed. It *also* does start/stop a sponsored segment or submit it. `,` and `.`, on the other hand, do nothing, but sponsorBlock won't let me use these as keybindings.
I don't know whether this difference is due to my browser language settings, my location, my keyboard mapping or something else, but the keybinding restriction doesn't make sense in my case.

**Comment by ajayyy** [comment]
Interesting. I guess the keybind check should be removed as it doesn't apply to all languages
