### ISSUE TITLE
Make it way easier to skip tiny segments in time.

### ISSUE THREAD

**Issue by connectety** [ajayyy/SponsorBlock#381]
When you have a short segment to skip (like LTTs self promotions) its incredibly hard to push the skip in time button.
Possibilities to solve this could be:
- Dramatically increase the size of the skip button (like YouTubes skip-ad button or Netflixes skip-intro button). Of course such an element would block a big amount of the video, which would be solved by making the element transparent. (the skip-notification should be more transparent anyway)
- add an option to skip every entry shorter than X seconds.

I personally would prefer the first approach.

**Comment by ajayyy** [comment]
Hmm, can you send a layout/mockup if you have an idea? Would a skip keybind be better?

**Comment by connectety** [comment]
Ok, just found out the skip-notification is transparent, just not very much. But thats ok.

**Comment by connectety** [comment]
ok, bigger text does not look good... But what if clicking the skip-nofication anywhare which is not a button skips the segment. Maybe remove the skip button and add a muted / greyer text between 
![mockup](https://user-images.githubusercontent.com/26038710/84958110-e47f0c00-b0fc-11ea-944c-675d10ca7ed9.png)

**Comment by Szpadel** [comment]
instead of larger button I would prefer to have some easy to access shortcut for skipping (enter maybe?)

**Comment by DuckOfDuckness** [comment]
I feel like #175 is probably the better way to do this.

**Comment by ajayyy** [comment]
I think a skip button in the video player controls could help
