### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [ajayyy/SponsorBlock#382]
https://addons.mozilla.org/en-GB/firefox/addon/sponsorblock/versions/2.0.1/updateinfo/ is empty; notes can not be seen at `about:addons` before deciding whether to allow the update. 

Found: https://github.com/ajayyy/SponsorBlock/compare/2.0...2.0.1

**Comment by ajayyy** [comment]
Thanks! AMO has a bug where it thinks English US is always the default locale for release notes, so it doesn't show the release notes I put in when submitting the new version (English Canada) unless I copy paste into English US and add a character to make it "different".

**Comment by grahamperrin** [comment]
> … AMO has a bug … 

Useful to know. Belated thanks!
