### ISSUE TITLE
Change "Intro Animations" to just "Recurring Animations"

### ISSUE THREAD

**Issue by ocbaker** [ajayyy/SponsorBlock#383]
Hey,

I was looking at something like this as an example: https://youtu.be/Y3GzfNRo5WY?t=962

The video is obviously pulled from TV, and they've left the Transition segments in that are used to wrap the commercial breaks. It would make sense that this would be something I should be able to mark as an animation that should be skipped.

**Comment by ajayyy** [comment]
I feel like that term is too confusing, but that definitely seems like an intro. Transition Animation could be another term, but I feel that is too broad and would include things that really shouldn't be skipped for "intro".

**Comment by mirror176** [comment]
Few intros I like to see more than once and some not even that. The transition clips at the end I have marked as endcards/credits but that does leave out the ones in the middle of the content from having a sane category. They're basically mini title screens at the start and/or end of commercial breaks and on youtube are sometimes thrown in where any other transition would have worked without advertising the program name being watched.

**Comment by ajayyy** [comment]
Closed in favour of https://github.com/ajayyy/SponsorBlock/issues/394

**Comment by ajayyy** [comment]
Done in 2.0.3
