### ISSUE TITLE
Category request: summary/conclusion

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#390]
Some content tells you what is coming up for the program, after a break, or summarizes what content you just saw or should have learned from it. Doesn't feel right calling it intro or ending/credits but could go into the same categories in a way if another category isn't desired.

**Comment by ajayyy** [comment]
You are right, talking should not go into the intro or outro categories

**Comment by SameenAhnaf** [comment]
What's the key difference between "Summary" and "Highlights"?

**Comment by mirror176** [comment]
Preview/recap covers this request well so topic could be closed. I do not have an understanding of how 'highlight' category should be used to answer SameenAhnaf's question from either my own best guess or from reading https://wiki.sponsor.ajay.app/w/Segment_Categories and do not know how 'spoken summary' should be left out. If the spoken summary is a preview/recap of content preceeding/following it in the video in more detail then I would have added it to the preview/recap already. Now wondering if I have made a mistake on any.

**Comment by mchangrh** [comment]
this can be closed - Preview/Recap now includes speech if it does not provide additional information
