### ISSUE TITLE
How to deal with overlapping skippable segments of different categories

### ISSUE THREAD

**Issue by awebeer256** [ajayyy/SponsorBlock#402]
For example, the channel, "MxRMods," often ends videos with an Endcards/Credits segment that's ~13 seconds long, the first 7 seconds of which _are also simultaneously_ a Sponsor segment. How should we users submit times in cases like this? The naive answer is to just submit overlapping times, so that if one user had credits set to auto-skip but not sponsors, and another had their settings the other way around, they would each supposedly get their intended behaviour. But I think the database's process of trying not to send "duplicate" segments to viewers ruins this strategy. Perhaps there should be a server-side change such that overlapping segments of different categories should not count as duplicates if a large fraction of either segment is non-overlapping, and/or if each category has a submission from the same user?

**Comment by ajayyy** [comment]
They do not count as duplicates right now (categories are fetched independently), but I plan on changing that due to as it is not ideal. The best way to do it is to submit the first part as sponsor and the endcard starting when the sponsor finishes

**Comment by awebeer256** [comment]
Could you elaborate a bit more, please?

Why is what you proposed better than submitting overlapping segments? Is it that they will count as duplicates after the future change you mentioned? If so, then why not make the changes I suggested instead?

Even if we ignore the option of submitting overlapping segments, why is it better to count a credits/sponsor overlap as a sponsor segment instead of a credits segment? Is it just because you're guessing that most people are more likely to skip sponsor segments than credits segments? If so, do you have a complete overlap hierarchy of _all_ the categories?

**Comment by ajayyy** [comment]
The categories are meant to be discrete and not overlap. I think credits should only be stuff that is not other categories

**Comment by ajayyy** [comment]
If it is a sponsor, it is not credits. Credits should not contain talking

**Comment by awebeer256** [comment]
Allow me to provide more details regarding the example I mentioned. During the last 13 seconds of the video, the YouTube end cards and the names of top Patreon patrons are displayed on screen. Starting at the same time but lasting only 7 seconds is a voice-over advertising the channel's sponsor, complete with coupon code.

I understand that you have been developing this software under the _assumption_ that categories should not overlap, but that is a model that does not survive contact with reality. You should revise your plans so that your software can provide a non-hacky solution to these more complicated cases.

**Comment by ajayyy** [comment]
They can overlap, but I plan on adding a check that the aren't 50% the same. This is due to people submitting the same segment as two categories.

I would say that is a sponsor then, not an outro. An outro should not contain a voiceover like that.

**Comment by ajayyy** [comment]
Here is an example of a video with endscreen and endcards that does not have an explicit "endcard/credits" section (https://www.youtube.com/watch?v=SHi4LLSJuxo).

The plan is to add custom chapters support to in the future. So, there would be a "sponsor" chapter and a "endcard" chapter.
