### ISSUE TITLE
[Site] Show categories on hover on the leaderboard

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#404]
> I know its been suggested before but I think a hover over on the leaderboard that shows how much of each category you've submitted maybe looking something like this would be pretty cool 
>
> no idea how much effort something like that would take but I'm always wondering what categories people are submitting and what my own count looks like

![Example](https://i.imgur.com/0dtYqZs.png)

From _FunkeymonkeyTTR_ on Discord

**Comment by MRuy** [comment]
The stats page source code is not public available.

**Comment by mchangrh** [comment]
fixed in https://github.com/ajayyy/SponsorBlockSite/commit/f5b08b73e01ab1d9556874b21128f7ebb5688dc5
