### ISSUE TITLE
Skipping like/subscribe spots, when already subscribed to channel

### ISSUE THREAD

**Issue by TheAlienDrew** [ajayyy/SponsorBlock#408]
We should have an option that if we already subscribed to a channel, that it'll automatically skip the like/subscribe bits, as if it makes no sense to watch those bits, yet it would still be something we would see on channels that we are not yet subscribed to.

**Comment by ajayyy** [comment]
This already exists, see the "interaction" category.

**Comment by TheAlienDrew** [comment]
I know, but it's not exactly what I'm talking about.

My feature suggestion would mean that it would only skip those things, if you have like/subscribed to that channel or video, so new videos/channels will still show those parts of the video, while already liked/subscribed videos/channels will skip past those parts.

**Comment by zjopy** [comment]
@TheAlienDrew Consider how hard it would be to mark these in a video. When is it a general interaction like "here is my second channel", "you should subscribe to my friend XYZ", "buy a shirt in my shop" and when only "like/subscribe"? Sometimes they are even in the same sentence.

If you created separate categories for it, it would *hugely* complicate tagging. IMHO the current categories are good enough and cover everything already. The more categories, the harder tagging will become. Generally, less complex categories should be strived for, not more complex ones.

You can always just set skipping to optional and manually skip when you want, in your case for "like and subscribe" but not for "buy muy t-shirt".

**Comment by ajayyy** [comment]
@TheAlienDrew I am planning on revamping the channel whitelisting to be channel overrides. This would let you choose to not skip certain categories on certain channels, but still skip other stuff. Soz you'd be able to do this.
