### ISSUE TITLE
Custom Labels/Custom Categories/Crowd Chapters

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#409]
Just an idea right now:

- [ ] Add player button to skip to the start of the next segment or the end of the current segment if inside a segment
- [ ] Open submission popup immediately after clicking start segment
- [ ] Add a separate stop segment button to allow you to make a new segment that starts at the end of the last one
- [x] Add `label` field to database
- [x] Autocomplete with previous chapters on that channel to help with autoskipping specific ones
- [ ] Grid-based submission notice to have more space?
- [ ] Allow someone to "edit" chapters by forking previous ones

Problems:

- These would have to use a different sorting system than the overlapping segments model
    - Maybe it would only use one users entire segment batch?
- Should sponsors and other categories still be stored separately?
    - Would it be useful to say a segment starts at the end of whatever sponsor was chosen as the "best" one instead of an arbitrary time?
- These should only be allowed to submit by high reputation users
   - Custom text is risky

Database:

- Store info in `chapterSegments` table with `UUID` linking to `sponsorTimes`, and a `version` to allow new versions to link to new segments.
- Store vote data in a `chapterInfo` table containing a link to the `chapterSegments` and credit to any forks

**Comment by zjopy** [comment]
Please don't allow for more and even custom categories. The more complex the category selection will become, the harder it will be. People will inadvertently choose wrong categories, detrementing user experience for everyone, since categories aren't useful anymore if you can't rely on them being correctly used.

Already today I often correct "sponsor" to "interaction".

IMHO the current categories are very much fine already and don't need more complexity.

**Comment by ajayyy** [comment]
@zjopy this is more to replicate the chapters feature. These would not auto skip.

**Comment by chirag127** [comment]
> * high reputation users

who are high reputation users? vips?

**Comment by GitMoleo** [comment]
I thought about this as well, and I would find it very useful!
Unfortunately, some channels don't use the chapter feature and this would be a nice

**Comment by SameenAhnaf** [comment]
Another idea could be adding key points for chapters and segments where summary of the full segment is discussed. Especially helpful for online classes as students can access directly the point when the math is fully solved.

**Comment by hyoretsu** [comment]
Great feature, even if slightly off topic.

**Comment by SameenAhnaf** [comment]
Sponsorblock shouldn't divide the seek bar into several parts or use seek bar colours. Instead, seperate the chapters by icons like `|` or `•`. 

There should be a clear indication that this is a relevant part of the video topic and does not fall into specific categories.

**Comment by ProgrammerWhoPrograms** [comment]
https://github.com/ajayyy/SponsorBlock/issues/2015
