### ISSUE TITLE
Skipping ads on chromecast

### ISSUE THREAD

**Issue by stephen304** [ajayyy/SponsorBlock#410]
I came across a cli thingy that lets you query and control chromecasts, so I made this: https://github.com/stephen304/castblock

Figured you might be interested. It automatically finds chromecasts and polls them for what they're playing / where the playhead is, and automatically fetches segments from sponsorblock api. Then it can automatically seek forward any time it hits a sponsor. It's a little rough (since the cli only allows skipping integer seconds, and because there's no skip to absolute position, you get a second of ad on either side, and I think there's an occasional error) but it works :D

**Comment by ajayyy** [comment]
Very cool, nice job!

**Comment by ItsIgnacioPortal** [comment]
Notice: The link above is now for the legacy project. The current project is at https://github.com/erdnaxeli/castblock
