### ISSUE TITLE
Disable auto upvote by default

### ISSUE THREAD

**Issue by zjopy** [ajayyy/SponsorBlock#411]
If I understand the current algorithm correctly, if you skip a tag, then this counts as an upvote. As many users have auto skip enabled, this would add many silent upvotes.

This is a problem. The part of users that actively curate the database and care about correct tags is surely the minority.

Consider a hugely popular video with a wrong tag. Then the many users all add silent upvotes for the wrong tag. The few explicit down votes from users trying to curate the database get lost in the sea of silent upvote.

I can't find an option to disable auto upvote in the settings. But maybe I'm just missing it. I don't think it's "Enable Sponsor Skip Count Tracking" though?

But most importantly, auto upvote should be disabled by default and optional to activate. This allows advanced users to let their absence of a downvote count as upvote, but prevent the skewing of the votes by beginner users that are unaware of the silent upvote mechanism.

EDIT: If this comment in [#231](https://github.com/ajayyy/SponsorBlock/issues/231#issuecomment-573344149) is still valid, then downvotes are already counted ten times as much as one upvote. However this is a fixed ratio, which makes sense only for some videos. On a popular video with millions of views there might be hundreds of upvotes, making -10 not worth much. However on a video with a handful of upvotes, -10 may be too much. The real solution would be to make them equal weight again, but disable auto upvote by default.

**Comment by ajayyy** [comment]
Auto upvoted was removed completely at the same time as the categories update. Can you link any pages that still mention autovote?

There is no option  for it as it's gone entirely.

**Comment by zjopy** [comment]
Thanks, that's great to hear! I think this is better than before.

I haven't read about it recently, I just haven't been aware of the change.
