### ISSUE TITLE
Never fetch database for unlisted videos option

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#413]
Instead of asking if the user wants to the SponsorBlock database for submissions every time they view an unlisted video, add an option to never check the database on unlisted videos.

**Comment by Michael82548** [comment]
I quit using this extension until this is added. I can't take it anymore.
![image](https://user-images.githubusercontent.com/53535277/107864831-55162e00-6e2e-11eb-8d5e-3095fec90efb.png)

**Comment by ajayyy** [comment]
@Michael82548 If you enable "query by hash prefix" (will be enabled by default in the next update), then the unlisted check is kind of redundant and can be disabled. In this new query method, it does not send the video ID, but only a small part of the hash of the video ID.

I'm not sure if I should just remove this option entirely, or instead reword the description to say that it is mostly unnecessary. Not really sure how to reword it.

**Comment by ajayyy** [comment]
Not necessary due to query by hash prefix
