### ISSUE TITLE
sponsorblock no longer skips segments

### ISSUE THREAD

**Issue by Moth-Tolias** [ajayyy/SponsorBlock#418]
for whatever reason, sponsorblock has failed to skip segments for at least the past week. it shows them in green on the timebar, but never actually skips them.

**Comment by ajayyy** [comment]
Go to options, and click copy debug info. Send it here.

**Comment by Moth-Tolias** [comment]
> Go to options, and click copy debug info. Send it here.

{
    "debug": {
        "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0",
        "platform": "Linux x86_64",
        "language": "en-GB",
        "extensionVersion": "2.0.2.2"
    },
    "config": {
        "hideDiscordLaunches": 4,
        "submissionCountSinceCategories": 2,
        "sponsorTimesContributed": 2,
        "sponsorTimes": [
            [
                "OcRJeeGZ61M",
                [
                    [
                        82.457211
                    ]
                ]
            ]
        ],
        "skipCount": 16,
        "minutesSaved": 9.873424383333337,
        "categoryUpdateShowCount": 3,
        "whitelistedChannels": 0,
        "forceChannelCheck": false,
        "startSponsorKeybind": ";",
        "submitKeybind": "'",
        "unsubmittedWarning": true,
        "disableSkipping": false,
        "trackViewCount": true,
        "dontShowNotice": false,
        "hideVideoPlayerControls": false,
        "hideInfoButtonPlayerControls": false,
        "hideDeleteButtonPlayerControls": false,
        "hideUploadButtonPlayerControls": false,
        "hideDiscordLink": false,
        "invidiousInstances": 2,
        "supportInvidious": false,
        "serverAddress": "Default server address",
        "minDuration": 0,
        "audioNotificationOnSkip": false,
        "checkForUnlistedVideos": false,
        "testingServer": false,
        "categorySelections": [
            {
                "name": "sponsor",
                "option": 2
            }
        ],
        "barTypes": {
            "sponsor": {
                "color": "#00d400",
                "opacity": "0.7"
            },
            "preview-sponsor": {
                "color": "#007800",
                "opacity": "0.7"
            },
            "intro": {
                "color": "#00ffff",
                "opacity": "0.7"
            },
            "preview-intro": {
                "color": "#008080",
                "opacity": "0.7"
            },
            "outro": {
                "color": "#0202ed",
                "opacity": "0.7"
            },
            "preview-outro": {
                "color": "#000070",
                "opacity": "0.7"
            },
            "interaction": {
                "color": "#cc00ff",
                "opacity": "0.7"
            },
            "preview-interaction": {
                "color": "#6c0087",
                "opacity": "0.7"
            },
            "selfpromo": {
                "color": "#ffff00",
                "opacity": "0.7"
            },
            "preview-selfpromo": {
                "color": "#bfbf35",
                "opacity": "0.7"
            },
            "music_offtopic": {
                "color": "#ff9900",
                "opacity": "0.7"
            },
            "preview-music_offtopic": {
                "color": "#a6634a",
                "opacity": "0.7"
            }
        }
    }
}

**Comment by ajayyy** [comment]
Go to `about:debugging#/runtime/this-firefox` and click inspect. See if any errors appear when it should skip.

**Comment by ajayyy** [comment]
And it doesn't skip anything? Or does it just not skip sometimes?

**Comment by Moth-Tolias** [comment]
huh. it's been pretty consistently not working the last week, but now i can't seem to replicate it. i guess i'll reopen this with the inspection results if it starts happening again?
