### ISSUE TITLE
Mark videos as not containing sponsors

### ISSUE THREAD

**Issue by Joe-Dowd** [ajayyy/SponsorBlock#419]
Mark videos as not containing any sponsors.

It's common to see unpopular videos vandalised by marking the entire video as a sponsorship (such as the youtube rewind videos).

Providing a mechinism to mark videos as not containing a sponsorship would help combat this type of vandalism.

VIP's tagging these videos could even act as an instant shadow ban for vandalising users (maybe if combined with segments being submitted over a certain % of the video length).

**Comment by DuckOfDuckness** [comment]
Could this work as a new special category? If it was a segment, certain parts of a video could also be marked as "Don't allow segment of category X" here. Or the whole video too.

**Comment by Joe-Dowd** [comment]
I don't envision this as a segment and don't think it should be - that would be a new type of category which requires special logic. I think categories should remain uniform in how they act within the system.

I see this more as a marker which can be proposed by many people which once reaching a limit, blocks all submissions.
This has downsides however, in that it's not forgiving in the event of new categories being added, and integration with the proposed custom category system.

**Comment by Joe-Dowd** [comment]
I see this more as a defence against vandalism, as opposed to trying to creating a system to accurately mark the entirety of youtube's content for user filtering.

**Comment by ajayyy** [comment]
> This has downsides however, in that it's not forgiving in the event of new categories being added

Yes, I was worried about this.

**Comment by Joe-Dowd** [comment]
So I see two ways around that: 
1. Store a list of categories the person who marked it as not containing anything has active at the time (for multiple markings, add any categories the additional user has to the list, and compare those to the potential vandal's lost on submission).
2: Only use this system for very specific frequently vandalised videos as a honey trap for vandals.

**Comment by Joe-Dowd** [comment]
> Store a list of categories the person who marked it as not containing anything has active at the time (for multiple markings, add any categories the additional user has to the list, and compare those to the potential vandal's list on submission.

Though then the consideration is on how we review submitters that use uncommon categories which are later added (such as the strobe recommendation)

**Comment by ajayyy** [comment]
Idea:

A new table is created in the private database for this. This table contains normal submission data (but no votes). This can be filled when marking a video as not containing sponsors or other categories. If multiple categories, it can make multiple submissions in that time with the same segment.

**Comment by ajayyy** [comment]
This is similar to my "completely incorrect" downvote idea, but that idea doesn't really work with categories.
