### ISSUE TITLE
Grammar Issue

### ISSUE THREAD

**Issue by unbeatable-101** [ajayyy/SponsorBlock#424]
In the extension menu it says "You have skipped _n_ sponsors
You have saved yourself _n_ minutes." It should say "You have skipped _n_ sponsors.
You have saved yourself _n_ minutes."

**Comment by ajayyy** [comment]
Fixed in new popup

**Comment by unbeatable-101** [comment]
There is still no period

**Comment by ajayyy** [comment]
The new popup has not been merged yet https://github.com/ajayyy/SponsorBlock/pull/440
