### ISSUE TITLE
Sponsors can still be seen in the preview when hovering over thumbnails

### ISSUE THREAD

**Issue by bbb651** [ajayyy/SponsorBlock#425]
I'm not sure if this can be fixed as the thumbnail preview is probably served directly from the server, but ideally you would want to see actual parts of the video instead of sponsors. It's probably more effort than it's worth as it's a rare occurrence but it might be something worth looking into.

**Comment by unbeatable-101** [comment]
I don't think this would be worth trying to fix, the extension would need to create a new thumbnail preview for every video with a reported sponsor.
