### ISSUE TITLE
Seeking to the last second moved on to the next video in the playlist even if loop is enabled

### ISSUE THREAD

**Issue by TG-KK** [ajayyy/SponsorBlock#426]
__Steps to reproduce:__

* Play this link: https://www.youtube.com/watch?v=cSnkWzZ7ZAA&list=PLgDP5UKLWaCA_cJeIJBcVLbLFid49AMQh&index=11
* Right click & enable loop on video
* At the end there is a non-music skip & I've non-music skip enabled in SB settings..

Expected:
* Song should play again after the non-music skip, since Loop is enabled 😋

Actual:
* Next song in the playlist starts playing! No no no! 😢

**Comment by ajayyy** [comment]
It seems seeking to the last second triggers it to go to the next video even if it is looped
