### ISSUE TITLE
Prevent vote manipulation

### ISSUE THREAD

**Issue by KevoSoftworks** [ajayyy/SponsorBlock#427]
I noticed using the online database that some users are manipulating the votes of their submissions. In some instances, there were 10000+ votes almost immediately after the submission, but only a few actual views (or no views at all). 

It might be benefitial to allow a user to only vote once on a submission, or to ensure that there cannot be more votes than views.

**Comment by ajayyy** [comment]
VIPs start with 10000 votes. See the server issues page for some ideas to prevent vote abuse.

**Comment by KevoSoftworks** [comment]
Sorry, I was unaware of this. Thank you for letting me know.
