### ISSUE TITLE
Suggestion: Highlighted "Title" Section in playback bar

### ISSUE THREAD

**Issue by lumitry** [ajayyy/SponsorBlock#436]
This feature would highlight where the title of the video occurs (for those videos that have 20 minutes of banter and like 30 seconds of what you came there for) that way you could skip to see what you clicked on.

**Comment by ajayyy** [comment]
I'm not sure I understand. Do you mean when person says the tytle?

**Comment by lumitry** [comment]
It's for clickbait videos where only part of the video represents what was in the title.

For example, a video titled "How we went to the moon" that features 20 minutes of unrelated information before getting to the point.

This would replace youtube comments that say "video starts at x:xx"

**Comment by ajayyy** [comment]
Probably better suited for https://www.jumpcut.app/

**Comment by lumitry** [comment]
Alright, fair enough

**Comment by ajayyy** [comment]
I'm planning on going with the https://github.com/ajayyy/SponsorBlock/issues/409 strategy instead. It will be sections, not timestamps
