### ISSUE TITLE
Search in the chapters according to key words

### ISSUE THREAD

**Issue by TheAngryPython** [ajayyy/SponsorBlock#439]
You can add a search in the chapters for the words "Sponsors"," Sponsored","Спонсор". These chapters should be automatically indexed and blocked. Like this: 
![изображение](https://user-images.githubusercontent.com/49928332/90536227-700c2c00-e184-11ea-8c2e-17cb650dfd30.png)

**Comment by ajayyy** [comment]
They are only precise to the second, so I don't think it is worth it.
