### ISSUE TITLE
Link to specific segment

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#442]
Read the YouTube URL's hash and fetch only those specific segments.

Example: https://www.youtube.com/watch?v=dQw4w9WgXcQ#s=[%22id1%22,%22id2%22]

**Comment by mchangrh** [comment]
closed in https://github.com/ajayyy/SponsorBlock/commit/38b1dda20bfeb4b6058ba98615866f450921c42c
