### ISSUE TITLE
Add new category "Preview"

### ISSUE THREAD

**Issue by qweered** [ajayyy/SponsorBlock#444]
Some videos have a preview of the video content at the beginning. Sometimes it is perceived as spoilers, and they spoil the whole feeling of watching, and sometimes even long (as in this https://youtu.be/Oag5DG8BhEA video). It would be nice for people who know exactly what they want to watch this video not to spoil the viewing experience and save time.

**Comment by ajayyy** [comment]
"Preview" is already being used for submitted segments. Could you think of some other possible names?

**Comment by ajayyy** [comment]
Unsubmitted segments could potentially be renamed to incomplete segments.

**Comment by HyphenSam** [comment]
"Sneak peek" could be an alternative. Can't really think of anything else.

**Comment by opl-** [comment]
I noticed that currently these are sometimes being marked with the intermission category. I guess incorporating sneak peeks into the intermission category description is the alternate option here, though personally I'm in favor of making it into a separate category for people who don't want to automatically skip intermissions.

**Comment by ajayyy** [comment]
@opl- those segments are incorrect and should be downvoted

**Comment by snowbie** [comment]
> 
> 
> "Preview" is already being used for unsubmitted segments. Could you think of some other possible names?

If naming is the problem, a name I included in my (re)post was "Highlight Reel".

**Comment by ajayyy** [comment]
Likely going with:

Name: Recap/Highlight Reel

Description: Quick recap of previous episodes, or highlights of what's coming up later in the current video. Meant for edited together clips, not for spoken summaries.

**Comment by HyphenSam** [comment]
That sounds good! I have no complains here.

**Comment by ajayyy** [comment]
Update has been submitted to the extension stores
