### ISSUE TITLE
YouTube Music Support

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#449]
https://music.youtube.com

This would not require any extra permissions.

**Comment by jesperbakhandskemager** [comment]
Just adding music.youtube.com as an Invidious instance will skip the non music parts of the videos, but will not really have an interface for reporting non music parts. (If i understood correctly, you can still add sponsors by clicking on the SponsorBlock icon in the toolbar, but it will only be able to report Sponsors, not non music parts)

**Comment by ajayyy** [comment]
Oh, sweet. I hadn't tested. I might as well just add it to the manifest then

**Comment by ajayyy** [comment]
@jesperbakhandskemager the submission in the popup will actually work for other categories too

**Comment by Sv443** [comment]
Was support removed? Sponsorblock has never worked on YT Music for me. I'd love being able to at least skip the non-music sections.
