### ISSUE TITLE
confirmation and optional edit of start / end time before submitting

### ISSUE THREAD

**Issue by 4e4e** [ajayyy/SponsorBlock#45]
I really like the idea of this extension and have added a few video sponsors to it. While doing this I found the interface for reporting a sponsor confusing. 

I found the interface to be a real pain to use. Is the stop button stop or pause? When I click play again am I resuming or starting again? Is there some way to clear what I've already recorded?

After trying a few times I think I ended up somehow making the recorded sponsor far too small (video in question https://www.youtube.com/watch?v=odscT429m-g).

I think that an easy (I think) solution to this would be to have a dialog come up whenever you push submit which says the times you've selected, and gives you an option to change it before submitting.

Also a couple of other points of feedback while I'm here, don't use browser notifications (or at least make them opt-out), they suck. I've already gotten dozens of "Do you want to submit the sponsor time" notifications flooding me. If I wanted to submit the sponsor time I already would have. The Chrome extension link is broken (or maybe removed from the web store).

Thank you.

**Comment by ajayyy** [comment]
Yea, sorry. Chrome just took it down from the store all of a suddent and it
says "pending removed". Hopefully that gets fixed quickly.

About the submissions, click the extensions icon in the corner and you'll
get more info about it, the button on the video player is supposed to be
the "simplified" menu.

Those are some good ideas. The buttons on the video player should be
improved a little, bit I feel it's hard to balance with making them not
intrusive and get in the way.

About the notifications, they should only happen if you've started
recording some sponsor times but didn't submit. I'm not sure why you would
start recording but not submit. The clear button is available if you click
the extension icon in the corner.

Anyways, thanks for trying it out and keep the feedback coming, I want to
make this as easy as possible to submit data.

**Comment by ajayyy** [comment]
I have added this for now:

![image](https://user-images.githubusercontent.com/12688112/62061572-720bf180-b1f5-11e9-8839-34a7c3909f50.png)

**Comment by ajayyy** [comment]
![deleting individual times](https://user-images.githubusercontent.com/12688112/62067678-493e2900-b202-11e9-8678-0ff507f3e590.gif)

**Comment by ajayyy** [comment]
![sponsorEditing](https://user-images.githubusercontent.com/12688112/62071918-82c76200-b20b-11e9-9d89-b5eac142d7c3.gif)

**Comment by ajayyy** [comment]
Please clarify what you mean by the notification issue after reading my reply, for now I am closing this as I solved the editing issue.
