### ISSUE TITLE
Sponsorblock not working on some videos

### ISSUE THREAD

**Issue by JCisLord** [ajayyy/SponsorBlock#454]
https://sb.ltn.fi/?videoid=hid7EJkwDNk

Plenty of segments contributed (a new one every few hours), yet in the YouTube video none of the contributions show up.

It previously was working, because the first contributions have views.  but then one day later the nonstop repeat contributions started (presumably when sponsorblock stopped working for this video).

**Comment by ajayyy** [comment]
Somehow a submission with negative values got in there. I'll have to check the logic
