### ISSUE TITLE
Automated voting of segments is manipulating user stats and polluting the database

### ISSUE THREAD

**Issue by JCisLord** [ajayyy/SponsorBlock#455]
The highest leader on the stats page, has a surprising amount of segments with exactly 10,000 positive votes.

https://sb.ltn.fi/?username=ltcars&sort=-views.

Many of these 10,000 vote segments, are basically identical to existing segments other users previously submitted. The bogus positive votes appears to influence the server into handing out their segment, rather than the existing identical segment from another user.

Just one example of the 10,000+ votes clobbering an existing positive voted segment:
https://sb.ltn.fi/video/6KDBpn8fW78/?sort=-timesubmitted

---------

Here's the second highest leader board user, also with an abnormal number of positive votes.  This is even worst, because the new segment has the wrong time stamps, when the previous existing segment had it correct:
https://sb.ltn.fi/video/giQ8xEWjnBs/?sort=timesubmitted

The second sponsor starts at around 14:21, which is what the previous top voted segment has.  But the new clobbering segment has the abrupt and wrong start of 14:41 (watch the video and see yourself, it's awful).

**Comment by ajayyy** [comment]
First case:

There was a semi-recent change that made all submissions by VIP users start with 10,000 votes. This was a hack to help fix bad segments.

Second case:

This is from the past when there used to be auto-vote.
