### ISSUE TITLE
Add official vanced app in the docs for "Unnofficial Ports"

### ISSUE THREAD

**Issue by SerinitySW** [ajayyy/SponsorBlock#457]
https://github.com/ajayyy/SponsorBlock/wiki/Unofficial-Ports

Youtube Vanced released the official version of the app with SponsorBlock built-in, working with the dev that made the unofficial port. You can simply point to https://vanced.app now rather than the port, which is outdated.

Thanks for all the amazing work you do!

**Comment by ajayyy** [comment]
It already links to the official GitHub, but thanks!
