### ISSUE TITLE
Buttons on Invidious

### ISSUE THREAD

**Issue by shivasagarrao** [ajayyy/SponsorBlock#458]
It would be nice if there are buttons for upload, delete, info for Invidious(Source: https://github.com/omarroth/invidious) player same as Youtube player buttons.

**Comment by ajayyy** [comment]
Duplicate: https://github.com/ajayyy/SponsorBlock/issues/227

**Comment by ajayyy** [comment]
By the way, you can still submit on invidious using the popup
