### ISSUE TITLE
Have buttons hidden until mouse over

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#47]
To reduce clutter on video player controls

**Comment by mirror176** [comment]
I'm a fan of static interfaces if this was going to mean the controls on the controls bar changes depending on if the mouse was in it or not. Dynamic interfaces generally slow down experienced users and add confusion to the inexperienced.

**Comment by ajayyy** [comment]
Yea, I agree with you. This was a suggestion by someone else.
