### ISSUE TITLE
Rename "Skip count tracking" to "Anonymous leaderboard contributions"

### ISSUE THREAD

**Issue by JCisLord** [ajayyy/SponsorBlock#470]
Since the sponsorblock leaderboard does not track individual user skips, it's a bit misleading to call it tracking.

Suggest renaming the setting toggle to "Anonymous leaderboard contributions"

**Comment by ajayyy** [comment]
Is "Anonymous Skip Count Tracking" better?

**Comment by JCisLord** [comment]
That's better.  But it still suggests tracking, when the user themselves are not being tracked.

The existing description makes it very clear to users what the feature does, it just needs to wipe any mention of tracking (because there isn't any).

Maybe "Anonymous skip counting"?

**Comment by ajayyy** [comment]
But it really is tracking. It sends a (anonymous) request after every skip. I think it would be misleading not to mention that.

**Comment by JCisLord** [comment]
Ok then.  "Anonymous Skip Count Tracking"  would be an improvement.
