### ISSUE TITLE
SB not skipping segments in Firefox

### ISSUE THREAD

**Issue by ceodoe** [ajayyy/SponsorBlock#473]
Hey, love the idea of this extension, but most times it does not work. The colored segment shows up on the seek bar, but once playback reaches that point, the skip does not happen if the video has played naturally since autostarting upon the tab being opened. If I however manually skip to a few seconds before the sponsor segment starts, it will skip as expected.

I'm running SponsorBlock under Firefox 80.0.1 on Kubuntu 20.04 LTS. The only other extension I have that touches the DOM of the page is uBlock Origin. Any ideas on how to remedy this, or is it a bug? Did a cursory search through the issues here and can't find anything similar.

**Comment by ajayyy** [comment]
Are you sure you have no other extensions installed?

**Comment by ceodoe** [comment]
Video autoplays as normal when tab is opened, and the youtube autoplay next video function is off. I have a number of other extensions, but none of them mess with YouTube.

**Comment by ceodoe** [comment]
After some investigation, it turned out that I had Privacy Badger still installed, albeit hidden from the toolbar and overflow menus. If anyone else encounters this, disabling/uninstalling Privacy Badger fixed this problem for me. Thanks for a great project!
