### ISSUE TITLE
Handle cases where userID was never generated on install: "Server said this request was invalid Error Code: 400"

### ISSUE THREAD

**Issue by NateHevens** [ajayyy/SponsorBlock#474]
**Browser:** Chrome 85.0.4183.102
(Yes, I know Chrome sucks, but Firefox refuses to hold on to my bookmarks, randomly deleting them and not archiving them even when I back-up constantly, and Chrome doesn't and my bookmarks are very important to me... so...)

[https://i.imgur.com/xffj61Q.jpg](https://i.imgur.com/xffj61Q.jpg)

I did look in the Dev Tools and it's apparently a bunch of different links with the following format:

https://sponsor.ajay.app/test/api/skipSegments?videoID=(video id)&categories=[%22sponsor%22,%22interaction%22]

What I find most interesting is that only some of these links correspond to the video in the screenshot. But all the links lead to a page that says "Not Found".

Sadly, I cannot submit the section right now because of it.

Apologies if this is repetitive. There is another post, but for Firefox, not Chrome.

**Comment by ErikPrantare** [comment]
Had the same issue, managed to solve it. Look in https://github.com/ajayyy/SponsorBlock/issues/466 to see what I did :)
