### ISSUE TITLE
Safari 14 is out with support for WebExtensions API

### ISSUE THREAD

**Issue by 2600box** [ajayyy/SponsorBlock#479]
Safari 14 has just been released for macOS Catalina. It has support for the WebExtensions API.

Apple actually has a conversion tool. https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

Has anyone tried it? Would happily pay for SponsorBlock on Safari.

**Comment by ajayyy** [comment]
See https://github.com/ajayyy/SponsorBlock/issues/312
