### ISSUE TITLE
Can't add an "Unpaid/Self Promotion" Segment

### ISSUE THREAD

**Issue by Jatoxo** [ajayyy/SponsorBlock#482]
![image](https://user-images.githubusercontent.com/39669932/93662909-f3f75380-fa63-11ea-86f9-07f958a1ccbb.png)
This all the categories you can choose, if you click on "more categories" it just opens a new tab with the extension settings

**Comment by ajayyy** [comment]
You must enable the category in options to use it (at least show in seek bar)

**Comment by Jatoxo** [comment]
It would be expected to be able to add any kind of segment even when it is disabled. Nothing in the UI hints at having to have those segments enabled. If I see a segment that I think other people want to skip, I'll add that segment regardless of whether I have that specific category enabled for myself or not

**Comment by ajayyy** [comment]
This would lead to duplicate submissions as you don't know if it is already submitted

**Comment by Jatoxo** [comment]
In that case, why not have it check for interfering submissions?
