### ISSUE TITLE
[Feature] Option to constantly randomize userID

### ISSUE THREAD

**Issue by tingwai** [ajayyy/SponsorBlock#485]
I think adding an option to constantly randomize the userID would be useful for those looking for more privacy but still want to help contribute segments. It is currently very easy to track user behavior/preferences/history by looking at their submitted segments in the public database. This is particularly worrisome if someone unknowingly leaked their userID allowing for very targeted tracking.

My feature request/proposed solution is to generate a new userID everytime before POST'ing to `/api/skipSegments` if user has enabled a certain flag. This would be a simple way to improve privacy if users don't want people to know their previously submitted segments. We could be even more aggressive by regenerating the userID anytime the field is accessed so even the server can't as easily correlate users with votes. I'd be happy to try to make a PR if there's interest.

**Comment by ajayyy** [comment]
I don't want this to be an official feature as it would make moderation a lot more difficult. I suggest not submitting or voting instead if worried privacy.
