### ISSUE TITLE
Highlight/Answer section

### ISSUE THREAD

**Issue by algotnExtra** [ajayyy/SponsorBlock#489]
Feature request to add a highlight/answer section, like those comments saying "answer at XX:XX, thank me later"
I know this really isn't inline with the other features of SponsorBlock, but I feel like it has the potential to save a lot of time for a lot of users. (would be hard to track the time saved though)

Example where this would be useful.
You search up how to do a specific thing, you find a good video about it, but the maker spends like 3 years talking about some other stuff before finally saying the answer.
![EXAMPLE1](https://user-images.githubusercontent.com/58611480/94595549-4833dc00-028b-11eb-9d5e-fed4d827f3a2.png)
![EXAMPLE2](https://user-images.githubusercontent.com/58611480/94595552-49650900-028b-11eb-8cc3-cc2cb0216b37.png)
Note that the example images does not reflect a video where it is would be useful, just a random Tom Scott video from the recommended recommended page that I quickly edited to make an example with.

**Comment by ajayyy** [comment]
Similar idea to https://chrome.google.com/webstore/detail/jumpcut/jicbaeklgoninplhmenhndnidnbfaohm/related

**Comment by algotnExtra** [comment]
> 
> 
> Similar idea to Jumpcut[https://chrome.google.com/webstore/detail/jumpcut/jicbaeklgoninplhmenhndnidnbfaohm/]

That doesn't exist in Firefox though.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/409
