### ISSUE TITLE
Fine tuning start and end of a segment using buttons/keys and instant preview

### ISSUE THREAD

**Issue by Stimmenhotel** [ajayyy/SponsorBlock#497]
To create a very well fitting segment, I am changing decimal places by hand and press preview.
Instead it would be awesome, if I could use buttons that will increment by 1s and 0.1s or even use my keyboard (1s increase/decrease by right/left and 0.1s by shift+right/left) and instantly see what have changed by playing the video on that position for start of a segment and stopping at the end.

**Comment by a-merlino** [comment]
When I make segments, I use the comma and period keys to move through individual frames on YouTube (US layout, keys might be different elsewhere). It works well enough for me although still a little clunky.

Instantly seeing the changes would be cool, but I can also see it getting annoying. Plus if you do it frame by frame, you're a lot less likely to need to see the preview multiple times. Ultimately I think that creating segments has to be faster, but I am not qualified to say what a good/bad approach to that is.

**Comment by SkaveRat** [comment]
I can also recommend just using the frames to properly mark segments. you'll never be as precise as using frames directly

**Comment by Stimmenhotel** [comment]
Oh nice, just checked this site: https://support.google.com/youtube/answer/7631406

I have tried comma and period keys, but they haven't had the right effect. (video not in focus? Don't know if paused or not, even if it makes no sense if it was running) 
But tried it again now and with paused video it is working perfectly. Thanks for the hint!
