### ISSUE TITLE
Duplicate segments in the database

### ISSUE THREAD

**Issue by sriharshachilakapati** [ajayyy/SponsorBlock#498]
This is not a bug report, but a potential optimization on your end. The popup is showing duplicate segments which is suggesting that there are duplicate segments in the database.

You might want to consider changing the record type to be unique to save space. Not critical but just an observation, thanks for the awesome addon!

**Comment by sriharshachilakapati** [comment]
<img width="351" alt="చిత్రము" src="https://user-images.githubusercontent.com/4593204/95082470-b0296d00-0738-11eb-9577-d074e2020c3f.png">

**Comment by MRuy** [comment]
The popup UI only shows minutes and seconds.
Segments can also have milliseconds like `177.85`
The segment time is stored as seconds (float) in database.

Can you share the videoID, i can only find one entry in the database that has this startTime and endTime
https://sb.ltn.fi/?videoid=pD7F8g1cPbc&sort=starttime

**Comment by sriharshachilakapati** [comment]
This is one such video: https://www.youtube.com/watch?v=3idBjnd5sr8

There are no entries when I saw, and hence I submitted them. After submitting them, this is how the UI is showing.

<img width="390" alt="image" src="https://user-images.githubusercontent.com/4593204/98440467-e9317480-211e-11eb-819d-4ae20795c3ea.png">

**Comment by MRuy** [comment]
There is only one entry in the database as you can see here:  
https://sb.ltn.fi/?videoid=3idBjnd5sr8

The reason for it will be that SponsorBlock will store your submission temporarily but also will fetch new segments in the background and therefore it will display your submission twice.

**Comment by sriharshachilakapati** [comment]
Ah, got it. That means this is a UI issue. Don't we need to clear out the temporary submissions in the frontend after a push acknowledgement from the server?
