### ISSUE TITLE
SponsorBlock not working while using "Video Speed Controller" extension

### ISSUE THREAD

**Issue by gototheskinny** [ajayyy/SponsorBlock#500]
When i use this extension for example if i speed up the video x2.5 SB not skipping the segments. I love this extension pls if you can solve this i would be very greatful.

**Comment by ajayyy** [comment]
https://github.com/igrigorik/videospeed/issues/683

> Video Speed hijacks the speed change events making SponsorBlock unable to detect them.
> 
> Solution for now: Click pause and play after every speed change.
