### ISSUE TITLE
High CPU usage on YouTube music

### ISSUE THREAD

**Issue by FireMasterK** [ajayyy/SponsorBlock#501]
I'm not too sure why SponsorBlock even runs on YouTube music.

![image](https://user-images.githubusercontent.com/20838718/95230031-f0631b00-081e-11eb-9018-f2fa16dd7ecc.png)

![image](https://user-images.githubusercontent.com/20838718/95230104-08d33580-081f-11eb-93f6-30a0095f60a8.png)

Let me know if there's any way I can help.

**Comment by ajayyy** [comment]
Looks like it may be caused by trying to show the category name on YouTube music, which shouldn't work anyway

**Comment by FireMasterK** [comment]
I would like to fix/work on this issue, it should be as simple as adding `exclude_matches` to  https://github.com/ajayyy/SponsorBlock/blob/60b9266a2a6963d5b87d08cf12d9577f8f27d94d/manifest/manifest.json#L9-L12
 from what I can see in the documentation at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/content_scripts.

**Comment by ajayyy** [comment]
YouTube music is supported now, so I'm not sure if this issue occurs anymore.

**Comment by FireMasterK** [comment]
Oh okay, I'll give that a test then.

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/119274680-c71cc100-bc2e-11eb-9084-314ab8728ea4.png)

The problem still appears to be present :/

![image](https://user-images.githubusercontent.com/20838718/119274709-e582bc80-bc2e-11eb-872f-3419f07052ca.png)
![image](https://user-images.githubusercontent.com/20838718/119274725-f4696f00-bc2e-11eb-8606-e0341ab91098.png)

Could these elements be cached so that a `querySelectorAll` isn't run?

**Comment by danopia** [comment]
I've also noticed this issue happening. The CPU usage starts at a reasonable level and ramps up over time.

SponsorBlock is useful on Youtube Music in case one watches music videos; the skipping of non-music segments is beneficial.

It seems like timers start building up when one has a single pageload going through dozens of tracks (say, several albums). I've been reloading Youtube Music through the day as a workaround.

Timer load is reasonable on the first track:

![Screenshot 2021-07-07 12 28 28](https://user-images.githubusercontent.com/40628/124744377-fb1e1e00-df1e-11eb-85e0-39a231de619e.png)

A couple albums later we're at 100% of a core:

![Screenshot 2021-07-07 12 27 03](https://user-images.githubusercontent.com/40628/124744416-05401c80-df1f-11eb-8c11-48860b87c085.png)

I'm not immediately sure why the `querySelectorAll` calls seem more expensive over time, but they're certainly called more often over time.

**Comment by ajayyy** [comment]
@danopia Does skipping work for you right now on YouTube music?

**Comment by FireMasterK** [comment]
![image](https://user-images.githubusercontent.com/20838718/124804846-5c261000-df78-11eb-98b6-ec2764a37a53.png)

Skipping seems to be working as expected (it actually skips it).

**Comment by ajayyy** [comment]
Interesting, it hasn't been working for me recently

**Comment by danopia** [comment]
Yea, I see skipping working when viewing music videos, but it's also seemed imperfect - segments starting at 0:00 seemed to be dropped sometimes, presumably because of how quickly YTM switches tracks (gapless playback as opposed to normal YouTube)

**Comment by edmundo096** [comment]
Got this issue from months, maybe a year ago, never bothered to check until today.
Still happens on v3.1.2, on Chromium Edge.

As danopia mentions avobe in https://github.com/ajayyy/SponsorBlock/issues/501#issuecomment-875491534, a workaround is to limit the extension only to the YouTube site.

Such workaround would end looking like this:
![image](https://user-images.githubusercontent.com/2168903/132940949-7e9f4b7e-cf85-4c57-b014-a59361857e70.png)

Have not tested skipping videos on YT music, so I can't comment on that.

**Comment by ajayyy** [comment]
Profiler link: https://github.com/ajayyy/SponsorBlock/issues/1034#issue-1046974890

**Comment by ajayyy** [comment]
That check should have a timeout of 5 seconds, does the CPU usage stop after a few seconds, or keep going?

**Comment by rohmishra** [comment]
On firefox it does not, I can provide a provider output for longer duration if that helps.

**Comment by ajayyy** [comment]
ah, I see now the one you already sent is 45 secs already, so that should be fine

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/pull/1113
