### ISSUE TITLE
Segment that goes to end of video ignores looping in playlist

### ISSUE THREAD

**Issue by PsyDrag** [ajayyy/SponsorBlock#503]
I recently submitted a endcards/credits segment that went to the end of the video. I also had YT's loop feature on within a playlist so that the video will start over again instead of moving on to the next video. If I skip the segment with the loop feature on, it ignores the loop feature and moves on to the next video.

**Comment by ajayyy** [comment]
This has been fixed and will go out in the next update (or second-to-next if I decide to push it to beta first)

https://github.com/ajayyy/SponsorBlock/issues/306
