### ISSUE TITLE
Make help page translatable

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#509]

**Comment by Elaborendum** [comment]
I think some strings are still not translatable. Crowdin says my language is fully translated, but I still see some english. Is this intended?
![imagen](https://user-images.githubusercontent.com/71190696/133911359-a8be33e6-ac34-43c2-913c-fd7168f7f780.png)
![imagen](https://user-images.githubusercontent.com/71190696/133911341-d5f66f9e-da12-4afa-94dd-6e53db6d6063.png)
