### ISSUE TITLE
Add a category for previews

### ISSUE THREAD

**Issue by asdsadsaasd12312132** [ajayyy/SponsorBlock#519]
I believe this would be beneficial as it falls under the "time wasting" category. The preview is pointless if I am going to watch the whole video regardless. The preview mainly exists to grab the attention of new viewers. Examples of previews:
https://youtu.be/wVu8TSWfP_c (0:00-1:00)
https://www.youtube.com/watch?v=XLkLStpyPVc (0:00-0:10)
https://www.youtube.com/watch?v=uU7FqJql2_8 (0:00-0:05)

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/444
