### ISSUE TITLE
Release notes at AMO

### ISSUE THREAD

**Issue by grahamperrin** [ajayyy/SponsorBlock#520]
Hi

https://addons.mozilla.org/en-GB/firefox/addon/sponsorblock/versions/2.0.6.1/updateinfo/ was OK. 

https://addons.mozilla.org/en-GB/firefox/addon/sponsorblock/versions/2.0.7/updateinfo/ is blank, and so notes can not be viewed at `about:addons` before deciding whether to accept an update. 

![image](https://user-images.githubusercontent.com/192271/96682133-4fbd4100-1370-11eb-8efe-31783f7a0077.png)

– needs a plain English summary of https://github.com/ajayyy/sponsorblock/compare/2.0.6.1...2.0.7

Thanks

**Comment by Joe-Dowd** [comment]
2.0.7
- Added query by hash prefix to preserve user privacy using k-anonymity 
- Don't unpause when inspecting

**Comment by ajayyy** [comment]
Fixed.

I'll leave the explanation here again for future visitors:

> AMO has a bug where it thinks English US is always the default locale for release notes, so it doesn't show the release notes I put in when submitting the new version (English Canada) unless I copy paste into English US and add a character to make it "different".

**Comment by grahamperrin** [comment]
Duplicate of #382 – sorry.
