### ISSUE TITLE
Close button on Firefox 82.0

### ISSUE THREAD

**Issue by Keiishu** [ajayyy/SponsorBlock#522]
## Platform
Windows 10 v2004
Firefox 82.0 64bits

## Issue
The new version of Mozilla Firefox introduces a change on the Picture-In-Picture button, which changes its design and position on the YouTube player.
The issue I have is that the position of that button is exactly under the close button on the SponsorBlock message box to manually skip unwanted parts of the video. Here is a visual : [imgur.com/a/YjzeLWg](https://imgur.com/a/YjzeLWg)

**Comment by ItzMichaelPhillips** [comment]
Having the same problem here. I found a temporary solution: go to **about:config**, and set **media.videocontrols.picture-in-picture.video-toggle.position** to **left**. It will put the button on the left, leaving it out of the way.

**Comment by Keiishu** [comment]
@ItzMichaelPhillips Thank you for that!

**Comment by ajayyy** [comment]
Any ideas on what can be done to fix this. Should the notices be a little higher up on Firefox?

**Comment by ItzMichaelPhillips** [comment]
@Keiishu You're welcome!

**Comment by Keiishu** [comment]
@ajayyy I think it would be great to shift it a little bit yeah, because right now (if the Firefox button is still set on right position, and it is by default) you can't click on the extension's close button, the Firefox one takes over.

**Comment by deosrc** [comment]
This also affects the submission pop-up where it appears under the "end" link. So many times I've been trying to set the end credits and accidentally popped the video out instead :joy: 

![sponsorblock_pip](https://user-images.githubusercontent.com/50599779/101267450-ba73e180-3750-11eb-81eb-b487f1417d31.png)

**Comment by rstarkov** [comment]
No chance of the position getting tweaked a little?
