### ISSUE TITLE
Auto skipping (sometimes) fails and video replays from the beginning on Firefox

### ISSUE THREAD

**Issue by swanknight** [ajayyy/SponsorBlock#525]
While watching a video that has at least two sponsor segments, when SponsorBlock tries to skip the second segment sometimes it fails. It stutters for a few seconds before replaying the entire video from the begining which is rather annoying when it happens.

Even though I encounter this issue often, I can't reproduce it manually.

PS: I use Firefox 82.0

**Comment by Kusurisan** [comment]
same issue. worked a while ago, now it stopped skipping :/

**Comment by BubiBalboa** [comment]
Same issue here using Firefox latest Beta release. Started happening a few weeks ago. 

I think it happens with long videos that have been paused for a long time.

**Comment by swanknight** [comment]
> I think it happens with long videos that have been paused for a long time.

Not in my case. The videos were never paused.

**Comment by ajayyy** [comment]
Is the issue only on Firefox?

I wonder if it is a browser bug

**Comment by swanknight** [comment]
> 
> 
> Is the issue only on Firefox?
> 
> I wonder if it is a browser bug. Maybe it should be reported there as well. It could also be YouTube doing something that messes with Firefox

Possibly but I only used Firefox so far so I wouldn't know if it occurs on other browsers or not.

**Comment by ajayyy** [comment]
Yea, another person mentioned this bug in discord who used Firefox as well, so that makes 3 people

**Comment by PeeVv** [comment]
Same issue here, using Firefox 83. Switched from Chrome a few days ago, Chrome didn't have this issue, so it seems to be Firefox messing with something.

**Comment by kalleguld** [comment]
I have the same issue, on Firefox 83 / macOS.
It seems to be specific videos. It has happened with this video a few times.
https://youtu.be/9lr9oxDBWQg
Unfortunately it's a long video, and the error doesn't seem to materialize when manually skipping in the video

**Comment by HaroldPetersInskipp** [comment]
Same issue for me, on Firefox 83 64bit / windows 10 home. Been happening for a while now. Seems to happen most often with long videos and multiple sponsor segments.

**Comment by bdonovan88** [comment]
Happening to me as well. Same as ^, looks to happen on longer videos and most of the time with more than 1 sponsor.
macOS 11.01 Big Sur, Firefox 83 64bit.
Happened on this video most recently if it helps at all: https://www.youtube.com/watch?v=zr_TQWpYNeo

**Comment by jungletek** [comment]
+1, FF Nightly on Win7 x64 here. FWIW, I seem to encounter it consistently on videos from https://www.youtube.com/channel/UCyZVCV9xhrCyz4hPehvb4Wg , perhaps because of the already speculated-on factor of longer videos, multiple sponsors, etc.

**Comment by ajayyy** [comment]
YouTube changes the video element when you change bitrates. When doing so, it resets the `currentTime` of the video element to zero temporarily before setting it to the correct value. This also can happen automatically when it determines the computer is slowing down. 

My guess it that Firefox is freezing right after the video seeks and then YouTube is lowering the bitrate due to that. This issue will only occur when there is a segment starting at zero seconds for SponsorBlock to think it has to skip.

**Comment by ajayyy** [comment]
Let me know if the issue continues on 2.0.10

**Comment by swanknight** [comment]
> 
> 
> Let me know if the issue continues on 2.0.10

When will 2.0.10 be live for FF? Because I only see 2.0.9 still.

**Comment by ajayyy** [comment]
Probably around a week. Right now it is just available for beta testing.

**Comment by BubiBalboa** [comment]
It's still happening for me with version 2.0.10.1 unfortunately. Could it have something to do with an ad skip right at the very start of the videos? That seems to be a common thread among the videos posted here.

**Comment by swanknight** [comment]
> 
> 
> Let me know if the issue continues on 2.0.10

So far I haven't experienced the same issue with version 2.0.10.1 but what happens is when it "stutters" the video goes black and I get the loading animation for maybe 30secs or so, then it resumes the video correctly after the sponsor segment. Just thought you should know.

**Comment by ajayyy** [comment]
315901f69b8de0a9913e3839ede572e10a96c553
