### ISSUE TITLE
Skippable segments won't show sometimes until I reload the video

### ISSUE THREAD

**Issue by faedy2** [ajayyy/SponsorBlock#526]
I just switched from Brave browser to Firefox because Brave glitched out hard on me, and one thing that I noticed is that SponsorBlock works a lot better out of the box than it does on Firefox for me. Sometimes the skippable segments will not show until I refresh the video, which you can understand is pretty annoying. I am running PopOS 20.10. Please let me know what other information I can provide to potentially fix this issue.

**Comment by ajayyy** [comment]
Are these new videos? Maybe there weren't any submissions

**Comment by faedy2** [comment]
> Are these new videos? Maybe there weren't any submissions

Here is how I found out that there **were** submissions. I tried to add a segment for an intro to the database, but the extension glitched and told me that the section was from 0:00 to 0:00. This was odd because the segment that I created was over 10 seconds in length. When I refreshed, there were already submissions on the video. So it seems that I was overriding another person's submission.

I thought that this was only for new videos since this glitch happened on a pretty recent video, but now it has been occurring for videos that have been up for quite some time.

**Comment by ajayyy** [comment]
That seems like the extension is losing context and being killed by the browser. This happens when it updates. I haven't been doing updates that often recently though, so maybe something else is making it be killed by firefox?

**Comment by faedy2** [comment]
The only other thing I can think of is maybe Cookie AutoDelete extension, but it has YouTube whitelisted.

**Comment by faedy2** [comment]
> I think I found out the problem, but will obviously keep updated if the issue happens again.
> I thought that I had disabled ad blocking from Malwarebytes Browser Guard, but apparently I only disabled it on certain sites.
> Once I disabled it globally, it appears that videos that I never watched before load the skipped segments correctly.

This was not the solution. Just watched a video from 2 years ago. Had a sponsor. Refreshed, and the sponsor segment showed.

**Comment by gthrow** [comment]
I have also been experiencing this. It's fairly inconsistent, I have tried to reproduce it by refreshing the page *a lot* of times. The only extension I've had enabled when reproducing is µblock origin

Firefox 83, SponsorBlock 2.0.9

There are three things that I've noticed when this issue appears:
- The above mentioned issue that the time selection for adding a segment doesn't work
- By hovering over where the segment is supposed to be, I can see the "Sponsor" text
- There is a very small green region at the very beginning of the progress bar

The two last points illustrated:
![firefox_YvXMttun20](https://user-images.githubusercontent.com/68082954/101088828-88c61380-35b4-11eb-8fa6-6724c481e9f3.png)

**Comment by faedy2** [comment]
>There is a very small green region at the very beginning of the progress bar
Ah yep. I've seen this as well.

**Comment by ajayyy** [comment]
I have noticed this when I leave a tab open for too long, which makes me think it is the extension losing context from the browser.

**Comment by gthrow** [comment]
I have done some detective work to track down the bug.

The video element is being recreated multiple times. It doesn't look like the extension has a `MutationObserver` to track the video element, the extension may as a result keep an old reference and functionality breaks down.

Each time I have seen the issue the callee has been `sponsorsLookup()` from this line:
https://github.com/ajayyy/SponsorBlock/blob/e39de9fd852adb9196e0358ed827ad38d9933e29/src/content.ts#L691

Note that the first thing `sponsorsLookup()` does is update the element reference. This means that at some point during the function's execution the video element must have been recreated. From then on the extension will not have a correct reference which leads to all observed issues.

**Comment by vtruong68** [comment]
I'm experiencing this issue daily on Firefox. There are often no segments populating on videos until I manually refresh the page to have the segments load. Loading the same videos in Vivaldi/Brave seems to populate segments every single time.

**Comment by jaredreardon** [comment]
I've been having this issue as well. Segments won't load until I refresh the page sometimes. And this is on older videos that have user submissions.

**Comment by phiresky** [comment]
I have the same issue for a while and finally managed to get some info from the dev tools. The only relevant error I can see is this:

`TypeError: can't access property "duration", v is undefined`

referring to this code:
![image](https://user-images.githubusercontent.com/2303841/126898697-30a1a92d-8f1f-441b-bdc0-90de49b91531.png)

Which is caused in the line @gthrow linked above.
There's a check for `if (video === null) return;` but not one for `video === undefined`. I'm not sure if just adding a early return in that case would be enough to fix it or if some more code would have to be changed as @gthrow  describes.

**Comment by phiresky** [comment]
> the video element must have been recreated

I don't see any code that ever sets the video variable to something nully though, it's only undefined at the very start before it is ever set I think. So I don't see how a throw with `video is undefined` could happen after the video element has been found once.

So maybe the issue happens if somehow the preview bar is initialized before the video element appears?

**Comment by ajayyy** [comment]
@WeebPiston This sounds more like a network issue

**Comment by ajayyy** [comment]
Going to close this for now. Open a new issue if there is a specific reproducible bug in a newer version
