### ISSUE TITLE
Make query by hash default

### ISSUE THREAD

**Issue by xPaw** [ajayyy/SponsorBlock#529]
Now that querying by hash prefix is supported, it's a good idea to make it the default option for privacy.

**Comment by ajayyy** [comment]
Performance testing still needs to be done before it is enabled by default

**Comment by Madis0** [comment]
Reposted ideas from #593:
- if cached well, would avoid extra network requests per video and work a bit more like a traditional content blocker (see also: #161)
- could be combined with the refetch feature to update many segment lists at once
- could be combined with skip count tracking to send counts in hash batches, e.g. once per day

**Comment by ajayyy** [comment]
Released
