### ISSUE TITLE
Segment going into auto skip fails to autoskip second segment

### ISSUE THREAD

**Issue by JCisLord** [ajayyy/SponsorBlock#531]
If there are two segments back to back, and there is any overlap of the two segments, then manually skipping the first segment fails to show a skip option for the second segment (giving no way to skip the second segment).

Commonly to get autoskip to look the best, there needs to be a few frames of overlap between adjacent segments (especially segments with scene transitions).  So making adjacent segments with no overlap is not as ideal.

Solution: if the first segment is skipped, then check if the new playback location is in another (second) segment.  If the second segment start time is inside the first segment, then show the manual skip dialog for the second segment.

**Comment by ajayyy** [comment]
Manual skip -> auto skip fails.

Auto skip -> manual skip works.

**Comment by JCisLord** [comment]
I'm speaking only of manual skipping adjacent segments.

**Comment by ajayyy** [comment]
Oh, I see. So, manual skip -> manual skip fails as well. That would make sense. It seems it does not pass the variable to check if it is currently inside the segment when manually skipping, but does so when autoskipping.
