### ISSUE TITLE
[Question] End cards category query

### ISSUE THREAD

**Issue by shivasagarrao** [ajayyy/SponsorBlock#541]
Could you explain in detail what End cards/credits category mean? 
I have another doubt, if I have same animation at both start and end of a video what should be the category of animation at the end of a video? 
I know the animation at start of the video comes under Intro animation category but what about same animation at the end of video? There is no category of End animation so does it also come under Intro animation category or End cards category?

**Comment by ajayyy** [comment]
If there is no content at the end, it can count as end card/credits.
