### ISSUE TITLE
Overlapping multible Segments problem

### ISSUE THREAD

**Issue by Sekkei** [ajayyy/SponsorBlock#551]
If user A creates sponsor section from 00:00 - 01:00 and user B creates a intermission section from 00:00 - 02:00 , the first one get an auto/manual skip but the second one fails to show after 01:00 

A better behavior would be to check if segments are overlapping and shorten the longer one to the amount of the overlapping section 
( Not sure if already exits , but a check where up to n% of similar timestamps of different users get merged with more weight for up-voted segments )

**Comment by ajayyy** [comment]
I think your symptom is the issue described here: https://github.com/ajayyy/SponsorBlock/issues/531

Manual skip -> auto skip fails.

Auto skip -> manual skip works.
