### ISSUE TITLE
API usage

### ISSUE THREAD

**Issue by hbt** [ajayyy/SponsorBlock#552]
>> If you end up using the API, I'd love to know about how you're using it. Tell me about it by making a GitHub issue or emailing me :)

I use the API to remove sponsors from podcasts. Mostly because sponsors are usually USA based stuff and are irrelevant products.

Workflow:

- call your API (thank you)
- use youtube-dl to get audio file
- ffmpeg to cut and concat 
- upload to s3 
- generate RSS from s3 
- listen on podcast app

I'd happily share the code but seeing what happened to the youtube-dl guys; I don't want to risk my account.

Thanks for keeping the database and API public.

**Comment by ajayyy** [comment]
Nice! Very cool.
