### ISSUE TITLE
SyncTube

### ISSUE THREAD

**Issue by vampiricwulf** [ajayyy/SponsorBlock#553]
The times for each segment and sometimes even the type of the segment are incorrect. Is it possible to fix?

The website in question is: https://sync-tube.de

I use it to watch videos with friends.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/150
https://github.com/ajayyy/SponsorBlock/issues/494

It doesn't know that the video is changing, since the embed stays with the same URL even though the video has changed.

**Comment by vampiricwulf** [comment]
Yeah, I see that. Very irritating.

Regardless, thanks for the speedy response!
