### ISSUE TITLE
SponsorBlock popup in every youtube video

### ISSUE THREAD

**Issue by diegoweb** [ajayyy/SponsorBlock#555]
Hey guys!

Since last week I'm receiving this error below, whenever I open a Youtube video:
"It seems that something is blocking SponsorBlock's ability to get video data. This is probably your ad blocker. Please check https://github.com/ajayyy/SponsorBlock/wiki/Fix-Ad-Blocker-Blocking-SponsorBlock's-Requests"

I've already visited the mentioned URL and added the filters to my uBlock Origin, although it stills shows the error above.
I'm running the latest Chrome version.

What can I do to fix this?

**Comment by ajayyy** [comment]
Are you sure you don't have another adblocker/pihole running?

As a workaround, you can disable the "check for unlisted" setting for now, as that is what is relying on that information.

**Comment by ajayyy** [comment]
Go to manage extensions, enable developer mode and click on the background page to inspect it.

![image](https://user-images.githubusercontent.com/12688112/100680130-ecdfa200-333e-11eb-9226-62df96af1882.png)

Then go to the console tab and send a screenshot of what network errors are occurring when you try to browse videos with the unlisted check setting **enabled**.

**Comment by diegoweb** [comment]
> Are you sure you don't have another adblocker/pihole running?

I do. Is there anything I have to do in PiHole?
Although it's weird, because I'm using SponsorBlock for over a month, and just last week this problem started.


> Then go to the console tab and send a screenshot of what network errors are occurring when you try to browse videos with the unlisted check setting **enabled**.


log:
```
background.js:1 GET https://sponsor.ajay.app/api/skipSegments?videoID=stg9RkuZVPw&categories=[%22sponsor%22,%22intro%22,%22interaction%22,%22selfpromo%22,%22music_offtopic%22] 404 (Not Found)
(anonymous) @ background.js:1
(anonymous) @ background.js:1
r @ background.js:1
f @ background.js:1
(anonymous) @ background.js:1

```
![image](https://user-images.githubusercontent.com/12632119/100682442-d93f3600-3354-11eb-82d3-8dcf984bd87c.png)

I tried disabling PiHole for 5 minutes, but refreshing the page keeps showing the popup error.



> As a workaround, you can disable the "check for unlisted" setting for now, as that is what is relying on that information.
This one fixed the problem (with/without PiHole), but this function is something I need.
And by the way, could you implement a function to disable any popup asking for permission for non-listed videos to be processed by SponsorBlock? I mean, I already checked the function to ignore unlisted video, I don't want to confirm in every page.

Thanks :D

**Comment by ajayyy** [comment]
Does https://www.youtube.com/get_video_info?video_id= load for you? That's the URL that is failing.

**Comment by ajayyy** [comment]
Are you watching on invidious?

**Comment by diegoweb** [comment]
> Does https://www.youtube.com/get_video_info?video_id= load for you? That's the URL that is failing.

It asks me to download a file.
The file contains:
`status=fail&reason=Invalid+parameters.&errorcode=2`



> Are you watching on invidious?

No clue what that is. It seems it's a front-end for Yt. I'm directly browsing Youtube from my Chrome and I don't use the mentioned extension (invidious).

**Comment by ajayyy** [comment]
I'm not sure why it would fail to load for the extension then

**Comment by diegoweb** [comment]
> I'm not sure why it would fail to load for the extension then

I just noticed I get a "Not Found" content when I visit:
https://sponsor.ajay.app/api/skipSegments?videoID=stg9RkuZVPw&categories=[%22sponsor%22,%22intro%22,%22interaction%22,%22selfpromo%22,%22music_offtopic%22]
![image](https://user-images.githubusercontent.com/12632119/100821369-f811fb00-342e-11eb-9455-af998389988a.png)

Isn't something wrong with SponsorBlock api?
As I said, it was working great until last week. Did you by any chance changed something in the API and now the extension is looking for a wrong url?

The problem seems to be related with /api/skipSegments

**Comment by ajayyy** [comment]
That video has no segments, so it is normal to return 404

**Comment by diegoweb** [comment]
OK!
So I've disabled all extensions in my browser but SponsorBlock. It worked.
Then I re-enabled one extension each time and refreshed the video so I could see if SponsorBlock would still work.
Now I know which extension is conflicting with SponsorBlock.... It's Windscribe extension.

I don't know why, so I will keep it disabled.
Perhaps you could try to fix and keep both extensions working together... If you can't, no problem. At least now we know Windscribe is not compatible with SponsorBlock :P

**Comment by ajayyy** [comment]
By the way, if you enable fetch with hash prefix, then the unlisted check isn't really needed anymore.

**Comment by diegoweb** [comment]
Oh nice.
Thanks!

Since this is solved, I will close this issue. Thank you again.
