### ISSUE TITLE
Voting on Segments color coding

### ISSUE THREAD

**Issue by elypter** [ajayyy/SponsorBlock#558]
currently the buttons for each segment are using a dark yellow. it would make make identifying the right segment much easier if it had the color of its category to correspond to the representation in the time line. they should also be in chronological order. i think that could prevent some accidental srong votes.

**Comment by ajayyy** [comment]
Chronological order is fixed in https://github.com/ajayyy/SponsorBlock/pull/440

**Comment by ajayyy** [comment]
Color coding added in https://github.com/ajayyy/SponsorBlock/pull/440

**Comment by elypter** [comment]
thanks
