### ISSUE TITLE
[Feature request] Off-topic information blocking or similar for educational videos

### ISSUE THREAD

**Issue by Kore-Development** [ajayyy/SponsorBlock#559]
After watching a CrashCourse video such as [https://youtu.be/UC5km6-o2oM](https://youtu.be/UC5km6-o2oM), there was way too much off-topic information unnecessary for learning what the main point is. I would like a new block category to block these kinds of things.

**Comment by ajayyy** [comment]
Will be covered under https://github.com/ajayyy/SponsorBlock/issues/409 instead
