### ISSUE TITLE
Minor spelling issue in the Wiki 

### ISSUE THREAD

**Issue by drvladb** [ajayyy/SponsorBlock#565]
On ["3rd Party Ports"](url) under the ["iOS"](https://github.com/ajayyy/SponsorBlock/wiki/3rd-Party-Ports#iOS) section it says "tweak that implements the implements SponsorBlock" which should be "tweak that implements the SponsorBlock".

**Comment by ajayyy** [comment]
Fixed, thanks!

By the way, the wiki can be edited by anyone by clicking the edit button at the top right.

**Comment by drvladb** [comment]
Thanks, never saw that button
