### ISSUE TITLE
How to install extension in firefox by downloading file via github?

### ISSUE THREAD

**Issue by shivasagarrao** [ajayyy/SponsorBlock#575]
If I try to install extension by downloading FirefoxExtension.zip a pop-up is being displayed which says "Mozila has prevented this site from installing an unverified add-on"? How to resolve this issue?

**Comment by ajayyy** [comment]
Download the `.xpi` file.

**Comment by shivasagarrao** [comment]
I downloaded and installed `.xpi` file. It is enough or we need to again install FirefoxExtension.zip?What's the difference between an `.xpi` file and `.zip` file?

**Comment by ajayyy** [comment]
You only need one. The `.xpi` file is signed by Mozilla. 

The `.zip` file can be by enabling developer mode and installing it as a temporary addon.

**Comment by shivasagarrao** [comment]
Are you saying that for normal users it is enough to download and install `.xpi` file but for developers `.zip` file is needed?

**Comment by ajayyy** [comment]
Yes

**Comment by shivasagarrao** [comment]
Thanks for the information.
