### ISSUE TITLE
Support channel trailers

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#58]

**Comment by OfficialNoob** [comment]
Is this because of the url?

**Comment by ajayyy** [comment]
Somehow a url would have to be extracted from the video frame. The video frame also has a different id, so buttons don't get added

**Comment by OfficialNoob** [comment]
Why is this "wontfix"?

**Comment by OfficialNoob** [comment]
videoID = document.getElementsByClassName("ytp-share-panel-link")[1].innerText.split(".be/")[1]

**Comment by OfficialNoob** [comment]
Im going to add a getTrailerID function in utils

**Comment by OfficialNoob** [comment]
Failed on this multiple times

**Comment by mchangrh** [comment]
.take
