### ISSUE TITLE
Silence/Waiting loop/Placeholder category

### ISSUE THREAD

**Issue by elypter** [ajayyy/SponsorBlock#583]
I suggest a new category for periods in videos that have no or no original content. that could be a waiting animation, black screen or streamer being afk on a recorded live stream, bad cuts, content that has been removed and replaced by a placeholder, corrupted video and similar uneventful skippable sections.

**Comment by ajayyy** [comment]
Most of that is covered under "Intermission"

**Comment by elypter** [comment]
sorry
