### ISSUE TITLE
Enable "Query By Hash Prefix" by default and improve on it

### ISSUE THREAD

**Issue by Madis0** [ajayyy/SponsorBlock#593]
I feel like that is a somewhat underappreciated feature that should be enabled in SponsorBlock by default, for all. 
Here's why:

- protects private videos by default without slowing down
- if cached well, would avoid extra network requests per video and work a bit more like a traditional content blocker (see also: #161)
- protects privacy of all user-watched videos
- could be combined with the refetch feature to update many segment lists at once
- could be combined with skip count tracking to send counts in hash batches, e.g. once per day

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/529

**Comment by Madis0** [comment]
Sorry.
