### ISSUE TITLE
Keep info button available when popup is shown

### ISSUE THREAD

**Issue by Madis0** [ajayyy/SponsorBlock#594]
It is bad UX to open the popup via the info button, but not being able to close it from there (and having to look for a small "close popup" link instead).

I suggest making the button show "info icon" by default and "close icon" (a cross inside of the SB outline) when the popup is open. That would make it consistent with the start/stop button.

Additionally, the in-page popup could also have a standard X on the top right corner, similar to the "submit segment" popup, so the user can use either way to close it.

**Comment by AlecRust** [comment]
@Madis0 I think we can close this, the close button is now implemented. I would create a separate issue for anything else outstanding.
