### ISSUE TITLE
Improve the info popup

### ISSUE THREAD

**Issue by Madis0** [ajayyy/SponsorBlock#596]
In my opinion the info popup looks quite cluttered at the moment. 
Here are ideas to improve it:

- "Your work" section and Website/Leaderboard/etc. should be a part of the main options page - those things are not needed to see in every video
- Skipping toggle and ~whitelist~ allowlist (#592) could be topmost (as it is the most important hidden interaction), after that comes the existing segments and segment creation
- Proper close button (#594)
- Make the wording clear enough so hint texts aren't needed
- See the mockup for how I imagine it could be:
![mockup](https://user-images.githubusercontent.com/8611110/102984384-2d81a400-4516-11eb-84aa-3f0500a77b6a.png)

**Comment by elypter** [comment]
i dont think a close button is needed. just click outside the popup to close it. all addons do this and the behavior is implied

**Comment by Madis0** [comment]
@elypter I mean the in-page version of it, not the extension button popup.
