### ISSUE TITLE
Expand the tool to include rumble

### ISSUE THREAD

**Issue by brunoais** [ajayyy/SponsorBlock#597]
With the current state of affairs related to many complaints. Many people are running to other video websites such as rumble (maybe I'll make one issue for each).

I create this issue to request the ability to have this tool working on other websites besides just youtube.
In rumble, urls have this format:

`https://rumble.com/[video id]-title-of-the-video-separated-by-hiphens.html`
A video id is currently composed of 6 alphanumeric characters but I think it will change to more and more variety of characters.

For example: `https://rumble.com/vc1rbt-little-girl-gives-her-huge-dog-and-little-puppy-christmas-treats.html?mref=6ald&mrefc=6`

How viable would it be to add rumble as part of this addon?

**Comment by ajayyy** [comment]
I've never heard of rumble and can't find much information online about it

**Comment by brunoais** [comment]
[Rumble](https://rumble.com/) is a [youtube](https://youtube.com) competitor just like [banned.video](https://banned.video/) and [bitchute](https://bitchute.com/).
Each one of them with different business models.
To search about rumble you have to use duckduckgo or similar. Google search censors it due to being a competitor.

**Comment by ajayyy** [comment]
I would rather not include those sites, but I do think it would be cool to add support for YouTube alternatives such as PeerTube and other platforms like podcasts

**Comment by brunoais** [comment]
They are all equally different from each other. Rumble is quite close to youtube, though. Except more free.

**Comment by TinyBabyOwl** [comment]
> I would rather not include it if it is like those other two.
> 
> I do think it would be cool to add support for YouTube alternatives such as PeerTube and other platforms like podcasts

Rumble is more mainstream and closer to YouTube than those other sides. You should consider it.

**Comment by joeyryan** [comment]
Please consider including it now that Rumble has become a 2 billion dollar competitor to youtube. It has legitimate content on it and not garbage like banned.video and bitchute.

**Comment by LingKuja** [comment]
@ajayyy I really hope you'll reconsider, or that at least you'll get push/merges from people who'd add support for it.
Youtube isn't the only video streaming website, and the reason many people are having a hard time moving away from it is because of addons like these being tailor-made for youtube only.
I wouldn't mind a sponsorblock fork for rumble, but you should consider just adding support.

Please re-open the issue, because discarding a website out of personal preference is not the way to go professionally.
