### ISSUE TITLE
Make it so that a slow computer doesn't have issues from channel pages

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#60]
If a computer is too slow, and a channel page with a channel trailer is loaded first, the buttons will be added to the channel player instead of the video. It is supposed to wait for an actual video to be loaded, but on slow PCs it doesn't wait long enough.

**Comment by OfficialNoob** [comment]
What do you mean by "channel player" is that the "mini-player"

Also just ask people to get better hardware as it would increase productivity!
People in the PC master race should not need to have extra code just cos...
Some people are console peasants!

**Comment by ajayyy** [comment]
The channel trailer player.

**Comment by OfficialNoob** [comment]
what channel player?

**Comment by mchangrh** [comment]
should be fixed in https://github.com/ajayyy/SponsorBlock/pull/1070/commits/7f374f0f860d898f3ceddc7134c21eb7f35fd156
