### ISSUE TITLE
Multi-tiered cuts

### ISSUE THREAD

**Issue by elypter** [ajayyy/SponsorBlock#600]
People have different preferences on where to cut sponsored segments. some want to cut out every milisecond that is dedicated to a sponsorship, some  people don't mind hearing the introduction or segway to a sponsored segment and some even want to hear what the sponsor is, out of interest or for context, just not the lengthy ad that comes after.

it would be great if there were multiple tiers like a maximum cut, a medium cut and a minimal cut that the user could choose in the general settings or per channel.

**Comment by ajayyy** [comment]
I think manual skip is best for this
