### ISSUE TITLE
Popup message every time an unlisted video is found and addon option "ignore unlisted videos" is enabled

### ISSUE THREAD

**Issue by dany123** [ajayyy/SponsorBlock#602]
I've checked the addon option "Ignore Unlisted/Private Videos" but now every time a page loads with an unlisted youtube video (even on youtube itself) a dialog box appears and asks me to confirm [or cancel] this:
"The video has been detected as unlisted. Click cancel if you do not want to check for skip segments."
which doesn't make sense as I already confirmed in settings that the answer is no to this question.

Note that this appears for every unlisted video if a page has multiple embedded ones.

![image](https://user-images.githubusercontent.com/3215812/103180801-e858cb80-48a1-11eb-950b-183bd47871cd.png)

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/413
