### ISSUE TITLE
Suggestion: "Preview" for new skippable category

### ISSUE THREAD

**Issue by snowbie** [ajayyy/SponsorBlock#607]
I was about to submit a 32sec segment of a 15min video because the very first 32secs of it function as a preview/highlight-reel for the video. Various 5-10sec clips ripped from other parts of the video. It doesn't meet any of the criteria for any of the current categories.

It's technically content, but imo it's redundant and something I'd rather always skip. I imagine people--especially the ones who use this extension--would prefer to skip a highlight reel of a video they're about to watch.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/444
