### ISSUE TITLE
Safari extension is broken on macOS Big Sur

### ISSUE THREAD

**Issue by WoodpeckerBaby** [ajayyy/SponsorBlock#608]
> @rakalix has uploaded it to the AppStore: https://github.com/rakalix/SponsorBlock#sponsorblock-for-safari-macos
> 
> _Originally posted by @ajayyy in https://github.com/ajayyy/SponsorBlock/issues/312#issuecomment-695831111_

It has been broken on macOS Big Sur since November and there is no way to submit issues in the Safari repo. People have been talking about this on Reddit.

This button doesn't do anything and the Safari extension doesn't load. I had to force quit the app.
<img width="520" alt="Screen Shot 2021-01-01 at 5 49 27 PM" src="https://user-images.githubusercontent.com/14303318/103436766-4565d000-4c5a-11eb-9810-a5c5098291dc.png">

**Comment by ajayyy** [comment]
This is probably best as a comment on that other issue
