### ISSUE TITLE
Support invidious

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#61]

**Comment by Z3ROGRAV1TYx** [comment]
Bumping this, would absolutely love to see [Invidious](https://github.com/omarroth/invidious) support please!

**Comment by tuxayo** [comment]
I suppose that many people knowing SponsorBlock and Invidious would like to use booth. So they are cannibalizing each other's userbase as one must choose one.

**Comment by Z3ROGRAV1TYx** [comment]
@tuxayo wdym?

**Comment by ajayyy** [comment]
Finished

**Comment by tuxayo** [comment]
I just tested, this amazing!!!!!! :D
Thank you! thank you! thank you!

**Comment by tuxayo** [comment]
@Z3ROGRAV1TYx 
> @tuxayo wdym?

For example, I couldn't use SponsorBlock because I used Invidious. And I guess a lot of people using SponsorBlock couldn't use Invidious even though they wanted. So it was splitting the user base. But not anymore!!! :D
