### ISSUE TITLE
Why ask for 'Access your data for all websites' in Firefox Add-on?

### ISSUE THREAD

**Issue by timvisee** [ajayyy/SponsorBlock#610]
The Firefox Add-on notes that it may ask for 'Access your data for all websites', instead of just accessing site data on YouTube.

![image](https://user-images.githubusercontent.com/856222/103566437-4d27ad80-4ec2-11eb-81a7-188c8a10fd72.png)

https://addons.mozilla.org/en-US/firefox/addon/sponsorblock/

What is this for?

**Comment by ajayyy** [comment]
It says that "**it may ask**". This is used to add support for your own Invidious instance (3rd-party frontend) as well as add a custom API server (this permission is required for all sites the extension sends requests to)

I guess better wording would be that it can "May ask to access your data for **any** website"

**Comment by timvisee** [comment]
I understand, didn't know about that feature. Thanks!
