### ISSUE TITLE
Not skipping on any videos

### ISSUE THREAD

**Issue by AntiSol** [ajayyy/SponsorBlock#611]
This may be something you're already aware of, apologies if it is. 

I'm seeing issues with sponsorblock on youtube. it looks like they've updated their player and that the new player isn't working with sponsorblock.

The new player has an "autoplay" button between the regular close caption button and sponsorblock's "segment starts now" button.

it seems that ever since this new player took effect, sponsorblock isn't working anymore. As an example, I added a couple of segments to https://www.youtube.com/watch?v=OytOJdGsrA0 but when I watch the video sponsorblock is not skipping them.

I'm running sponsorblock in Waterfox classic 2020.12 (64-bit).

**Comment by AntiSol** [comment]
...no response at all? am I missing something really obvious? is my description unclear? is nobody else seeing the same issue?

Sponsorblock is currently completely useless to me as a result of this, has been for about a week...

https://user-images.githubusercontent.com/351169/104418441-0412e000-55cb-11eb-9a16-70e23778c51f.mp4

**Comment by t1g3pf4c3** [comment]
Same issue. Checked plugin preferences and all firefox addons. Nothing works. SponsorBlock just mark segments, but can't skip it

**Comment by ajayyy** [comment]
@t1g3pf4c3 which browser version?

**Comment by t1g3pf4c3** [comment]
@ajayyy Firefox 84.0.2

**Comment by UserNaem** [comment]
Tried Firefox 84, Firefox 56, Waterfox 56.2.14, no issues to report, everything works fine here. Try making a new profile in about:profiles.

**Comment by t1g3pf4c3** [comment]
@UserNaem thanks a lot. Switching to new profile worked for me. Looks like it's just my firefox issues

**Comment by prediscover** [comment]
Sponsorblock broken for me, firefox 85 :( Going to see if it's the profile

**Comment by ajayyy** [comment]
Next person who experiences this, please go the options and copy the debug info before making a new profile.

**Comment by therobdog7** [comment]
This is happening to me, here's my debug info.
[debug_info.txt](https://github.com/ajayyy/SponsorBlock/files/5913285/debug_info.txt)

**Comment by ajayyy** [comment]
I unfortunately can't reproduce it with your config

**Comment by therobdog7** [comment]
Weird, it might be an addon problem for me, it only happens sometimes.

**Comment by ajayyy** [comment]
@therobdog7 oh, that's a different problem then. Do you have video speed?

**Comment by therobdog7** [comment]
Yes, do they conflict with each other?

**Comment by ajayyy** [comment]
@therobdog7 Yes. Until they merge my pull request into their extension (https://github.com/igrigorik/videospeed/pull/740), changing the speed using that extension will break it. However, you can easily work around this by pausing/playing the video after every speed change.

**Comment by therobdog7** [comment]
Great, thank you

**Comment by Tudi20** [comment]
For me, it breaks when installed by default via Firefox syncing

**Comment by OwO-tism** [comment]
Same problem here. I have the "Enhancer for YouTube™" add-on, is that the source of the problem? If yes, is there any workaround (since pausing and un-pausing doesn't do anything)

What's confusing me is that I have skipped some segments already. Can't recall any since most of the time I have YouTube running in the background, but I installed the Enhancer for YT before Sponsorblock

**Comment by kolva1** [comment]
This has been also happening to me too. When I also disable uBlock Origin, it doesn't skip.

**Comment by kolva1** [comment]
[debug.txt](https://github.com/ajayyy/SponsorBlock/files/6072907/debug.txt)

**Comment by Ryanlie** [comment]
for me it breaks after i sign in to sync

**Comment by UberActivist** [comment]
I had this issue and by trying various things I managed to fix it by opening up the permissions page and enabling it to work for all sites. 
![image](https://user-images.githubusercontent.com/11623577/111566736-b7cf5200-876b-11eb-8e5c-b3fc12255f2b.png)

Whenever I turned this setting off, it stopped working again. No clue why this is the case, but hopefully this will help someone.

**Comment by AntiSol** [comment]
where is that page? my sponsorblock settings look completely different and I don't see that option anywhere

**Comment by UberActivist** [comment]
This is on the addons page. Click on the add-on in the list.
![image](https://user-images.githubusercontent.com/11623577/111567163-81460700-876c-11eb-8981-f121353b2a32.png)
Then click on the permissions button.
![image](https://user-images.githubusercontent.com/11623577/111567214-94f16d80-876c-11eb-99e9-3fa9e2b4068a.png)

**Comment by AntiSol** [comment]
still don't see that

**Comment by AntiSol** [comment]
and apparently github is broken and won't let me attach files anymore, so: 
https://antisol.org/Screenshot_2021-03-18_14-24-54.jpg

**Comment by unbeatable-101** [comment]
What shows up when you click `preferences`?

**Comment by AntiSol** [comment]
https://antisol.org/Screenshot_2021-03-18_18-13-06.jpg

**Comment by Ryanlie** [comment]
press ctrl + shift + a to open addons page or press the 3 lines on top right and look for addons button

**Comment by Mattwmaster58** [comment]
Relatively recently started having this issues as well.  Firefox 88

**Comment by OlgaForoga** [comment]
Having the same issue. I have tried the last five releases each of Chrome, Firefox and have tried the latest release (and dev release) of Microsoft Edge. I have tried to load a YT video that I know had sponsor segments which skipped in the past, with all of the various releases I've tested, none of them showed up. For each attempt, the extension popup reads "No segments found". When I tried to submit my own, the arrow on the player spun for about five minutes, then the segments were highlighted green, but upon reloading the page, no segments were found. I have tested this as the only extension installed, and used the official version from the relevant app store in each case.

**Comment by ajayyy** [comment]
@OlgaForoga Yea, the server is broken right now, but feel free to post again if it is still not working one it is fixed

**Comment by ajayyy** [comment]
I think this is caused by https://github.com/ajayyy/SponsorBlock/issues/698

**Comment by Deliphin** [comment]
The force channel check is not the cause. It may be a cause for some people, but on my machine it has no effect.
Force Channel Check ON, Permissions Fix = Skipping works.
Force Channel Check ON, No Perm Fix = Skipping doesn't work.

**Comment by AntiSol** [comment]
it looks like #738 solves this for me. I just got a prompt to accept permissions and now it seems that sponsorblock is working again! I've watched a couple of videos and seen skipping work for each. 

I've missed it so much! Thanks! :)

**Comment by ajayyy** [comment]
Perfect! Thanks for letting me know

**Comment by MMaskell** [comment]
Not sure that fixed it, I got the prompt clicked it, reloaded the page and got the prompt again

**Comment by ajayyy** [comment]
Mozilla has to manually review the update

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/741
