### ISSUE TITLE
[Suggestion] Support to skip curse words

### ISSUE THREAD

**Issue by CreeperPookie** [ajayyy/SponsorBlock#614]
Your extension works great; especially in YouTube Vanced. However one problem that has is that curse words aren't skipped. If there was a way to directly skip over curse words, it would make not only desktop YouTube better, but also Vanced which uses your extension.

**Comment by ajayyy** [comment]
https://github.com/richardfrost/AdvancedProfanityFilter#installation

**Comment by CreeperPookie** [comment]
Yes, I am well aware of this extension; I use it myself. The problem is now that YouTube Vanced supports your extension, it can't use that (two different programming languages). I submitted a suggestion to them, but their best advice was to submit it here and wait for the feature to go downstream into Vanced; I watch videos quite often on a phone, which is why I suggested this.

**Comment by ajayyy** [comment]
haha, now I see that I the link I got the link from your other thread. Anyway, I don't think that really makes sense as something user generated
