### ISSUE TITLE
Improve server address settings clarity

### ISSUE THREAD

**Issue by Madis0** [ajayyy/SponsorBlock#615]
Instead of 
![current](https://user-images.githubusercontent.com/8611110/104091989-c3912a80-5289-11eb-8c3d-71b687289859.png)
I would recommend doing it like
![new](https://user-images.githubusercontent.com/8611110/104092089-53cf6f80-528a-11eb-83ee-2f07b2cd1f49.png)

Benefits:

- always clear, which option is activated (e.g. currently beta toggle doesn't change the URL)
- main URL can be changed by the extension at any time (if so needed) without changing users' config
- no reset button needed because the user can just choose another radio button

**Comment by ajayyy** [comment]
I think it might be clearer just to hide the server settings if the beta server is enabled.

I don't think it is used enough to warrant being so prominent in your proposed design.
