### ISSUE TITLE
Feature request: "Video Preview reel" segment

### ISSUE THREAD

**Issue by m-orsh** [ajayyy/SponsorBlock#620]
Different from the currently available categories, a "Video preview" consists of short clips at the start of a video showing the most interesting parts of the following full video. Sometimes these are included to lengthen a video while catching the interest of viewers. But they often spoil the video's best parts as well, and hence are worth considering adding as a skippable segment.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/444
