### ISSUE TITLE
"Intermission skipped" when changing the resolution on a playing video

### ISSUE THREAD

**Issue by FunctionDJ** [ajayyy/SponsorBlock#621]
Title pretty much says it all. It doesn't happen when the video is paused though.
Maybe SponsorBlock just thinks something was skipped because the video sort of reloads?
It doesn't show up when using the number keys to jump to a part in the video, so that might be false.

**Comment by ajayyy** [comment]
Which version?

**Comment by ajayyy** [comment]
see https://github.com/ajayyy/SponsorBlock/issues/183, but it should have been fixed

**Comment by FunctionDJ** [comment]
Indeed appears to be fixed, will re-open the issue otherwise.
Thanks a lot for this epic extension, has saved me a lot of time already! ♥
