### ISSUE TITLE
Looking to use the API in Nuclear - my music player

### ISSUE THREAD

**Issue by nukeop** [ajayyy/SponsorBlock#623]
>If you end up using the API, I'd love to know about how you're using it. Tell me about it by making a GitHub issue or emailing me :)

I want to integrate SponsorBlock API with my music player: https://github.com/nukeop/nuclear
I noticed that some songs have fillers from music labels or other sponsor-type garbage in them, so it would be useful for my users to cut those segments out and leave only the music.

**Comment by ajayyy** [comment]
Nice! Thanks for letting me know
