### ISSUE TITLE
Segment length templates

### ISSUE THREAD

**Issue by c0mplexx92** [ajayyy/SponsorBlock#625]
So for example if someone has a 15sec and 1 frame or something intro I can just start the segment and then pick it and it will fill it in by itself instead of me constantly picking start and end point

**Comment by mchangrh** [comment]
fixed in https://github.com/ajayyy/SponsorBlock/pull/988

**Comment by ajayyy** [comment]
no, this is about predefined templates

**Comment by ajayyy** [comment]
#799
