### ISSUE TITLE
Question: What are the type buttons for after voting on a multiple segment skip?

### ISSUE THREAD

**Issue by FunctionDJ** [ajayyy/SponsorBlock#626]
Screenshot:
![image](https://user-images.githubusercontent.com/34871211/105554305-58bf0500-5d07-11eb-9f35-264647a4988b.png)

The last line of the popup show some skip types, probably of the two things that were just skipped, and clicking on them also casts a vote, but i'm not sure how i'm supposed to use them. When a multi-skip occurs, and it's good, i would think that voting just upvotes all skipped segments.

**Comment by ajayyy** [comment]
You choose which segment to vote on

**Comment by FunctionDJ** [comment]
I see. Thanks for the response. Can i upvote all segments at once, or vote on one segment and then on another one?

**Comment by ajayyy** [comment]
Only one at a time
