### ISSUE TITLE
Suggestion: New Other Category

### ISSUE THREAD

**Issue by CreeperPookie** [ajayyy/SponsorBlock#627]
Your extension works great for skipping sponsors, self-promotion, etc. One thing is that sometimes there's something I want to skip, but doesn't necessarily fit in a category. For this, an 'other' category would be really helpful, especially for things that fit multiple or none of the categories.

**Comment by MRuy** [comment]
Having specific categories makes it possible to enforce the guidelines and fight spam.  
Having a "other" category could lead to massive spam submissions that cant be moderated.
