### ISSUE TITLE
Have I been banned?

### ISSUE THREAD

**Issue by realNZZN** [ajayyy/SponsorBlock#628]
Every submission I make is instantly marked as "shadowhidden" on https://sb.ltn.fi/?username=NZZN%E2%9E%9F&page=1&sort=timesubmitted- and doesn't show up as a segment in sponsorblock.

**Comment by MRuy** [comment]
Yes you are banned.  
(Join your discord to get in contact and dont use github issues for this)

Looks like the ban happend around 2020-10-31 11:45:29  
https://sb.ltn.fi/userid/0b77cd2a88244947d18e91bc42aa2e55969eaa7ab8c89819bc5dfbcdfa28d588/?page=4

**Comment by realNZZN** [comment]
Will changing my userid from the settings menu get around this or will my ban transfer over, I don't even know why or how I could be banned, might be because I dislike and overwrite segments that had bad timing a lot.

**Comment by ajayyy** [comment]
It will transfer over

**Comment by whyiswhen** [comment]
> It will transfer over. Please see your submissions on the scale of the universe video, they were very wrong

how is that possible to track someone if someone have reinstalled the extension. don't he get a new userid if reinstalled?
