### ISSUE TITLE
Default segment key 'semicolon' collides with native speed-down hotkey (shift + semicolon)

### ISSUE THREAD

**Issue by FunctionDJ** [ajayyy/SponsorBlock#629]
On YouTube you can use shift + semicolon / colon to speed up or slow down videos. Since i do this a lot, i often got the notification by the extension that i had unsubmitted segments after leaving a video.

Either the segment function shouldn't be triggered if another key like shift is being held, or the default key should be a different one.

**Comment by pxeger** [comment]
The actual key definitions for speed changing are Shift + Comma and Shift + Dot. There are only a few keyboard layouts where this happens to be the same as `;` and `:`, so I don't think it's worth changing the defaults. You can simply override them.

**Comment by pxeger** [comment]
Also this is a duplicate of #616 and #147. Please search for existing issues before posting a new one

**Comment by FunctionDJ** [comment]
> The actual key definitions for speed changing are Shift + Comma and Shift + Dot. There are only a few keyboard layouts where this happens to be the same as `;` and `:`, so I don't think it's worth changing the defaults. You can simply override them.

My bad, i actually meant colon and period. I only said semicolon because that's what shift + colon gives you. I didn't know this issue isn't present on QWERTY keyboards, i assumed this was an oversight, since you wouldn't notice this issue if you never used speed up/down keys.

> Also this is a duplicate of #616 and #147. Please search for existing issues before posting a new one

I did try, but the terms i used didn't bring up the first issue. When reading the title of the second issue, i didn't think it would mention this specific case of collision.
