### ISSUE TITLE
Suggestion: Jumpscare category

### ISSUE THREAD

**Issue by Lucas7yoshi** [ajayyy/SponsorBlock#633]
Was recently watching some horror videos and came across a reply mentioning the creator should have a jumpscare countdown.
Seeing as sponsorblock has non sponsorship related categories already, eg. Music: Non-music section i felt that it could be a decent possibility.

Probably with like a countdown to it, optional of course. 
But i think it could have potential.

Apologies if this is an incorrect usage of the issues, but i saw other suggestions so im bouncing it here.

**Comment by ajayyy** [comment]
I don't this makes sense for this extension
