### ISSUE TITLE
Better Segment Recognition

### ISSUE THREAD

**Issue by Haxorzz** [ajayyy/SponsorBlock#639]
To my (poor) understanding, sponsorblock really only checks if the playhead has reached the start of a segment, not caring if the play head is already in a segment (by skipping forward or by placing it there manually) This also shows why it disappears with a timer and not just if it exits the segment. I suggest two ideas:
1. Start a 3-5s timer when the playhead reaches the end of a segment, instead of having a timer be the length of a segment + 5 seconds, because skipping forward whilst in said segment will cause the pop-up to stay there for a longer period of time
2. Implement it like the front end "Youtube Vanced". The mentioned front end shows the pop up only when its within a segment, no timer just a skip button. It works flawlessly! If it worked like that with the addon it would be perfect!

Atleast that's my opinion. I don't know if this is even possible.

**Comment by ajayyy** [comment]
Moved to https://github.com/ajayyy/SponsorBlock/issues/640
