### ISSUE TITLE
Mark the timeline

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#64]
We have gray for buffered and a different for unbuffered, yellow for ad, red for watched. Can we get green for go...er, I mean skipmarked? Option to jump to the end of a skip if seeking within and display skippable details (count/time) either on icon hover or skip time detail if over its spot on the timeline could be neat. Please don't noticeably hurt browsing performance just to implement any of this though and thanks again for the great addon.

**Comment by ajayyy** [comment]
![image](https://user-images.githubusercontent.com/12688112/62414303-9564e100-b5e7-11e9-9441-93e4b814c531.png)
This is how the "video segments" extension does it. I think something like that could be nice. Maybe make the color a little more noticeable?

**Comment by ajayyy** [comment]
https://github.com/videosegments/videosegments/blob/f1e111bdfe231947800c6efdd51f62a4e7fef4d4/segmentsbar/segmentsbar.js

https://github.com/videosegments/videosegments/blob/f1e111bdfe231947800c6efdd51f62a4e7fef4d4/player/player.js#L253

**Comment by mirror176** [comment]
As I do not know the video, I presume it is the dark gray below areas? I have a 1920x1200 monitor which puts the timebar over black by default in fullscreen so hope it may still be visible for reference.

**Comment by ajayyy** [comment]
Yes, the grey. I'd want to change the color
