### ISSUE TITLE
Endcards block manual skip prompt

### ISSUE THREAD

**Issue by tennessinegd** [ajayyy/SponsorBlock#642]
The endscreen video/channel buttons overlay the manual skip prompt and make it impossible to click.

Here is a screenshot.
![image](https://user-images.githubusercontent.com/60480128/107120065-6befda00-689c-11eb-8bf0-e4f6f1e4fe34.png)

I'm using the official Microsoft Edge SponsorBlock extension linked in the README file, along with the uBlock Origin and Enhancer for YouTube extensions.

**Comment by whyiswhen** [comment]
just add these rule to user rules in ublock origin if you are having problem by endscreen
! Removes recommended and featured videos in the endscreen
||ytimg.com/yts/swfbin/player-*/endscreen.swf$object-subrequest,domain=youtube.com
youtube.com##.html5-endscreen-content
youtube.com##.html5-endscreen

**Comment by MRuy** [comment]
Looks like the z-index of 50 must be increased to 1000, by inspecting the endcards it looks like they have at least 922.  
A different approach would be to check the value of the endcards and then use a higher one by code
