### ISSUE TITLE
Add a "set current time" button to the edit menu

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#65]
Seems easy to mark a start/stop initially but after that its either delete and do it again or edit times by typing numbers. Did I miss something?

**Comment by ajayyy** [comment]
Yep you can also delete individual times now. Right beside the edit button.

You can also mark multiple sponsors at once before uploading.

**Comment by ajayyy** [comment]
I don't really understand what you mean by the title

**Comment by mirror176** [comment]
I do not see a way to mark the start or stop of an edit after the start/stop point has been marked short of deleting it to do it again. A second edit can be started/stopped but it is not easy to modify the start/stop without editing the time itself. A better title may be "Ability to mark the start/stop of an edit with a button is lost after the initial start/stop has been set."

**Comment by ajayyy** [comment]
So, are you saying that, when in edit mode, there should be a button saying "current time" that will edit that one to the current time?

**Comment by mirror176** [comment]
Sounds right. mark current time for stop or mark current time for start of an edit so a time wouldn't have to be entered manually.
