### ISSUE TITLE
Lie to YouTube in watch time statistics

### ISSUE THREAD

**Issue by leo-lb** [ajayyy/SponsorBlock#651]
Hello!

To avoid that one day sponsors use the watch time statistics in YouTube dashboard to punish content creators financially, I would suggest that SponsorBlock especially tries to fake the watch time statistics so YouTube does not log the sponsor (or others) segments as skipped but as viewed. How that can be achieved remains the be researched.

Do you think it's something worth considering?

Thank you

**Comment by ajayyy** [comment]
I thought about this, but no, for several reasons:

- This would encourage people to make long sponsors
- This would affect YouTube Premium revenue

**Comment by leo-lb** [comment]
@ajayyy Affect YouTube Premium revenue in what way? Care to explain?

Yes skip data is public but if a sponsor cannot prove people skipped their ad segment on one particular video then they can't argue with it.

**Comment by ajayyy** [comment]
YouTube premium revenue is based off what percentage of watch time you have compared to the entire platform

**Comment by leo-lb** [comment]
@ajayyy I see, and that's what arbitrary content creators will receive instead of revenue from ads, correct? How exactly you think it is bad that it affect this YouTube Premium revenue?

**Comment by ajayyy** [comment]
It would be probably fraud. 

It also would give more money to people with sponsorships than those without sponsorships, which is the definitely not something I'd want to do.

**Comment by leo-lb** [comment]
@ajayyy Makes more sense now. But the status-quo still remains kind of embarassing, I don't think sponsors are given access to watch time statistics right now but it could become a threat. Either way, I'd love if content creators could easily obtain funding without depending on any form of advertisement at all.

**Comment by ajayyy** [comment]
Yes, I agree. Maybe it's inevitable that sponsors will become devalued, and we'll be able to move onto other funding methods, but time will tell what will happen.
