### ISSUE TITLE
want feature to create repetitive segment in a playlist at one time.

### ISSUE THREAD

**Issue by whyiswhen** [ajayyy/SponsorBlock#652]
i have seen many channel who just add same introduction  animation, end card and subscribe request animation in every video. and it is quite difficult to segment is each and every segment .  i  tried make as much as segment as i can but now I'm exhausted . initially i used to thought that sponsor block is using artificial intelligence and will itself make segment in few weeks but i was wrong.

example - https://www.youtube.com/watch?v=EdUAecpYVWQ&list=PLwjK_iyK4LLBVM18VZ7JKW-q88FAtnr8_&index=1 ( this have a introduction  intermission animation of 00:12.414 in each and every video . 
2.)https://www.youtube.com/watch?v=227Wi6h1h7o&list=UUOhHO2ICt0ti9KAh-QHvttQ&index=2( this channel have  3586 video till this date and all those have a subscribe reminder in every video of 0:07.414 . i hope you can understand it is not possible to make segment in every video . )

**Comment by ajayyy** [comment]
I think this is too risky, as some videos might have different intros.

**Comment by whyiswhen** [comment]
then can you please provide the option to make those segments only for me . for my user id only or in local database( i don't know how difficult is that to code)  if you think it is risky for other. i want to see the complete playlist and if there are any different segment i will bear them. as i  https://www.youtube.com/watch?v=EdUAecpYVWQ&list=PLwjK_iyK4LLBVM18VZ7JKW-q88FAtnr8_&index=1 know really have same intro and endcard in all video. 
i think you will agree it is not possible for me to mark all the segment.
Is that real that sponsor block is using machine learning . i think the i have read about it somewhere on your website.in my opinion the systems should at least process the videos of the youtubes with more that  20 million subscribers for introductions and end cards.

**Comment by ajayyy** [comment]
I think it is risky for everyone
