### ISSUE TITLE
Edge with Chrome extension can't submit

### ISSUE THREAD

**Issue by Cyberbeni** [ajayyy/SponsorBlock#653]
I was using the Chrome extension in Edge but I couldn't submit times for a while. Whenever I hit submit, the thing would just spin infinitely and if I closed and reopened Edge, the segments wouldn't be there.
I copied my settings/userID and downloaded the Edge store version, restored my settings, and it could instantly submit segments.

**Comment by Cyberbeni** [comment]
Hmm, I tried reinstalling the Chrome extension and it also works now 🤔

**Comment by ajayyy** [comment]
This is probably the bug where the userID never gets generated (stays at undefined). I'm scared to add a check for it as I'm worried about overwriting actual userIDs, since sometimes the synced storage takes time to load.
