### ISSUE TITLE
Preview Submissions - Skip to right before the start to see if it is accurate

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#66]
A button to help jump to just before an edit would help verify it. A one second ad is easy to test with the left arrow key a few times but long cuts are best seeked with a series of repeated keystrokes or clicking on the timebar. Could also have an option to decide how close to just before the edit tit will jump to as a general setting but a default short time (1-2s or so would likely be good).

  After the jump, a loop over the same edit would be nice too but a repeatedly clickable button or something on hotkey would be very nice already.

  In my experience, each playthrough doesn't comes out identical either so for my first edit I set the start a little earlier than I expected as sometimes frames of the sponsor appeared while other times they were missing. I do not know if that reliability changes by seeking back/forward different amounts or to different times but my quick left arrow previewing to approximately the same place caused variations in each playback.

**Comment by ajayyy** [comment]
I think I am misunderstanding what you mean by edit. Do you mean a sponsor skip?

**Comment by ajayyy** [comment]
The inconsistency of the skips is due to the browser sending an event to the extension 4 times per second to check. This is not as accurate as frame by frame, but I feel good enough.

**Comment by mirror176** [comment]
if i have a cut from 3min to 4min, make a button that can jump to 2min 58 sec (or whatever offset before) to make testing an edit easier. Playback then will roll for about 2 seconds and perform the jump from 3min to 4min as it currently does so the cut can be previewed. A separate loop feature would then repeat that at say 4min 2 sec jumping back to 3min 58sec as a further enhancement so microadjustments could be tested easier while adjusting.
