### ISSUE TITLE
server overload

### ISSUE THREAD

**Issue by whyiswhen** [ajayyy/SponsorBlock#660]
![image](https://user-images.githubusercontent.com/76880977/109414754-98e66700-79da-11eb-8e03-56d2b3fcc946.png)

getting this error most of the times from some days every time i try to upload segment

**Comment by whyiswhen** [comment]
![image](https://user-images.githubusercontent.com/76880977/109415424-a867af00-79de-11eb-880d-ae102d757ade.png)
this error too

**Comment by ajayyy** [comment]
See http://status.sponsor.ajay.app/ for server status

**Comment by whyiswhen** [comment]
Hmm... So i was correct that I'm facing issue in submission from someday .
What Is the reason of these issues .is that because of the lack of servers.
Both of the sponsor block and the sponsor block submission are red right
now. And I'm not able to use sponsor block. It will create  a
bigger problem for me. When sponsor block is not working I will try to
submit segments for it and will not be able to submit segments. I think you
should give a popup when the sponsor block is not working.

**Comment by whyiswhen** [comment]
![image](https://user-images.githubusercontent.com/76880977/109458788-870cce80-7a83-11eb-8853-eb0c427d5eb9.png)

**Comment by whyiswhen** [comment]
![image](https://user-images.githubusercontent.com/76880977/109484618-a9641380-7aa6-11eb-8b22-e96aaaf8631f.png)

**Comment by KLVN** [comment]
> I think you should give a popup when the sponsor block is not working.

Soo... something like https://github.com/ajayyy/SponsorBlock/issues/660#issue-818169890 and https://github.com/ajayyy/SponsorBlock/issues/660#issuecomment-787430832 ?

**Comment by whyiswhen** [comment]
> > I think you should give a popup when the sponsor block is not working.
> 
> Soo... something like [#660 (comment)](https://github.com/ajayyy/SponsorBlock/issues/660#issue-818169890) and [#660 (comment)](https://github.com/ajayyy/SponsorBlock/issues/660#issuecomment-787430832) ?

ya similar even also for not working.

**Comment by whyiswhen** [comment]
![image](https://user-images.githubusercontent.com/76880977/109980682-2a7d0e00-7d26-11eb-834b-f6e480aaf159.png)
today this happened again and  i thought that this video does not  have segment.
