### ISSUE TITLE
Tagging fixed length endcards for a specific channel. 

### ISSUE THREAD

**Issue by KorayUlusan** [ajayyy/SponsorBlock#662]
Some channels have fixed length endcards for each video. It would be helpful to mark last XX seconds (eg. 10 secs) of every video as Endcards/Credits. 

For example all videos of [this](https://www.youtube.com/channel/UCgCudMsK-kxYxB2RgiS3bzQ) channel has always has 10 second endcards. Example [video](https://www.youtube.com/watch?v=UzmtxCml_JQ)

**Comment by ajayyy** [comment]
I think this would be too prone to error. However, it could be interesting to calculate it based on when the actual endcards appear in the player.
