### ISSUE TITLE
Whitelist Cytube

### ISSUE THREAD

**Issue by Deliphin** [ajayyy/SponsorBlock#664]
https://cytu.be/ is a syncing platform, and I and my friends use it for youtube.

When youtube videos play on it, sponsorblock still takes effect. It will still attempt to skip ads and the like. The problem with this is cytube expects to be in control of that stuff. It gets kinda buggy. If I'm the leader it's fine, but that's not a guarantee-able thing.
Also, when the video changes, the sponsorblock data gets kind of messed up, which means even if you were to make sponsor block detect if I'm the cytube leader, it still wouldn't work properly.

What I'm requesting is for sponsorblock to automatically disable when it detects when the youtube player is an embed on this specific domain.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/554
 
https://github.com/ajayyy/SponsorBlock/issues/537

https://github.com/ajayyy/SponsorBlock/issues/150
