### ISSUE TITLE
saved time not updating 

### ISSUE THREAD

**Issue by whyiswhen** [ajayyy/SponsorBlock#665]
![image](https://user-images.githubusercontent.com/76880977/109920299-19a9a980-7ce0-11eb-9c54-d5d90a791dd7.png)
the number of skip are not updating from some days . it is 50938 from some days .

**Comment by ajayyy** [comment]
It has been disabled temporarily to reduce load.

**Comment by whyiswhen** [comment]
where did you had updated about it .now there is no incentive for me and other to add segments.

**Comment by whyiswhen** [comment]
okay 👍

**Comment by ajayyy** [comment]
The incentive should be to help others, even if you don't know exactly how much you are helping.

**Comment by whyiswhen** [comment]
Hmm,You are right. But still try to bring that back as soon as possible.

**Comment by whyiswhen** [comment]
![image](https://user-images.githubusercontent.com/76880977/110237537-9946ab00-7f62-11eb-90ef-7a59f616e8d1.png)
what are the other things that are not updating.
