### ISSUE TITLE
Ghost skips

### ISSUE THREAD

**Issue by MRuy** [ajayyy/SponsorBlock#667]
Chat messages from SponsorBlock Discord  

> [[16:14] Nanobyte](https://discord.com/channels/603643120093233162/607338052221665320/817414898736693298): I just had a ghost skip on a video and did a little investigation about it.
The skip belonged to the previews video i watched, ironically i even submitted it while watching it, and the video (first video) was just released.
I suspect, because the video (first) is new, that the background loading for new segments doesn't get canceled if you switch to the next video.
I think its hard to debug and i dont have any knowledge about the code so i hope that could help fixing the ghost skips.  

[...]
  
> [[16:55] Nanobyte](https://discord.com/channels/603643120093233162/607338052221665320/817425119353110528): I think here is one part of the problem
https://github.com/ajayyy/SponsorBlock/blob/26197d4ff9b9389036633eb9c14618a2a8269e6e/src/content.ts#L673
the retryFetch gets the videoID and sets a timeout but never checks if the video changed

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/303
