### ISSUE TITLE
Hide segments when downvoted from the popup panel

### ISSUE THREAD

**Issue by chirag127** [ajayyy/SponsorBlock#668]
![image](https://user-images.githubusercontent.com/76880977/110196415-59040180-7e6a-11eb-8ae4-290b4e580047.png)
here the end card is a wrong segment. i downvoted it ,but segment not removed and i want to listen to this atleast 10 times. so will i have to press unskip button everytime i watch this video.

so i want to say that the segment should get removed for the user who downvote it instantly.

**Comment by ajayyy** [comment]
It should be removed until you reload

**Comment by whyiswhen** [comment]
![image](https://user-images.githubusercontent.com/76880977/110196831-23144c80-7e6d-11eb-9b56-1c310efed514.png)
no it have not been removed .

**Comment by ajayyy** [comment]
You need to downvote it with the unskip notice for it to be hidden

**Comment by whyiswhen** [comment]
![image](https://user-images.githubusercontent.com/76880977/110196881-7b4b4e80-7e6d-11eb-9fcd-5ca8984643a0.png)
i have notice disabled . i have downvoted there 2 times.

**Comment by whyiswhen** [comment]
i think  that my downvotes are counted as 1 only. and i know that a segment need at least 3 downvotes to get removed. i think that the segment should get instantly removed for the user who downvoted it one time  .

**Comment by whyiswhen** [comment]
![image](https://user-images.githubusercontent.com/76880977/110200909-43043a00-7e86-11eb-84c1-c902e2a892e6.png)
the segment has not even been removed yet and that too on justin bieber's official music video.

**Comment by whyiswhen** [comment]
okay is that something like downovotes done from popup panel don't count or is that something like popup player downvoting is useless. i used to think that it works that the reason it is given there right?

**Comment by whyiswhen** [comment]
![image](https://user-images.githubusercontent.com/76880977/110499811-9c869600-811e-11eb-8e47-eb14e755a087.png)
![image](https://user-images.githubusercontent.com/76880977/110499829-a14b4a00-811e-11eb-9998-6542ebb3a379.png)
the like and dislike come in which service.

**Comment by securingmom** [comment]
How are competing submissions weighted after voting down erroneous timing?

**Comment by mchangrh** [comment]
implemented in https://github.com/ajayyy/SponsorBlock/commit/4d60dec7f997bb076bfe7dc9d2b7079b96df3e95
