### ISSUE TITLE
Is server down?

### ISSUE THREAD

**Issue by ToRRent1812** [ajayyy/SponsorBlock#669]
It's over 2 months and I can't submit blocks or receive them on new videos. Submitting throws 504 gateway error
![Zrzut ekranu 2021-03-06 154810](https://user-images.githubusercontent.com/4561094/110210767-8b762480-7e93-11eb-9d49-dd202bdd6760.jpg)

**Comment by MRuy** [comment]
The server is under high load at peak times right now, Ajay is already working on a solution

**Comment by ajayyy** [comment]
https://status.sponsor.ajay.app/

**Comment by whyiswhen** [comment]
i'm observing that the server getting down every sunday.
sponsorblock don't work on sundays.

**Comment by DRSDavidSoft** [comment]
@ajayyy Is there something that we could help with?
Maybe an alternative submission server that _temporarily_ holds into that data, and the main server could query it when it's not busy?  That way the submission data is not lost when server is unavailable.
Personally, I had to sniff the POST query and save it locally on my machine, but I've been trying for a couple of days now, and am still getting the nginx' `50x` status code from your server.
If there is a way to donate some backup servers for help, please let us know.
