### ISSUE TITLE
option to block seeking within a block

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#67]
Blocking works correctly when playback reaches the start of a block to jump to the end but if already inside the block it just plays. May be nice to have an option to autoskip outside that area again. For example if clicking on the timeline puts you inside the block, autojump to a point outside it. 

  It may be beneficial to consider seeking to a moment shortly before the block so it will then have autoskip kick in. It would seem like a nuisance glitch for a short moment if not a clean transition but would even make left arrow reversing through a video supported instead of reaching a point the keyboard cannot rewind before.

  If implemented, this may impact the 'go back' feature of the popup mentioning it skipped a section that offers to watch the skipped portion so the content block would need to be temporarily disabled when this happens.

**Comment by ajayyy** [comment]
Yep, this doesn't exist now because of the go back feature.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/124
