### ISSUE TITLE
Server Issues

### ISSUE THREAD

**Issue by Deerath** [ajayyy/SponsorBlock#671]
Just received this error and a bunch of code. The code is withheld unless the author wishes me to post it. 
I was trying to submit a sponsor segment in a video, although I have been getting a lot of server issues with voting lately too. 

```

The server seems to be overloaded. Try again in a few seconds. Error Code: 502

Check status.sponsor.ajay.app for server status.

```

**Comment by Deerath** [comment]
I will also add that I just got this error. Again, code withheld unless author wants me to post it.


`
A connection error has occured. Error code: 524
`

**Comment by ajayyy** [comment]
http://status.sponsor.ajay.app/
