### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by evans-ebenezer** [ajayyy/SponsorBlock#673]
Can We get an option to skip silence in a specific video (like in NewPipe App)

**Comment by whyiswhen** [comment]
hmm... good idea brother .  sponsorblock has already became useless segment block extension. it will be a very good if skip silence feature added .

**Comment by ajayyy** [comment]
https://github.com/vantezzen/skip-silence

**Comment by whyiswhen** [comment]
hmm.... this extension don't skip silence like newpipe it can just increase the speed of the silence.

> https://github.com/vantezzen/skip-silence
