### ISSUE TITLE
[No valid userID field(s) provided] Error

### ISSUE THREAD

**Issue by someonenameguy** [ajayyy/SponsorBlock#674]
Everytime I try to submit a segment it just show this error.
I have change the username in sponsorblock but this error continues to persist.

"Server said this request was invalid Error Code: 400
Check status.sponsor.ajay.app for server status.
No valid userID field(s) provided"

![image](https://user-images.githubusercontent.com/54163580/110758750-d45d1d00-8287-11eb-8b78-283d06144330.png)

![image](https://user-images.githubusercontent.com/54163580/110758854-f22a8200-8287-11eb-8251-e1a37de3e6b9.png)

**Comment by whyiswhen** [comment]
server maybe down.
check server status here.
https://status.sponsor.ajay.app/

**Comment by MRuy** [comment]
Go to the options page and check if there is a userID set.  
(Dont share it)

**Comment by someonenameguy** [comment]
Hmm the UserID was set, but I press the set button again and seems to work now.
