### ISSUE TITLE
Feature: Segment type for marking a part of the video as clear/deleting other segments.

### ISSUE THREAD

**Issue by laundmo** [ajayyy/SponsorBlock#675]
Motivation:
sometimes a segment will skip over an important part of the video, which often happens with very long videos and the intermission segment. I believe this is because whoever first created the segment skipped ahead without watching everything.

Proposal:
Add a type of segment that's meant to delete that specific range in the other segment.
name ideas:
- "remove others"
- "delete here"
- "main content"

Example:
- intermission from 00:30: to 01:00:
- there is an important part at 00:45 to 00:47
- someone adds a "remove others" or "delete here" segment for that range
- now the intermission segment is split into 2 segments, 00:30 - 00:45 and 00:47 - 01:00

**Comment by whyiswhen** [comment]
Any video example?

**Comment by laundmo** [comment]
@whyiswhen 

https://www.youtube.com/watch?v=U4sWbTfrzj8 at around 1:03:00 there is a short (few minute) part that was falsely marked as intermission when i saw it. I dont know whether its fixed now, but yesterday around the time i openend the issue it was the case. Im on a device without the extension right now so i cant check.

**Comment by ajayyy** [comment]
I don't think this makes sense for this system. Instead, downvote that incorrect segment and submit two correct ones.

**Comment by laundmo** [comment]
@ajayyy that would be 2 unintuitive steps for the goal of "mark this part as correct" where a single very intuitive one could be used.

**Comment by ajayyy** [comment]
Marking non-segments would be very hard to moderate and complicate it too much I feel
