### ISSUE TITLE
Feature: Offtopic Category

### ISSUE THREAD

**Issue by LordThelia** [ajayyy/SponsorBlock#677]
It would be nice to have an additional category to appropriately categorize segments that are not related to the actual topic of the video so that they are skipped.

I've seen a lot of videos where the title was a question, a recipe, etc. and the first few minutes of the video people are driving through a drive-through, telling half their life story or why the rainbow they saw yesterday while walking the dog changed their life.

I don't want to mark the corresponding parts as "Intermission/Intro Animation", because some people might like to hear that and it has some content just not related to the the title.

**Comment by MRuy** [comment]
> [25. Sep 2020 11:14] LTcars: There was an offtopic category before, but it was scrapped for being to subjective  

[Discord message link](https://discord.com/channels/603643120093233162/603643205552177155/758979840157155338)

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/409
