### ISSUE TITLE
Is there a plan for accounts and a reputation system?

### ISSUE THREAD

**Issue by Alistair1231** [ajayyy/SponsorBlock#681]
Hey I love the addon, 
I am in awe of the ratio between active participators in adding segments and just passive users pointed out on your [stats page](https://sponsor.ajay.app/stats/).
I also started contributing and while I like the ease of use, as a developer myself I see a lot of potential for abuse. 
Also, I don't want to lose my personal stats when using e.g. different browsers or systems.
I would like to see an **login with google option for the synchronization of the user stats**, as well as, if needed, a **requirement to log in**, in order to submit segments.

Thanks for your hard work and especially for supporting FOS software! :)

**Comment by MRuy** [comment]
SponsorBlock is using a privat userID that you can save, for example in a password manager, and use in multiple browsers.  
With it its also possible to see the time you saved others in the extension.  
The private stats with your saved time is currently not synced to my knowledge.

**Comment by ajayyy** [comment]
Data is synced automatically with the browser's syncing service if you are signed into your browser.
