### ISSUE TITLE
Add category for "likely to cause a seizure"?

### ISSUE THREAD

**Issue by zsarge** [ajayyy/SponsorBlock#682]
**Proposed enhancement:** Add a category in the options menu that would enable skipping content likely to trigger seizures. 

**Benefits of this enhancement:** Given this extension already skips unwanted content, it would be reasonable to support flagging portions of video likely to trigger those with photosensitive epilepsy. This type of feature would be unobtrusive to average users, but potentially life-saving for others.

**Drawbacks to this enhancement:** Given this is not directly related to skipping sponsors, this feature could be a precedent for other non-sponsor related features, eventually contributing to bloat in the app. 

Just an idea, but I think it could be helpful to some.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/403

**Comment by rjoken** [comment]
Please add this I keep finding accidental flashing image sections in peoples' videos and wishing I could sponsorblock them. It would be so helpful.
