### ISSUE TITLE
duplicate segments show up in the popup after submitting

### ISSUE THREAD

**Issue by caneleex** [ajayyy/SponsorBlock#685]
sometimes, after submitting, the segments in the popup are duplicated resulting in this:

![](https://i.imgur.com/Sno0j1x.png)

however, i don't have the exact repro steps, but i'll try to get them asap

**Comment by whyiswhen** [comment]
that just happen for sometime . just refresh after submitting and problem is solved. i think it is not even a problem at all. who is getting by that duplication in popup.

**Comment by lord-blex** [comment]
I have a very similar issue, but I'm not 100% sure if it's exactly the same.

Steps to reproduce:

1. Submit a segment
2. Submit another segment

The first segment you submitted will now be duplicated. Segments already submitted by others won't be and neither will the one made in step 2. Refreshing makes the dupes go away.
![kép](https://user-images.githubusercontent.com/9072794/143662857-809f61bd-ea84-44f9-9b47-8a889ae42347.png)
On this screenshot: 1 was there when I opened the video, then I submitted the others one by one and each duplicated the last one.

**Comment by mchangrh** [comment]
I seem to have gotten repro steps down pretty well

Duplicate Segments
1. Info panel never opened
2. Submitted a segment without opening info panel
3. Open info panel

If the info panel is opened and then closed before submitting, the segments will appear de-duplicated and at the correct times.

Missing Segments
1. Keep Info panel open during submission
2. Submit a segment
3. Segment will not appear in the into popup

**Comment by mchangrh** [comment]
this seems to have been resolved after refresh on submit
