### ISSUE TITLE
Consider assuming segments are sequential when gap is small

### ISSUE THREAD

**Issue by Jonta** [ajayyy/SponsorBlock#688]
Example: [Dream - Minecraft Speedrunner VS 4 Hunters GRAND FINALE - 39min - 32M views - premiered 5th Feb](https://www.youtube.com/watch?v=a8ds6SnOGow) (Edit: Spoilers for previous videos at the beginning. Proceed with caution)

Segments at the beginning:

| Segment      |       T |
|:-------------|--------:|
| Intermission |    0-25 |
| Interaction  |   25-35 |
| Unpaid       |   25-35 |
| Sponsor      | 35-1:15 |

Dual skips in popular videos seem inevitable, so a fix to Unskip seems in order

**Comment by ajayyy** [comment]
It works fine when segments are overlapping or start and end at the same time. In this case, the segments have a slight gap between them

**Comment by mirror176** [comment]
Having a visual cue that current time is within a bound would help too; tracking dot on timeline with detail is much harder than for example having submission controls and/or window colored/titled to represent the segment(s) that are currently in that timeframe.
