### ISSUE TITLE
How to report an incorrect segment that doesn't match solutions?

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#689]
I was looking at https://youtu.be/67350MLGXXQ?t=187 where the entry was marked as a promotion, though I would have considered it more of like citing a source (+ a thank you to that person for their research). Agree or not about if it should be a 'promotion' type of marking, it still brings up the question of how to mark a skip as bad when there should be no skip present in an area based on current criteria to mark, such as if I hit submit when I had a bogus entry in the mix (maybe picked up by gui absorbing my keyboard controls when I was trying to control playback/navigation of normal content sections and it got marked inadvertently.
  On a similar but separate note I was browsing through options of how to report when I went to see what options were presented if I marked as wrong time and it removed the entry from my timeline completely without option of correcting the time

**Comment by ajayyy** [comment]
You'd select the "Incorrect/Wrong timing" option. This is for segments that are "Incorrect" or for segments that have the "wrong timing"
