### ISSUE TITLE
Sponsorship popup doesn't refresh details for next video

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#69]
Clicked on the next video at the end of watching one from a thumbnail within the video player window while the popup was open on the right and the popup does not refresh even though skips perform from the new video's rulesets. Closing+reopening the popup does refresh it. Issue was also present on video list to the right and autoplay.

**Comment by ajayyy** [comment]
I didn't think about the fact that people would open the popup while changing videos (since the popup was originally just the default one). I'll make it auto hide when a video change occurs.

**Comment by ajayyy** [comment]
Closing and reopening doesn't fix it?
