### ISSUE TITLE
SponsorBlock website, API is down, no segments being blocked

### ISSUE THREAD

**Issue by hjc25** [ajayyy/SponsorBlock#691]
![image](https://user-images.githubusercontent.com/28969068/111891507-7afba780-8a58-11eb-980c-56fde317c208.png)

![image](https://user-images.githubusercontent.com/28969068/111891519-8949c380-8a58-11eb-95f9-66392b9c6542.png)

![image](https://user-images.githubusercontent.com/28969068/111891555-e9406a00-8a58-11eb-879d-f10fea613dd3.png)

**Comment by MeztliRA** [comment]
its happenning to me too but i can go to the website, is it still down?

**Comment by hjc25** [comment]
> 
> 
> its happenning to me too but i can go to the website, is it still down?

Looks like he might have just restarted the server. Cloudflare provides a cached version of the site for when the webserver goes down.

**Comment by hjc25** [comment]
Yup, it's back up, cheers Ajay.

![image](https://user-images.githubusercontent.com/28969068/111891845-e181c500-8a5a-11eb-9f9a-f3c68b5a72d8.png)

**Comment by hjc25** [comment]
![image](https://user-images.githubusercontent.com/28969068/111891891-40473e80-8a5b-11eb-8f40-08b55fc43069.png)

Nah, there still seems to be problems with submitting new segements to the database. Will reopen the issue.

502 Bad Gateway.

**Comment by ajayyy** [comment]
https://twitter.com/SponsorBlock/status/1373361688733483008
