### ISSUE TITLE
Intermission/Intro Animation clarification

### ISSUE THREAD

**Issue by skatcat743** [ajayyy/SponsorBlock#693]
It is defined as "An interval without actual content. Could be a pause, static frame, repeating animation. This should not be used for transitions containing information." Is it acceptable to skip redundant explanation that is in every video from a channel? An example would be the channel "Coin Bureau". The format they use is like an abstract of the topic to animation to the constant period where they say along the lines of "like and subscribe, this is not financial advice, use the video timestamps if you wish" so would a cut starting at [here](https://youtu.be/I2D-fvxPkuY?t=45) and ending at 1 minute 53 be reasonable? Should this be a new category?

**Comment by ajayyy** [comment]
No
