### ISSUE TITLE
Force Channel Check is Stopping SponsorBlock from Skipping Ads

### ISSUE THREAD

**Issue by leganrac** [ajayyy/SponsorBlock#698]
Sorry for the really long and weirdly capitalized title.
When "forceChannelCheck": true, the addon will be unable to actually skip the sponsors, and will instead continue the video. 
See also: [This Reddit post describing the issue](https://www.reddit.com/r/SponsorBlock/comments/m5htpb/firefox_windows_sponsorblock_not_autoskipping_no/)

**Comment by ajayyy** [comment]
See https://github.com/ajayyy/SponsorBlock/issues/635 https://github.com/ajayyy/SponsorBlock/issues/611

A warning should be added if the channel request fails after X seconds.
