### ISSUE TITLE
[Feature request] Option that disable the time saved count in incognito mode

### ISSUE THREAD

**Issue by MRuy** [ajayyy/SponsorBlock#703]
It would be nice to have a option that dont count time saved in incognito for moderation reasons

**Comment by whyiswhen** [comment]
hmm.. I think you should not allow sponsorblock in incognito mode ( option in chrome).

**Comment by MRuy** [comment]
I allow SB to run in incognito mode to moderate submissions without F up my YouTube history/recommendations

**Comment by whyiswhen** [comment]
> I allow SB to run in incognito mode to moderate submissions without F up my YouTube history/recommendations

hence not for privacy resons?

**Comment by wilkmaciej** [comment]
Pretty easy to add. There is
```typescript
chrome.extension.inIncognitoContext
```
