### ISSUE TITLE
Swagger API docs

### ISSUE THREAD

**Issue by Forcebyte** [ajayyy/SponsorBlock#706]
I've been playing with the UI docs here (https://github.com/ajayyy/SponsorBlock/wiki/API-Docs) and have found them super cool to see if a video has been tagged or not with skip segments, its also nice to have overlays into the amount of time that a youtuber dedicates to an ad on a video

It may get better traction if this had a swagger autogenerated page maybe? (https://swagger.io/) under where you normally host the site? (https://ajay.app/)

More of a suggestion than anything, either way this app is freaking amazing! Awesome work!

**Comment by mchangrh** [comment]
I currently maintain a postman collection that is almost-portable to OpenAPI, I can convert it and try to integrate Swagger with our current MediaWiki install

**Comment by mchangrh** [comment]
Swagger API documentation is complete https://github.com/mchangrh/sb-openapi
