### ISSUE TITLE
Extension doesn't work when video plays in miniplayer mode

### ISSUE THREAD

**Issue by devanshuDesai** [ajayyy/SponsorBlock#707]
To test this, you can start watching any video and press `i` before a sponsor segment.

**Comment by wilkmaciej** [comment]
SponsorBlock gets video ID required to retrieve segments from URL which doesn't contain video ID in miniplayer mode. Probably the only way to get video ID would be to monitor network requests.

**Comment by mchangrh** [comment]
Miniplayer works and was added in one of my PRs - probably added in #1425
