### ISSUE TITLE
Feature: Wait x seconds before skipping sponsor.

### ISSUE THREAD

**Issue by tcmal** [ajayyy/SponsorBlock#709]
I generally prefer to know who sponsored a video, even if I don't want to listen to the whole spiel. It would be nice to be able to be able to auto-skip segments after playing the first few seconds (or just not skip at all if the segment is smaller than the value).

**Comment by dev-osiris** [comment]
Sounds good

**Comment by ajayyy** [comment]
![image](https://user-images.githubusercontent.com/12688112/114318967-546fe000-9add-11eb-8019-746b98b19fb7.png)

This option exists

**Comment by RDKRACZ** [comment]
This only applies to the second part of the "issue".
