### ISSUE TITLE
Addition of new "filler" category

### ISSUE THREAD

**Issue by koczadly** [ajayyy/SponsorBlock#710]
I'm sure this must've been suggested before, but I couldn't find any existing issues relating to it — apologies if it's been mentioned or recently implemented.

A separate category for "filler" content, which could include:
- Video previews (already mentioned in #444)
- Disclaimers (eg. "don't try this at home", "heres why this vid constitutes fair use", yada yada...)
- Introductions and intermissions which *do* have content or provide additional context to the video, but the user may wish to skip (ie. "in this vid, we'll explain how to...", and talking sections between top-10 style videos)

Default behaviour could just be to offer manual skipping and let the user decide.

**Comment by MRuy** [comment]
Warnings/Disclaimers like "don't try this at home" will not be accepted in any category for obvious reasons.

**Comment by ajayyy** [comment]
Better suited as https://github.com/ajayyy/SponsorBlock/issues/409
