### ISSUE TITLE
Cannot create <1 second long submission sometimes

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#713]
Get Invalid error code: 400 saying sponsor must be longer than 1 second when trying to submit submit https://youtu.be/TWAx9kGtiUY?t=328 with marking from 5:28.222 to 5:28.889 (just a few frames) as a sponsor; it looks like it was really an editing mistake or corrupt data stream (room for new categories?) but what flashes through just looks like an ad. Worked when I added an interaction reminder that was <1 second near https://youtu.be/4mJyDM7u02U?t=14 though it numerically crossed from one second to the next but did total <1s if I recall. My minimum time is set to 0 in settings. Are sponsors just a protected group of submissions or am I finding a different issue? Though not sure how close to 1 second I've seen, I know I have found plenty of short sponsor spots in videos (<5 seconds for sure) and can try to find some for further testing if needed.

**Comment by ajayyy** [comment]
The restriction only applies to the sponsor category
