### ISSUE TITLE
Feature request: New segment type: "Padding"

### ISSUE THREAD

**Issue by yoshi314** [ajayyy/SponsorBlock#716]
There are videos with actual content comprising less than 20% of the entire video. Tangents, rambling, off-topic banter padding the video. Attempts to get the viewer hooked to watch the whole thing, lengthy introductions, while you are just want them to get to the point.

Being able to mark those segments as separate type with dedicated skip feature would be helpful for some people who just want the gist of things. Especially if you are re-watching a video and don't want to go through the entire thing again. Just the bullet points.

**Comment by ajayyy** [comment]
Too general
