### ISSUE TITLE
Error: No valid UserID field(s) provided. 

### ISSUE THREAD

**Issue by ksixen** [ajayyy/SponsorBlock#717]
I want to upload sponsor segment. but i getting this error. What this meaning? I tried reinstall the SposorBlock, but it's doesn't work

Lightshot prntscrn: https://prnt.sc/11il59f
translation: 
The server rejected this request Error code: 400
See the server status at status. sponsor.ajay.app.

**Comment by MRuy** [comment]
Check out the options page if there is a userID, if not, generate a new one

**Comment by ksixen** [comment]
I had. Btw he's creating new one every time after reloading browser

![изображение](https://user-images.githubusercontent.com/38946653/115082140-1fbcb800-9f25-11eb-9e7c-dfcf0bbdd029.png)

**Comment by MRuy** [comment]
Thats your username, on the options page here:

![sponsorblock-userid](https://user-images.githubusercontent.com/1896243/115084878-c4310100-9f09-11eb-9f01-83fd14931400.jpg)
