### ISSUE TITLE
Un-skipping overlapping segements skips to end of larger segement

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlock#719]
similar to #686, after skipping past both (multiple segments skipped) unskipping either segment will skip to the end of the larger segment instead of the beginning of the smaller or larger segments.

**Comment by ajayyy** [comment]
This doesn't occur when they actually overlap

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/688
