### ISSUE TITLE
New category suggestion: Blocked content (e.g. for copyright reasons)

### ISSUE THREAD

**Issue by r0uv3n** [ajayyy/SponsorBlock#720]
I was watching a German news program ([tagesschau](https://www.youtube.com/watch?v=vEw9FLL6V4g)), which often includes audio-only sports segments for which they don't have the rights to show the Video on YouTube. These segments are already skipped, as people often add them as category "Sponsor". This doesn't seem to fit. 

This category could also be used for segments of twitch streams with muted audio (due to copyrighted music playing at the time).

**Comment by ajayyy** [comment]
Maybe intermission can work?

**Comment by r0uv3n** [comment]
Oftentimes only part of the content is blocked (such as audio for twitch streams or the video in the case of my example), but there is still information contained in these parts. Intermission with the current description does not seem the right fit.

Apart from this I got a question: Is there a general reason why you seem to prefer less categories (when those categories can be cleanly seperated)? The ability to designate different behavior (such as autoskipping) for different categories is great and could be awesome, but when one can't predict what a certain category might include, one becomes hesitant to enable autoskipping. But I get that the problem of categorizing the kinds of interruption is not a clean and cut job and the current system might be good enough to do the job.
