### ISSUE TITLE
Proposal: Switch licenses for SponsorBlock from GPL-3.0 to LGPL-3.0

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#721]
https://www.gnu.org/licenses/lgpl-3.0.txt

### Reasoning

Due to mandatory DRM/SDK (?) and other issues, GPL software probably can't be distributed on the Apple App Store. This is required to be able to publish a Safari extension. 

See https://apple.stackexchange.com/questions/6109/is-it-possible-to-have-gpl-software-in-the-mac-app-store

The LGPL-3.0 license will allow SponsorBlock to remain copy-left, while still being able to be distributed on the Apple App Store.

https://stackoverflow.com/questions/35068054/does-app-store-accept-qt-app-linked-with-qt-library-lgplv3/39438539#39438539

> 0) Convey the Minimal Corresponding Source under the terms of this
>       License, and the Corresponding Application Code in a form
>       suitable for, and under terms that permit, the user to
>       recombine or relink the Application with a modified version of
>       the Linked Version to produce a modified Combined Work, in the
>       manner specified by section 6 of the GNU GPL for conveying
>       Corresponding Source.

### Acceptance

- [x] @ajayyy
- [x] @NDevTK
- [x] @FoseFx
- [x] @mbledkowski
- [x] @Joe-Dowd
- [x] @MRuy
- [x] @opl-
- [x] @Lartza
- [x] @jplsek
- [x] @rafern
- [x] @afrmtbl 

### Response

**This thread is not for discussion.** Please discuss in [Discord](https://discord.gg/sponsorblock) or [Matrix](https://matrix.to/#/!DmnDlUxdKzYtVfHTin:blob.cat?via=blob.cat&via=matrix.org&via=ajay.app) in the #development channel.

Please add a comment similar to the following:

> I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=USERNAME-GOES-HERE) under LGPL-3.0

**Comment by MRuy** [comment]
I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=mruy) under LGPL-3.0

**Comment by jplsek** [comment]
I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=jplsek) under LGPL-3.0

**Comment by rafern** [comment]
I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=rafern) under LGPL-3.0

**Comment by NDevTK** [comment]
I license all of my past "SponsorBlock" contributions (https://github.com/ajayyy/SponsorBlock/commits?author=NDevTK) under LGPL-3.0
I license all of my past "YTSponsorSkip" contributions (https://github.com/NDevTK/YTSponsorSkip/commits?author=NDevTK) under LGPL-3.0

**Comment by Lartza** [comment]
I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=Lartza) under LGPL-3.0

**Comment by FoseFx** [comment]
I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=FoseFx) under LGPL-3.0

**Comment by mbledkowski** [comment]
I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=mbledkowski) under LGPL-3.0

**Comment by Joe-Dowd** [comment]
I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=Joe-Dowd) under LGPL-3.0

**Comment by opl-** [comment]
I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=opl) under LGPL-3.0

**Comment by afrmtbl** [comment]
I license all of my past contributions (https://github.com/ajayyy/SponsorBlock/commits?author=afrmtbl) under LGPL-3.0

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/commit/919b72a5900d5263e914169b64f178ea18950307
