### ISSUE TITLE
Option to edit already submitted segments.

### ISSUE THREAD

**Issue by AriesvMars** [ajayyy/SponsorBlock#722]
It would be good to have an option to edit submitted segments of your own and even other people. Some segments have weird timed cuts and late skips and I usually try to fix the issues when I come across them, but it can only be done if I were to make segments on top of those segments, and some segments cut into actual content and it is impossible to correct them. Personally I do not mind about the leader board or anything like that so, imo, if I just edit someone's else's segment to adjust it well, I do not mind not receiving the leader board score from it. I just wish the option to edit was there so I can adjust it to be more seamless and perfect. (also it would really help my OCD lol)

Also if people make segments on top of segments like I do except motivated to abuse the leader board system, It would help to make it impossible to make segments on top of segments and instead giving an option to adjust them.

**Comment by chirag127** [comment]
just submit the right segment.

**Comment by AriesvMars** [comment]
> 
> 
> just submit the right segment instead of editing.

I can't edit even If I wanted to, that's the issue. Some people do not submit correct segments or time the segments correctly, I can't telepathically transcend space and time to get inside their heads to make them "just submit the right segment", which is why I thought a editing tool would be helpful. Unless, if you are saying that submitting a segment on top of already submitted one will delete the previously submitted segment, idk how that is any help tbh.

**Comment by chirag127** [comment]
Yes , submitting a segment on top of already submitted one will delete the
previously submitted segment, If your segment get more votes.

**Comment by AriesvMars** [comment]
> 
> Yes , submitting a segment on top of already submitted one will delete the previously submitted segment, If your segment get more votes.
Hm, Wasn't aware of that. Still an editing tool would be mighty helpful. But I guess it doesn't need as much priority as I thought. Thank you.

**Comment by MRuy** [comment]
> Yes , submitting a segment on top of already submitted one will delete the previously submitted segment, If your segment get more votes.

Thats not correct, the system will pick one of the overlaping segments with the same category at random + the segment with more votes will have a greater chance of getting picked.  

Segments that get voted to `-2`, all segments start with `0`, will get removed.

**Comment by AriesvMars** [comment]
>
> Thats not correct, the system will pick one of the overlaping segments with the same category at random + the segment with more votes will have a greater chance of getting picked.
> 
> Segments that get voted to `-2`, all segments start with `0`, will get removed.

Alright that makes sense, still is a editing tool on the roadmap or do you guys plan to continue with the vote system. (Just asking so I can either close the issue or keep it open)

**Comment by AriesvMars** [comment]
Issue closed as an alternative solution has already been implemented.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/370
