### ISSUE TITLE
Support for submitting segments on Sponsorblock mobile website

### ISSUE THREAD

**Issue by SameenAhnaf** [ajayyy/SponsorBlock#723]
Hi, thank you for your amazing contribution.

Could you please let user contribute segments on SponsorBlock website? I use Newpipe Sponsorblock. It has no ability to submit segments for unknown reasons. Plus, YouTube Vanced is too heavy app for me for a single purpose. It would have been nice to contribute on SponsorBlock mobile website.

Let the user type the URL on a title bar. Video will start playing (just like main player on YouTube and other websites). YouTube Vanced options seem to be a little clunky for me. I have already included a detailed suggession here: https://github.com/polymorphicshade/NewPipe/issues/57

**Comment by SameenAhnaf** [comment]
Long press on 'Contribute' button should let the user manage segments and manually input any new segment. Segments should get automatically in a chronological order after including them. Overlapping of segments (0:09-8:54 and 0:09-6:57 can't be separate segments) should warn the user to choose between a segment.

All segments should play one after another before submission. Unlike YouTube player (on other websites), there should be an option to change playback speed from 0.5x to 2x.

**Comment by ajayyy** [comment]
I had this at one point in the mobile extension but removed it due to it being hard to create precise segments on mobile.
