### ISSUE TITLE
Replace description and comment session by "show" button to hide annoying sponsored texts and links.

### ISSUE THREAD

**Issue by gut1414** [ajayyy/SponsorBlock#724]
I'm amazed that no one thought of trying to block sponsored texts and links in descriptions and comments. A real pollution like the classic advertising banners. Maybe I haven't looked through the suggestions enough. Sorry in that case.

If sponsorblock becomes popular, youtubers may put many more sponsors directly visible in the description and a pinned comment to bypass blocking by users who have chosen not to be polluted by advertising.

The idea, as I know it's extremely difficult to sort sponsored descriptions and comments versus other descriptions and comments that are not sponsored, would be to hide the description and the comments session with a button (show description , show comments).

When I'm on YouTube in mobile version, I have the pleasant surprise to see only the video player and the suggested videos, then only buttons to see the description and another button to see the comments. Just click on it to expand the description or comments. In addition, YouTube is easier to load in terms of resource consumption (RAM, CPU)

On the computer, unfortunately, everything is visible by default, with the unpleasant feeling of disgust at seeing sponsored texts and links with the description and comment visible by default.

Another idea would be to create a blacklist of channels where everything is blocked by default (local blacklist or on server like sponsored segments reported by the community), and on the contrary, a whitelist (local or on server also) of channels respectful of users (sponsored section that does not start at the start of the video, sponsored links hidden at the bottom of the description, ...).

**Comment by MRuy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/649
