### ISSUE TITLE
Feature- disable popup 

### ISSUE THREAD

**Issue by etaui** [ajayyy/SponsorBlock#725]
Feature request: Disable the popup in the video or make it shorter (or an adjustable length). Right now it's kinda annoying to close and takes a long time to disappear. (Also could add a hotkey to close the popup)

**Comment by ajayyy** [comment]
Already possible

**Comment by etaui** [comment]
how?

**Comment by etaui** [comment]
I mean like disable the popup but still be able to skip using hotkeys?
