### ISSUE TITLE
Skip popup persists when switching between videos.

### ISSUE THREAD

**Issue by nathanielcwm** [ajayyy/SponsorBlock#726]
When switching between videos with a sponsorblock popup currently on the screen it persists, and can be used, even after the new video loads in.

SB: 2.0.13.1
FF: 88.0
Also repro on Edgium 90 (installed from Chrome web store).
Windows 10

**Comment by wilkmaciej** [comment]
@ajayyy we can probably add window locationchange event listener and close popup or just reload it.

**Comment by ajayyy** [comment]
@wilkmaciej The existing `videoIDChanged` function can be used. Popups are now tracked in a list, so it should be possible to close them now

**Comment by wilkmaciej** [comment]
Hmm I looked at the function and looks like there is
https://github.com/ajayyy/SponsorBlock/blob/257098fd96c96ea94ab73859418ab8277d832389/src/content.ts#L299-L300
which should close popup. I will find out why it's not being closed.

**Comment by ajayyy** [comment]
This is referring to the popup on the side (same as clicking the extension icon in the browser toolbar)

**Comment by wilkmaciej** [comment]
Oh. I thought we were talking about popup from extension icon which indeed doesn't close on video change. Not sure then which popup issue author had in mind.

**Comment by ajayyy** [comment]
I thought this was referring to the unskip/manual skip notices
