### ISSUE TITLE
Submissions not appearing in video.

### ISSUE THREAD

**Issue by DShip91** [ajayyy/SponsorBlock#729]
I downvoted and hid a sponsor segment with incorrect timing and submitted a segment with the correct timing. However, when I loaded the video a second time, the downvoted segment was back and the one that _I_ had submitted was nowhere to be found; which wouldn't be an issue if I wasn't prohibited from submitting the segment again. When I try, I get the following error:

> This has already been submitted before Error Code: 409
> Check status.sponsor.ajay.app for server status.
> Conflict

I just want the segments I submit to actually show up in a video.

**Comment by ajayyy** [comment]
Your segment is there, it probably just has less votes.
