### ISSUE TITLE
auto upvotes works wrong way

### ISSUE THREAD

**Issue by sulfur17** [ajayyy/SponsorBlock#731]
people are too lazy and stupid to downvote wrong segments. So if somebody report wrong segment it will be forever there, because it will be auto upvoted much more frequently then downvoted.

example here: https://youtu.be/KDSnWFB1iss
someone set sponsor segment at start of the video and now we always have to skip start of the song

Hope somebody will fix that somehow.

**Comment by ajayyy** [comment]
Auto upvote has been removed since a while ago

**Comment by sulfur17** [comment]
then would be good do fix "help" page
![image](https://user-images.githubusercontent.com/4643260/117319255-cbf21e80-ae93-11eb-81d5-cc3069758919.png)

and how to remove this wrong segment which somebody set on my song?
