### ISSUE TITLE
Segements that you've downvoted should be permanently hidden from you...

### ISSUE THREAD

**Issue by DShip91** [ajayyy/SponsorBlock#733]
...unless brought back using the popup menu.

**Comment by wilkmaciej** [comment]
Can you explain? They should be hidden for whom? Only the person which down voted it or everyone? The vote system is responsible for determining if segment is good or not.

**Comment by DShip91** [comment]
> 
> 
> Can you explain? They should be hidden for whom? Only the person which down voted it or everyone? The vote system is responsible for determining if segment is good or not.

Only the person who downvoted it, obviously.

**Comment by wilkmaciej** [comment]
For @ajayyy to decide.

**Comment by mchangrh** [comment]
implemented in https://github.com/ajayyy/SponsorBlock/commit/4d60dec7f997bb076bfe7dc9d2b7079b96df3e95
