### ISSUE TITLE
Applying segment to multiple videos

### ISSUE THREAD

**Issue by avt613** [ajayyy/SponsorBlock#735]
In some channels most of the videos start or end with the same animation. It would be very useful to be able to submit a segment for multiple videos at once by sending the time from beginning/ end of videos. 
For example in many of [TLMaths](https://www.youtube.com/channel/UCCgGyPD6MYQcHuMIc-Kv-Uw/playlists)'s videos there is a 4 second animation at the beginning and end of each video. (Not all of his videos contain this)

Also some channels have an intro animation which is played part-way through the video. I'm not sure if this is practical, but it would be quite cool if I could submit an animation segment from one video and then a computer searches through other videos on the same channel for that same animation.
For example submitting the intro animation on one of [LTT](https://www.youtube.com/c/LinusTechTips)'s videos would search for the same intro on other [LTT](https://www.youtube.com/c/LinusTechTips) and apply the same category.

**Comment by ajayyy** [comment]
Too easy to make mistakes
