### ISSUE TITLE
Add 'Link Interaction" category

### ISSUE THREAD

**Issue by SameenAhnaf** [ajayyy/SponsorBlock#736]
Some of my subscriptions suggest solely related links and SponsorBlock recommends not to include them in "Sponsor" category

However, in many cases, such segments are simply unnecessary. For example, I regularly watch reviews of Samsung products. Now, it's unnecessary for me to know how to access Samsung e-commerce website. Description is always there for any time access.

It might be required for other users. A separate category could immensely help us.

**Comment by ajayyy** [comment]
Too subjective

**Comment by SameenAhnaf** [comment]
@ajayyy Yes, this is not always necessary. But I am sure many users like me need it.

1. Description readers: Many users read description or check i button before watching the video.
2. Subscribers: Most videos (especially, educational) suggest a lot of related videos for full understanding.
3. Users with low-bandwidth: Users with low data packs simply have no ability to check every single suggestions.
4. Users with specific requirements: Suppose, I want to revise all my playlists one week before my exams. Or, suppose, I wish to watch videos which have irregular sequels. I really don't need to hear those things again.
5. Opinion receivers: This is especially for users who want up-to-date information about any product or anything.
