### ISSUE TITLE
YouTube video info request fails with 404

### ISSUE THREAD

**Issue by s-crypt** [ajayyy/SponsorBlock#741]
Ever since #738 , I am getting this prompt on every video and tab that has youtube open despite the permission being granted. The popup happens around 3 seconds after the video has started playing.
EDIT: Or any site with a youtube embed.

![image](https://user-images.githubusercontent.com/41712656/117923106-5974aa80-b2a8-11eb-8a26-149c1594ecc8.png)
![image](https://user-images.githubusercontent.com/41712656/117923127-609bb880-b2a8-11eb-92c0-58f74587ce41.png)

**Comment by ajayyy** [comment]
Could you go to about:debugging and inspect the add-on? Check for errors in the console related to requests to YouTube and sent them here.

I guess the add-on should give up if it knows the permission request succeeded and not prompt for them to do it again, but it would be good to see what's causing the video info to continue to fail to load.

**Comment by s-crypt** [comment]
![image](https://user-images.githubusercontent.com/41712656/117926805-30efaf00-b2ae-11eb-8451-9eb677b6a7bc.png)

**Comment by ajayyy** [comment]
https://twitter.com/consoleSkunk/status/1391259464586579972?s=19

**Comment by ajayyy** [comment]
I pushed an update to not repeatedly ask and will convert this issue into tracking this new `404` request issue for YouTube video info.

**Comment by s-crypt** [comment]
For more info: I use a container for youtube/google sites as well as the person on the twitter thread you linked.

**Comment by ajayyy** [comment]
Someone else got this using only Facebook container

**Comment by ajayyy** [comment]
Someone else got this issue without a container add-on and it somehow fixed itself when the Google container add-on was installed.

**Comment by richardfuca** [comment]
I am also experiencing this, seems to be linked to Google account as it works when logged out or when retrying the request with no cookies, and the issue reoccurs when logging back in.

Switching to different Google account also seems to fix the problem.

**Comment by nicolasGEL** [comment]
i am having this issue on chrome, logged in with ublock origin as the only possible other problem
i disabled the option and the popup stopped showing up

**Comment by xenago** [comment]
I am experiencing this as well, using a Firefox container for YouTube. The workaround of disabling that option does prevent the popup from appearing.

**Comment by Pixstrad** [comment]
I am experiencing this issue on Edge, here is a screenshot of my console from the time I press F5 to refresh the page with the video and the error appearing:
![image](https://user-images.githubusercontent.com/11033561/118587072-ebc5f400-b769-11eb-95b3-57ef13ce1154.png)

**Comment by s-crypt** [comment]
> 
> 
> I pushed an update to not repeatedly ask (still has to be approved by Mozilla) and will convert this issue into tracking this new `404` request issue for YouTube video info.

It still sends a warning whenever a youtube video or embed is loaded. Would it be possible to have an experimental toggle to disable this warning in settings? I have had to disable the extension because the warnings heavily interfere with my ability to use youtube and sites that use youtube embeds.

**Comment by ajayyy** [comment]
@s-crypt it should tell you which setting you need to disable to get rid of the warning

**Comment by s-crypt** [comment]
I turned off the 'force channel check' option as the dialogue says and the extension seems to be functioning perfectly.

The segments load correctly even when 'force channel check' is on and the error occurs (as I can see through the faded background), so perhaps the error is an error?

**Comment by ajayyy** [comment]
@s-crypt it is failing to load the video info, so cannot know what channel the video is by. If you have the "'force channel check" option enabled, it has to assume that you are on a whitelisted channel when this occurs, so it would fail to skip anything. 

Disabling it will allow it to ignore the whitelist check and assume all videos are not whitelisted if it is unable to determine the channel.

**Comment by killeik** [comment]
![image](https://user-images.githubusercontent.com/69602482/118836224-598a3100-b8cc-11eb-80d2-bacd8c755c7d.png)
Firefox 88.0.1
I disabled all extensions except the sponsor block, the problem still persists.
Thought about the default "improved tracking protection" in firefox, but disabling that didn't help

**Comment by ajayyy** [comment]
It looks like YouTube has completely removed this API endpoint and does not use it in the player anymore either. I am going to push an update that will instead read the link from the channel icon below the video, however, this will be significantly slower.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/commit/ac6cd2cec16eaf5151ff3730d1d1fbd1fdf59726

**Comment by NicoTheCinderace** [comment]
On the topic of this issue, it's telling me "If you are unable to resolve this, then disable the setting 'Force Channel Check Before Skipping', as SponsorBlock is unable to retrieve the channel information for this video.", but I didn't even have this checked in the first place.

But I can't even check to see if I accidentally enabled it or not, because the options button does literally nothing. What should I do?

**Comment by fluffy-critter** [comment]
I've just started getting the annoying popup a couple hours ago, myself, and for me the settings page is also not loading. Oddly enough I'm getting this popup even on videos which have already received all of the segment information.

**Comment by ajayyy** [comment]
@NicoTheCinderace @fluffy-critter 

Could you open inspect element and look at the console on the options page? Send any errors in this issue instead -> https://github.com/ajayyy/SponsorBlock/issues/750

**Comment by ajayyy** [comment]
As for this issue, the update changing the method to get channel information is submitted to the stores.

**Comment by NicoTheCinderace** [comment]
> 
> 
> @NicoTheCinderace 
> 
> Could you open inspect element and look at the console on the options page? Send any errors in this issue instead -> #750

The issue was was thankfully resolved after a quick reinstall, and I'm not having issues again. Seems like "Force Channel Check" was enabled, and that was causing the issue.

All's good now, thanks!
