### ISSUE TITLE
Manual skip counting

### ISSUE THREAD

**Issue by wilkmaciej** [ajayyy/SponsorBlock#743]
I'm not sure if its intended but if user skips segments manually SponsorBlock doesn't count it.
If I'm not mistaken deleting `&& autoSkip` in line 1008 check should eliminate this problem and not couse any side effects.
https://github.com/ajayyy/SponsorBlock/blob/040339312458d84dcca07c47368fa82be7688c00/src/content.ts#L1007-L1030
Waiting for some feedback and if everything looks good I will open a PR.

**Comment by ajayyy** [comment]
I think it is like this since manual skip doesn't really count for the full skip time

**Comment by wilkmaciej** [comment]
Well u have a good point, but some time was skipped. I can dig into this and maybe change it, so it will calculate time by subtracting time of skip click from segment end but its up to you. For me, it would be nice to at least count skips even if time isn't 100% accurate

**Comment by ajayyy** [comment]
Yea, maybe we can still not send the `viewedVideoSponsorTime` request though and just locally track it.

**Comment by wilkmaciej** [comment]
I analyzed the code and function `skipToTime` is not called when skipping manually.
If I'm not mistaken if we want manual skipping to count we need to add code inside this function https://github.com/ajayyy/SponsorBlock/blob/040339312458d84dcca07c47368fa82be7688c00/src/content.ts#L1040-L1044
I'm not very familiar with SponsorBlock, so please correct me if I'm wrong.
I would also consider moving this part to a new function, something like `sendTelemetry` so it can be used for both skippign methods.
https://github.com/ajayyy/SponsorBlock/blob/040339312458d84dcca07c47368fa82be7688c00/src/content.ts#L1007-L1030
