### ISSUE TITLE
Skipping your own submissions increment the skip count for others

### ISSUE THREAD

**Issue by L1pE** [ajayyy/SponsorBlock#745]
After submitting a segment, if you skip that segment yourself after it will increment the counter for segments skipped by others by your submissions. This also affects the personal skip count to a lesser extent as at least it doesn't say it's by others' submissions, but perhaps it should, and then it should only count others' submissions and not your own. Maybe add an extra count purely for when you skip segments submitted by you.

**Comment by wilkmaciej** [comment]
I think it can be done by storing UUID's of submitted segments locally. @ajayyy if you think it would be nice to implement I can do that.

**Comment by ajayyy** [comment]
I think it makes sense to count it, since this will only happen after reloading, so it could be on another day when you are watching the video a second time.

**Comment by chirag127** [comment]
> it should only count others' submissions and not your own

Yes, I don't there is any problem in that. It should include the time saved on personal skip count.

**Comment by L1pE** [comment]
It's just that I expected the intention to be an accurate count of how much you've helped purely others, considering the wording (or at least that's how it's worked in the PT-BR localization, haven't checked how it's in English), and I personally would've preferred that, but if it's not the intention then fair enough.
