### ISSUE TITLE
No `beta` in CWS beta extension name nor in toolbar button tooltip

### ISSUE THREAD

**Issue by darkred** [ajayyy/SponsorBlock#748]
I've noticed that the stable and beta versions have the exact same name:
![2021-05-17_104256](https://user-images.githubusercontent.com/723651/118451187-a7047380-b6fd-11eb-9269-a8f67b943e1d.jpg)
i.e. they have the same name in CWS: [stable](https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/mnjggcdmjocbbbhaepdhchncahnbgone), [beta](https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/ajjollijmimolcncegpgkbilohbhjnhi)

And the toolbar button is the same for both versions:
![12345~](https://user-images.githubusercontent.com/723651/118451125-97852a80-b6fd-11eb-8b18-f0635a43c9dd.gif)

&nbsp;
My suggestion is to add `BETA` in the beta extension name *(just like TM/VM/Stylus/uBO beta, [see](https://user-images.githubusercontent.com/723651/118450965-699fe600-b6fd-11eb-9a4c-e062e8c69fb3.gif) )*
And also, add `beta` in the toolbar button tooltip.

Thank you for your awesome work.

PS. Here is how Violentmonkey implemented this: 
https://github.com/violentmonkey/violentmonkey/pull/1078 and https://github.com/violentmonkey/violentmonkey/commit/6c3dd9e703af9d6b54719c970b7b8712ab1ad35a

**Comment by ajayyy** [comment]
The "beta" is an old deprecated version, you should switch to the main version. Could you please tell me where you found the link to it?

**Comment by darkred** [comment]
I had bookmarked https://chrome.google.com/webstore/detail/beta-sponsorblock/ajjollijmimolcncegpgkbilohbhjnhi
which now redirects to https://chrome.google.com/webstore/detail/sponsorblock-for-youtube/ajjollijmimolcncegpgkbilohbhjnhi .

It had title: "BETA - SponsorBlock - Chrome Web Store"

**Comment by ajayyy** [comment]
Alright, please remove that bookmark

**Comment by darkred** [comment]
Ok, thank you for responding.

**Comment by ajayyy** [comment]
Beta's are now handled on discord because the chrome web store is too slow to distribute them.
