### ISSUE TITLE
Channel ID not loaded placeholder issue

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#753]
For comments if people experience this issue.

**Comment by Oppion44** [comment]
Same issue, uninstalled as my favorite channels can't be whitelisted anymore

**Comment by TheGreenkey** [comment]
I have the same issue. On some channels the alert appears, on others it just thinks the channel is already whitelisted which they never have been.

**Comment by ajayyy** [comment]
Please provide other add-ons you may have or anything else you think might affect how the channel image is drawn to the screen. The way it gets the channel url is reading the link on the channel's profile picture under the video.

**Comment by TheGreenkey** [comment]
After writing my comment here, I explained my issue [here](https://github.com/ajayyy/SponsorBlock/issues/766#issuecomment-851001385) in more detail. Hope that helps.

**Comment by RMoDOOM** [comment]
I have no addons which modify the channel ID icon at all, but this issue has been occuring since about yesterday. I can see the channel ID in both the profile picture link and the name link in the developer tools.

I disabled uBlock Origin just to make sure that wasn't somehow interfering but that didn't work either.

**Comment by nicolasGEL** [comment]
i am having this issue in a normal LinusTechTips youtube video on chrome, where whitelisting doesn't work, is there any specific info required?

**Comment by confusicus** [comment]
Same issue here on most recent build. all channels. Have tried it without any other addons and the issue still persists

**Comment by gdude2002** [comment]
I'm noting this issue in Firefox 89.0.1 with [Enhancer for YouTube](https://addons.mozilla.org/en-US/firefox/addon/enhancer-for-youtube/) enabled. I've had it for some time now, but didn't notice the request for comment in the alert pop-up.

[Example video](https://www.youtube.com/watch?v=3e-f8iK5QLs)
[Screenshot showing how videos look like for me](https://user-images.githubusercontent.com/204153/122622599-1bca2500-d091-11eb-8970-9cba26af060e.png)

Would any additional info be useful?

**Comment by ajayyy** [comment]
I got the old channel info thing working again. If you want to test it, it is available in the most recent beta https://github.com/ajayyy/SponsorBlock/releases/tag/2.1.0

**Comment by gdude2002** [comment]
Unfortunately, [that version doesn't work for me](https://user-images.githubusercontent.com/204153/122622883-0b667a00-d092-11eb-8781-cba37984e538.png).

**Comment by ajayyy** [comment]
@gdude2002 Darn, I'll probably have to add back the permission logic from here: https://github.com/ajayyy/SponsorBlock/commit/a5189014adb78a94b1e661de8d8f341e14809dad

**Comment by vitekc45c** [comment]
Got this error on Brave, other addons: uBlock origin, HTML5 Autoplay blocker.

**Comment by vetlehlu** [comment]
I got this error message today:
"Channel ID is not loaded yet. If you are using an embedded video, try using the YouTube homepage instead. This could also be caused by changes in the YouTube layout, if you think so, make a comment here:"

It was on  this video: https://www.youtube.com/watch?v=JnGXTk57rOU

Im using Chrome on desktop, chrome version 96.0.4664.45
Thanks

**Comment by vetlehlu** [comment]
> I got this error message today: "Channel ID is not loaded yet. If you are using an embedded video, try using the YouTube homepage instead. This could also be caused by changes in the YouTube layout, if you think so, make a comment here:"
> 
> It was on this video: https://www.youtube.com/watch?v=JnGXTk57rOU
> 
> Im using Chrome on desktop, chrome version 96.0.4664.45 I was not using embedded video, I clicked on the video through my YouTube "Subscriptions"-page. Thanks

Same issue on this video: 
https://www.youtube.com/watch?v=zPmqbtKwtgw

**Comment by bill-pairaktaridis** [comment]
Same. I started getting this error on Firefox about a month ago.

**Comment by will64gamer** [comment]
I can't whitelist any channels, and since the message says it could be due to layout changes, could it be because I always use YouTube at 90% zoom?

**Comment by ajayyy** [comment]
Probably not. Can you try right click -> save as and sending that HTML to me at dev @ ajay.app

**Comment by Ferm93** [comment]
I love the extensions, but i hate that i cant add channels to the whitelist. I use FIREFOX and Its been a problem for almost a year now. 

I know not a lot of people use Firefox but i would love a solution. I have tried everything besides reinstalling Firefox. Some times it "works" (no popup) but if i change tabs or open a video in another tab, I'm back to not having that channel whitelisted anymore. 

Again, love the extensions, thank you so much for everything, hope a solution can be found eventually. I will sent anything you ask me for (_hopefully, I'm a forgetful idiot_).

 Cheers, have a nice day

**Comment by MarcusForss** [comment]
I had the same experience as @will64gamer, I have Youtube at 80% zoom and the error popped, went back to 100%, reloaded the video and I could whitelist the channel. 

Firefox v. 98.0.2 
Sponsorblock v. 4.2.1

**Comment by Nicolas-GE** [comment]
i've had issues whitelisting videos for a moment and i'm finally making a comment about it here

i don't have special zoom or anything, only Return YouTube Dislike

SponsorBlock v. 4.4
Chrome 101.0.4951.67 (Official Build) (64-bit) (cohort: Stable) 
Windows 10 Version 21H2 (Build 19044.1706)

**Comment by Golden-Serpents** [comment]
not sure what's the issue here but no matter which video i click on or whatever i've tried, i can't get channels to whitelist as the channel ID isn't loading. i've left the pages for extended time periods and i've refreshed them. accessed them through history and through the channel's page as well as attempting to whitelist the channel on the channel page. channels not working so far (i'm unlikely to remember to come back and edit this if i find more tbh): spice8rack, frost prime

sponsorblock v4.4
Chrome Version 101.0.4951.67 (Official Build) (64-bit)
Windows 10 Version 21H2 (Build 19044.1706)

**Comment by a-plastic-bag** [comment]
> not sure what's the issue here but no matter which video i click on or whatever i've tried, i can't get channels to whitelist as the channel ID isn't loading. i've left the pages for extended time periods and i've refreshed them. accessed them through history and through the channel's page as well as attempting to whitelist the channel on the channel page. channels not working so far (i'm unlikely to remember to come back and edit this if i find more tbh): spice8rack, frost prime
> 
> sponsorblock v4.4 Chrome Version 101.0.4951.67 (Official Build) (64-bit) Windows 10 Version 21H2 (Build 19044.1706)

I have the same problem.

SponsorBlock v. 4.4
Version 101.0.4951.64 (Official Build) (arm64)
macOS 12.3.1 (21E258)

**Comment by ajayyy** [comment]
Pushed a change that should help in 4.4.2

**Comment by a-plastic-bag** [comment]
> Pushed a change that should help in 4.4.2

Updated to 4.4.2, same problem.

**Comment by ajayyy** [comment]
Can you try right click -> save as and sending that HTML to me at dev @ ajay.app

**Comment by Blazzycrafter** [comment]
![image](https://user-images.githubusercontent.com/39300111/169709802-fd4edb10-0208-4422-90b1-8b6ebfbf339a.png)
ahnd here a zip version
with htm.file and its folder...
[html.zip](https://github.com/ajayyy/SponsorBlock/files/8749997/html.zip)

saved in inconnito mode for no username leaking XD

**Comment by Tsoomer** [comment]
I'm having the same issue on 4.4.2

**Comment by taxedtomato** [comment]
I'm too having issues with this. I think the userid regex is missing a check for '/user/...'?

<img width="630" alt="yt-user" src="https://user-images.githubusercontent.com/74880509/170615580-886470b9-8da8-4b36-93f5-faaf921a016e.png">

maybe this is a new thing.

**Comment by ajayyy** [comment]
Added

**Comment by Synetech** [comment]
You can (currently) get the channel-ID in video pages from a meta tag (simplified with no error-handling):

`document.body.querySelector("meta[itemprop='channelId']")["content"];`

**Comment by ajayyy** [comment]
@Synetech YouTube is a single page app, this only appears for the first channel you visit directly from a URL, not from channels you navigate to

**Comment by Golden-Serpents** [comment]
still experiencing the same issue as perviouslt mentioned on 4.4.5

**Comment by ajayyy** [comment]
Ah, looks like I forgot that adding `/user/` wasn't in the latest release, I'll try to publish an update tomorrow

**Comment by DoTrONoL** [comment]
Still waiting the new update 😣😔

**Comment by reneroth** [comment]
Still getting the alert that tells me to write a comment here when trying to whitelist a channel, so I'll just do as the machine commands and write a comment here :)

**Comment by Blazzycrafter** [comment]
@ajayyy even in the beta version i have the error...
![image](https://user-images.githubusercontent.com/39300111/175837128-7f515458-319b-4fa9-96c1-00423e819de0.png)
![image](https://user-images.githubusercontent.com/39300111/175837132-bd2bc717-14d1-48a5-86bc-1693e97fcffb.png)
in video:
https://www.youtube.com/watch?v=EA3LiXvjdTE&ab_channel=DoktorWhatson

**Comment by ToothyDev** [comment]
Can't whitelist a channel when I try to, tells me the channel ID isn't loaded

**Comment by ToothyDev** [comment]
EDIT: For some reason it looks like other channels work, just this one doesnt https://www.youtube.com/Corrupted (just open any video and try to whitelist the channel, not working

**Comment by JustAnon** [comment]
[This](https://chrome.google.com/webstore/detail/ycs-youtube-comment-searc/pmfhcilikeembgbiadjiojgfgcfbcoaa) addon seems to be the problem for me. I would appreciate if you could make whitelisting work with it.
Thanks

**Comment by ToothyDev** [comment]
I don't know why this is closed, this is still an issue

**Comment by JackingIntoOnline666** [comment]
the problem persists if youre also using youtube enhancer on firefox

**Comment by Splarkszter** [comment]
Firefox, happens sometimes... that's weird.

**Comment by KuryKat** [comment]
![image](https://github.com/user-attachments/assets/e6a874d6-98d6-45c1-a612-bded23ace728)

Anything else I should add? I don't know lol

**Comment by ajayyy** [comment]
@KuryKat Can you try disabling your other extensions

**Comment by KuryKat** [comment]
Thing is, that issue didn't happen anymore, just that night for some reason... now I don't seem able to reproduce it anymore @ajayyy
