### ISSUE TITLE
Use frame count instead of decimals on seconds when editing

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#76]
The fields to edit the seconds are too small to show the whole value. Sometimes can be confusing seeing most significant digits (left digits) incorrectly due to the view having panned right while editing it. Not sure if the player will ever support proper jumping to thousandths of a second but external uses may.
  Another option could be to display fractional seconds as framecount within that second. Don't know if YouTube allows large framerate differences but smaller edit precision can be useful for cleaner cuts on audio and some podcasts and similar audio only content is present on YouTube.

**Comment by mirror176** [comment]
At 30fps, framecount editing is less to enter/edit and makes the concept of so many frames an easier edit too without grabbing a calculator, trial+error, or using an editor that displays the converted result. Useful to edit that way when audio is not considered and trying to remove frames showing the ad completely.

**Comment by mirror176** [comment]
I still like fractional values if seeking is really going to be controlled that precisely

**Comment by HyphenSam** [comment]
FYI, you can use the comma and period keys to seek through the video frame by frame.
This feature would still be nice to have though.

**Comment by Mathnerd314** [comment]
The [video API](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/currentTime) uses decimal seconds. There isn't really a good way to get frame numbers. You can kind of fake it by multiplying FPS by the time and rounding to a frame numbers, but there are more problems:
1. There also isn't a good way to get FPS, besides hacking into the YouTube API.
2. It's easy to run into floating point precision issues, see all the issues here: https://github.com/allensarkisyan/VideoFrame/issues
3. Playing around with http://www.inconduit.com/smpte/, it seems browsers are a few frames off when seeking

**Comment by DuckOfDuckness** [comment]
An alternative could be to add buttons for 'previous frame' / 'next frame' when editing times. The comma and period keys aren't really explained by YouTube, so most people don't know about it.
