### ISSUE TITLE
Upload only one unsubmitted segment

### ISSUE THREAD

**Issue by chirag127** [ajayyy/SponsorBlock#765]
### Description:
Provide option to keep some segment and provide a submit button below each segment as I don't want to upload the first segment. As I want the first segment but not sure about the consensus and correctness about the first segment. 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/76880977/119963213-735efe80-bfc5-11eb-8d77-a00b840a0f90.png)

</details><br/>

**Comment by TheJzoli** [comment]
Making it so every segment is included by default would probably be the best, and you can then exclude the segments you want via some button.  This'd be the best for most people, since I'd say there are more people who want to submit everything immediately, than those who don't.

**Comment by chirag127** [comment]
> Making it so every segment is included by default would probably be the best, and you can then exclude the segments you want via some button. This'd be the best for most people, since I'd say there are more people who want to submit everything immediately, than those who don't.

@TheJzoli 
Well, I have made this issue so that I don't have to upload wrong segments ( segment only i want or segment not timed correctly ) .

**Comment by b201605f018137** [comment]
tool+
