### ISSUE TITLE
Channel ID Not Loaded Yet

### ISSUE THREAD

**Issue by Dustyragon** [ajayyy/SponsorBlock#766]
![image](https://user-images.githubusercontent.com/12465782/120061135-bfdc2580-c029-11eb-90bc-0f79a47924d8.png)
Just performed a reinstall of the addon (using Vivaldi browser) and it is doing this. I don't want to skip the intros on this particular channel.

**Comment by ajayyy** [comment]
Looks like you have some extension that modifies what the channel icon looks like in the page

**Comment by Dustyragon** [comment]
I have uh.. enhancer (really only gives me fine tuning on volume, I disabled most else from it aside from speed) and channel blocker. Channel blocker just hides channels, like the "don't show" button should do.

**Comment by TheGreenkey** [comment]
Seems like I have kinda the same problem. I'm using ['Improve YouTube!' (Video & YouTube Tools)🎧](https://chrome.google.com/webstore/detail/improve-youtube-video-you/bnomihfieiccainjcjblhegjgglakjdd) which changes the channel link below the video to `https://www.youtube.com/channel/[channel-id]/videos` if the option `Channel > Default Channel Tab` is set to `Videos`. Therefore the `videos` segment is appended and the regex used in SponsorBlock only returns `https:videos`.

I'd suggest splitting the channel url into segments with `/` as a delimiter and then just always picking the second segment. A quick and dirty example would be:
```javascript
[,, channelId] = (new URL(document.querySelector(".ytd-channel-name a")?.getAttribute("href"))).pathname.split('/')
```
Of course this doesn't yet handle the case where the `querySelector` returns undefined.

**Comment by ajayyy** [comment]
It probably can match up to the next `/` optionally/lazy

**Comment by Dustyragon** [comment]
Appears to be only semi working. Sometimes I can get it to say that it whitelisted a channel, but it'll still skip the segment regardless. Watching a different video and coming back to the previous channel, it'll act like it was never whitelisted. As far as I'm aware enhancer doesn't change the layout much, if at all, it just changes the overall look with it's own theme selection.

**Comment by PXAbstraction** [comment]
I've got this issue as well. I can't whitelist channels anymore without getting the channel ID error and channels I previously whitelisted are not being respected. I'm also running Improve YouTube (which I need because YouTube has now decided to default every video to 720p) but disabling it doesn't seem to resolve the issue. This has been going on for well over a month now.

**Comment by ajayyy** [comment]
@PXAbstraction Browser and version?

**Comment by PXAbstraction** [comment]
> @PXAbstraction Browser and version?

Chrome 91.0.4472.106 and extension version 2.0.16.2.

**Comment by ajayyy** [comment]
@PXAbstraction Try again after updating to 2.1.0.1 

https://support.kixie.com/hc/en-us/articles/235601588-How-to-Force-an-Update-of-Your-Chrome-Extensions

**Comment by PXAbstraction** [comment]
That did it! Thank you sir! :)

**Comment by Dustyragon** [comment]
Tried the force update bit on my end, while I stopped getting this error it seems that whitelisting doesn't appear to stick.
