### ISSUE TITLE
Sponsor section, except with valuable content

### ISSUE THREAD

**Issue by mielipuolinen** [ajayyy/SponsorBlock#768]
Hi!
I love the plugin, it's saving so much time and it's working very well!

I ran into a little issue with the plugin with this video:
https://www.youtube.com/watch?v=MUaTOoVmg1Q

It's SmarterEveryDay channel and it has a section sponsored by Google (8:59 - 10:40). Therefore it's technically a sponsored section. However the content of the section is very typical SmarterEveryDay content: _educating viewers in good spirit_.

In the section Destin is actually educating about critical thinking and it's not blatantly advertising something (you know, Raids legends for a millionth time garbage...). I can't help but think this particular skip is causing more harm than helping and wonder how often valuable content will be skipped.

I feel like there should be some kind of exception or a sub category available.
I can guess that probably quite many plugin users have already reported the section as an incorrect section because moderators already had to force it to stay put. Therefore I would like to think that many users are agreeing with me in this case.

Cheers and Happy dev'ing!

**Comment by ajayyy** [comment]
Any kinds of exceptions like this would cause a lot of backlash, as people already get mad about the rule where fully sponsored videos are not labeled, but thanks for thinking about it.
