### ISSUE TITLE
Prevent editing sponsor with no end time

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#77]
I have been working with video in another editor to try to get precision on my edits. Clicking start+stop gives an edit with both times being the same but clicking on start will make an entry with a start but no end and has a delete button but no edit button. Clicking on its time does open it for editing but gives NAN for endtime and delete below it but no save button even after filling in an end time. Clicking sponsor stop and start on the video closes the popup (as does start, kind of annoying) and when reopened it will have a complete and editable entry.
  Using the 'Sponsorship starts/stops now' buttons work from the popup to complete it without closing the popup but always closes any times editors that are open without saving or prompting to do so.

**Comment by mirror176** [comment]
I should have added that editing could fill the endtime as the start time to at least be something and have it not consider start=end as valid candidates to upload. Maybe a comment that stop has not been hit could make sense for users to understand the lack of useful endtime too but that'd be more relevant as a 'just before upload' step rather than telling them all the time.

**Comment by ajayyy** [comment]
Edit should not be possible in these cases. This is a unintended consequence of adding the feature to be able to edit by clicking the test, originally you could only use the edit button
