### ISSUE TITLE
Feature request: Countdown timers + Custom event segments

### ISSUE THREAD

**Issue by andrewdev738** [ajayyy/SponsorBlock#770]
For anticipating events such as like Jumpscares, Not Safe For Work/Life, Flashing images, Spoilers, etc by adding a 3 to 5 second timer before the segment happens, like the the one used in youtube for ads, and the possibility to skip the segment. Something like:
"Jumpscare in 3... Skip|>"
If omit automatically is disabled.
Sorry if seems to may not work, but there's the idea.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/702
