### ISSUE TITLE
category suggestion: music timelapse

### ISSUE THREAD

**Issue by bogger33** [ajayyy/SponsorBlock#776]
Usually in videos when there's a timelapse where there's no narration, only music, I skip it. I would certainly make use of a category like that a lot.

However, I understand that if a category is too specific/isn't broadly applicable enough, it may end up just making the interface messier and not be worth including, since you would probably want to keep the number of categories as small as possible, to keep it possible to quickly scan through all options. Still, I thought I would at least suggest it, feel free to close this issue if you think it's not worth including.

**Comment by ajayyy** [comment]
Better as https://github.com/ajayyy/SponsorBlock/issues/409
