### ISSUE TITLE
What are we voting for?

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#78]
My current understanding is we are trying to just say good edit or not so bad edits get filtered out of community view and good edits get a stronger footing but am I right and how should others know what is?
  Skipping a sponsor has a thumbs up/down but doesn't clarify what you are saying by that. The homepage does not provide documentation. It should be more clear what the feedback is such as the following: the starttime was too early or too late or endtime (...) or wasn't smooth/clean (and not sure that can ever be smooth if skipping to an area outside bufferd content). Was it a sponsor or not something you thought should be blocked. Are we just saying "thanks for skipping 'something' for me"?
  Once categories/properties are added then it could be for if a block needs such details changed/refined. Without categories I was planning to block blatent unrelated ads that cut into programming without targeting self sponsorship. Would also likely block the misleading ones where it sounds like they talk of a product/service as if they are a user when its just a paid promo. I could see even on 'sponsor' blocking that people will have different preferences on what is worthy of a block and vote on their decision until either a formal decision is made for what is desired for community blocking standards, what is meant exactly by the vote, or more detailed feedback can be given.

**Comment by ajayyy** [comment]
Hi, the voting system is described here: https://ajay.app/blog.html#voting-and-pseudo-randomness-or-sponsorblock-or-youtube-sponsorship-segment-blocker

You are voting if if this should be skipped for others or not.
