### ISSUE TITLE
[Feature Request] Allow whitelisting domains (for "watch together" websites)

### ISSUE THREAD

**Issue by meoiswa** [ajayyy/SponsorBlock#782]
Feature request: Allow specifying a list of domains/hosts where the plugin will not automatically skip segments regardless of settings, in order to play well with websites like sync-tube.de and other "watch YouTube together" websites.
Blacklisting domains will allow for the automatic disabling of the plugin where it cause any sort of conflict with the particular website's implementation of the synchronized playback, without requiring for any site-specific fixes to be implemented.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/554

**Comment by meoiswa** [comment]
Apologies for the duplicate, It never ocurred to me to look for "blacklist where the plugin works" instead of "whitelist a domain for allowing segments" 🤔
