### ISSUE TITLE
[Feature Request] Ability to tell if a video doesn't have segments defined before loading the video (thumbnail, etc.)

### ISSUE THREAD

**Issue by zedseven** [ajayyy/SponsorBlock#786]
I don't think this should be on by default or anything, but for long playlists/series it would be helpful to see which videos are missing segments in a playlist.

For some series where every video has an intro and an outro for instance, only some videos have segments defined. It would make it much easier to fill in the videos with missing segments if I could see exactly which ones were missing them, rather than combing through every video to check manually.

The way I envision this is just as a little icon over the video thumbnail in the playlist when the feature is enabled, or something similar. This could potentially be expanded to show over all video thumbnails rather than just for playlists, too, and would make adding segments to videos a little more ergonomic.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/42
