### ISSUE TITLE
Hide specific segment locally permanently

### ISSUE THREAD

**Issue by prajaybasu** [ajayyy/SponsorBlock#787]
I would like the ability to blacklist all segments on a video or a particular segment by video/segment ID. 

A way to manually enter these IDs would be nice, but I feel like the downvote button for a skip should automatically blacklist the submission locally.

Music videos are the main issue, it's very subjective as to what is a "non music section" that needs to be skipped. And people just go crazy trying to find even the most subtle transitions to mark as non music sections.    

I don't want to whitelist the entire channel, because auto skips for end credits, etc. would also be disabled. And I also don't want to disable auto skip for a particular category just because of one bad segment.

Here's 2 specific videos as example which have bad submissions:   

https://www.youtube.com/watch?v=YSoT3T58QFY  
https://www.youtube.com/watch?v=YvVonQ7LUJ0  

Example of good skips:  
https://www.youtube.com/watch?v=Nj2U6rhnucI  
https://www.youtube.com/watch?v=leopt__ATR0

**Comment by ajayyy** [comment]
See also https://github.com/ajayyy/SponsorBlock/issues/646

**Comment by mchangrh** [comment]
closed in https://github.com/ajayyy/SponsorBlock/commit/4d60dec7f997bb076bfe7dc9d2b7079b96df3e95
