### ISSUE TITLE
Could SponsorBlock be made to work on iOS/iPadOS by using Shortcuts?

### ISSUE THREAD

**Issue by HouzuoGuo** [ajayyy/SponsorBlock#795]
Hey!

Looks like AdGuard figured out a way to better block ads in Safari mobile by using Shortcuts to manipulate the javascript displayed on the YouTube page: https://adguard.com/en/blog/how-to-add-a-shortcut-to-block-youtube-ads.html

Could SponsorBlock take some inspiration from that method and help Safari mobile users to auto-skip sponsor segments?

Thanks!

**Comment by ajayyy** [comment]
iOS 15 will support web extensions, so we can just wait for that.
