### ISSUE TITLE
Feedback when segment id copy button is clicked

### ISSUE THREAD

**Issue by chirag127** [ajayyy/SponsorBlock#796]
**Issue URL** : https://www.youtube.com/watch?v=uVQpdX8S4uI

Description : show the text Copied after if the segment id is copied just like we show Voted after voting .

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/122819955-b37d7c80-d2f8-11eb-9e7b-6e77b1f66721.png)
![image](https://user-images.githubusercontent.com/76880977/122820125-e4f64800-d2f8-11eb-866f-6221e7b9bdf1.png)

</details><br/>

**Comment by ajayyy** [comment]
The current behavior is intended so that you can click other buttons after copying, but some feedback mechanism could be useful
