### ISSUE TITLE
Look into switching dynamic script method to support Invidious on Safari

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#798]
The current methods that work on both Chrome and Firefox to add scripts to dynamic pages (Invidious, Cloudtube) do not work on Safari. Switching to https://github.com/fregante/content-scripts-register-polyfill may help.

**Comment by Nothankslads** [comment]
Is this likely to come to safari for MacOS?

**Comment by ajayyy** [comment]
Used a different solution, this does not support custom instances but at least will work with anything on https://api.invidious.io/

**Comment by ajayyy** [comment]
Now this is actually implemented
