### ISSUE TITLE
Ability to adjust the skip notification pop-up time

### ISSUE THREAD

**Issue by lavosday** [ajayyy/SponsorBlock#803]
I'd love to be able to adjust for how long the skip notification stays onscreen (in my case I'd like to make it shorter). Currently, the only option I've found was only to turn it on or off.

**Comment by lord-ne** [comment]
In some cases this could even be considered a bug. The "Skip Sponsor?" button remains on screen even after the segment is over (for 4 seconds), and clicking on it then will move you _backwards_ in the video a few seconds to right after the sponsorship segment ended. That button moving you backwards should certainly be considered unintended behavior. 

The only case where the button needs to remain after the segment is if the segment was skipped and the button presents you with the "Unskip" option.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/commit/38bc6e2b1c0ac54de10f0f947fc3c9d10847ca4b

**Comment by ajayyy** [comment]
@lord-ne It stays on for minimum 4 seconds

**Comment by lord-ne** [comment]
Ah I see. In that case I'll just set it to not show segments shorter than 4 seconds and call it a day.

**Comment by ajayyy** [comment]
The minimum time is in case voting is needed
