### ISSUE TITLE
Highlight Category - Skip-to-the-Point Button

### ISSUE THREAD

**Issue by William071802** [ajayyy/SponsorBlock#806]
It would be incredible to have a button that allows you to skip to the point (aka whatever question the title seeks to answer) when applicable. This would be very useful for when the video title advertises the answer of a question then buries it with 10 minutes of pretext building up to the point, that one juicy line that directly tells you what you clicked to learn.

**Comment by ajayyy** [comment]
WIP https://github.com/ajayyy/SponsorBlock/pull/690

**Comment by mchangrh** [comment]
closed in #690
