### ISSUE TITLE
Submitted times stop taking effect until a page refresh

### ISSUE THREAD

**Issue by mirror176** [ajayyy/SponsorBlock#81]
When creating but before submitting, a complete block performs its function correctly. Clicking submit on the popup has it stop working until the page is refreshed. The popup also will not mention that there are any entries until that refresh. Possible solutions would be allowing continuation of editing the submission (maybe mark uploaded+unaltered lines), reread the dataset and refresh the popup to the newest data after submitting, or replace the message about what exists with a message that the changes were submitted and will be available on all future page loads.

**Comment by ajayyy** [comment]
I think reloading from the database would be the easiest to implement

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/commit/3a4d867ae379cada70cf2916978d107739c9a407
