### ISSUE TITLE
Add skip to clickbait/thumbnail option?

### ISSUE THREAD

**Issue by Cpaczek** [ajayyy/SponsorBlock#813]
Just had an idea and I am not sure if this would fit in this extension but it would be cool to add a "skip to thumbnail/title" for videos that have a clickbaity thumbnail or title but make you watch half the video before getting to it. 

How I would imagine that it would work would be something like this.

Take this video for example https://www.youtube.com/watch?v=htTy_-HbcMY 

the clickbait title is "dog bites a paramotor" however that clip does not get shown until 4:14. it would be cool if there was a button I could click that would allow me to skip to the part that is mentioned in the title or thumbnail.

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/806
