### ISSUE TITLE
Sponsorblock not working anymore on own Invidious Instance if accessed over LAN IP

### ISSUE THREAD

**Issue by lunainvictum** [ajayyy/SponsorBlock#815]
Hey,

like the Title describes, Sponsorblock stopped working after a Update of Sponsorblock (but i dont know wich version i had). 

Now i can only sponsorblock in combination with my own invidious instance, if i add a fake domain to my hosts file for example or if i port redirect my instance and use my domain.

But i use my invidious instance alone on my LAN. 

I have in the Sponsorblock Settings "192.168.5.30:3000, 192.168.5.30, my.fakeinvidious.domain".

The first two dont work anymore. 

What is exactly not working? -> Sponsorblock says he dont find any video

Thanks.

**Comment by ajayyy** [comment]
Browser?

**Comment by lunainvictum** [comment]
ungoogled-chromium. But in Firefox i tested and it is the same.

**Comment by sdfg2** [comment]
I can confirm this is also the same for Cloudtube.

**Comment by sdfg2** [comment]
I just tried setting up a domain for this, and the problem persisted until I enabled https.  Perhaps that's what the problem is with this, no HTTPS?

**Comment by k073l** [comment]
The problem still exists.
Tested on own Cloudtube instance with http and https (self-signed). Sponsorblock (on Firefox) reports either no video found or no segments, while on official instance of Cloudtube the extension reports 2 segments.

**Comment by ajayyy** [comment]
@k073l Did you add your domain to the list of Cloudtube sites in options?

**Comment by k073l** [comment]
I did, all options I could: local ip, localip:port, fake.domain, fake.domain:port (also tried the same for https)
Domain is working locally, as I have it as a local DNS entry.

**Comment by tralph3** [comment]
I'm using Firefox. My instance is hosted on a remote server, but accessed only via a private VPN. I have a domain name which points to an internal IP address of that VPN. Sponsor Block doesn't work. It fails with error code "undefined". As far as I know, I'm not doing anything wrong. I even added the domain name in the Misc. settings, and then disabled and re-enabled support for 3rd party clients to *ensure* that I was giving permission to the extension on the full list of domains (which includes mine).

Note that it doesn't say it can't find a YouTube video, it detects it, and it tries to fetch the segments, but it fails. It does work on the instances it has listed by default.

**Comment by Steven11q** [comment]
Ive tried adding my personal instance (ip:port) to the list of custom domains, but it still gives the error "No YouTube video found.
If this is incorrect, refresh the tab." I tried forcefully adding the port through editing the json, but still nothing.

**Comment by ProPatte** [comment]
> Ive tried adding my personal instance (ip:port) to the list of custom domains, but it still gives the error "No YouTube video found. If this is incorrect, refresh the tab." I tried forcefully adding the port through editing the json, but still nothing.

Same issue here!

**Comment by UltraBlackLinux** [comment]
can still reproduce. Any updates?

**Comment by chrisafraser** [comment]
This has fixed the iOS extension in safari as well! Thank you!
