### ISSUE TITLE
Support for android firefox compatibility

### ISSUE THREAD

**Issue by Thewisem** [ajayyy/SponsorBlock#816]
I want to be able to support sponsorblock on android using firefox but I can't. I would love to help contribute to the project

**Comment by ajayyy** [comment]
It fully supports Firefox for Android as of a few weeks ago

**Comment by Thewisem** [comment]
No it doesnt

**Comment by Thewisem** [comment]
Uhhhhh
![Screenshot_20210701-053212](https://user-images.githubusercontent.com/74511929/124056069-b9c4d480-da2d-11eb-982a-31fe0888125c.jpg)

**Comment by ajayyy** [comment]
https://www.ghacks.net/2020/10/01/you-can-now-install-any-add-on-in-firefox-nightly-for-android-but-it-is-complicated/

**Comment by ajayyy** [comment]
I can't control that, they made it hard to install extensions on the new Firefox. I have emailed them requesting to be on the official list.

**Comment by Thewisem** [comment]
Oh ok

**Comment by Thewisem** [comment]
So it only can be done on firefox nightly

**Comment by Thewisem** [comment]
Dame

**Comment by Thewisem** [comment]
By the way, can you give me an add on collection which includes you?
