### ISSUE TITLE
Hide Submit segment notice after switching videos

### ISSUE THREAD

**Issue by chirag127** [ajayyy/SponsorBlock#818]
Problem : I many times intentionally mark the segment  but do not upload it due to many different reasons but after going to next video I face a permanent notice that ask me to submit the segment on the previous video everytime I leave a segment unuploaded .

![image](https://user-images.githubusercontent.com/76880977/123995974-7bf38c00-d9ec-11eb-8490-c9b09c9c2250.png)

**Comment by ajayyy** [comment]
I think this is fixed
