### ISSUE TITLE
Support YouTube "privacy-enhanced mode" (youtube-nocookie.com)

### ISSUE THREAD

**Issue by bershanskiy** [ajayyy/SponsorBlock#82]
## Summary

This extension already supports URLs like `https://www.youtube.com/embed/*` used for embedding YouTube in iframes on other pages, so I think it should also support URLs like `https://www.youtube-nocookie.com/embed/*` used for embedding videos in YouTube "privacy-enhanced mode".

## Details
From [official Google documentation](https://support.google.com/youtube/answer/171780) (under "Turn on privacy-enhanced mode" dropdown):
> Privacy Enhanced Mode allows you to embed YouTube videos without using cookies that track viewing behavior.
> ...
> To use Privacy Enhanced Mode, change the domain for the embed URL in your HTML from `https://www.youtube.com` to `https://www.youtube-nocookie.com`...

`youtube-nocookie.com` is an official YouTube domain that serves videos for iframes without setting cookies. Some site administrators prefer these URLs over regular ones for simplifying compliance with EU regulations (e.g., cookie directive or GDPR). Some users install browser extensions or scripts that automatically switch the URL for a slight improvement in privacy (reducing behavioral tracking, but not the number of ads).

I believe it would be nice if this extension supported this mode as well, however, this feature might need to be optional because if users do not want to be tracked by YouTube, they might not want to be tracked by this extension. Note that it's already possible in modern Chrome/Chromium versions (user can individually disable sites under extension's permissions). Something similar should eventually land in Firefox.

**Comment by ajayyy** [comment]
This would require adding this domain to the manifest permissions as well.

This comment is for my future reference or someone implementing it.

**Comment by OfficialNoob** [comment]
@ajayyy I did :D should be the same as the "normal" domain

**Comment by ajayyy** [comment]
Maybe some parts can be disabled on this domain?

**Comment by OfficialNoob** [comment]
Well I think its the same as http://youtube.com/embed

**Comment by ajayyy** [comment]
I am referring to:

> I believe it would be nice if this extension supported this mode as well, however, this feature might need to be optional because if users do not want to be tracked by YouTube, they might not want to be tracked by this extension. Note that it's already possible in modern Chrome/Chromium versions (user can individually disable sites under extension's permissions). Something similar should eventually land in Firefox.

**Comment by bershanskiy** [comment]
@ajayyy Ultimately, there are two approaches: make access to `youtube-nocookie.com` required (install-time permission) or make it optional (runtime permission).
I'd prefer the install-time permission approach. @OfficialNoob already added URL regex to the array, that should make extension work on these videos (I haven't tested). However, I would also recommend disabling all automatic information collection, even if it is enabled globally. I'd leave enabled all information communication explicitly initiated by the user (including video reporting and casting votes on previously skipped segments) but would disable all information collection not initiated by the user (view count). Just consider adding this detail to the privacy policy.
Optional permissions are kinda a pain to do because you need to interact with the user more and most users do not care.
