### ISSUE TITLE
Support YouTube music when "minimized"

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#821]
When minimized, the URL does not show the videoID

**Comment by mchangrh** [comment]
this might work with #1312 once it's rebased out of videoinfo

**Comment by mchangrh** [comment]
.take

**Comment by mchangrh** [comment]
Doesn't work with #131, it seems to pull the first song from ytConfig and not change

**Comment by mchangrh** [comment]
nvm it was just the server dying and a bad extension install, works fine on 5.1.0

**Comment by mchangrh** [comment]
for some reason it skips fine on playlist? but not watch?v=- will investigate
