### ISSUE TITLE
Info button hiding looks strange when other extensions that add buttons are enabled

### ISSUE THREAD

**Issue by tayloroneill** [ajayyy/SponsorBlock#822]
I use both SponsorBlock and Enhancer for YouTube, both of which add buttons to the player bar. Due to the info button auto-hiding, it ends up looking like this, with a gap where the info button goes.

![image](https://user-images.githubusercontent.com/61822772/124380789-195b0280-dd02-11eb-86fd-58ee6e0e3549.png)

This isn't a big deal but is kinda annoying and it would be good if there was an option to disable hiding the info button or something.

**Comment by ajayyy** [comment]
There will be a way to disable it now, will roll out in the next update

**Comment by ajayyy** [comment]
Fixed in 3.3
