### ISSUE TITLE
Rules Based Segment Matching

### ISSUE THREAD

**Issue by hl2guide** [ajayyy/SponsorBlock#832]
Rules based segment matching would be really useful.

Especially for repetitive, reliable segment markings.

A basic psuedocode example:

```
IF channel EQUALS 'example' AND video_title LIKE '*example*'
THEN
DEFINE SEGMENT 'intro' STARTS '00:00' ENDS '00:03'
```

**Comment by ajayyy** [comment]
I think there is too much room for error in these cases

**Comment by hl2guide** [comment]
Couldn't that be mitigated by making it local only and manually defined?

**Comment by ajayyy** [comment]
How often are two videos going to have the same `video_total_length`?

**Comment by hl2guide** [comment]
For that property it'd be like:

```
IF channel EQUALS 'example' AND video_title LIKE '*example*' AND video_total_length LESS THAN '05:00'
THEN
DEFINE SEGMENT 'intro' STARTS '00:00' ENDS '00:03'
```

**Comment by ajayyy** [comment]
I don't think this makes sense for this extension
