### ISSUE TITLE
Better names for categories

### ISSUE THREAD

**Issue by vwkd** [ajayyy/SponsorBlock#833]
Currently, the category names are a bit confusing. Some have alternative names after slashes, others have examples in parentheses. Related categories like intro and outro, or paid and unpaid promotion aren't easily identifiable, since they use different words.

I suggest to decide on one general name for each category. Then any subcategories can be written as examples in parentheses. In the future the parenthesized text could even move into its own field (maybe `description_short`) and be displayed distinctly from the header (maybe as smaller grey text).

| current names | suggested names |
| - | - |
| Sponsor | Non-self Promotion (e.g. paid sponsor) |
| Unpaid/Self Promotion | Self Promotion (e.g. merch) |
| Interaction Reminder (Subscribe) | Interaction Reminder (e.g. like, subscribe) |
| Intermission/Intro Animation | Intro (e.g. animated logo) |
| Endcards/Credits | Outro (e.g. endcards, credits) |
| Preview/Recap | Repetition (e.g. preview, recap) |
| Music: Non-Music Section | | |

**Comment by ajayyy** [comment]
I disagree with these suggestions. Also, "Intro Animation" refers specifically to animated logos, not general introductions.
