### ISSUE TITLE
Multiple popups at the same time from different videos is difficult

### ISSUE THREAD

**Issue by vwkd** [ajayyy/SponsorBlock#835]
Interacting with multiple popups from different videos is difficult.

- Popups don't show to which video they pertain to. You need to guess either by their position in the stack or the difference in their timeout delay
- Interacting with one popup doesn't stop the timeout delay of the others. If you want to interact with each, you effectively race against the clock trying to interact with each one within 5 seconds.

Having multiple popups from different videos happens more often than you might think. Take a playlist with at least two videos, for which the first has an outro marked at the end, and the next one has an intro marked at the beginning. Skipping the outro in the first one, YouTube automatically starts playing the next video in the playlist. Skipping the intro of the second one, you now have two popups for different videos at the same time.

I'd suggest, instead of creating little popups with individual timeouts, create one "master popup" which contains all the little popups, just like notifications appear in a notification center. The little popups are given names for the videos they pertain to and have no timeout. Only the master popup has a timeout, and the little popups are dismissed only together with the master popup.

https://user-images.githubusercontent.com/33468089/125167878-f2d61500-e1a2-11eb-8539-499ba92b9a06.mov

Note, the example video shows a related problem, where inputs to the popup of the previous video don't work. See https://github.com/ajayyy/SponsorBlock/issues/834

**Comment by ajayyy** [comment]
caae61a6a89a393a6308d52f3c57875b05f48b52
