### ISSUE TITLE
Option to change or disable Notice countdown

### ISSUE THREAD

**Issue by planet0** [ajayyy/SponsorBlock#838]
I often like to contribute segments and in particular vote up or down existing segments. Sometimes the default timer/countdown when the notice does appear can be quite short.

Would it be possible to add an option to change the notice countdown timer, or set to 0 to keep notices shown until the user manually votes or closes it?

**Comment by ajayyy** [comment]
Already implememented

**Comment by planet0** [comment]
Ah brilliant. Thanks @ajayyy!
