### ISSUE TITLE
Rename 'Music' into 'Music and Movies' section

### ISSUE THREAD

**Issue by SameenAhnaf** [ajayyy/SponsorBlock#845]
It will be nice from Sponsorblock to include segments from intros and outros from movies too. There's a lot of Indian and Classic movies on YouTube.

**Comment by ajayyy** [comment]
What are you suggesting be renamed?

**Comment by SameenAhnaf** [comment]
Sorry if I was not clear. I was talking about this section. 

A separate 'Movies' section should get the job done as well.
![IMG_20210716_232134](https://user-images.githubusercontent.com/79245641/125985918-9f869f0d-9fd1-43b9-af6a-7c6643a3a1e2.jpg)

**Comment by ajayyy** [comment]
Are you suggesting a new category?

**Comment by SameenAhnaf** [comment]
Just like music videos, movies' intros and outros should be blocked as well. Either one of the following options will get the job done

1. Add 'Movies' section solely related for movies' intros and outros.
2. Rename 'Music: Non-music section' into 'Music and Movies: Additional Parts' so that contributors can include intros and I of movies as well.

Off-topic. Is it possible to make a Sponsorblock app which can detect if a YouTube video is playing (from native YouTube app or browsers like Chrome, Safari etc)? If yes, I would like to open a separate issue on this with additional information.

Contributing segments on Newpipe has been a matter of debate for a long time. Separate android app should solve that issue too.

**Comment by ugurcansayan** [comment]
I fail to follow how your "movie" suggestion differs from intro and outro/ending segments in general.
And I can't understand why create and merge movies to music category.
Also I believe "non-music" includes "additional parts" as of now.

**Comment by SameenAhnaf** [comment]
Sorry for my poor vocabulary. But this should help. As you can see, real movie actually starts from 05:14. 

https://user-images.githubusercontent.com/79245641/125996427-b4af30db-32f6-4c6b-8cdd-a9d1e390c130.mp4

Disclaimer, cast, sponsors and other stuff (what I refer as 'Intro') should be avoided. Also, outro could be like an ending song or information about cast and crew which is not directly to the plot (such as 'My heart will go on' from movie 'Titanic')


>Also I believe "non-music" includes "additional parts" as of now.

If you think practically, any part of a music video either has information or entertainment. But the music part is always the centre of attention.

The same is the case with movies. The plot or story is  always the core part. Intros and outros (as I explained above) may or may not contain music. So, if we merge both sections, it can't be called "Music: Non-music section", rather "Movies and Music: Additional Parts'.

The reason why I am asking to merge both sections is the fact that both focus on the core part of any music video or movie. No additional information.

**Comment by SameenAhnaf** [comment]
@ajayyy Are you willing to make me do something? I have received "Assign issue to contributor" notification multiple times. Sorry, I can't understand as I am a non-developer user.

**Comment by ajayyy** [comment]
I have not tried to assign you to an issue, I'm not sure why you would get an email

**Comment by ajayyy** [comment]
Rejected
