### ISSUE TITLE
Error 400: No valid userID field(s) provided

### ISSUE THREAD

**Issue by ugurcansayan** [ajayyy/SponsorBlock#846]
Since yesterday server went down, I'm not able to submit any submissions anymore. 

Error message says (translated)
Server responden request was invalid. Error Code: 400
Check status.sponsor.ajay.app for server status.
No valid userID field(s) provided

Tried with four different Firefoxes. Also tried with different UserID's (default ones, random words, random strings etc)

>> SOLUTION

> It should be a random value 32 characters long. It should not be words or anything memorable due to the way it is published (its hash is public).

**Comment by ajayyy** [comment]
I recently added a length requirement to the userID. How many chracters is your ID?

**Comment by ugurcansayan** [comment]
> I recently added a minimum length requirement to the userID. How many characters is your ID?

I tried with multiple IDs varying from 8 to 30+ characters (i think). What I use is between 12 and 16

**Comment by ajayyy** [comment]
It should be a random value 32 characters long. It should not be words or anything memorable due to the way it is published.

**Comment by ugurcansayan** [comment]
> It should be a random value 32 characters long. It should not be words or anything memorable due to the way it is published (it's hash is public).

Thanks! I have tried with 32 characters now and it works. Can you please mention this in extension settings page?

**Comment by ajayyy** [comment]
I'll update the API docs
