### ISSUE TITLE
[Feature Request] Ability to change skip options for a specific channel

### ISSUE THREAD

**Issue by ellieaii** [ajayyy/SponsorBlock#847]
As the title suggests, I'd really like a feature where you're able to change the skip options for a specific channel.

An example of this would be an ability to disable intro skips for a specific channel only, and the 'global' settings remain as usual. 

Not sure how viable this is, but I'd really like a feature similar to this. Thank you!

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/435
