### ISSUE TITLE
[Feature Request] Add custom Timeskip for Entire Playlist

### ISSUE THREAD

**Issue by rickninja765** [ajayyy/SponsorBlock#848]
Yoo. So there's one channel who puts subscribe reminder in every videos.
And Its not quite popular tho. So no sponsorblock skip.
But First 7 seconds are about subscribe reminder.
Is it possible to add entire playlist in sponsorblock. I know its possible but little bit amount of effort needed.
And some people will misuse it.

**Comment by ajayyy** [comment]
Rejected
