### ISSUE TITLE
[Question] Why UserID being randomize in the API?

### ISSUE THREAD

**Issue by barraIhsan** [ajayyy/SponsorBlock#849]
I try to put my UserID and submit trough the API
`POST sponsor.ajay.app/api/skipSegments`
And I put my UserID to the json body. But when I see in the database, its not my userid, its a random userid. Why? Is there a reason why you don't allow submit a sponsor trough the API?

**Comment by ajayyy** [comment]
The public userID is different than the private userID otherwise your password would be public. The public userID is sha256 5000 times.

**Comment by barraIhsan** [comment]
oh ok. Can you see your own private userID?

**Comment by ajayyy** [comment]
Yes, in the options

**Comment by barraIhsan** [comment]
oh ok. Thanks!
