### ISSUE TITLE
Chrome crash when opening youtube tab

### ISSUE THREAD

**Issue by JeremyMahieu** [ajayyy/SponsorBlock#852]
Using Chrome 91.0.4472.164 on windows 10. Sponsorblock version 2.1.2.1.

I've been having this problem repeatedly (3 times already). When I open a tab and go to youtube, all chrome windows (including incognito) close without any message. This continues to happen each time I open a youtube tab. I've found two was to get out of it: reboot or turn off sponsorblock add-on.

How can I assist in diagnosing this further? Are there any logs I can generate?

**Comment by JeremyMahieu** [comment]
It wasn't due to sponsorblock. Don't know the cause.

**Comment by ajayyy** [comment]
This is odd. Someone else has this too https://github.com/ajayyy/SponsorBlock/issues/850

Maybe it's a bug in the browser?

**Comment by JeremyMahieu** [comment]
Doesn't sound similar tbh.
