### ISSUE TITLE
SponsorBlock extension badge not showing on Firefox Android

### ISSUE THREAD

**Issue by Nojuuu** [ajayyy/SponsorBlock#855]
![image](https://user-images.githubusercontent.com/84513173/126650692-b09ed899-7463-477f-baae-f2fdb52c46ca.png)

**Comment by PranavBhattarai** [comment]
Wait, do we really have SponsorBlock addon available for Firefox Android?!

I would love to have this addon in Firefox Android, but sadly we don't, do we?

**Comment by Nojuuu** [comment]
@PranavBhattarai 

You can do that in Nightly:
https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/

**Comment by ajayyy** [comment]
Fixed
