### ISSUE TITLE
No submit button

### ISSUE THREAD

**Issue by pdonias** [ajayyy/SponsorBlock#857]
I created a segment but then I'm only seeing 2 "play" buttons and no submit button so I can't upload the segment I just created. The first button says "Segment starts now" and the 2nd button says "Sponsorship starts now" and if I click on them, it starts a new segment.

![2021-07-25_20-36-48](https://user-images.githubusercontent.com/10992860/126909776-5eb412a2-4b20-446f-bc8e-7f73d8d0dc7b.png)

SponsorBlock 2.1.2.1
Google Chrome 91.0.4472.164

**Comment by ajayyy** [comment]
The text "Sponsorship starts now" does not exist in the codebase anymore, are you running two versions?

**Comment by pdonias** [comment]
Good catch! I had a beta version enabled. I disabled it and now the submit button is back.

Thanks and sorry for the noise :)
