### ISSUE TITLE
incorrect usage?

### ISSUE THREAD

**Issue by abrahimladha** [ajayyy/SponsorBlock#867]
Consider this video uploaded today: https://www.youtube.com/watch?v=qIy8uIJloeg

Basically this channel harvests clips from twitch and elsewhere. Sponsorblock has listed one of the people as an "ad" but no one else. I have no idea why this person was blocked but no one else was. Is it the case they paid to have their clips in the video, making it an ad, or is it the case that someone doesn't like this person and marked their clips as sponsor?

**Comment by ajayyy** [comment]
This stuff should go in Discord/Matrix
