### ISSUE TITLE
SponsorBlock integration on Tartube

### ISSUE THREAD

**Issue by axcore** [ajayyy/SponsorBlock#869]
I recall you wanted to be notified about other applications using SponsorBlock. So here's a new one:

[Tartube](https://github.com/axcore/tartube) is a GUI for youtube-dl/yt-dlp, and includes SponsorBlock support as of v.2.3.279. A brief summary of its capabilities is [here](https://github.com/axcore/tartube#627-video-slices).

**Comment by ajayyy** [comment]
Awesome, thanks for sharing!
