### ISSUE TITLE
support for reporting skip parts on invidious?

### ISSUE THREAD

**Issue by rezad1393** [ajayyy/SponsorBlock#872]
I see that skipping is enabled in invidious instances (thank you for that) but submitting reports is not supported on invidious instances? what would make this addon even more awesome.

**Comment by ajayyy** [comment]
Submitting should work fine using the popup

**Comment by rezad1393** [comment]
I dont see any way to submit

**Comment by rezad1393** [comment]
there is no popup for me.

**Comment by rezad1393** [comment]
like so;
![screen](https://user-images.githubusercontent.com/7523164/128119620-d6122eb7-a8e3-4025-9cf4-42781e36cf9b.png)
