### ISSUE TITLE
"Inspect" segment has rounding issues

### ISSUE THREAD

**Issue by stdedos** [ajayyy/SponsorBlock#874]
_From discussion at https://discord.com/channels/603643120093233162/603643180663177220/872538990899773521, https://discord.com/channels/603643120093233162/603643180663177220/872553818045415444_

For video https://www.youtube.com/watch?v=P8UVu-kGusg, if someone attempts to create a Sponsor segment 0:11.870 / 7:13.453, then, clicking "Inspect":

Expected: The segment is inspected, i.e. https://github.com/ajayyy/SponsorBlock/blob/9392d16617d2d48abb6125c00e2ff6042cb7bebe/src/components/SponsorTimeEditComponent.tsx#L331-L338

Actual: `video.currentTime` is somehow set to < 0:11.870, and the video is played as normal i.e. segment is almost instantly skipped.

After further debugging:
* `0:11.000` works as expected, `0:11.0001` exhibits this behavior.
* Video (or video duration) does not seem to affect the behavior
* > imo it seems to occur more often/  with more leniency the earlier in the video it is

PS: Please try to expose `video.currentTime` somewhere (`window.sb.video.currentTime` perhaps?), as it might have been invaluable in debugging this faster; without the extension experience or (whatever) setup is required to develop the extension.

**Comment by mchangrh** [comment]
The endtime is completely irrelevant, but the starting time seems to skip with more leniency the earlier in the video (by %) it is

eg. 1:00.990 wouldn't skip to end but 1:10.990 would, while .993 would skip until 1:30

**Comment by stdedos** [comment]
![ezgif-6-ec8b3ed77ed4](https://user-images.githubusercontent.com/133706/128243061-444bae25-c23f-4991-9ef3-bbf0d1462e36.gif)

**Comment by stdedos** [comment]
> The endtime is completely irrelevant, but the starting time seems to skip with more leniency the earlier in the video (by %) it is

Something like that, e.g. the same does not happen with 3:57:29.{1,9}56 / 3:59:07.907
