### ISSUE TITLE
I can't send new segment

### ISSUE THREAD

**Issue by vitonsky** [ajayyy/SponsorBlock#877]
I trying send segment for https://youtu.be/J52C5n6enKs?t=3293 
But after success sending i reload page and can't see my segment. Why?

Maybe someone setup bot which remove this segment?

Or your plugin give this service for commercial users?

If not, then is have your solution protection versus bots?

**Comment by vitonsky** [comment]
Ok, i check it right now and this segment is exist and work. But why it take some time?

And what about protection versus bots which remove their ads segments?

Do you have moderators (maybe from users) or some algorithms?

**Comment by vitonsky** [comment]
Hmm. I check it again and not find my segment. It's weird.

In some time it is exist but in other time not.

**Comment by ajayyy** [comment]
Seems like an internet issue on your end

**Comment by vitonsky** [comment]
Then why it not show me alert?

And what about protection versus bots?
