### ISSUE TITLE
Use non-persistent background page

### ISSUE THREAD

**Issue by bershanskiy** [ajayyy/SponsorBlock#88]
The persistent background page is loaded persistently, so even when there are no events to handle and even no YouTube videos (tabs or embedded frames) are open. This is wasteful since most of the time user does not watch videos let alone constantly actively interact with the server.

[How to do it.](https://developer.chrome.com/extensions/background_migration)

I think this refactoring might simplify #87.

**Comment by ajayyy** [comment]
Right now the background script just waits for messages from the content script, so this should not be hard to implement. Good idea!

**Comment by bershanskiy** [comment]
Since the PR was merged, I'll close this issue now.

@ajayyy FYI: The non-background script did reduce memory usage on my system somewhat, but extension still listens on all tab changes so still consumes resources when there are no YouTube videos open (on the main site or embedded). I still see the actual background process in the task manager often even when I do not have YouTube and do not have embedded videos. For me, the stack size fell from 3-4 MB to 2-3MB and overall process memory from  28MB to 19MB.
This happens because you still have an `chrome.tabs.onActivated` event listener that gets called each time any tab gets activated, so browser evicts the process from memory only if you do not do any tab changes and navigations within the same tab. The should be resolved when this event listener is removed.

**Comment by ajayyy** [comment]
Thanks for the update and PR! 10 mb is a pretty good reduction in ram.
