### ISSUE TITLE
Video breaks when there's a segment at the beginning

### ISSUE THREAD

**Issue by serg06** [ajayyy/SponsorBlock#881]
For example, this video has a segment at the beginning and I cannot play it no matter what: https://www.youtube.com/watch?v=Ig4NK2xeboI

The only fix I found was to change the URL to skip the segment by adding `&t=20s`: https://www.youtube.com/watch?v=Ig4NK2xeboI&t=20s

Maybe related to #539?

**Comment by ajayyy** [comment]
Works fine for me

**Comment by serg06** [comment]
And suddenly I can't reproduce it no matter what. That was weird. Thanks for checking.
