### ISSUE TITLE
sponsorblock causes certain videos to repeat

### ISSUE THREAD

**Issue by AntiSol** [ajayyy/SponsorBlock#884]
Here's a <strike>fun</strike> weird one for you to try to track down.

Some videos will repeat playing for me if I have sponsorblock enabled. i.e they play through, and when they get to the end they start playing from the start again. This has been going on for quite a while (months) but I've been too lazy to bother reporting it until now, it's a pretty minor thing. Sponsor segments are skipped on all play-throughs.

I have noticed it most prominently on videos made by Isaac Arthur (https://www.youtube.com/channel/UCZFipeZtQM5CKUjx6grh54g). But it may not affect all of his videos. I haven't really kept track of it until now. Sorry I can't be more specific!

The video which did it for me today was this one: 
https://www.youtube.com/watch?v=qqJ-a5WkoRg

This is the first time I've let a video play through two whole times, and it repeated to play back a third time. I'm not sure whether videos will keep repeating forever or only play a certain number of times.

It appears to only happen if I let the video play through in its entirety. If I open the link above, press play, and then skip to ~39 mins, it stops playing at the end as normal.

My hunch is that it happens on videos that have sponsor segments defined at the very end of the video. Or perhaps both at the start and end?

I'm running on waterfox classic 2020.12 (64-bit). May be specific to this browser?

I'll come back to this issue and report new things (and specific videos) as I notice them. And as always, happy to answer any questions or do tests. 

Thanks for your time!

**Comment by mchangrh** [comment]
Pretty sure this was brought up by a user in the discord, will try to reference it.

Their issue was that they had `YouTube Enhancer` and it was autorepeating the videos, try disabling all other extensions that might be active or interact with YouTube

**Comment by AntiSol** [comment]
The only other thing I have that would touch youtube is ublock origin. Next time something repeats I'll see if disabling ublock makes a difference.

**Comment by mchangrh** [comment]
Try disabling all your extensions and re-enabling them one at a time

**Comment by mchangrh** [comment]
Discord conversation referenced earlier: https://discord.com/channels/603643120093233162/603643180663177220/872566015932891167

**Comment by AntiSol** [comment]
yeah sorry but I don't have the kind of time necessary for fishing expeditions

**Comment by mchangrh** [comment]
fair enough, at least check if you have `Youtube Enhancer` installed, uBo shouldn't affect SponsorBlock

**Comment by AntiSol** [comment]
nah I definitely don't, never heard of that one.

I have a bunch of stuff, too much to make disabling them one-by-one fun. Tampermonkey, stylus, modify headers, toomanytabs, more dev-type addons.

I have looked through the list and I'm about 95% certain that there's nothing apart from ubo and sponsorblock that touches youtube.

I'd be very unsurprised if it was some weird waterfox-only thing. It seems not many people use it.

Like I said in the initial report, it's not a big game-breaking issue. ~50% of the reason I raised it is so that I can keep track of it in the hope of spotting a pattern :)

Thanks for the suggestions though!

**Comment by AntiSol** [comment]
Today I was watching https://youtu.be/T7TQFFH9gj8 in fullscreen.

The video got to the sponsor segment, then I saw a skip and two "segment skipped" popups, and then the video started playing at the start again.

I think it skipped to the end of the sponsor, and then back to the start, within ~1s.

So I guess it's not only videos with segments at both start and end. :/

**Comment by DiogeNEETs** [comment]
> The only other thing I have that would touch youtube is ublock origin. Next time something repeats I'll see if disabling ublock makes a difference.

Can you list the extensions you have installed besides uBlock origin?

**Comment by AntiSol** [comment]
hopefully this is enough info? If there's a better way to get a list, let me know

```
Extensions

British English Dictionary (Marco Pinto)

Extension ID
    marcoagpinto@mail.telepac.pt

English (Australian) Dictionary

Extension ID
    en-AU@dictionaries.addons.mozilla.org

English (GB) Language Pack

Extension ID
    langpack-en-GB@waterfox

SponsorBlock for YouTube - Skip Sponsorships

Extension ID
    sponsorBlocker@ajay.app

Stylus

Extension ID
    {7a7a4a92-a2a0-41d1-9fd7-1e92480d612d}

Tab Counter

Extension ID
    tabcounter@morac

Tab Groups

Extension ID
    tabgroups@quicksaver

Tampermonkey

Extension ID
    firefox@tampermonkey.net

Tool Tool

Extension ID
    {58786c8c-0225-4fad-b8e7-ca0d819611b0}

uBlock Origin

Extension ID
    uBlock0@raymondhill.net
```

**Comment by AntiSol** [comment]
actually there are a couple more which didn't show up in that list:
* classic theme restorer 1.7.7.2
* modify headers 0.7.1.1.1
* resurrect pages 3
* toomanytabs 1.4.8
* user agent switcher 0.7.3.1

pretty sure that's all

**Comment by ahti** [comment]
For reference, I just had this occur in Safari on [this video](https://www.youtube.com/watch?v=1-uNMj57Y4c).

In my case, it seems to be some interaction with [YouTube Auto HD + FPS](https://apps.jeurissen.co/auto-hd-fps-for-youtube). After I disabled that one SponsorBlock behaved as expected.

**Comment by AntiSol** [comment]
@DiogeNEETs I'm sorry this totally slipped my mind. I've been busy with a new job and haven't had a chance to do anything WRT your fishing expedition. I'll try to get to it soon.

I do get json when I Import/export all options:
```{"autoSkipOnMusicVideosUpdate":true,"categorySelections":[{"name":"sponsor","option":2},{"name":"intro","option":2},{"name":"outro","option":2},{"name":"interaction","option":2},{"name":"selfpromo","option":2},{"name":"preview","option":1},{"name":"poi_highlight","option":1}],"disableSkipping":false,"dontShowNotice":false,"forceChannelCheck":false,"hasShownYouCapNotice":true,"hideDiscordLaunches":10,"highlightCategoryAdded":true,"highlightCategoryUpdate":true,"invidiousInstances":["invidio.us","invidious.snopyta.org","invidio.us"],"invidiousUpdateInfoShowCount":6,"minutesSaved":1396.0073979172187,"previewCategoryUpdate":true,"segmentTimes":[["H6kp3QZkIdc",[{"segment":[8.167729,10.523812],"UUID":null,"category":"chooseACategory"}]],["uNsmO2AYzbE",[{"segment":[63,63],"UUID":null,"category":"sponsor"}]],["1fXACfkyvLc",[{"segment":[7.198916],"UUID":null,"category":"chooseACategory"}]]],"skipCount":2438,"sponsorTimesContributed":81,"submissionCountSinceCategories":73,"supportInvidious":true,"userID":"WQgbO0hh3WaHBYhnpURjHiOfN5hhh3aqw4Bk","whitelistedChannels":["UCrTNhL_yO3tPTdQ5XgmmWjA","UCrr7y8rEXb7_RiVniwvzk9w","UCNvsIonJdJ5E4EXMa65VYpA","UCbWcXB0PoqOsAvAdfzWMf0w","UC2-i3KuYoODXsM99Z3-Gm0A","whatdamath","RedLetterMedia"],"ytInfoPermissionGranted":true,"defaultCategory":"chooseACategory","skipKeybind":"Enter","startSponsorKeybind":";","submitKeybind":"'","showTimeWithSkips":true,"muteSegments":true,"trackViewCount":true,"trackViewCountInPrivate":true,"noticeVisibilityMode":3,"hideVideoPlayerControls":false,"hideInfoButtonPlayerControls":false,"hideDeleteButtonPlayerControls":false,"hideUploadButtonPlayerControls":false,"hideDiscordLink":false,"serverAddress":"https://sponsor.ajay.app","minDuration":0,"skipNoticeDuration":4,"audioNotificationOnSkip":false,"checkForUnlistedVideos":false,"testingServer":false,"refetchWhenNotFound":true,"allowExpirements":true,"showDonationLink":true,"autoHideInfoButton":true,"autoSkipOnMusicVideos":false,"barTypes":{"preview-chooseACategory":{"color":"#ffffff","opacity":"0.7"},"sponsor":{"color":"#00d400","opacity":"0.7"},"preview-sponsor":{"color":"#007800","opacity":"0.7"},"selfpromo":{"color":"#ffff00","opacity":"0.7"},"preview-selfpromo":{"color":"#bfbf35","opacity":"0.7"},"interaction":{"color":"#cc00ff","opacity":"0.7"},"preview-interaction":{"color":"#6c0087","opacity":"0.7"},"intro":{"color":"#00ffff","opacity":"0.7"},"preview-intro":{"color":"#008080","opacity":"0.7"},"outro":{"color":"#0202ed","opacity":"0.7"},"preview-outro":{"color":"#000070","opacity":"0.7"},"preview":{"color":"#008fd6","opacity":"0.7"},"preview-preview":{"color":"#005799","opacity":"0.7"},"music_offtopic":{"color":"#ff9900","opacity":"0.7"},"preview-music_offtopic":{"color":"#a6634a","opacity":"0.7"},"poi_highlight":{"color":"#ff1684","opacity":"0.7"},"preview-poi_highlight":{"color":"#9b044c","opacity":"0.7"}}}
```

**Comment by ajayyy** [comment]
This should be fixed now

**Comment by AntiSol** [comment]
I switched from waterfox -> brave many months ago and haven't seen this since. But @ajayyy , you rock, it's awesome to see things being fixed and not just piling up :)
