### ISSUE TITLE
Skip segment button always on screen

### ISSUE THREAD

**Issue by clenz93** [ajayyy/SponsorBlock#888]
On YT Vanced on Android the skip segment button is always on screen even if not in a segment. See attached screenshot. Button is not clickable.

![Screenshot_20210815-130857](https://user-images.githubusercontent.com/8890735/129486905-cddf1e10-08ff-4d0c-ac5d-8ae87e18aefd.png)

**Comment by ajayyy** [comment]
This is not vanced

**Comment by clenz93** [comment]
What do you mean? 
![Uploading Screenshot_20210815-132559.png…]()

**Comment by clenz93** [comment]
> This is not vanced

What do you mean?

![Screenshot_20210815-132559](https://user-images.githubusercontent.com/8890735/129487136-af6ec8e7-a872-43f7-9d1a-9e5331866f52.png)

**Comment by ajayyy** [comment]
this repository

**Comment by clenz93** [comment]
Ok. For future reference you can say "this likely isn't an issue with sponsorblock, please try contacting Vanced's team."

**Comment by ajayyy** [comment]
no, this has nothing to do with the SponsorBlock browser extension
