### ISSUE TITLE
Error 502 Bad Gateway for SponserBlock

### ISSUE THREAD

**Issue by Drflash55** [ajayyy/SponsorBlock#891]
There seems to be an issue where it doesn't want to upload segments because of a gateway error.

![image](https://user-images.githubusercontent.com/13694448/129650684-003a950e-cef1-4bf7-892b-3c42e05500d5.png)

![image](https://user-images.githubusercontent.com/13694448/129650675-72ddbbb9-2f96-4af5-a67a-ecc01b804789.png)
The last line repeats over and over about 4 more times.

**Comment by ajayyy** [comment]
Server issues are best reported via Discord/Matrix

**Comment by Drflash55** [comment]
Not sure what Matrix is, but are you suggesting I have to join the Discord server to report this issue?

**Comment by ajayyy** [comment]
or let someone else do it

**Comment by Drflash55** [comment]
Ah, alright then. Didn't know what the general purpose of this was.
My Google Chrome apparently crashed for no reason when that happened, so I thought it was an issue on my end. Glad to see the issue was resolved quickly.
