### ISSUE TITLE
Extension not working while using Brave Browser

### ISSUE THREAD

**Issue by gunjannandy** [ajayyy/SponsorBlock#892]
First of all, this is one of the best extensions I have used, hands down. This is my daily driver in both Google Chrome and Firefox. It works flawlessly.

I recently switched to Brave browser. Somehow I am noticing, this extension is not working anymore.
No skippable section appears on the video, neither can I submit new skippable sections to the database. 
I have also tried disabling Brave shield (Brave ad-blocker) and enabling u-block origin for YouTube, but nothing happened.

Has anyone else faced this issue? If not, can you please look into this? 
Please let me know if somehow I can help, in reproducing the issue.

Thank you.

**Comment by DiogeNEETs** [comment]
Have you tried uninstalling the extension and reinstalling it to see if it makes a difference?

**Comment by Kainzo** [comment]
I also don't see this as working in Brave... is this a known issue? No videos I am watching have it working.

**Comment by AlecRust** [comment]
> I also don't see this as working in Brave... is this a known issue?

Works fine for me in Brave.
