### ISSUE TITLE
SponsorBlock connects to www.youtube.com when using a third party client

### ISSUE THREAD

**Issue by TotalDarkness-NRF** [ajayyy/SponsorBlock#903]
SponsorBlock is an great piece of software and has helped me skip sponsors that I know I will never buy from.
I have been using the extenstion on my phone and computers and it work great!

I have been using Invidious (A third party client for youtube) to access videos from youtube without sending youtube and google my data, and potentially increase loading speeds and use less data.

I have recently been keeping an eye on network usage and noticed that my computer requests a connection to www.youtube.com whenever I load a video. After some testing I have realized that it is SponsorBlock attempting this connection despite me not being on youtube. It is not too big of a deal as I blocked it a few months ago, but it worries me that I may have been sending requests to youtube for the time I did not have it blocked without knowing.

I do not see a reason for why it should attempt a connection to youtube when using a 3rd party client. Everything seems to work just fine when it is blocked.

The expected behaviour would be to have it only connect to the SponsorBlock server the user request when connected to a 3rd party client.

**Comment by ajayyy** [comment]
this actually was removed a few days ago

**Comment by ajayyy** [comment]
the request has no authentication headers, so it would be like you were logged out.

**Comment by TotalDarkness-NRF** [comment]
Thanks for the quick response! I will try on the latest release.
