### ISSUE TITLE
Idea: Remove "Choose a Category" from list of Categories?

### ISSUE THREAD

**Issue by DiogeNEETs** [ajayyy/SponsorBlock#904]
![image](https://user-images.githubusercontent.com/89327673/130444828-a4efc91e-41f8-401a-87a1-7739e1a3cd05.png)

DRY principle but applied to UI/UX

https://www.wikiwand.com/en/Don%27t_repeat_yourself

PS. Since a majority of time saved seems to come from blocking sponsors, have sponsor as default category (as an option in settings?) if submitters don't RTFM then that's on them 🤷‍♂️

![image](https://user-images.githubusercontent.com/89327673/130444946-8ce0f7f6-2012-4b8c-b9ee-102c3670f38a.png)

**Comment by ajayyy** [comment]
I don't think this is possible with native html elements
