### ISSUE TITLE
Idea: Having a label for specific brand of sponsor

### ISSUE THREAD

**Issue by tacohitbox** [ajayyy/SponsorBlock#908]
Elaborating: 

If you don't mind ads from brands like Squarespace or whatever - you can label a sponsored segment's respective brand and have it not skip that brand but still continue to skip others.

**Comment by ajayyy** [comment]
rejected

**Comment by hazysu** [comment]
But why? You give no reason at all lol what

**Comment by tacohitbox** [comment]
why?
