### ISSUE TITLE
UI problems caused by new notice design

### ISSUE THREAD

**Issue by 0purple** [ajayyy/SponsorBlock#914]
![Знімок екрана (82)](https://user-images.githubusercontent.com/68148475/130944850-e46ac9c6-4c28-4446-8f94-d94ed9d8ad9b.png)
Browser: Mozilla Firefox Nightly 93.0a1

**Comment by 0purple** [comment]
> 
> 
> > > ![image](https://user-images.githubusercontent.com/89558747/130957204-09ce1c00-852d-4c16-a5e7-376abd46df74.png)
> > > Happening here too. Vivaldi, extension in Portuguese.
> > 
> > 
> > What is the issue here? Did it look different before 3.0?
> 
> Sorry, that's true, I thinked it because it's strange to see "Pré-visualizar" with a line break, then I thinked the box was with the wrong width. Actually, before "Pré-visualizar" haven't a line break, but I don't know the specific version.

+1, before it didn`t have line break

**Comment by enzon19** [comment]
![image](https://user-images.githubusercontent.com/89558747/131233931-cde551c3-0ff5-44a9-acfc-030591302483.png)
![image](https://user-images.githubusercontent.com/89558747/131233960-8a8e5aeb-6a16-4f4e-97b5-9afc4488fb32.png)
I think all the UI problems I have are connected to the translation of the extension.
