### ISSUE TITLE
[BUG] Skip to highlight not respecting global skip toggle

### ISSUE THREAD

**Issue by mchangrh** [ajayyy/SponsorBlock#916]
Discord Conversation: https://discord.com/channels/603643120093233162/603643180663177220/881268578224054282

The global skipping is enable/disabled button obeys all segments but highlight, when highlight is set to "auto skip to the start"

Replicated on Chrome 92, SB 3.0.3 Win 10

**Comment by mchangrh** [comment]
I have no idea how the logic is supposed to work, since manual skip seems fine but 

relevant code:
https://github.com/ajayyy/SponsorBlock/blob/a2c3116bdd4e0208726173566881923b7a84c251/src/content.ts#L771-L783

**Comment by ajayyy** [comment]
Looks like it only checks when creating the skipping schedule
