### ISSUE TITLE
Publish latest version on edge store

### ISSUE THREAD

**Issue by BitGrub** [ajayyy/SponsorBlock#918]
Some videos won't skip (automatically OR manually) the sponsored bits, even those they show up correctly on the seek bar

This is an example https://www.youtube.com/watch?v=zF2KF-SVIXc

Extension version 3.0

Microsoft Edge Version 92.0.902.78 (stable)

**Comment by ajayyy** [comment]
Works fine for me

**Comment by BitGrub** [comment]
:/ that's odd. That specific video and a few others (which I didn't make note of because I thought I was going insane) don't skip sponsorspots for me.

It's extra weird because I can see the Green indicator on the seekbar, it just doesn't get skipped.

Is there any other logs I can provide?
Have you tried it with the Edge version of the extension as well?

**Comment by ajayyy** [comment]
Maybe it is related to whitelisting? Do you have skipping enabled? 
![image](https://user-images.githubusercontent.com/12688112/131734010-7e266990-8b8f-448f-9198-edf845ec97e7.png)

**Comment by ajayyy** [comment]
Ooh, yes, I know the issue then which is sobze fixed

**Comment by ajayyy** [comment]
published, will take time for them to review it
