### ISSUE TITLE
[Feature Request] View Video Segments on sb.ltn.fi

### ISSUE THREAD

**Issue by barraIhsan** [ajayyy/SponsorBlock#921]
Add `View Video Segments on sb.ltn.fi` (Or a better name, because I suck at naming thing) and when you click it, it will go to `https://sb.ltn.fi/video/<videoID>`. 

When you click a specific segment, it will show up an additional eye / see button? And when you click it, it will go to maybe `https://sb.ltn.fi/?uuid=<UUID>`?

Image Example :
![image](https://user-images.githubusercontent.com/57800056/131693744-1ec60c23-9f55-49fb-8622-8d03ff8d4596.png)
(Credit to [FontAwesome](https://fontawesome.com/v5.15/icons/eye?style=solid) for the eye emoji)

**Comment by FlorianZahn** [comment]
https://wiki.sponsor.ajay.app/index.php/Community#Bookmarklets

For the time being you can use this, or the userscript by Deedit.

**Comment by ajayyy** [comment]
not planned
