### ISSUE TITLE
Skip notice for sponsored content doesn't show up

### ISSUE THREAD

**Issue by Andre601** [ajayyy/SponsorBlock#929]
Currently experiencing a weird issue, where the timeline of a video shows the `Sponsored content` section (Green line) but doesn't show me the prompt to skip it.

The setting is set to manual skipping and the channel is not added to the whitelist.

Extension version: 3.0
Browser: Microsoft Edge

Please note that outside of setting the different skip options for the sponsor types, none of the other options have been modified and are still the defaults.

**Comment by ajayyy** [comment]
Closed for inactivity
