### ISSUE TITLE
Minimum browser versions?

### ISSUE THREAD

**Issue by bershanskiy** [ajayyy/SponsorBlock#93]
What are your target browser versions? Do you plan to add them to the manifests?

**Comment by ajayyy** [comment]
I have not tested on anything but the latest, if someone wants to do that, they can. It would probably take a while

**Comment by bershanskiy** [comment]
You don't need to test anything, all the API support data is readily available from Google's documentation and MDN. I was wondering if you are choosing APIs based on backward compatibility (e.g., `XMLHttpRequest` instead of Fetch API).

**Comment by OfficialNoob** [comment]
Well I would like the Crypto.getRandomValues() API for other things using a polyfill via something like https://babeljs.io/ may work
