### ISSUE TITLE
Username sometimes appears cut off

### ISSUE THREAD

**Issue by ajayyy** [ajayyy/SponsorBlock#931]
![image](https://user-images.githubusercontent.com/12688112/132119092-7b075749-c06a-402e-bde9-91d9048e1390.png)

**Comment by planet0** [comment]
Also cut off entirely in Safari.

<img width="94" alt="image" src="https://user-images.githubusercontent.com/65204836/133248323-52ef8393-976f-4384-9921-f0d83d10038a.png">
