### ISSUE TITLE
Show skip notice in advance

### ISSUE THREAD

**Issue by ioMozo** [ajayyy/SponsorBlock#932]
The idea is to show the notice few seconds prior to the start of the segment so that user can choose to cancel the auto skip without an interruption or enforce the manual skip as soon as the segment will start. The delay should be customizable down to zero seconds (current behaviour)
Other possibility would be to add the duration of the segment into the notice

**Comment by ajayyy** [comment]
Duplicate issue

**Comment by ioMozo** [comment]
May you show me the original? I couldn't find one
