### ISSUE TITLE
if I accidentally select the Highlight category and then select the intro category before uploading then the two boxes for the time do not come back.

### ISSUE THREAD

**Issue by chirag127** [ajayyy/SponsorBlock#939]
**Issue URL** : https://www.youtube.com/watch?v=bFzo9xzYS7s

if I accidentally select the Highlight category and then select the intro category before uploading then the two boxes for the time that come have the same time and I lose the second time stamp of the segment and I have to mark the second time stamp of the segments again that's very annoying.

<details><summary>Screenshots:</summary>

![image](https://user-images.githubusercontent.com/76880977/132468385-74b042a0-2eb6-4150-ad95-09bb3c5a65ba.png)

</details><br/>

**Comment by mchangrh** [comment]
if you click to the right of the first timestamp, the second box will appear. This is the same when the submit box is brought up when only the start time is set

**Comment by chirag127** [comment]
But still I lose 1 timing.

**Comment by chirag127** [comment]
@ajayyy can you reopen it?
