### ISSUE TITLE
Use a dedicated option page

### ISSUE THREAD

**Issue by bershanskiy** [ajayyy/SponsorBlock#94]
Did you put the extension options onto the popup intentionally or do you plan to use `opions_ui`? This might be just a preference thing, but all extensions I have use it and thus feel well-integrated with the browser.

**Comment by ajayyy** [comment]
What is `options_ui`? Is that the openable options panel?

**Comment by bershanskiy** [comment]
[MDN article](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/options_ui)
[Google's docs](https://developers.chrome.com/extensions/options)

`options_ui` is a manifest key used to specify a page that opens up when the user wants to access extension options.
Option pages can open either as a full-tab page or be integrated within `chrome://extensions` and `about:addons` if they don't need much space, like this extension).

The benefit of `options_ui` is that options don't clutter up the popup and user can open extension options in a more "integrated" manner: via `chrome://extensions` and `about:addons` or by right-clicking the extension icon and in context menu choosing "Options".

It's a dedicated page that you specify in the extension Manifest.

Note that there is the newer `options_ui` key and deprecated `options_page`.

**Comment by OfficialNoob** [comment]
Can common options be displayed on the same tab via the popup?

**Comment by bershanskiy** [comment]
> Can common options be displayed on the same tab via the popup? (As well)

Yes, of course. All options are stored as just internal variables (in `storage.sync`) and, of course, you can modify them from anywhere in the extension's context (background, popup, userAction, content scripts, even context menus).
However, you already hide options on popup behind a click. That means you already don't have enough space to permanently put them there. Since the user has to click something anyway, why not [open a proper page](https://developer.chrome.com/extensions/runtime#method-openOptionsPage)?

**Comment by OfficialNoob** [comment]
Well I think theirs a UI change planed so it will hopefully not be hidden by a button

**Comment by OfficialNoob** [comment]
options_ui should be something like __MSG_optionsUI__
https://github.com/ajayyy/SponsorBlock/pull/86
