### ISSUE TITLE
Req: Ability to mark several skipped sections, to unskip

### ISSUE THREAD

**Issue by Jonta** [ajayyy/SponsorBlock#940]
Steps:
- LTT: Fixing The Verge PC Build - feat. Stefan Etienne - https://www.youtube.com/watch?v=QKzmYsySGFQ
- 27:43ish: https://youtu.be/QKzmYsySGFQ?t=1663
- "Multiple segments skipped"-notice comes up (currently 3: Unpaid/Self promotion, Sponsor, Endcards/Credits)
- Decide I want to watch several of those
- Ctrl+click the 1st one (Unpaid/Self promotion)
 
Actual results:
- Skips 1st one

Expected results:
- Recognises Ctrl+click as being different from click
- Highlights 1st section label in the Unskip-box
- Allows me to select other sections in addition
- Then hit enter
- And all sections selected for unskipping, are unskipped

Edit:
- SB v 3.1.1
- Firefox 91.0.2

**Comment by ajayyy** [comment]
I'm a little confused, what would it mean to "unskip" multiple segments. Isn't unskipping the earliest one the same thing?

**Comment by Jonta** [comment]
> I'm a little confused, what would it mean to "unskip" multiple segments? Isn't unskipping the earliest one the same thing?

@ajayyy No

If I want to unskip the 1st and 2nd, I currently have to interact twice:
- Once to skip the 1st one
- The 2nd time to skip the 2nd one

In my request, there's only 1 point in time where I decide which segments to unskip

"Ah. It skipped over 3 segments. But I'd prefer to see the first 2. Ctrl+click, ctrl+click, watch both"

Instead of

"Ah. It skipped over 3 segments. But I'd prefer to see the first 2. Click, watch the 1st one. Click, watch the 2nd one"

(Mouse movements omitted for readability)

**Comment by ajayyy** [comment]
#1609
