### ISSUE TITLE
[BUG] [Firefox] "skip to highlight" is not always shown when set to "ask when video loads"

### ISSUE THREAD

**Issue by natis1** [ajayyy/SponsorBlock#941]
How to reproduce:
1. open a private window with the plugin enabled in private browsing
2. go here: https://www.youtube.com/c/MarkRober/videos
3. click the world's tallest elephant toothpaste volcano video, "skip to highlight" should appear
4. click the back button in the browser.
5. click the world record domino robot video. "skip to highlight" will not appear
6. refreshing the page with ctrl r will cause it to appear.

I'm guessing this might be related to the video player not actually being loaded the second time and not triggering the "when video loads" thing. but anyway in practice when watching more than one youtube video skip to highlight doesn't appear at all and since highlights are tiny on the playback bar having to scan the bar (or click open sponsorblock popup) for them to know that I should refresh the page for the skip to highlight button to appear again is rather annoying.

**Comment by mchangrh** [comment]
Can replicate on chrome 93, SB 3.1.2, the skip to highlight will only appear on reloads

**Comment by mchangrh** [comment]
Can't replicate on 3.6.2 or 3.7beta - probably fixed by https://github.com/ajayyy/SponsorBlock/pull/958

**Comment by Elaborendum** [comment]
Still present for me, using Invidious.

**Comment by mchangrh** [comment]
which version of sponsorblock are you using

**Comment by ajayyy** [comment]
I don't think invidious has skip to highlight support at the moment
