### ISSUE TITLE
Random parts of YouTube Shorts are skipped with sponsorblock toggled

### ISSUE THREAD

**Issue by Natem05** [ajayyy/SponsorBlock#945]
Shorts are cut off as sponsored segments or intros, making them impossible to watch with sponsorblock toggled.

**Comment by MRuy** [comment]
Does it always happend in the same shorts video or does it work after reloading the page?
Please share a video link so we can check it

**Comment by ajayyy** [comment]
I don't think this is talking about the browser extension

**Comment by Natem05** [comment]
I'm not talking about the browser extension. It's about the sponsorblock in the YouTube vanced app, but I thought it was a problem I should talk about here. But perhaps I should talk to the people of vanced about it.

**Comment by Ryhon0** [comment]
Shorts worked for me perfectly until today, now it skips intros and sponsors on completely random videos.
Since vanced is no longer supported it would require a fix on the API server

**Comment by ajayyy** [comment]
No, it's a bug in the client
