### ISSUE TITLE
Adblocker Ultimate makes it impossible to send a segment

### ISSUE THREAD

**Issue by LeoLTM** [ajayyy/SponsorBlock#946]
I have AdBlocker Ultimate ([this](https://adblockultimate.net/)) as a Firefox extension and when I have it enabled (what I have to do when I watch YouTube videos because otherwise I'd have to watch 3 ads in a row before the video starts playing...),
I'm no longer able to use the "send segment" button in the YouTube player. neither is the big red "send" button in the addon menu working. 

They both start working when I disable AdBlocker Ultimate. 
I added 

@@||youtube.com/get_video_info$~script
@@||sponsor.ajay.app^$~script

to my custom rules and to my whitelist but it just won't work.

**Comment by ajayyy** [comment]
https://twitter.com/gorhill/status/1165747661691064322?lang=en

I recommend uninstalling AdBlocker Ultimate and using uBlock Origin or Adguard
