### ISSUE TITLE
Username weirdness?

### ISSUE THREAD

**Issue by ToothyDev** [ajayyy/SponsorBlock#947]
Alright so I had a bit of weird stuff with the username. First off, I use YouTube Vanced with the SponsorBlock built into it, and normal SponsorBlock on PC. Now first I had the usual random username but I soon changed that to my name I use elsewhere, I did that on PC and my stats and all stayed. Good. But then, I put that same name into the Vanced app and hoped for my skipped and submitted segments to sync up, however they didnt. It still only shows the 2 I skipped on phone. Do I have to somehow export / import my data to the phone app, or should it work with just the username? (which i somehow doubt). Would love to hear how I can basically sync up SponsorBlock on multiple platforms!

**Comment by MRuy** [comment]
Your personal skips are only counted on the client and not synced to a server.  
The stats of people used your segments are linked to the privateUserID and not the username.

**Comment by ToothyDev** [comment]
Ah I see, so I guess syncing it up to another PC would be the exporting / importing UserID option in the settings (which sadly isn't available in youtube vanced but oh well)?
