### ISSUE TITLE
Auto-fetch `invidious` instances from instance list

### ISSUE THREAD

**Issue by Rikj000** [ajayyy/SponsorBlock#948]
### Feature request
If `Support 3rd Party YouTube-Sites`is toggled on, periodically automatically scrape invidious instances from the [instance list](https://invidio.us/).

This will eliminate the need to manually configure invidious instances most of the time.
However I believe these domains should also be blacklist-able, since it may not always be wanted to automatically block video segments on all of these sites at the same time.

I briefly went through the source code of the instance list's [`main.js`](https://git.sr.ht/~cadence/invidious-redirect/tree/master/item/src/main.js) and spotted following [`instances.json`](https://api.invidious.io/instances.json).

That `.json` file is from where it loads the currently up and running instances, it should also be usable to implement this feature in SponsorBlock. :slightly_smiling_face:

**Comment by ajayyy** [comment]
It needs to ask permission for domains, do it can't do this automatically in the background

**Comment by Rikj000** [comment]
Then perhaps GitHub Actions can be of help to kind of implement this.

Instead of full automation you could make SponsorBlock ship with a default & up-to date instance list:
https://github.community/t/can-github-actions-directly-edit-files-in-a-repository/17884

**Comment by mchangrh** [comment]
.take
