### ISSUE TITLE
Periodically refresh segments on new videos

### ISSUE THREAD

**Issue by Alainx277** [ajayyy/SponsorBlock#954]
When viewing a new video, no segments are found when playback is started. If the sponsor is later in the video (a minute or more in), there is often already a segment submitted, but not loaded from the server (as it was created between playback start and sponsorship start).

I propose refreshing the segment list periodically while no segments are available and the video is new (not sure about the cutoff).

**Comment by MRuy** [comment]
Already existing, check the settings

**Comment by Alainx277** [comment]
> Already existing, check the settings

I have it enabled and still didn't have a segment almost 4 minutes in (after refresh it was there)... maybe we could make an issue to have a setting for the interval?

**Comment by ajayyy** [comment]
The interval is set to a value that won't kill the server

**Comment by Alainx277** [comment]
> The interval is set to a value that won't kill the server

Fair enough, hosting costs exist 😔

**Comment by ajayyy** [comment]
Real time would be cool in the future though with websocket
