### ISSUE TITLE
text-align: center -> right/left depending on locale

### ISSUE THREAD

**Issue by Jonta** [ajayyy/SponsorBlock#956]
Reason in 156 words: https://practicaltypography.com/centered-text.html

`git grep center` finds most of these in `public`, and 3 in `source`

I especially notice it in `popup.ts`; the dropdown menu from the extension-logo-button, that gives us an overview for this particular video

There's at least 1 left-to-right locale for SB: ar (arabic)

I suggest labeling that one and other languages as such, and having them right-aligned

**Comment by ajayyy** [comment]
Don't really get that reasoning
