### ISSUE TITLE
Safari Extension lost all data

### ISSUE THREAD

**Issue by planet0** [ajayyy/SponsorBlock#963]
Since upgrading to Safari 15, I've lost all my data in SponsorBlock, including my User ID and settings, all reset with a randomly generated username and ID.

Aside from the issue, is there any way to get my User ID back with all my submissions?

**Comment by ajayyy** [comment]
Not oh my side. I suggest looking up where safari put the data

**Comment by planet0** [comment]
Right.

**Comment by ajayyy** [comment]
to clarify, the server only stores a hashed version of the private id

**Comment by planet0** [comment]
Oh, yes that's understandable - I am wondering more why the extension has suddenly deleted/reset everything, though?

**Comment by ajayyy** [comment]
Very weird. Are those other extensions web extensions or app extensions? Maybe it only happened to web extensions?

**Comment by planet0** [comment]
I'm not too sure actually - I've got Bitwarden, 1Password, AdGuard for Safari and Dark Reader for Safari currently installed alongside SponsorBlock so I'm unsure which is what, but none of them have been affected.

**Comment by ajayyy** [comment]
I know Bitwarden is a web extension now, so I guess not

**Comment by planet0** [comment]
@ajayyy I figured out the cause — it's when you reinstall macOS Big Sur, my other extensions are fine, but SponsorBlock loses all it's data.

**Comment by planet0** [comment]
@ajayyy Just tested it further with easy replication - happens every time, reinstalling macOS erases all SponsorBlock data. No other extensions affected.

**Comment by planet0** [comment]
This issue occurred again when updating from macOS 12.0.1 stable to 12.1 beta.
