### ISSUE TITLE
I can't find an extension to activate on safari

### ISSUE THREAD

**Issue by jesusdeveloper** [ajayyy/SponsorBlock#967]
Hello there!!

Thank you for this wonderful program.
I am trying to install the safari version, I have downloaded the project, I have run successfully on mac and it shows me the following window:

<img width="901" alt="Captura de pantalla 2021-09-25 a las 0 39 37" src="https://user-images.githubusercontent.com/17848602/134746537-268dfe62-31c2-4742-a912-db5939c60217.png">

The problem is that I go to Safari and Safari does not show any SponsorBlock extensions.

What am I doing wrong? The compilation is correct and I have tried to restart safari but I still do not see this extension to activate it (I have activated unsigned extensions also in safari).

Thanksss

<img width="312" alt="Captura de pantalla 2021-09-25 a las 0 39 48" src="https://user-images.githubusercontent.com/17848602/134746542-ecb7595d-b2ea-4db4-9bd1-904fda9e42be.png">

**Comment by ajayyy** [comment]
https://github.com/ajayyy/SponsorBlock/issues/827

**Comment by jesusdeveloper** [comment]
Hi!

I have seen the post but I see that the solution is to upgrade to Safari 15.
I have the version: Version 15.0 (16612.1.29.41.4, 16612)
And it does not work :(

**Comment by ajayyy** [comment]
It's still best to keep all that related discussion in one place

**Comment by jesusdeveloper** [comment]
Excuse me friend!

I will write this in the other message and we consider this closed.

Thanks.
