### ISSUE TITLE
Add "Irrelevant" category

### ISSUE THREAD

**Issue by ShawkMusic** [ajayyy/SponsorBlock#968]
Add "Irrelevant/off topic/waste of time" category for sections of a video that don't add anything to the video and just wastes your time

Let's say, for example, I look for a tutorial on how do something. Often YouTubers will add irrelevant stuff at parts of the video, usually at the start, where they waste your time with things like "Hey what's up guys, welcome back to another tutorial today we're gonna be..." etc etc where they introduce themselves and explain what they're gonna be doing (which I already know because I read it on the title) and a bunch of other pointless stuff I don't care about that just serves to pad out the video length or something.
It would be so much nicer to just search what I want, click on the video, and just be taken straight to what I searched for

Right now, the closest category to that is "intermission/intro animation" but that's not quite right for this.

**Comment by ajayyy** [comment]
rejected, too broad

**Comment by ajayyy** [comment]
By the way, have you seen highlight category? it does the last thing you meantion
