### ISSUE TITLE
automatic adjustments to timings

### ISSUE THREAD

**Issue by TheVaccin3** [ajayyy/SponsorBlock#969]
Some of the videos I watch have built in chapters for sponsor segments/intros. people will also submit the times when there is something to skip but they may or may not be perfect, while the built in chapters are done more accurately. so, is there a way to automatically update the timings based on the chapters if they are present and match +/- 1 second with the submitted timings?

I dont really know how this extension works so forgive me if idk what im talking about.

**Comment by ajayyy** [comment]
The chapters are actually less accurate as they don't have sub-second precision

**Comment by ajayyy** [comment]
They also don't follow all our guidelines such as including segues

**Comment by TheVaccin3** [comment]
I know doing this will not cover all cases, but what if for example the submitting timing is a little late compared to the chapter, and it ends too early, even if its just slightly, would it not be easier to use chapter timestamps? or when trying to make a timestamp

**Comment by Feyko** [comment]
I think it would be great to be able to mark a chapter as being a sponsor spot etc. It may not be as accurate as manually starting and stopping, but it's easier. Less friction means more entries, more participation, and ultimately a better experience for all users
