### ISSUE TITLE
Safari version / App Store publishing

### ISSUE THREAD

**Issue by ViniDalvino** [ajayyy/SponsorBlock#970]
Hello, 

I was wondering if the extension could be published to the Mac App Store. I managed to convert it to a safari extension following the instruction found [here](https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari) using xcrun on so  it's entirely fesable.  

So, can the extension be published on the App Store to use it on safari. 

Thank you

**Comment by ajayyy** [comment]
It already is https://github.com/ajayyy/SponsorBlock/wiki/Safari
