### ISSUE TITLE
Don't snap to highlight for keybind seeking

### ISSUE THREAD

**Issue by Drflash55** [ajayyy/SponsorBlock#973]
Using Google Chrome Version 94.0.4606.61 on the latest version of SponserBlock (V3.2).

If a video has a Highlight segment and the video goes anywhere past it, trying to use YouTube's built-in frame advance will make it jump back to the highlight portion of the video.

Frame advancing works perfectly fine before the highlight segment, it only seems to do this after it goes past that portion.

EDIT: This only really does seem to happen around the part where the Hightlight is considered "active" (about 35 seconds or so). When it stops showing up on the player, frame advancing works as normal.

**Comment by Drflash55** [comment]
Did more testing on this, it doesn't seem to be just tied to frame advancing. Using the arrow keys (or J/K) to advance the player forwards or back, or even clicking around the Highlight part seems to bring it back to that portion. Maybe this was probably intended instead of it being a bug, but I'm unsure about it.

**Comment by ajayyy** [comment]
It is kind of intended, but I didn't expect the buffer to get up to 5 seconds. It is based on the color size on the preview bar

**Comment by Drflash55** [comment]
Oh, then that makes sense.
The longer the video is, the longer the buffer would be. For reference, the video I'm watching is over an hour and 30 minutes long. So it takes up quite a bit of time.

**Comment by ajayyy** [comment]
A partial skip for this is in place by waiting 3 seconds before skipping again
