### ISSUE TITLE
[Bug] [Chrome Beta] Sponsorblock suddenly not working at all

### ISSUE THREAD

**Issue by Peca21** [ajayyy/SponsorBlock#974]
Sponsorblock extension is suddenly not working for me. Worked fine yesterday and works fine on a android device (in YouTube vanced). Chrome restart, page refresh and extension refresh do nothing, it says no segments found.
Chrome Version 95.0.4638.17 (Official Build) beta (64-bit)
![image](https://user-images.githubusercontent.com/13818400/134919325-f7a24f31-94fe-4a10-8ff4-0f8a15f5ec4c.png)

**Comment by xorbital** [comment]
The server is down.
Check the status page which is linked on the website: https://status.sponsor.ajay.app/
