### ISSUE TITLE
Pressing a button in the Segment-Creation-Popup closes player options

### ISSUE THREAD

**Issue by FlorianZahn** [ajayyy/SponsorBlock#981]
Further description:
When you press a button in the Segment-Creation-Popup the youtube player options close. When opening the player-options the Segment-Creation-Popup isn't closed.
https://streamable.com/m70kjy

When does this happen to me?
This scenario comes up often when i want to finetune a music segment. I open the creation-popup to preview the segment, but notice after that i haven't adjusted the playback speed yet. I go to do that, but no matter what i do i need to 1. close the creation-popup and 2. open the player-options.

Possible ways to make the user experience better:
- Close creation-popup when opening player-options.
- Don't close player-options when closing the creation-popup

**Comment by ajayyy** [comment]
think this is fixed
