### ISSUE TITLE
Downvote reason is missing a "this is a sponsored video disclosure" reason

### ISSUE THREAD

**Issue by Berengal** [ajayyy/SponsorBlock#987]
Sometimes I run into a sponsor segment that's actually the initial disclosure on a sponsored video. Marking this is a sponsored segment is harmful and against the guidelines, but when I downvote this segment the options I get for why I'm downvoting are all wrong. It's not mistimed, and there are no alternative categories that would fit better. There should be a way of saying that this segment shouldn't exist at all.

**Comment by ajayyy** [comment]
Slash means "or"
