### ISSUE TITLE
Segments not being fetched on load

### ISSUE THREAD

**Issue by McCaffeteria** [ajayyy/SponsorBlock#989]
It used to work, but now when a video starts there are no segments shown on the timeline. A video will start playing a sponsor segment and I will click on the "segment starts now" button and the extension suddenly "wakes up" and instantly identifies the segment and skips me to the end of the segment.

This happens consistently, between browser reboots, through PC reboots, and will not resolve itself no matter how long the video is. I HAVE to interact with the extension EVERY VIDEO in order to get it to even show me there is a segment to skip.

**Comment by McCaffeteria** [comment]
Quick reply, thanks

---

{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.71 Safari/537.36",
        "platform": "Win32",
        "language": "en-US",
        "extensionVersion": "3.3.2"
    },
    "config": {
        "autoSkipOnMusicVideos": true,
        "autoSkipOnMusicVideosUpdate": true,
        "categorySelections": [
            {
                "name": "sponsor",
                "option": 2
            },
            {
                "name": "music_offtopic",
                "option": 2
            },
            {
                "name": "poi_highlight",
                "option": 1
            }
        ],
        "disableSkipping": false,
        "dontShowNotice": true,
        "forceChannelCheck": false,
        "highlightCategoryAdded": true,
        "highlightCategoryUpdate": true,
        "minDuration": "5",
        "minutesSaved": 1566.2196729999998,
        "previewCategoryUpdate": true,
        "segmentTimes": [
            [
                "eL4PyhxSv94",
                [
                    {
                        "UUID": null,
                        "category": "sponsor",
                        "segment": [
                            818.325814,
                            889.073371
                        ]
                    }
                ]
            ]
        ],
        "skipCount": 1570,
        "sponsorTimesContributed": 1,
        "submissionCountSinceCategories": 1,
        "whitelistedChannels": 1,
        "defaultCategory": "chooseACategory",
        "skipKeybind": "Enter",
        "startSponsorKeybind": ";",
        "submitKeybind": "'",
        "showTimeWithSkips": true,
        "muteSegments": true,
        "trackViewCount": true,
        "trackViewCountInPrivate": true,
        "noticeVisibilityMode": 3,
        "hideVideoPlayerControls": false,
        "hideInfoButtonPlayerControls": false,
        "hideDeleteButtonPlayerControls": false,
        "hideUploadButtonPlayerControls": false,
        "hideSkipButtonPlayerControls": false,
        "hideDiscordLaunches": 0,
        "hideDiscordLink": false,
        "invidiousInstances": 1,
        "supportInvidious": false,
        "serverAddress": "Default server address",
        "skipNoticeDuration": 4,
        "audioNotificationOnSkip": false,
        "checkForUnlistedVideos": false,
        "testingServer": false,
        "refetchWhenNotFound": true,
        "ytInfoPermissionGranted": false,
        "allowExpirements": true,
        "showDonationLink": true,
        "autoHideInfoButton": true,
        "barTypes": {
            "preview-chooseACategory": {
                "color": "#ffffff",
                "opacity": "0.7"
            },
            "sponsor": {
                "color": "#00d400",
                "opacity": "0.7"
            },
            "preview-sponsor": {
                "color": "#007800",
                "opacity": "0.7"
            },
            "selfpromo": {
                "color": "#ffff00",
                "opacity": "0.7"
            },
            "preview-selfpromo": {
                "color": "#bfbf35",
                "opacity": "0.7"
            },
            "interaction": {
                "color": "#cc00ff",
                "opacity": "0.7"
            },
            "preview-interaction": {
                "color": "#6c0087",
                "opacity": "0.7"
            },
            "intro": {
                "color": "#00ffff",
                "opacity": "0.7"
            },
            "preview-intro": {
                "color": "#008080",
                "opacity": "0.7"
            },
            "outro": {
                "color": "#0202ed",
                "opacity": "0.7"
            },
            "preview-outro": {
                "color": "#000070",
                "opacity": "0.7"
            },
            "preview": {
                "color": "#008fd6",
                "opacity": "0.7"
            },
            "preview-preview": {
                "color": "#005799",
                "opacity": "0.7"
            },
            "music_offtopic": {
                "color": "#ff9900",
                "opacity": "0.7"
            },
            "preview-music_offtopic": {
                "color": "#a6634a",
                "opacity": "0.7"
            },
            "poi_highlight": {
                "color": "#ff1684",
                "opacity": "0.7"
            },
            "preview-poi_highlight": {
                "color": "#9b044c",
                "opacity": "0.7"
            }
        }
    }
}

**Comment by ak-42** [comment]
I have started seeing same behaviour about 5 days ago.

I have following extension/userscripts interacting with YouTube, but it is worth noting that all of those used to work seamlessly with Sponsorblock, and I have not changed my setup lately.

[uBlock Origin](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)
[reddit comments for YouTube](https://addons.mozilla.org/en-US/firefox/addon/reddit-comments-for-youtube/)
[Violentmonkey](https://addons.mozilla.org/en-US/firefox/addon/violentmonkey/)
[Simple YouTube Age Restriction Bypass](https://greasyfork.org/en/scripts/423851-simple-youtube-age-restriction-bypass)(userscript running in Violentmonkey)

Debugging info follows:
<details>

```

{
    "debug": {
        "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:93.0) Gecko/20100101 Firefox/93.0",
        "platform": "Win32",
        "language": "en-AU",
        "extensionVersion": "3.3.3"
    },
    "config": {
        "barTypes": {
            "interaction": {
                "color": "#cc00ff",
                "opacity": "0.7"
            },
            "intro": {
                "color": "#00ffff",
                "opacity": "0.7"
            },
            "music_offtopic": {
                "color": "#ff9900",
                "opacity": "0.7"
            },
            "outro": {
                "color": "#0202ed",
                "opacity": "0.7"
            },
            "preview-interaction": {
                "color": "#6c0087",
                "opacity": "0.7"
            },
            "preview-intro": {
                "color": "#008080",
                "opacity": "0.7"
            },
            "preview-music_offtopic": {
                "color": "#a6634a",
                "opacity": "0.7"
            },
            "preview-outro": {
                "color": "#000070",
                "opacity": "0.7"
            },
            "preview-selfpromo": {
                "color": "#bfbf35",
                "opacity": "0.7"
            },
            "preview-sponsor": {
                "color": "#007800",
                "opacity": "0.7"
            },
            "selfpromo": {
                "color": "#ffff00",
                "opacity": "0.7"
            },
            "sponsor": {
                "color": "#00d400",
                "opacity": "0.7"
            },
            "preview-chooseACategory": {
                "color": "#ffffff",
                "opacity": "0.7"
            },
            "preview": {
                "color": "#008fd6",
                "opacity": "0.7"
            },
            "preview-preview": {
                "color": "#005799",
                "opacity": "0.7"
            },
            "poi_highlight": {
                "color": "#ff1684",
                "opacity": "0.7"
            },
            "preview-poi_highlight": {
                "color": "#9b044c",
                "opacity": "0.7"
            }
        },
        "categorySelections": [
            {
                "name": "sponsor",
                "option": 2
            },
            {
                "name": "selfpromo",
                "option": 2
            },
            {
                "name": "poi_highlight",
                "option": 1
            },
            {
                "name": "interaction",
                "option": 2
            },
            {
                "name": "intro",
                "option": 2
            },
            {
                "name": "outro",
                "option": 2
            },
            {
                "name": "preview",
                "option": 1
            },
            {
                "name": "music_offtopic",
                "option": 2
            }
        ],
        "segmentTimes": [
            [
                "Anmy0XQ5jhc",
                [
                    {
                        "UUID": null,
                        "category": "sponsor",
                        "segment": [
                            216.793944,
                            216.793944
                        ]
                    },
                    {
                        "UUID": null,
                        "category": "sponsor",
                        "segment": [
                            216.786549,
                            221.786549
                        ]
                    },
                    {
                        "UUID": null,
                        "category": "sponsor",
                        "segment": [
                            225.766957,
                            225.766957
                        ]
                    }
                ]
            ],
            [
                "89EX1NF7eHQ",
                [
                    {
                        "UUID": null,
                        "category": "sponsor",
                        "segment": [
                            598.234686,
                            598.276092
                        ]
                    },
                    {
                        "UUID": null,
                        "category": "sponsor",
                        "segment": [
                            633.960374,
                            634.123775
                        ]
                    },
                    {
                        "UUID": null,
                        "category": "sponsor",
                        "segment": [
                            634.648877,
                            634.648877
                        ]
                    }
                ]
            ],
            [
                "Vi9Y9AL13Rc",
                [
                    {
                        "UUID": null,
                        "category": "sponsor",
                        "segment": [
                            30.084,
                            106.845
                        ]
                    }
                ]
            ],
            [
                "7trv8KWD7oA",
                [
                    {
                        "UUID": null,
                        "category": "outro",
                        "segment": [
                            253.684361,
                            283.138503
                        ]
                    }
                ]
            ],
            [
                "d1aNUDCSNI4",
                [
                    {
                        "segment": [
                            31.994583,
                            94.659827
                        ],
                        "UUID": null,
                        "category": "sponsor"
                    }
                ]
            ],
            [
                "Xb0nd19T4b0",
                [
                    {
                        "segment": [
                            293.070835
                        ],
                        "UUID": null,
                        "category": "chooseACategory"
                    }
                ]
            ],
            [
                "9fcH6-WQUAw",
                [
                    {
                        "segment": [
                            0,
                            12.759
                        ],
                        "UUID": null,
                        "category": "sponsor",
                        "source": 1
                    },
                    {
                        "segment": [
                            657.65932,
                            759.009812
                        ],
                        "UUID": null,
                        "category": "sponsor",
                        "source": 1
                    },
                    {
                        "segment": [
                            759.009812,
                            771.181
                        ],
                        "UUID": null,
                        "category": "selfpromo",
                        "source": 1
                    }
                ]
            ],
            [
                "uL9W_NJqPAM",
                [
                    {
                        "segment": [
                            112.073993
                        ],
                        "UUID": null,
                        "category": "chooseACategory",
                        "source": 1
                    }
                ]
            ],
            [
                "tYWi1hqtFss",
                [
                    {
                        "segment": [
                            0,
                            0
                        ],
                        "UUID": null,
                        "category": "sponsor",
                        "actionType": "skip",
                        "source": 1
                    }
                ]
            ]
        ],
        "previewCategoryUpdate": true,
        "highlightCategoryUpdate": true,
        "highlightCategoryAdded": true,
        "hideDiscordLaunches": 10,
        "invidiousUpdateInfoShowCount": 6,
        "supportInvidious": false,
        "whitelistedChannels": 0,
        "submissionCountSinceCategories": 36,
        "minutesSaved": 1411.4220357502522,
        "sponsorTimesContributed": 62,
        "autoSkipOnMusicVideos": true,
        "autoSkipOnMusicVideosUpdate": true,
        "skipCount": 3051,
        "defaultCategory": "chooseACategory",
        "forceChannelCheck": false,
        "skipKeybind": "Enter",
        "startSponsorKeybind": ";",
        "submitKeybind": "'",
        "showTimeWithSkips": true,
        "disableSkipping": false,
        "muteSegments": true,
        "trackViewCount": true,
        "trackViewCountInPrivate": true,
        "dontShowNotice": false,
        "noticeVisibilityMode": 3,
        "hideVideoPlayerControls": false,
        "hideInfoButtonPlayerControls": false,
        "hideDeleteButtonPlayerControls": false,
        "hideUploadButtonPlayerControls": false,
        "hideSkipButtonPlayerControls": false,
        "hideDiscordLink": false,
        "invidiousInstances": 1,
        "serverAddress": "Default server address",
        "minDuration": 0,
        "skipNoticeDuration": 4,
        "audioNotificationOnSkip": false,
        "checkForUnlistedVideos": false,
        "testingServer": false,
        "refetchWhenNotFound": true,
        "ytInfoPermissionGranted": false,
        "allowExpirements": true,
        "showDonationLink": true,
        "autoHideInfoButton": true
    }
}
```

</details>

**Comment by McCaffeteria** [comment]
Not sure if this is something you wanted everyone to do or just ak-42, but I don't know what you mean by "open about:debugging and inspect the addon." Can you be more specific?

**Comment by ajayyy** [comment]
Those were the instructions for firefox. On chrome, you need to go to chrome://extensions/, enable developer mode (top right) then click

![image](https://user-images.githubusercontent.com/12688112/137594985-1757857a-5e0e-4bad-8b2d-e1b86cbad979.png)

**Comment by ak-42** [comment]
> 
> 
> Can you open about:debugging and inspect the addon. Then see if the skip segments request is actually happening when you first load the page and see if it fails.

I opened the about:debugging page for Sponsoblock and observed it. I loaded about 10 random videos (clearing the network tab before loading next video) and I saw GET requests flying about as expected. 

Then one of the videos failed to load segments, and I still observed status 200 GET request for the times, but it did not get loaded into the player. So, it looks like it's not network, but how Sponsorblock is handling the data.

**Comment by ajayyy** [comment]
ooh, awesome! That probably is https://github.com/ajayyy/SponsorBlock/commit/5f34a777f1e7a2b11545702dcb7928596bfa3758 then, and that means it should work again in 3.4

**Comment by ajayyy** [comment]
Ooh wait, that commit is in 3.3 as well, I guess there is something else causing it. But, it's probably related to that duration filter removing stuff that it should not. Does this occur when changing videos on the same page, or only when loading directly from the url? If the first, then maybe it is filtering against the previous video's duration.

**Comment by ajayyy** [comment]
let me know if the fix in 3.4.1 was good

**Comment by ajayyy** [comment]
More info in https://github.com/ajayyy/SponsorBlock/issues/1030

**Comment by ak-42** [comment]
@ajayyy The issue appears to be fixed. I have not noticed it in days now. Thank you for your efforts and I am sorry that some other users forget that this is FOSS and if they don't like how it works they can either submit a pull request, fork the repo or shut up.

**Comment by ak-42** [comment]
@ajayyy Unfortunately, I am seeing this again. I don't know if I just had a good run of few days when it did not happen, or the bug was reintroduced, but I am seeing cases of segments not loading again. Let me know if there is anything further I can do to troubleshoot.

**Comment by ajayyy** [comment]
I'm pretty sure the current issue is from server-timeouts that have been happening in the past few days

**Comment by ak-42** [comment]
That makes sense. I noticed it behaves slightly differently. In the past it either didn't work or it did, no between. And when it did not work, you could force load it by opening the addon interface window. Now it also sometimes loads few seconds in (sometimes as many as 15 seconds in), and when it fails to load opening the interface button does not force-load it. So, it might we on the network layer. Thanks for the update.
