### ISSUE TITLE
UI issues again

### ISSUE THREAD

**Issue by 0purple** [ajayyy/SponsorBlock#991]
![Знімок екрана (84)](https://user-images.githubusercontent.com/68148475/136336246-4e9c891c-950c-4f4f-b08a-e6d0ae187d4d.png)
The UI is broken again
Firefox Nightly 95.0a1
Looks similar to https://github.com/ajayyy/SponsorBlock/issues/914

**Comment by ajayyy** [comment]
Closed for inactivity
