### ISSUE TITLE
[Feature] Podcast Support

### ISSUE THREAD

**Issue by seniorm0ment** [ajayyy/SponsorBlock#994]
Requesting support for Podcasts. They're riddled with sponsors bad these days, it would be nice. Maybe gPodder would be a good start to add support for. Unless there's another service, or better way to do it.
https://gpodder.net/

**Comment by ajayyy** [comment]
That seems to be a desktop client, not a web client.

**Comment by seniorm0ment** [comment]
gPodder is a common "server" that can fetch and track podcasts from all around.
They also have actual clients though, which is the desktop client you speak of. 
They have an open api so apps such as AntennaPod connect to the gPodder site to grab podcasts and if the user wants to login, they can and track their progress and such from any devices.

Realistically my end goal is to download podcasts from gPodder, then have Sponsorblock apply to the downloaded files. This is something that can be done with MPV for YouTube videos. Of course this would mean Sponsorblock needs to support gPodder though.
